CREATE TABLE [compliance].[AvetmissStudent] (
    [AvetmissStudentSK]                        BIGINT                                              NOT NULL,
    [PersonCode]                               BIGINT                                              NULL,
    [RegistrationNo]                           BIGINT                                              NULL,
    [USI]                                      NVARCHAR (10)                                       NULL,
    [AboriginalGroup]                          NVARCHAR (20)                                       NULL,
    [AboriginalGroupDescription]               NVARCHAR (50)                                       NULL,
    [Age]                                      INT                                                 NULL,
    [ATSICode]                                 NVARCHAR (3)                                        NULL,
    [ATSICodeDescription]                      NVARCHAR (50)                                       NULL,
    [InternationalFlag]                        NVARCHAR (2)                                        NULL,
    [DateOfBirth]                              DATE MASKED WITH (FUNCTION = 'default()')           NULL,
    [CompletedQualification]                   NVARCHAR (50)                                       NULL,
    [CountryOfBirth]                           NVARCHAR (20)                                       NULL,
    [CountryOfBirthDescription]                NVARCHAR (50)                                       NULL,
    [IndigenousFlag]                           NVARCHAR (50)                                       NULL,
    [DisabilityFlag]                           NVARCHAR (1)                                        NULL,
    [DisabilityFlagDescription]                NVARCHAR (100)                                      NULL,
    [DisabilityNeedHelp]                       NVARCHAR (30)                                       NULL,
    [DisabilityTypeOrig]                       NVARCHAR (5)                                        NULL,
    [EmailAddress]                             NVARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [EmploymentStatus]                         NVARCHAR (4)                                        NULL,
    [EmploymentStatusDescription]              NVARCHAR (75)                                       NULL,
    [EnglishHelpFlag]                          NVARCHAR (30)                                       NULL,
    [EnglishLevel]                             INT                                                 NULL,
    [EnglishLevelDescription]                  NVARCHAR (50)                                       NULL,
    [Forename]                                 NVARCHAR (50)                                       NULL,
    [Gender]                                   NVARCHAR (6)                                        NULL,
    [HighestSchoolLevel]                       NVARCHAR (20)                                       NULL,
    [HomePostCode]                             NVARCHAR (4)                                        NULL,
    [HomePostcodeName]                         NVARCHAR (50)                                       NULL,
    [LanguageGroup]                            NVARCHAR (20)                                       NULL,
    [LanguageGroupDescription]                 NVARCHAR (75)                                       NULL,
    [LanguageSpoken]                           NVARCHAR (20)                                       NULL,
    [LanguageSpokenDescription]                NVARCHAR (75)                                       NULL,
    [MiddleNames]                              NVARCHAR (240)                                      NULL,
    [MultiPriorEducationLocation]              NVARCHAR (5)                                        NULL,
    [PostalAddressLine1]                       NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAddressLine2]                       NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAddressLine3]                       NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAddressLine4]                       NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAddressLine5]                       NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAddressCountry]                     NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAddressPostcode]                    NVARCHAR (4) MASKED WITH (FUNCTION = 'default()')   NULL,
    [PostalAddressPostcodeName]                NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAddressRegion]                      NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PostalAvetmissCountry]                    NVARCHAR (4) MASKED WITH (FUNCTION = 'default()')   NULL,
    [HomePhone]                                NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [WorkPhone]                                NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [MobilePhone]                              NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [QualificationAdvancedCertificate]         NVARCHAR (5)                                        NULL,
    [QualificationAdvancedCertificateLocation] NVARCHAR (50)                                       NULL,
    [QualificationAdvancedDiploma]             NVARCHAR (5)                                        NULL,
    [QualificationAdvancedDiplomaLocation]     NVARCHAR (50)                                       NULL,
    [QualificationAssociateDiploma]            NVARCHAR (5)                                        NULL,
    [QualificationAssociateDiplomaLocation]    NVARCHAR (50)                                       NULL,
    [QualificationCertificateI]                NVARCHAR (5)                                        NULL,
    [QualificationCertificateILocation]        NVARCHAR (50)                                       NULL,
    [QualificationCertificateII]               NVARCHAR (5)                                        NULL,
    [QualificationCertificateIILocation]       NVARCHAR (50)                                       NULL,
    [QualificationDegree]                      NVARCHAR (5)                                        NULL,
    [QualificationDegreeLocation]              NVARCHAR (50)                                       NULL,
    [QualificationOtherCertificate]            NVARCHAR (5)                                        NULL,
    [QualificationOtherCertificateLocation]    NVARCHAR (50)                                       NULL,
    [QualificationTradeCertificate]            NVARCHAR (5)                                        NULL,
    [QualificationTradeCertificateLocation]    NVARCHAR (50)                                       NULL,
    [ResidentialAddressLine1]                  NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ResidentialAddressLine2]                  NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ResidentialAddressLine3]                  NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ResidentialAddressLine4]                  NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ResidentialAddressLine5]                  NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ResidentialCountry]                       NVARCHAR (50)                                       NULL,
    [ResidentialRegion]                        NVARCHAR (3)                                        NULL,
    [ResidentialAvetmissCountry]               NVARCHAR (4)                                        NULL,
    [StillAttendSchool]                        NVARCHAR (20)                                       NULL,
    [Surname]                                  NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [Title]                                    NVARCHAR (10)                                       NULL,
    [VisaClassName]                            NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [VisaClassNo]                              INT MASKED WITH (FUNCTION = 'default()')            NULL,
    [YearOfArrival]                            INT                                                 NULL,
    [YearSchoolCompleted]                      INT                                                 NULL,
    [DateUSIVerified]                          DATE                                                NULL,
    [USIManuallyVerified]                      NVARCHAR (1)                                        NULL,
    [VisaType]                                 NVARCHAR (5) MASKED WITH (FUNCTION = 'default()')   NULL,
    [VisaSubClass]                             NVARCHAR (10) MASKED WITH (FUNCTION = 'default()')  NULL,
    [VisaSubClassDescription]                  NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [VisaHolderCode]                           NVARCHAR (10) MASKED WITH (FUNCTION = 'default()')  NULL,
    [VisaHolderDescription]                    NVARCHAR (75) MASKED WITH (FUNCTION = 'default()')  NULL,
    [IsTemporaryVisaHolder]                    NVARCHAR (1)                                        NULL,
    [VisaIssueDate]                            DATE MASKED WITH (FUNCTION = 'default()')           NULL,
    [VisaExpiryDate]                           DATE MASKED WITH (FUNCTION = 'default()')           NULL,
    [ARIA11B]                                  NVARCHAR (50)                                       NULL,
    [HighestPreviousQualification]             NVARCHAR (100)                                      NULL,
    [RegionalRemoteFlag]                       NVARCHAR (50)                                       NULL,
    [SEIFADecile]                              INT                                                 NULL,
    [SEIFAPercentile]                          INT                                                 NULL,
    [LGA_Name]                                 NVARCHAR (50)                                       NULL,
    [ResidentialStatus]                        NVARCHAR (200)                                      NULL,
    [USIProvided]                              NVARCHAR (20)                                       NULL,
    [VisaProvided]                             NVARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [AusState]                                 NVARCHAR (3)                                        NULL,
    [SA4NAME]                                  NVARCHAR (50)                                       NULL,
    [SA2NAME]                                  NVARCHAR (50)                                       NULL,
    [SurveyContactStatus]                      NVARCHAR (10)                                       NULL,
    [_DLCuratedZoneTimeStamp]                  DATETIME2 (7)                                       NULL,
    [_RecordStart]                             DATETIME2 (7)                                       NULL,
    [_RecordEnd]                               DATETIME2 (7)                                       NULL,
    [_RecordDeleted]                           INT                                                 NULL,
    [_RecordCurrent]                           INT                                                 NULL
);








GO
