CREATE TABLE [compliance].[AvetmissPrimaryLearner] (
    [AvetmissPrimaryLearnerSK]  BIGINT                                              NULL,
    [MatchGroupID]              NVARCHAR (255)                                      NULL,
    [Surname]                   NVARCHAR (255) MASKED WITH (FUNCTION = 'default()') NULL,
    [FirstName]                 NVARCHAR (255) MASKED WITH (FUNCTION = 'default()') NULL,
    [DateOfBirth]               DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PersonCode]                NVARCHAR (255)                                      NULL,
    [RegistrationNo]            NVARCHAR (255)                                      NULL,
    [PrimaryPersonCode]         NVARCHAR (255)                                      NULL,
    [PrimaryRegistrationNo]     NVARCHAR (255)                                      NULL,
    [PrimaryLearner]            NVARCHAR (255)                                      NULL,
    [PrimaryRecordFlag]         NVARCHAR (255)                                      NULL,
    [USIValue]                  NVARCHAR (255)                                      NULL,
    [USIScore]                  INT                                                 NULL,
    [MobilePhoneValue]          NVARCHAR (255) MASKED WITH (FUNCTION = 'default()') NULL,
    [MobilePhoneScore]          INT MASKED WITH (FUNCTION = 'default()')            NULL,
    [EntitlementValue]          NVARCHAR (255)                                      NULL,
    [EntitlementScore]          INT                                                 NULL,
    [PersonalEmailValue]        NVARCHAR (255) MASKED WITH (FUNCTION = 'default()') NULL,
    [PersonalEmailScore]        INT MASKED WITH (FUNCTION = 'default()')            NULL,
    [RegistrationNoValue]       NVARCHAR (255)                                      NULL,
    [MisingRegistrationNoScore] INT                                                 NULL,
    [EnrolmentCount]            BIGINT                                              NULL,
    [EnrolmentScore]            BIGINT                                              NULL,
    [FeeRecordCountByEnrolment] BIGINT                                              NULL,
    [FeeRecordCountByScore]     BIGINT                                              NULL,
    [ProgressCourseCount]       BIGINT                                              NULL,
    [ProgressCourseScore]       BIGINT                                              NULL,
    [PreviousForenameValue]     NVARCHAR (255)                                      NULL,
    [PreviousForenameScore]     INT                                                 NULL,
    [AddressLine1Value]         NVARCHAR (255) MASKED WITH (FUNCTION = 'default()') NULL,
    [DoNotMigrateScore]         INT                                                 NULL,
    [CompletedThisYearCount]    BIGINT                                              NULL,
    [CompletedThisYearScore]    BIGINT                                              NULL,
    [TotalScore]                BIGINT                                              NULL,
    [_DLCuratedZoneTimeStamp]   DATETIME2 (7)                                       NULL,
    [_RecordStart]              DATETIME2 (7)                                       NULL,
    [_RecordEnd]                DATETIME2 (7)                                       NULL,
    [_RecordDeleted]            INT                                                 NULL,
    [_RecordCurrent]            INT                                                 NULL
);


GO

