CREATE TABLE [compliance].[AvetmissCourseEnrolment] (
    [AvetmissCourseEnrolmentSK]                        BIGINT                                            NULL,
    [ReportingYear]                                    NVARCHAR (10)                                     NULL,
    [CourseOfferingEnrolmentId]                        BIGINT                                            NULL,
    [AvetmissCourseCode]                               NVARCHAR (10)                                     NULL,
    [DeliveryLocationCode]                             NVARCHAR (10)                                     NULL,
    [AvetmissClientId]                                 NVARCHAR (20)                                     NULL,
    [InstituteId]                                      INT                                               NULL,
    [AvetmissClientIdMissingFlag]                      NVARCHAR (1)                                      NULL,
    [StudentId]                                        INT                                               NULL,
    [CourseOfferingId]                                 INT                                               NULL,
    [CourseCaloccCode]                                 NVARCHAR (10)                                     NULL,
    [CourseCode]                                       NVARCHAR (20)                                     NULL,
    [NationalCourseCode]                               NVARCHAR (20)                                     NULL,
    [CourseCodeConverted]                              NVARCHAR (30)                                     NULL,
    [CourseEnrolmentStartDate]                         DATE                                              NULL,
    [CourseEnrolmentEndDate]                           DATE                                              NULL,
    [CourseProgressCode]                               NVARCHAR (20)                                     NULL,
    [CourseProgressStatus]                             NVARCHAR (1)                                      NULL,
    [CourseProgressReason]                             NVARCHAR (100)                                    NULL,
    [CourseProgressDate]                               DATE                                              NULL,
    [CourseAwardDate]                                  DATE                                              NULL,
    [CourseAwardDescription]                           NVARCHAR (200)                                    NULL,
    [CourseAwardStatus]                                NVARCHAR (20)                                     NULL,
    [CourseFundingSourceCode]                          NVARCHAR (5)                                      NULL,
    [FundingSourceNationalID]                          NVARCHAR (5) MASKED WITH (FUNCTION = 'default()') NULL,
    [CourseEnrolmentIdTransitionFrom]                  BIGINT                                            NULL,
    [CourseCodeTransitionFrom]                         NVARCHAR (20)                                     NULL,
    [CourseCaloccCodeTransitionFrom]                   NVARCHAR (10)                                     NULL,
    [CourseEnrolmentStartDateTransitionFrom]           DATE                                              NULL,
    [CourseOfferingRemarks]                            NVARCHAR (40)                                     NULL,
    [CourseOfferingFunctionalUnit]                     NVARCHAR (10)                                     NULL,
    [ReportingYearStartDate]                           DATE                                              NULL,
    [ReportingYearEndDate]                             DATE                                              NULL,
    [CourseAwardFlag]                                  NVARCHAR (1)                                      NULL,
    [GraduateFlag]                                     NVARCHAR (1)                                      NULL,
    [CourseProgressRank]                               INT                                               NULL,
    [SubsidisedAmount]                                 MONEY MASKED WITH (FUNCTION = 'default()')        NULL,
    [StandardSubsidyAmount]                            MONEY MASKED WITH (FUNCTION = 'default()')        NULL,
    [NeedsLoadingAmount]                               MONEY MASKED WITH (FUNCTION = 'default()')        NULL,
    [LocationLoadingAmount]                            MONEY MASKED WITH (FUNCTION = 'default()')        NULL,
    [APPRTRAINEE]                                      NVARCHAR (1)                                      NULL,
    [CommitmentIdentifier]                             NVARCHAR (20)                                     NULL,
    [EnrolmentTeachingSectionName]                     NVARCHAR (100)                                    NULL,
    [HasLongTermUnemploymentEvidence]                  NVARCHAR (1)                                      NULL,
    [CourseEnrolmentOfferingType]                      NVARCHAR (10)                                     NULL,
    [TrainingContractID]                               NVARCHAR (10)                                     NULL,
    [WhoToPay]                                         NVARCHAR (20)                                     NULL,
    [EmployerPostcode]                                 NVARCHAR (10)                                     NULL,
    [EmployerSuburb]                                   NVARCHAR (20)                                     NULL,
    [WorksInNSW]                                       NVARCHAR (10)                                     NULL,
    [VFHCourse]                                        NVARCHAR (1)                                      NULL,
    [OriginalFee]                                      MONEY                                             NULL,
    [ActualFee]                                        MONEY                                             NULL,
    [FeePaid]                                          MONEY                                             NULL,
    [FeeInstalment]                                    MONEY                                             NULL,
    [FeeAdjustment]                                    MONEY                                             NULL,
    [FeeOutstanding]                                   MONEY                                             NULL,
    [ProgramStartDate]                                 DATE                                              NULL,
    [TotalHours]                                       INT                                               NULL,
    [RPLHours]                                         INT                                               NULL,
    [TrainingHours]                                    INT                                               NULL,
    [ContinuingHours]                                  INT                                               NULL,
    [ValidUnitCount]                                   INT                                               NULL,
    [UnitCount]                                        INT                                               NULL,
    [FinalGradeUnitCount]                              INT                                               NULL,
    [PassGradeUnitCount]                               INT MASKED WITH (FUNCTION = 'default()')          NULL,
    [WithdrawnUnitCount]                               INT                                               NULL,
    [FailGradeUnitCount]                               INT                                               NULL,
    [RPLUnitCount]                                     INT                                               NULL,
    [CreditTransferUnitCount]                          INT MASKED WITH (FUNCTION = 'default()')          NULL,
    [NonAssessableUnitCount]                           INT                                               NULL,
    [MissingGradeUnitCount]                            INT                                               NULL,
    [ContinuingUnitCount]                              INT                                               NULL,
    [RPLGrantedUnitCount]                              INT                                               NULL,
    [RPLNotGrantedUnitCount]                           INT                                               NULL,
    [CreditTransferNationalRecognitionUnitCount]       INT MASKED WITH (FUNCTION = 'default()')          NULL,
    [SupersededUnitCount]                              INT                                               NULL,
    [NonAssessableSatisfactorilyCompletedUnitCount]    INT                                               NULL,
    [NonAssessableNotSatisfactorilyCompletedUnitCount] INT                                               NULL,
    [PayableUnitCount]                                 INT                                               NULL,
    [Semester1UnitCount]                               INT                                               NULL,
    [Semester2UnitCount]                               INT                                               NULL,
    [Semester3UnitCount]                               INT                                               NULL,
    [Semester1Hours]                                   INT                                               NULL,
    [Semester2Hours]                                   INT                                               NULL,
    [ExemptedDeliveryUnitCount]                        INT                                               NULL,
    [InClassDeliveryUnitCount]                         INT                                               NULL,
    [DistanceDeliveryUnitCount]                        INT                                               NULL,
    [ElectronicDeliveryUnitCount]                      INT                                               NULL,
    [BlendedDeliveryUnitCount]                         INT                                               NULL,
    [SelfDeliveryUnitCount]                            INT                                               NULL,
    [OnTheJobTrainingDeliveryUnitCount]                INT                                               NULL,
    [OnTheJobDistanceDeliveryUnitCount]                INT                                               NULL,
    [SimulatedDeliveryUnitCount]                       INT                                               NULL,
    [MissingDeliveryModeUnitCount]                     INT                                               NULL,
    [OtherDeliveryUnitCount]                           INT                                               NULL,
    [DeliveredUnitCount]                               INT                                               NULL,
    [ValidFlag]                                        INT                                               NULL,
    [ValidUnitExistsFlag]                              INT                                               NULL,
    [PayableUnitExistsFlag]                            INT                                               NULL,
    [ShellEnrolmentFlag]                               INT                                               NULL,
    [ID_PC]                                            NVARCHAR (50)                                     NULL,
    [ID_UIO]                                           NVARCHAR (50)                                     NULL,
    [ID_CPU]                                           NVARCHAR (50)                                     NULL,
    [ID_NCC]                                           NVARCHAR (50)                                     NULL,
    [ID_CE]                                            NVARCHAR (50)                                     NULL,
    [TafeDigital]                                      INT                                               NULL,
    [OTEN]                                             INT                                               NULL,
    [TOL]                                              INT                                               NULL,
    [TNW]                                              INT                                               NULL,
    [OPEN]                                             INT                                               NULL,
    [Age]                                              INT                                               NULL,
    [AgeGroup]                                         NVARCHAR (20)                                     NULL,
    [ANZSCO]                                           NVARCHAR (10)                                     NULL,
    [ARIA11B]                                          NVARCHAR (20)                                     NULL,
    [AWARD]                                            INT                                               NULL,
    [CommencementFlag]                                 NVARCHAR (20)                                     NULL,
    [CommencementSemester]                             NVARCHAR (10)                                     NULL,
    [CommencementYear]                                 INT                                               NULL,
    [GRAD]                                             INT                                               NULL,
    [YEAR_COMPLETE]                                    INT                                               NULL,
    [COREFND]                                          NVARCHAR (10)                                     NULL,
    [AVETCOUNT]                                        INT                                               NULL,
    [ENRFLAG]                                          INT                                               NULL,
    [AvetmissFlag]                                     NVARCHAR (1)                                      NULL,
    [CSENM]                                            NVARCHAR (100)                                    NULL,
    [FOE4]                                             NVARCHAR (4)                                      NULL,
    [AVFUND]                                           INT                                               NULL,
    [FundingVFH]                                       NVARCHAR (40)                                     NULL,
    [HIGHED]                                           NVARCHAR (20)                                     NULL,
    [HQUALN]                                           NVARCHAR (30)                                     NULL,
    [SECED]                                            NVARCHAR (30)                                     NULL,
    [ISC]                                              NVARCHAR (40)                                     NULL,
    [LGANAM]                                           NVARCHAR (40)                                     NULL,
    [RIND11]                                           NVARCHAR (30)                                     NULL,
    [SponsorOrginationCode]                            NVARCHAR (10)                                     NULL,
    [SponsorCode]                                      NVARCHAR (100)                                    NULL,
    [SA_STATE]                                         NVARCHAR (4)                                      NULL,
    [SA4_NAME]                                         NVARCHAR (50)                                     NULL,
    [SA2_NAME]                                         NVARCHAR (50)                                     NULL,
    [Decile]                                           INT                                               NULL,
    [Percentile]                                       INT                                               NULL,
    [WelfareStatus]                                    INT                                               NULL,
    [UnitsDeliveryMode]                                NVARCHAR (10)                                     NULL,
    [SkillsPoint]                                      INT                                               NULL,
    [StudyReason]                                      NVARCHAR (2)                                      NULL,
    [CTOnly]                                           INT                                               NULL,
    [Region]                                           NVARCHAR (20)                                     NULL,
    [TransitionFlag]                                   NVARCHAR (1)                                      NULL,
    [FeeHelpFlag]                                      NVARCHAR (1)                                      NULL,
    [VSLFlag]                                          NVARCHAR (1)                                      NULL,
    [SBIGroup]                                         NVARCHAR (30)                                     NULL,
    [SBICategory]                                      NVARCHAR (50)                                     NULL,
    [SBISubCategory]                                   NVARCHAR (100)                                    NULL,
    [TSNSWFundCode]                                    NVARCHAR (3)                                      NULL,
    [TSNSWFundGroupCode]                               NVARCHAR (3)                                      NULL,
    [WaiverCodes]                                      NVARCHAR (100)                                    NULL,
    [OrganisationTypeDescription]                      NVARCHAR (100)                                    NULL,
    [PredominantDeliveryMode]                          NVARCHAR (20)                                     NULL,
    [SubsidyStatus]                                    NVARCHAR (20)                                     NULL,
    [AwardID]                                          INT                                               NULL,
    [IssuedFlag]                                       NVARCHAR (3)                                      NULL,
    [ParchmentIssueDate]                               DATETIME2 (7)                                     NULL,
    [DateConferred]                                    DATETIME2 (7)                                     NULL,
    [ConfigurableStatusID]                             INT                                               NULL,
    [AttainmentCreatedDate]                            DATETIME2 (7)                                     NULL,
    [AttainmentUpdatedDate]                            DATETIME2 (7)                                     NULL,
    [ProgramStream]                                    NVARCHAR (1)                                      NULL,
    [CourseDeliveryLocation2]                          NVARCHAR (10)                                     NULL,
    [ReportingDate]                                    DATE                                              NULL,
    [EnrolCountPU]                                     INT                                               NULL,
    [_DLCuratedZoneTimeStamp]                          DATETIME2 (7)                                     NULL,
    [_RecordStart]                                     DATETIME2 (7)                                     NULL,
    [_RecordEnd]                                       DATETIME2 (7)                                     NULL,
    [_RecordDeleted]                                   INT                                               NULL,
    [_RecordCurrent]                                   INT                                               NULL
);

GO

CREATE NONCLUSTERED INDEX [Avetmiss_Course_StudentId]
    ON [compliance].[AvetmissCourseEnrolment]([StudentId] ASC);
GO

CREATE NONCLUSTERED INDEX [idx_AvetmissCourseEnrolment_ReportingDate]
    ON [compliance].[AvetmissCourseEnrolment]([ReportingDate] ASC);
GO

CREATE NONCLUSTERED INDEX [idx_AvetmissCourseEnrolment_ReportingYear]
    ON [compliance].[AvetmissCourseEnrolment]([ReportingYear] ASC);
GO

CREATE NONCLUSTERED INDEX [idx_AvetmissCourseEnrolment_ReportingYearReportingDate]
    ON [compliance].[AvetmissCourseEnrolment]([ReportingYear] ASC, [ReportingDate] ASC);
GO

