CREATE TABLE [compliance].[AvetmissUnitEnrolment] (
    [AvetmissUnitEnrolmentSK]                BIGINT                                             NULL,
    [RecordSource]                           NVARCHAR (50)                                      NULL,
    [InstituteId]                            INT                                                NULL,
    [UnitEnrolmentId]                        BIGINT                                             NULL,
    [UnitDeliveryLocationCode]               NVARCHAR (50)                                      NULL,
    [AvetmissClientId]                       NVARCHAR (50)                                      NULL,
    [AvetmissClientIdMissingFlag]            NVARCHAR (1)                                       NULL,
    [StudentId]                              BIGINT                                             NULL,
    [UnitOfferingEnrolmentId]                BIGINT                                             NULL,
    [UnitOfferingCode]                       NVARCHAR (50)                                      NULL,
    [AvetmissUnitCode]                       NVARCHAR (50)                                      NULL,
    [UnitCode]                               NVARCHAR (50)                                      NULL,
    [NationalUnitCode]                       NVARCHAR (50)                                      NULL,
    [DeliveryMode]                           NVARCHAR (50)                                      NULL,
    [UnitEnrolmentStartDate]                 DATE                                               NULL,
    [UnitEnrolmentEndDate]                   DATE                                               NULL,
    [AvetmissDeliveryMode]                   NVARCHAR (50)                                      NULL,
    [UnitScheduledHours]                     INT                                                NULL,
    [UnitFundingSourceCode]                  NVARCHAR (50)                                      NULL,
    [AvetmissSpecificFundingId]              NVARCHAR (50)                                      NULL,
    [AvetmissFundingSourceNationalId]        NVARCHAR (50) MASKED WITH (FUNCTION = 'default()') NULL,
    [UnitRecognitionType]                    NVARCHAR (50)                                      NULL,
    [UnitAwardDate]                          DATE                                               NULL,
    [Grade]                                  NVARCHAR (50)                                      NULL,
    [AdjustedGrade]                          NVARCHAR (50)                                      NULL,
    [UnitOutcome]                            NVARCHAR (50)                                      NULL,
    [DateConferred]                          DATE                                               NULL,
    [SDRCompletionCode]                      NVARCHAR (50)                                      NULL,
    [UnitHoursAttended]                      INT                                                NULL,
    [UnitOfferingId]                         BIGINT                                             NULL,
    [UnitProgressCode]                       NVARCHAR (50)                                      NULL,
    [UnitProgressStatus]                     NVARCHAR (50)                                      NULL,
    [UnitProgressReason]                     NVARCHAR (200)                                     NULL,
    [UnitProgressDate]                       DATE                                               NULL,
    [UnitSponsorOrganisationCode]            NVARCHAR (50)                                      NULL,
    [UnitOfferingFunctionalUnit]             NVARCHAR (50)                                      NULL,
    [AttainmentCode]                         BIGINT                                             NULL,
    [AcademicHistoryMissingFlag]             INT                                                NULL,
    [UnitLevelStatus]                        NVARCHAR (50)                                      NULL,
    [UnitLevelStatusActive]                  NVARCHAR (2)                                       NULL,
    [UnitLevelStatusType]                    NVARCHAR (20)                                      NULL,
    [CourseOfferingEnrolmentId]              BIGINT                                             NULL,
    [CourseOfferingCode]                     NVARCHAR (50)                                      NULL,
    [CourseOfferingId]                       BIGINT                                             NULL,
    [CourseDeliveryLocationCode]             NVARCHAR (50)                                      NULL,
    [CourseCode]                             NVARCHAR (50)                                      NULL,
    [NationalCourseCode]                     NVARCHAR (50)                                      NULL,
    [CourseCodeConverted]                    NVARCHAR (50)                                      NULL,
    [CourseProgressCode]                     NVARCHAR (50)                                      NULL,
    [CourseProgressReason]                   NVARCHAR (200)                                     NULL,
    [CourseProgressStatus]                   NVARCHAR (50)                                      NULL,
    [CourseProgressDate]                     DATE                                               NULL,
    [CourseAwardDate]                        DATE                                               NULL,
    [CourseEnrolmentStartDate]               DATE                                               NULL,
    [CourseEnrolmentEndDate]                 DATE                                               NULL,
    [CourseFundingSourceCode]                NVARCHAR (50)                                      NULL,
    [CourseAwardDescription]                 NVARCHAR (250)                                     NULL,
    [CourseAwardStatus]                      NVARCHAR (50)                                      NULL,
    [CourseOfferingRemarks]                  NVARCHAR (250)                                     NULL,
    [CourseOfferingFunctionalUnit]           NVARCHAR (50)                                      NULL,
    [CourseEnrolmentIdTransitionFrom]        BIGINT                                             NULL,
    [CourseCodeTransitionFrom]               NVARCHAR (50)                                      NULL,
    [CourseCaloccCodeTransitionFrom]         NVARCHAR (50)                                      NULL,
    [CourseEnrolmentStartDateTransitionFrom] DATE                                               NULL,
    [CourseEnrolmentCreatedDate]             DATE                                               NULL,
    [StudyReasonID]                          NVARCHAR (50)                                      NULL,
    [StudyReasonDescription]                 NVARCHAR (250)                                     NULL,
    [DeliveryLocationName]                   NVARCHAR (50)                                      NULL,
    [VetInSchoolFlag]                        NVARCHAR (1)                                       NULL,
    [ReportingYear]                          NVARCHAR (50)                                      NULL,
    [ReportingYearStartDate]                 DATE                                               NULL,
    [ReportingYearEndDate]                   DATE                                               NULL,
    [AvetmissCourseCode]                     NVARCHAR (50)                                      NULL,
    [ProgramStartDate]                       DATE                                               NULL,
    [CourseCommencementYear]                 INT                                                NULL,
    [CourseCommencementSemester]             NVARCHAR (50)                                      NULL,
    [CommencingProgramIdentifier]            NVARCHAR (100)                                     NULL,
    [OutcomeNational]                        NVARCHAR (50)                                      NULL,
    [ValidFlag]                              INT                                                NULL,
    [IncludeFlag]                            INT                                                NULL,
    [AvetmissScheduledHours]                 INT                                                NULL,
    [Semester1Hours]                         INT                                                NULL,
    [Semester2Hours]                         INT                                                NULL,
    [FinalUnit]                              INT                                                NULL,
    [ID_UUIO]                                NVARCHAR (50)                                      NULL,
    [ID_UPU]                                 NVARCHAR (50)                                      NULL,
    [ID_CPU]                                 NVARCHAR (50)                                      NULL,
    [ID_PC]                                  NVARCHAR (50)                                      NULL,
    [SponsorDescription]                     NVARCHAR (200)                                     NULL,
    [ProgramStream]                          NVARCHAR (1)                                       NULL,
    [ReportingDate]                          DATE                                               NULL,
    [UnitEndDate]                            DATE                                               NULL,
    [AttainmentCreatedDate]                  DATETIME2 (7)                                      NULL,
    [AttainmentUpdatedDate]                  DATETIME2 (7)                                      NULL,
    [_DLCuratedZoneTimeStamp]                DATETIME2 (7)                                      NULL,
    [_RecordStart]                           DATETIME2 (7)                                      NULL,
    [_RecordEnd]                             DATETIME2 (7)                                      NULL,
    [_RecordDeleted]                         INT                                                NULL,
    [_RecordCurrent]                         INT                                                NULL,
    [OriginalDeliveryMode]                   NVARCHAR (50)                                      NULL,
    [SponsorCode]                            VARCHAR (500)                                      NULL
);

GO

CREATE NONCLUSTERED INDEX [idx_AvetmissUnitEnrolment_ReportingDate]
    ON [compliance].[AvetmissUnitEnrolment]([ReportingDate] ASC);
GO

CREATE NONCLUSTERED INDEX [idx_AvetmissUnitEnrolment_ReportingYear]
    ON [compliance].[AvetmissUnitEnrolment]([ReportingYear] ASC);
GO

CREATE NONCLUSTERED INDEX [idx_AvetmissUnitEnrolment_ReportingYearReportingDate]
    ON [compliance].[AvetmissUnitEnrolment]([ReportingYear] ASC, [ReportingDate] ASC);
GO

