trigger:
  branches:
    include:
      - master
      - develop
  paths:  
    include: 
      - Automation/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- bash: |
    mkdir -p "$(Build.ArtifactStagingDirectory)/automation"
    cp Automation/RotateStorageSASTokens.ps1 "$(Build.ArtifactStagingDirectory)/automation/RotateStorageSASTokens.ps1"
  displayName: 'Prepare Automation Build Artifacts'
  
- task: PublishBuildArtifacts@1
  displayName: Publish Automation Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/automation'
    artifactName: automation
