trigger:
  branches:
    include:
      - master
      - develop
  paths:  
    include: 
      - AzureResources/*

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- bash: |
    mkdir -p "$(Build.ArtifactStagingDirectory)/arm_template"
    cp AzureResources/azuredeploy.parameters.json "$(Build.ArtifactStagingDirectory)/arm_template/azuredeploy.parameters.json"
    cp AzureResources/azuredeploy.json "$(Build.ArtifactStagingDirectory)/arm_template/azuredeploy.json"
  displayName: 'Prepare Azure Resource Manager template Build Artifacts'

- task: PublishBuildArtifacts@1
  displayName: Publish ARM Template Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/arm_template'
    artifactName: arm_template