# Databricks notebook source
RBAC_UC1 = [
    {
        "Name" : "DataAnalystAdvUsr"
        ,"ExistingGroup" : "True"
        ,"OtherCommands" : [
        ]
        ,"TableFilter" : [
            "raw.access*"
            ,"raw.isu*"
            ,"raw.crm*"
            ,"raw.hydra_tlotparcel"
            ,"raw.hydra_tsystemarea"
            ,"cleansed.access*"
            ,"cleansed.isu*"
            ,"cleansed.crm*"
            ,"cleansed.hydra_tlotparcel"
            ,"cleansed.hydra_tsystemarea"
            ,"curated.brginstallationpropertymetercontract"
            ,"curated.dimbusinesspartner"
            ,"curated.dimbusinesspartnergroup"
            ,"curated.dimcontract"
            ,"curated.dimdate"
            ,"curated.diminstallation"
            ,"curated.dimlocation"
            ,"curated.dimmeter"
            ,"curated.dimmeterconsumptionbillingdocument"
            ,"curated.dimmeterconsumptionbillinglineitem"
            ,"curated.dimmeterinstallation"
            ,"curated.dimmetertimeslice"
            ,"curated.dimproperty"
            ,"curated.dimsewernetwork"
            ,"curated.dimstormwaternetwork"
            ,"curated.dimwaternetwork"
            ,"curated.factbilledwaterconsumption"
            ,"curated.factmonthlyapportionedconsumption"
            ,"curated.view_contract"
            ,"curated.view_contractaccount"
            ,"curated.view_device"
            ,"curated.view_installation"
            ,"curated.view_property"
            ,"curated.view_propertyrelationship"
            ,"curated.view_propertyservices"
            ,"curated.view_qqv"
            ,"curated.view_zbl"
            ,"curated.viewbilledwaterconsumption"
            ,"curated.viewmonthlyapportionedconsumption"
            ,"curated_v2.dimaccountbusinesspartner"
            ,"curated_v2.dimbusinesspartner"
            ,"curated_v2.dimbusinesspartneraddress"
            ,"curated_v2.dimbusinesspartnergroup"
            ,"curated_v2.dimbusinesspartneridentification"
            ,"curated_v2.dimbusinesspartnerrelation"
            ,"curated_v2.dimcontract"
            ,"curated_v2.dimcontractaccount"
            ,"curated_v2.dimcontracthistory"
            ,"curated_v2.dimdate"
            ,"curated_v2.dimdevice"
            ,"curated_v2.dimdevicecharacteristics"
            ,"curated_v2.dimdevicehistory"
            ,"curated_v2.dimdeviceinstallationhistory"
            ,"curated_v2.dimdisconnectiondocument"
            ,"curated_v2.diminstallation"
            ,"curated_v2.diminstallationfacts"
            ,"curated_v2.diminstallationhistory"
            ,"curated_v2.dimlocation"
            ,"curated_v2.dimmeterconsumptionbillingdocument"
            ,"curated_v2.dimmeterconsumptionbillinglineitem"
            ,"curated_v2.dimproperty"
            ,"curated_v2.dimpropertylot"
            ,"curated_v2.dimpropertyrelation"
            ,"curated_v2.dimpropertyservice"
            ,"curated_v2.dimpropertytypehistory"
            ,"curated_v2.dimregisterhistory"
            ,"curated_v2.dimregisterinstallationhistory"
            ,"curated_v2.dimsewernetwork"
            ,"curated_v2.dimstormwaternetwork"
            ,"curated_v2.dimwaternetwork"
            ,"curated_v2.factbilledwaterconsumption"
            ,"curated_v2.factmonthlyapportionedconsumption"
            ,"curated_v2.viewbusinesspartner"
            ,"curated_v2.viewbusinesspartnergroup"
            ,"curated_v2.viewcontract"
            ,"curated_v2.viewcontractaccount"
            ,"curated_v2.viewdevice"
            ,"curated_v2.viewdevicecharacteristics"
            ,"curated_v2.viewinstallation"
            ,"curated_v2.viewproperty"
            ,"curated_v2.viewpropertyrelation"
            ,"curated_v2.viewpropertyservice"
        ]
        ,"Users" : []
        ,"AADGroups" : []
    }
]

# COMMAND ----------


