# Databricks notebook source
# MAGIC %run ./dimensions/Property

# COMMAND ----------

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<AUTO GENERATED BY CONFLICT EXTENSION<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< develop
# MAGIC %run ./dimensions/Location

# COMMAND ----------

# MAGIC %run ./dimensions/Date

# COMMAND ----------
====================================AUTO GENERATED BY CONFLICT EXTENSION====================================
# MAGIC %run ./dimensions/BillingDocumentSapisu

# COMMAND ----------
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>AUTO GENERATED BY CONFLICT EXTENSION>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> dev_Kumar_SP2_v02

#%run ./dimensions/OfferingSkillsPoint

# COMMAND ----------

#%run ./dimensions/UnitOffering

# COMMAND ----------

# MAGIC %run ./dimensions/Meter
