# Databricks notebook source
# MAGIC %run /MDP-Framework/ControlDB/common-controldb

# COMMAND ----------

tables = ['ADDRESS', 'ALNDOMAIN', 'ASSET', 'ASSETATTRIBUTE', 'ASSETMETER', 'ASSETSPEC', 'CLASSIFICATION', 'CLASSSTRUCTURE', 'CONTRACT', 'DOCLINKS', 'FAILURECODE', 'FAILUREREPORT', 'FINCNTRL', 'JOBLABOR', 'JOBPLAN', 'LABOR', 'LABTRANS', 'LOCANCESTOR', 'LOCATIONMETER', 'LOCATIONS', 'LOCATIONSPEC', 'LOCHIERARCHY', 'LOCOPER', 'LONGDESCRIPTION', 'MATUSETRANS', 'MAXINTMSGTRK', 'MULTIASSETLOCCI', 'PERSON', 'PERSONGROUP', 'PERSONGROUPTEAM', 'PHONE', 'PM', 'RELATEDRECORD', 'ROUTE_STOP', 'ROUTES', 'SERVRECTRANS', 'SWCBUSSTATUS', 'SWCHIERARCHY', 'SWCLGA', 'SWCPROBLEMTYPE', 'SWCWOEXT', 'SYNONYMDOMAIN', 'TICKET', 'TOOLTRANS', 'WOANCESTOR', 'WORKLOG', 'WORKORDER', 'WORKORDERSPEC', 'WOSTATUS', 'DOCINFO', 'ACCOUNTDEFAULTS', 'ACTCI', 'ACTCIRELATION', 'ACTCISPEC', 'ACTION', 'ACTIONGROUP', 'ACTIONSCFG', 'ALTITEM', 'AMCREW', 'AMCREWLABOR', 'AMCREWLABPOS', 'AMCREWMODAVAIL', 'AMCREWQUAL', 'AMCREWSTATHIS', 'AMCREWT', 'AMCREWTOOL', 'AMCREWTOOLSQ', 'AMCREWWOLAB', 'AMCREWWORKZONE', 'AMCREWWOTL', 'AMCTCRAFT', 'AMCTQUAL', 'AMCTSTATHIST', 'AMCTTOOL', 'APPDOCTYPE', 'APPLICATIONAUTH', 'ARCHIVE', 'AREASAFFECTED', 'ASSETANCESTOR', 'ASSETFEASPECHIST', 'ASSETFEATURE', 'ASSETFEATUREHIST', 'ASSETFEATURESPEC', 'ASSETHIERARCHY', 'ASSETHISTORY', 'ASSETLOCCOMM', 'ASSETLOCRELATION', 'ASSETLOCRELHIST', 'ASSETLOCUSERCUST', 'ASSETMNTSKD', 'ASSETOPSKD', 'ASSETSPECHIST', 'ASSETSTATUS', 'ASSETTOPOCACHE', 'ASSETTRANS', 'ASSETWORKZONE', 'ASSIGNMENT', 'ASSIGNREPLOC', 'ASTMSOVER', 'ASTSPECMSOVER', 'ATTENDANCE', 'AUTOATTRUPDATE', 'AUTOSCRIPTVARS', 'BBOARDAUDIENCE', 'BBOARDMSGSTATUS', 'BBSTATUSHISTORY', 'BILLTOSHIPTO', 'BOOKMARK', 'BULLETINBOARD', 'CALENDAR', 'CALENDARBREAK', 'CDMCITYPES', 'CHARPOINTACTION', 'CHARTOFACCOUNTS', 'CI', 'CIRELATION', 'CIRELATIONHIS', 'CISPEC', 'CISPECHIS', 'CISTATUS', 'CITEMPLATE', 'CITYPESTATUS', 'CLASSANCESTOR', 'CLASSSPEC', 'CLASSSPECUSEWITH', 'CLASSUSEWITH', 'COLLECTDETAILS', 'COLLECTION', 'COLLECTIONAUTH', 'COMMITGROUP', 'COMMITPERSON', 'COMMLOG', 'COMMLOGDOCS', 'COMMODITIES', 'COMMTEMPLATE', 'COMMTEMPLATEDOCS', 'COMMTMPLTSENDTO', 'COMPANIES', 'COMPANYACCDEF', 'COMPCOMMODITY', 'COMPCONTACT', 'COMPCONTACTMSTR', 'COMPMASTER', 'CONDITION', 'CONTASSETMETER', 'CONTCOMMODITY', 'CONTLINEASSET', 'CONTLINEMETER', 'CONTRACTASSET', 'CONTRACTAUTH', 'CONTRACTDEFAULT', 'CONTRACTLEASE', 'CONTRACTLINE', 'CONTRACTMASTER', 'CONTRACTPROPERTY', 'CONTRACTPURCH', 'CONTRACTSFW', 'CONTRACTSTATUS', 'CONTRACTSWLIC', 'CONTRACTTERM', 'CONTRACTTYPE', 'CONTRACTTYPETERM', 'CONTSFWLIC', 'CONVERSION', 'COSTTYPE', 'CRAFT', 'CRAFTRATE', 'CRAFTSKILL', 'CRONTASKHISTORY', 'CURRENCY', 'DEFAULTQUERY', 'DEPHISTORY', 'DEPLOYEDASSET', 'DEPRECIATION', 'DEPSCHED', 'DEPSCHEDHISTORY', 'DEPSCHEDPERIODS', 'DEPTRANS', 'DMSAPISETTING', 'DOCTYPES', 'DPACOMMDEVICE', 'DPACOMPUTER', 'DPACPU', 'DPADISK', 'DPADISPLAY', 'DPAFILE', 'DPAIMAGEDEVICE', 'DPAIPX', 'DPALOGICALDRIVE', 'DPAMEDIAADAPTER', 'DPANETADAPTER', 'DPANETDEVCARD', 'DPANETDEVICE', 'DPANETPRINTER', 'DPAOS', 'DPASOFTWARE', 'DPASWSUITE', 'DPATCPIP', 'DPAUSERINFO', 'EMAIL', 'ESCALATION', 'ESCNOTIFICATION', 'ESCREFPOINT', 'ESCREPEATTRACK', 'ESCSTATUS', 'EVENTRESPONSE', 'EXCHANGE', 'EXCLUDEPASSWORD', 'FACONFIG', 'FAILURELIST', 'FAILUREREMARK', 'FAVITEM', 'FEATURES', 'FEATURESPEC', 'FEATURESTATUS', 'FINANCIALPERIODS', 'GLAUTH', 'GLCOMPONENTS', 'GLCONFIGURE', 'GROUPUSER', 'GRPREASSIGNAUTH', 'HAZARD', 'HAZARDPREC', 'IBMCONTENTCATALOG', 'IBMCONTENTRECEIPTS', 'IMPROFILE', 'INBCOMMSECURITY', 'INBOUNDCOMM', 'INBOUNDCOMMCFG', 'INBXCONFIG', 'INVBALANCES', 'INVCOST', 'INVENTORY', 'INVLIFOFIFOCOST', 'INVLOT', 'INVOICE', 'INVOICECOST', 'INVOICELINE', 'INVOICEMATCH', 'INVOICESTATUS', 'INVOICETERM', 'INVOICETRANS', 'INVRESERVE', 'INVSTATUS', 'INVTRANS', 'INVUSE', 'INVUSELINE', 'INVUSELINESPLIT', 'INVUSESTATUS', 'INVVENDOR', 'ITEM', 'ITEMCONDITION', 'ITEMORGINFO', 'ITEMORGSTATUS', 'ITEMSPEC', 'ITEMSTATUS', 'ITEMSTRUCT', 'JOBITEM', 'JOBPLANCLASS', 'JOBPLANSPEC', 'JOBTASK', 'JOBTASKSPEC', 'JPASSETSPLINK', 'JPTASKRELATION', 'KPIAUTH', 'KPIGCONFIG', 'KPIHISTORY', 'KPILCONFIG', 'KPIMAIN', 'KPIOEE', 'KPISCHEDULE', 'KPITEMPLATE', 'KPITEMPLATEMAIN', 'KPITEMPLATEVAR', 'KPITEMPLATEVARVALUE', 'KPITRENDCFG', 'LABORAUTH', 'LABORCERTHIST', 'LABORCRAFTRATE', 'LABORQUAL', 'LABORQUALSTATUS', 'LABORSTATUS', 'LABORWORKZONE', 'LANGUAGE', 'LAUNCHPOINTVARS', 'LAYOUT', 'LBSLOCATION', 'LIMITTOLERANCE', 'LINEARREFMETHOD', 'LNRRECALIB', 'LNRRECALIBNONAF', 'LOCATIONMNTSKD', 'LOCATIONOPSKD', 'LOCATIONWORKZONE', 'LOCAUTH', 'LOCKOUT', 'LOCLEADTIME', 'LOCMETERREADING', 'LOCSTATUS', 'LOCSYSTEM', 'LOGINBLOCK', 'LOGINTRACKING', 'MAPMANAGER', 'MAPSITES', 'MAPTIP', 'MAPTIPDEFAULTS', 'MAPTIPMENU', 'MASTERPM', 'MASTERPMMETER', 'MASTERPMSEASONS', 'MASTERPMSEQ', 'MATRECTRANS', 'MAXASYNCJOB', 'MAXASYNCJOBMSG', 'MAXASYNCJOBPARAM', 'MAXDOMAINLINK', 'MAXDOMVALCOND', 'MAXDYNAMICDOMLINK', 'MAXENDPOINTDTL', 'MAXGROUP', 'MAXINTERROREXTRACT', 'MAXINTMSGTRKDTL', 'MAXINTOBJAPP', 'MAXLICAPPACCESS', 'MAXLICENSE', 'MAXLICPRDKEYLIST', 'MAXLICPURCHDET', 'MAXLICSTATUS', 'MAXPROP', 'MAXPROPVALUE', 'MAXRECORDLOCK', 'MAXROLE', 'MAXROWSTAMP', 'MAXSERVSECURITY', 'MAXTOKEN', 'MAXUSER', 'MAXUSERSTATUS', 'MEASUREMENT', 'MEASUREPOINT', 'MEASUREUNIT', 'METER', 'METERGROUP', 'METERINGROUP', 'METERREADING', 'MFMAILCFG', 'MFMAILST', 'MFMAILSTCFG', 'MFMAILSTVALCFG', 'MFMAILTRACK', 'MFMAILWF', 'MFMAILWFNODECFG', 'MFMAILWFVALCFG', 'MODAVAIL', 'MR', 'MRCOST', 'MRLINE', 'MRSTATUS', 'MULTIASSETLOCCIPR', 'MXODMAPP', 'MXODMAPPPKG', 'NAMEDUSERS', 'NONWORKTIME', 'OBJECTAPPAUTH', 'OMP', 'OMPCIRLN', 'ORGANIZATION', 'PALETTEITEM', 'PDSPEC', 'PERSCOMMODITY', 'PERSONANCESTOR', 'PERSONCAL', 'PERSONSTATUS', 'PLUSCASSETSTATUS', 'PLUSCDSASSETLINK', 'PLUSCDSCONFIG', 'PLUSCDSINSTR', 'PLUSCDSPOINT', 'PLUSCDSSTATUS', 'PLUSCJPDATASHEET', 'PLUSCJPSTATUS', 'PLUSCPMEXTDATE', 'PLUSCSPOTCHECK', 'PLUSCTEMPLATE', 'PLUSCTPASSET', 'PLUSCTPDATASHEET', 'PLUSCTPHISTORY', 'PLUSCTPMETER', 'PLUSCTPSPAREPART', 'PLUSCTPSPEC', 'PLUSCWODS', 'PLUSCWODSINSTR', 'PLUSCWODSPOINT', 'PLUSDSPLAN', 'PMANCESTOR', 'PMFORECAST', 'PMFORECASTJP', 'PMFORECASTLABOR', 'PMFORECASTMATERIAL', 'PMFORECASTSERVICE', 'PMFORECASTTOOL', 'PMMETER', 'PMSEASONS', 'PMSEQUENCE', 'PO', 'POCOST', 'POECOMSTATUS', 'POINTWO', 'POLINE', 'PORTLET', 'PORTLETDISPLAY', 'POSTATUS', 'POTERM', 'PPCRAFTRATE', 'PPLABORRATE', 'PR', 'PRCOST', 'PRECAUTION', 'PREMIUMPAY', 'PRICALC', 'PRLINE', 'PROCOBJ', 'PROCRULE', 'PRODUCTUPDATE', 'PROPERTYASSOC', 'PROPERTYDEFAULT', 'PRSTATUS', 'PRTERM', 'QUALCRAFTSKILL', 'QUALIFICATION', 'QUALSTATUS', 'QUERY', 'QUOTATIONLINE', 'RECONCOMPFILTER', 'RECONLINK', 'RECONMULTILINK', 'RECONRESULT', 'RECONRULE', 'RECONRULECLAUSE', 'RECONTASK', 'RECONTASKCOMP', 'RECONTASKFILTER', 'RECONTASKFLTRVAL', 'RECONTASKLINK', 'RECORDTIMEZONE', 'RELATEDSLA', 'RELATION', 'RELATIONRULES', 'RELATIONRULESEXT', 'REORDERMUTEX', 'REORDERPAD', 'REPFACAUTH', 'REPORT', 'REPORTADHOC', 'REPORTADHOCCALC', 'REPORTADHOCFIELD', 'REPORTADHOCSUM', 'REPORTAPPAUTH', 'REPORTAUTH', 'REPORTDEPEND', 'REPORTDESIGN', 'REPORTDS', 'REPORTDSPARAM', 'REPORTEXPVALUE', 'REPORTFILEEXPORT', 'REPORTHYPERLINKQUERYURL', 'REPORTJOB', 'REPORTLABEL', 'REPORTLISTCFG', 'REPORTLOOKUP', 'REPORTOSAUTH', 'REPORTOUTPUT', 'REPORTOUTPUTAUTH', 'REPORTOUTPUTCNT', 'REPORTPARAM', 'REPORTPROCRESERVE', 'REPORTPROCSCHED', 'REPORTRUNLOCK', 'REPORTRUNPARAM', 'REPORTRUNQUEUE', 'REPORTSCHED', 'REPORTSECATTKEY', 'REPORTUSAGELOG', 'RESULTSETCOLS', 'RFQ', 'RFQLINE', 'RFQSTATUS', 'RFQTERM', 'RFQVENDOR', 'RFQVENDORTERM', 'RSCONFIG', 'SAFETYLEXICON', 'SAFETYPLAN', 'SCCONFIG', 'SCHEDULE', 'SCHEDULELINE', 'SCRIPTLAUNCHPOINT', 'SCTEMPLATE', 'SECURITYRESTRICT', 'SERVICEADDRESS', 'SETS', 'SFWLICENSE', 'SFWLINE', 'SHIFT', 'SHIFTPATTERNDAY', 'SHIPMENT', 'SHIPMENTLINE', 'SITE', 'SITEAUTH', 'SITEECOM', 'SKDACTION', 'SKDACTIVITY', 'SKDACTIVITYQBE', 'SKDAPPLETEXT', 'SKDASSETLOCQUERY', 'SKDCAPACITYPLANPARAM', 'SKDCOMPLIANCE', 'SKDCOMPLIANCEWOLIST', 'SKDCONSTRAINT', 'SKDCOST', 'SKDCOSTTEMP', 'SKDDATAGROUP', 'SKDEMAVAILRES', 'SKDEXTRACAPACITY', 'SKDGVPREF', 'SKDLABORHRS', 'SKDLABORHRSTEMP', 'SKDLABORMODPARAM', 'SKDOBJECT', 'SKDOBJECTMGR', 'SKDODMAPP', 'SKDODMEMSG', 'SKDODMERUN', 'SKDORIGINDESTMATRIX', 'SKDPMFOCOST', 'SKDPMFOCOSTTEMP', 'SKDPMFORECAST', 'SKDPMFORECASTJP', 'SKDPROJECT', 'SKDPROJECTASSTS', 'SKDPROJECTEMWO', 'SKDPROJECTOBJ', 'SKDPROJECTPUBLISH', 'SKDPROJECTSCENARIO', 'SKDPROJECTSHIFTS', 'SKDPROJECTSTATUS', 'SKDPROPERTY', 'SKDPROPERTYMAP', 'SKDQUERY', 'SKDRESERVATION', 'SKDRESLEVELPARAM', 'SKDRESOBJECT', 'SKDRESOURCE', 'SKDRESOURCEUSE', 'SKDRESOURCEVIEW', 'SKDSPATIALPARAM', 'SKDUSERPROP', 'SKDWORKPLANEXTCAP', 'SLA', 'SLAASSETLOC', 'SLACOMMITMENTS', 'SLACONTRACT', 'SLAKPI', 'SLARECORDS', 'SLROUTE', 'SLRTRAVELTIME', 'SMS', 'SOLUTION', 'SOLUTIONSPEC', 'SOLUTIONSTATUS', 'SPAREPART', 'SPLEXICONLINK', 'SPRELATEDASSET', 'SPWORKASSET', 'SWCACCT', 'SWCALLBUYER', 'SWCAUDITRULES', 'SWCBUYERDEPT', 'SWCCCAUDIT', 'SWCCHGLOCATTR', 'SWCCHGLOCCODE', 'SWCCHGLOCCODEHIST', 'SWCCHTEMP', 'SWCCLAIM', 'SWCCLAIMAUDIT', 'SWCCLAIMDETAILS', 'SWCCONACCESS', 'SWCCONTACCTMAP', 'SWCCONTTASKMAP', 'SWCCPV', 'SWCCPVDETAILS', 'SWCCRONEXTACT', 'SWCCRONEXTACTHIST', 'SWCCRSECURITY', 'SWCDEPENDENCY', 'SWCDEPT', 'SWCDISPATCHWO', 'SWCDISTBATCH', 'SWCDISTBATCHSTATUS', 'SWCDISTDETAIL', 'SWCDISTEXLWO', 'SWCDISTSTATUS', 'SWCDISTWO', 'SWCDISTWOACT', 'SWCEXTFMISINVOICE', 'SWCFMISBUYER', 'SWCFMISBUYERPO', 'SWCFMISCONTRACTPO', 'SWCFMISWOMATPROCESSING', 'SWCFRMORDER', 'SWCGISNAVIGATE', 'SWCGROUPAUTH', 'SWCHIERANCESTOR', 'SWCHIERARCHY_BCKUP', 'SWCHIERROLE', 'SWCINSPECTCODE', 'SWCINVOICESENT', 'SWCLABTRANS_COMPARISION', 'SWCLATESTUSERLOGIN', 'SWCLOCCALLINST', 'SWCLOCHAZDETAIL', 'SWCLOCPRODLVL', 'SWCLOCSERVDEF', 'SWCOPRBUYER', 'SWCPAGEQUERY', 'SWCPROBTYPEPROD', 'SWCPRODLVL', 'SWCPROJACT', 'SWCPROJPNUM', 'SWCRDOMLOOKUP', 'SWCRRTRATE', 'SWCSERVCONTDEPT', 'SWCSERVITEMVENDOR', 'SWCSERVMAP', 'SWCSERVSWAP', 'SWCSERVSWAPBYPASS', 'SWCSRALOG', 'SWCSRAPT', 'SWCWOACTPLAN', 'SWCXLLOADPROCESSING', 'TABLEEXTTPLT', 'TAGLOCK', 'TAGOUT', 'TAMITDPAHWM', 'TAMITSWPRTNUM', 'TAX', 'TAXORDER', 'TAXTYPE', 'TDTVERSION', 'TEMPLATESTATUS', 'TERM', 'TICKETSPEC', 'TIMEZONERULE', 'TKOWNERHISTORY', 'TKSERVICEADDRESS', 'TKSTATUS', 'TKTEMPLATE', 'TKTEMPLATESPEC', 'TKTEMPLTACTIVITY', 'TKTEMPLTACTYSPEC', 'TLOAMASSETGRP', 'TLOAMDPAANCESTOR', 'TLOAMDPAHWM', 'TLOAMPRMDFLT', 'TLOAMSOFTWARE', 'TLOAMSWCATALOG', 'TLOAMSWREL', 'TOOLQUAL', 'USERPURGL', 'VENDORSTATUS', 'WARRANTYASSET', 'WARRANTYLINE', 'WFACTION', 'WFACTIVATION', 'WFAPPTOOLBAR', 'WFASGNGROUP', 'WFASSIGNMENT', 'WFCALLSTACK', 'WFCONDITION', 'WFINPUT', 'WFINSTANCE', 'WFINTERACTION', 'WFNODE', 'WFNOTIFICATION', 'WFPROCESS', 'WFREVISION', 'WFSTART', 'WFSTOP', 'WFSUBPROCESS', 'WFTASK', 'WFTRANSACTION', 'WFWAITLIST', 'WMASSIGNTMP', 'WMMATCH', 'WMMATCHCRW', 'WOCONTRACT', 'WOGEN', 'WOHAZARD', 'WOHAZARDPREC', 'WOLOCKOUT', 'WOMATSTATUSSYNC', 'WOMETER', 'WOOWNERHISTORY', 'WOPRECAUTION', 'WORELEXT', 'WORKPERIOD', 'WORKPRIORITY', 'WORKTYPE', 'WORKVIEW', 'WORKZONE', 'WOSAFETYLINK', 'WOSAFETYPLAN', 'WOSERVICEADDRESS', 'WOTAGLOCK', 'WOTAGOUT', 'WOTASKRELATION', 'WPEDITSETTING', 'WPITEM', 'WPLABOR', 'NUMERICDOMAIN']

#Tables that needs to be refreshed every 15 mins
tables15Mins = ['DOCLINKS', 'FAILUREREPORT', 'LABTRANS', 'LONGDESCRIPTION', 'MAXINTMSGTRK', 'MULTIASSETLOCCI', 'RELATEDRECORD', 'TICKET', 'SWCBUSSTATUS', 'SWCWOEXT', 'TOOLTRANS', 'WORKLOG', 'WORKORDER', 'WORKORDERSPEC', 'WOSTATUS', 'ASSETSTATUS', 'LOCSTATUS']

# COMMAND ----------

base_query = """    WITH _Base AS (
      SELECT 'maximo' SourceSchema, 'oracle-load' SourceHandler, 'raw-load-delta' RawHandler, 'cleansed-load-delta' CleansedHandler, '{"GroupOrderBy" : "CAST(rowStamp as bigint) Desc"}' ExtendedProperties, 'CAST(rowstamp as INT)' WatermarkColumn, 'daf-oracle-maximo-connectionstring' SourceKeyVaultSecret, '' SourceQuery, '' RawFileExtension
    )"""

# COMMAND ----------

for table in tables:
    if table in tables15Mins:
        base_query += (f"SELECT 'maximo|15Min' SystemCode, '{table}' SourceTableName, * FROM _Base \n UNION \n")
    else:
        base_query += (f"SELECT 'maximo' SystemCode, '{table}' SourceTableName, * FROM _Base \n UNION \n")

#base_query += base_query
df = spark.sql(f"{base_query[:-5]}")    
display(df)

# COMMAND ----------

def ConfigureManifest(df):
    # ------------- CONSTRUCT QUERY ----------------- #
    
    # ------------- DISPLAY ----------------- #
    ShowQuery(df)

    # ------------- SAVE ----------------- #
    AddIngestion(df)
    

    # ------------- ShowConfig ----------------- #
    ShowConfig()
    

for system_code in ['maximo', 'maximo|15Min']:
    SYSTEM_CODE = system_code
    print(SYSTEM_CODE)
    ConfigureManifest(df.where(f"SystemCode = '{SYSTEM_CODE}'"))       

# COMMAND ----------

# ------------- POST LOAD UPDATE ----------------- #  

#Update Business Key for Maximo tables
ExecuteStatement("""
update dbo.extractLoadManifest set
businessKeyColumn = case sourceTableName
when 'a_asset' then 'asset, site, eAuditTimestamp'
when 'a_assetspec' then 'attribute, asset, linearSpecificationId, aAssetspecSection, site, eAuditTimestamp'
when 'a_failurereport' then 'failurereportid, eAuditTimestamp'
when 'a_groupuser' then 'userId, aGroupuserGroup, eAuditTimestamp'
when 'a_inventory' then 'item, itemSet, storeroom, site, eAuditTimestamp'
when 'a_jobplan' then 'organization, jobPlan, site, eAuditTimestamp, revision'
when 'a_locationspec' then 'attribute, location, aLocationspecSection, site, eAuditTimestamp'
when 'a_locoper' then 'location, site, eAuditTimestamp'
when 'a_longdescription' then 'ldkey, ldownertable, ldownercol, eAuditTimestamp, languageCode, internalContentUniqueId'
when 'a_pm' then 'pm, site, eAuditTimestamp'
when 'a_po' then 'po, revision, site, eAuditTimestamp'
when 'a_route_stop' then 'route, stopAddedToRoute, site, eAuditTimestamp'
when 'a_routes' then 'route, site, eAuditTimestamp'
when 'a_swcclaim' then 'swcclaimid, eAuditTimestamp'
when 'a_swcconaccess' then 'swcconaccessid, eAuditTimestamp'
when 'a_swccrsecurity' then 'workTeam, aSwccrsecurityUser, eAuditTimestamp'
when 'accountdefaults' then 'groupType, commodityGroup, organization'
when 'actci' then 'actualCi'
when 'actcirelation' then 'relation, sourceActualCi, targetActualCi'
when 'actcispec' then 'actualCi, attribute, actcispecSection'
when 'action' then 'actionName'
when 'actiongroup' then 'actionIdentifier, actiongroupAction, actiongroupSequence'
when 'actionscfg' then 'uniqueId'
when 'address' then 'addressCode, organization'
when 'alndomain' then 'alndomainDomain, organization, site, alndomainValue'
when 'altitem' then 'altItem, item, itemSet'
when 'amcrew' then 'crew, organization'
when 'amcrewlabor' then 'crew, uniqueId, organizationorgan, amcrewlaborPosition'
when 'amcrewlabpos' then 'crew, organization, amcrewlabposPosition'
when 'amcrewmodavail' then 'uniqueId'
when 'amcrewqual' then 'uniqueId'
when 'amcrewstathis' then 'crew, changeDate, organization, status'
when 'amcrewt' then 'crewType, organization'
when 'amcrewtool' then 'crew, uniqueId, organization, toolSequence'
when 'amcrewtoolsq' then 'crew, organization, toolSequence'
when 'amcrewwolab' then 'uniqueId'
when 'amcrewworkzone' then 'crew, organization, workZone'
when 'amcrewwotl' then 'uniqueId'
when 'amctcraft' then 'crewType, organization, amctcraftPosition'
when 'amctqual' then 'uniqueId'
when 'amctstathist' then 'uniqueId, organization'
when 'amcttool' then 'crewType, organization, toolSeq'
when 'appdoctype' then 'application, documentFolder'
when 'applicationauth' then 'application, applicationauthGroup, applicationauthOption'
when 'archive' then 'archivedDate, archiveModule'
when 'areasaffected' then 'uniqueId, site, workOrder'
when 'asset' then 'asset, site, rowStamp'
when 'assetancestor' then 'ancestor, asset, site'
when 'assetattribute' then 'attribute, organization, site'
when 'assetfeaspechist' then 'attribute, assetFeatureUniqueId, asset, startDate, featureUniqueId, assetfeaspechistSection, site'
when 'assetfeature' then 'asset, feature, linearAssetFeatureId, site'
when 'assetfeaturehist' then 'uniqueId'
when 'assetfeaturespec' then 'attribute, asset, feature, linearFeatureSpecificationId, assetfeaturespecSection, siteId'
when 'assethierarchy' then 'asset, site, workOrder'
when 'assethistory' then 'assetHistoryId'
when 'assetloccomm' then 'assetLOCCommId'
when 'assetlocrelation' then 'relation, linearSpecificationId, sourceAsset, targetAsset'
when 'assetlocrelhist' then 'uniqueIdHist'
when 'assetlocusercust' then 'asset, location, person, site'
when 'assetmeter' then 'asset, linearSpecificationId, meter, site'
when 'assetmntskd' then 'asset, maintenanceHours, site, scheduleStart'
when 'assetopskd' then 'asset, operatingHours, site, scheduleStart'
when 'assetspec' then 'attribute, asset, linearSpecificationId, assetspecSection, site'
when 'assetspechist' then 'attribute, asset, uniqueId, assetSpecificationUniqueId, startDate, assetspechistSection, site'
when 'assetstatus' then 'assetStatusId'
when 'assettopocache' then 'uniqueId'
when 'assettrans' then 'id'
when 'assetworkzone' then 'asset, organization, site, workZoneType'
when 'assignment' then 'assignmentid'
when 'assignreploc' then 'uniqueId'
when 'astmsover' then 'internalName'
when 'astspecmsover' then 'internalName'
when 'attendance' then 'attendanceId'
when 'autoattrupdate' then 'uniqueId'
when 'autoscriptvars' then 'script, autoscriptvarsVariable'
when 'bboardaudience' then 'bBoardAudienceId'
when 'bboardmsgstatus' then 'uniqueId'
when 'bbstatushistory' then 'statushistory'
when 'billtoshipto' then 'address, organization, site'
when 'bookmark' then 'application, bookmark, bookmarkUser'
when 'bulletinboard' then 'messageId'
when 'calendar' then 'calendar, organization'
when 'calendarbreak' then 'uniqueId, organization'
when 'cdmcitypes' then 'uniqueId'
when 'charpointaction' then 'measurementPoint, site, charpointactionValue'
when 'chartofaccounts' then 'glAccount, organization'
when 'ci' then 'configurationItem'
when 'cirelation' then 'relation, sourceCi, targetCi'
when 'cirelationhis' then 'relation, sourceCi, startDate, targetCi'
when 'cispec' then 'attribute, configurationItem, cispecSection'
when 'cispechis' then 'attribute, configurationItem, cispechisSection, startDate'
when 'cistatus' then 'uniqueId'
when 'citemplate' then 'uniqueId'
when 'citypestatus' then 'uniqueId'
when 'classancestor' then 'ancestor, classStructure'
when 'classification' then 'classification, organization, site'
when 'classspec' then 'attribute, classStructure, organization, classspecSection, site'
when 'classspecusewith' then 'attribute, classstructureId, objectName, organization, classspecusewithSection, site'
when 'classstructure' then 'classStructure'
when 'classusewith' then 'classStructureId, useWith'
when 'collectdetails' then 'uniqueId'
when 'collection' then 'collection'
when 'collectionauth' then 'collection, groupName'
when 'commitgroup' then 'personGroup, projectName'
when 'commitperson' then 'person, projectName'
when 'commlog' then 'communicationId'
when 'commlogdocs' then 'commLogDocSId'
when 'commodities' then 'commodityGroup, itemSet'
when 'commtemplate' then 'template'
when 'commtemplatedocs' then 'application, documentFolder, template'
when 'commtmpltsendto' then 'email, template, type'
when 'companies' then 'company, organization'
when 'companyaccdef' then 'organization, companyType'
when 'compcommodity' then 'compCommodityId'
when 'compcontact' then 'company, contact, organization'
when 'compcontactmstr' then 'company, companySet, contact'
when 'compmaster' then 'company, companySet'
when 'condition' then 'conditionCondition'
when 'contassetmeter' then 'uniqueId'
when 'contcommodity' then 'contCommodityId'
when 'contlineasset' then 'uniqueId'
when 'contlinemeter' then 'uniqueId'
when 'contract' then 'contract, organization, revision'
when 'contractasset' then 'uniqueId'
when 'contractauth' then 'organizationAuthUseContract, site, contract, organization, revision, vendor'
when 'contractdefault' then 'internalContractType, propertyId'
when 'contractlease' then 'contract, organization, revision'
when 'contractline' then 'line, contract, organization, revision'
when 'contractmaster' then 'contract, organization, revision'
when 'contractproperty' then 'propertyId'
when 'contractpurch' then 'contract, organization, revision'
when 'contractsfw' then 'contractnum, organization, revision'
when 'contractstatus' then 'contractStatusId'
when 'contractswlic' then 'contract, orgid, revision'
when 'contractterm' then 'contractTermId'
when 'contracttype' then 'contractType, organization'
when 'contracttypeterm' then 'contractTypeTermId'
when 'contsfwlic' then 'uniqueId'
when 'conversion' then 'fromUnitOfMeasure, itemNumber, itemSet, toUnitOfMeasure'
when 'costtype' then 'costType'
when 'craft' then 'craft, organization'
when 'craftrate' then 'contract, craft, organization, revision, skillLevel, vendor'
when 'craftskill' then 'craft, organization, skillLevel'
when 'crontaskhistory' then 'cronTaskName, instanceName, crontaskhistorySequence'
when 'currency' then 'currency'
when 'defaultquery' then 'application, saveQueryAs, defaultqueryUser'
when 'dephistory' then 'changeDate, depreciationId, organization'
when 'deployedasset' then 'nodeId'
when 'depreciation' then 'depreciationId, organization'
when 'depsched' then 'depreciationId, schedule, organization'
when 'depschedhistory' then 'changeDate, depreciationId, schedule, organization'
when 'depschedperiods' then 'schedule, organization, period'
when 'deptrans' then 'depreciationId, schedule, organization, period, transactionDate'
when 'dmsapisetting' then 'dMS'
when 'docinfo' then 'docInfoId'
when 'doclinks' then 'docinfoId, documentFolder, ownerId, ownerTable'
when 'doctypes' then 'documentFolder'
when 'dpacommdevice' then 'deviceId'
when 'dpacomputer' then 'nodeId'
when 'dpacpu' then 'cpuId'
when 'dpadisk' then 'diskId'
when 'dpadisplay' then 'displayId'
when 'dpafile' then 'fileId'
when 'dpaimagedevice' then 'deviceId'
when 'dpaipx' then 'ipxId'
when 'dpalogicaldrive' then 'logicalDriveId'
when 'dpamediaadapter' then 'adapter'
when 'dpanetadapter' then 'adapter'
when 'dpanetdevcard' then 'card'
when 'dpanetdevice' then 'nodeId'
when 'dpanetprinter' then 'nodeId'
when 'dpaos' then 'operatingSystemId'
when 'dpasoftware' then 'softwareId'
when 'dpaswsuite' then 'uniqueIdentifier'
when 'dpatcpip' then 'tcpipId'
when 'dpauserinfo' then 'nodeId, person'
when 'email' then 'email'
when 'escalation' then 'escalation'
when 'escnotification' then 'escalation, referencePointNumber, template'
when 'escrefpoint' then 'escalation, escalationPoint'
when 'escrepeattrack' then 'escalation, escrepeattrackObject, ownerid, refPointId'
when 'escstatus' then 'uniqueId'
when 'eventresponse' then 'unqiueId'
when 'exchange' then 'convertFromCurrency, convertToCurrency, expirationDate, organization'
when 'excludepassword' then 'password'
when 'faconfig' then 'configId'
when 'failurecode' then 'failureCode, organization'
when 'failurelist' then 'failureList, organization'
when 'failureremark' then 'site, ticketClass, ticket, workOrder'
when 'failurereport' then 'failureReportId'
when 'favitem' then 'description, item, itemSet, favitemUser, storeroom, site'
when 'features' then 'feature'
when 'featurespec' then 'attribute, feature, featurespecSection'
when 'featurestatus' then 'uniqueId'
when 'financialperiods' then 'period, organization'
when 'fincntrl' then 'fCId, organization'
when 'glauth' then 'glComponent, glauthGroup, organization'
when 'glcomponents' then 'glComponentValue, glOrder, organization'
when 'glconfigure' then 'glOrder, organization'
when 'groupuser' then 'groupuserGroup, groupuserUser'
when 'grpreassignauth' then 'grpreassignauthGroup, grpreassignauthUser'
when 'hazard' then 'hazard, organization'
when 'hazardprec' then 'associatedHazard, precaution, site'
when 'ibmcontentcatalog' then 'ibmcontentcatalogid'
when 'ibmcontentreceipts' then 'ibmcontentreceiptsid'
when 'improfile' then 'instantMessagingProfileIdentifier'
when 'inbcommsecurity' then 'maximoApplication, eMailAddress, mailServer, maximoBusinessObject'
when 'inboundcomm' then 'uniqueId'
when 'inboundcommcfg' then 'eMailAddress, mailServer'
when 'inbxconfig' then 'inboxConfigurationId'
when 'invbalances' then 'bin, conditionCode, item, itemSet, storeroom, lot, site'
when 'invcost' then 'conditionCode, item, itemSet, location, site'
when 'inventory' then 'item, itemSet, storeroomPrimary, site'
when 'invlifofifocost' then 'contentUniqueId'
when 'invlot' then 'item, storeroom, lot, site'
when 'invoice' then 'invoice, site'
when 'invoicecost' then 'costLine, invoiceLine, invoice, site'
when 'invoiceline' then 'line, invoice, site'
when 'invoicematch' then 'invoiceMatchId'
when 'invoicestatus' then 'invoiceStatusId'
when 'invoiceterm' then 'invoiceTermId'
when 'invoicetrans' then 'invoiceTransId'
when 'invreserve' then 'request, site'
when 'invstatus' then 'uniqueId'
when 'invtrans' then 'id, site'
when 'invuse' then 'invuseUsage, site'
when 'invuseline' then 'line, invuselineUsage, site'
when 'invuselinesplit' then 'contentUniqueId'
when 'invusestatus' then 'uniqueId'
when 'invvendor' then 'catalogNumber, conditionCode, item, itemSet, manufacturer, modelPrimaryVendor, organization, site, vendor'
when 'item' then 'item, itemSet'
when 'itemcondition' then 'conditionCode, item, setIdentifier'
when 'itemorginfo' then 'service, itemSet, organization'
when 'itemorgstatus' then 'uniqueId'
when 'itemspec' then 'attribute, item, itemSet, itemspecSection'
when 'itemstatus' then 'uniqueId'
when 'itemstruct' then 'instance, itemId, item, itemSet'
when 'jobitem' then 'jobItemId'
when 'joblabor' then 'jobLaborId'
when 'jobplan' then 'jobPlan, organization, revision, site'
when 'jobplanclass' then 'jobplanid, defaultWoClass'
when 'jobplanspec' then 'attribute, jobPlan, organization, jobPlanRevisionNumber, jobplanspecSection, site'
when 'jobtask' then 'jobPlan, task, organization, jobPlanRevisionNumber, site'
when 'jobtaskspec' then 'attribute, jobPlan, task, organization, jobPlanRevisionNumber, jobtaskspecSection, site'
when 'jpassetsplink' then 'jpAssetLink'
when 'jptaskrelation' then 'uniqueId'
when 'kpiauth' then 'kpiauthGroup, theNameOfTheKpi'
when 'kpigconfig' then 'configId'
when 'kpihistory' then 'uniqueId'
when 'kpilconfig' then 'kpiListConfigId'
when 'kpimain' then 'kpiName'
when 'kpioee' then 'asset, oeeDate, part, site'
when 'kpischedule' then 'cronTaskInstanceName, theNameOfTheKpi'
when 'kpitemplate' then 'template'
when 'kpitemplatemain' then 'kPI, relatedTemplate'
when 'kpitemplatevar' then 'relatedTemplate, variableName'
when 'kpitemplatevarvalue' then 'relatedTemplateNum, relatedTemplate, variableName'
when 'kpitrendcfg' then 'uniqueId'
when 'labor' then 'labor, organization'
when 'laborauth' then 'laborauthGroup, labor, organization'
when 'laborcerthist' then 'labOrcERThisTId'
when 'laborcraftrate' then 'contract, craft, labor, organization, skillLevel, vendor'
when 'laborqual' then 'labor, organization, qualification'
when 'laborqualstatus' then 'changedDate, labor, organization, qualification'
when 'laborstatus' then 'labOrStatusId'
when 'laborworkzone' then 'labor, organization, workZone'
when 'labtrans' then 'labor, id, site'
when 'language' then 'languageCode'
when 'launchpointvars' then 'script, launchPoint, launchpointvarsVariable'
when 'layout' then 'layout'
when 'lbslocation' then 'lbsLocationId'
when 'limittolerance' then 'limittoleranceGroup, organization'
when 'linearrefmethod' then 'lRM'
when 'lnrrecalib' then 'uniqueId'
when 'lnrrecalibnonaf' then 'uniqueId'
when 'locancestor' then 'searchLocationHierarchy, location, site, locancestorSystem'
when 'locationmeter' then 'location, meter, site'
when 'locationmntskd' then 'location, maintenanceHours, site, scheduleStart'
when 'locationopskd' then 'location, operatingHours, site, scheduleStart'
when 'locations' then 'location, site, rowStamp'
when 'locationspec' then 'attribute, location, locationspecSection, site'
when 'locationworkzone' then 'location, organization, site, workZoneType'
when 'locauth' then 'locauthGroup, storeroom, site'
when 'lochierarchy' then 'location, parent, site, lochierarchySystem'
when 'lockout' then 'lockoutId, site'
when 'locleadtime' then 'storeroom, site'
when 'locmeterreading' then 'meterReadingId, site'
when 'locoper' then 'location, site'
when 'locstatus' then 'lOCStatusId'
when 'locsystem' then 'site, locsystemSystem'
when 'loginblock' then 'uniqueId'
when 'logintracking' then 'loginTrackInGId'
when 'longdescription' then 'longdescriptionLanguage, ldkey, ldownercol, ldownertable'
when 'mapmanager' then 'mapmanagerMap'
when 'mapsites' then 'mapsitesMap, site'
when 'maptip' then 'maptipMap, objectName'
when 'maptipdefaults' then 'objectName'
when 'maptipmenu' then 'uniqueId'
when 'masterpm' then 'masterPm'
when 'masterpmmeter' then 'masterPm, meter'
when 'masterpmseasons' then 'endDay, endMonth, masterPm, startDay, startMonth'
when 'masterpmseq' then 'masterpmseqSequence, masterPm'
when 'matrectrans' then 'receiptId'
when 'matusetrans' then 'usageId, site'
when 'maxasyncjob' then 'jobNumber'
when 'maxasyncjobmsg' then 'jobNumber, maxasyncjobmsgSequence'
when 'maxasyncjobparam' then 'jobNumber, name'
when 'maxdomainlink' then 'attributeName, domainId, objectName'
when 'maxdomvalcond' then 'conditionNumber, domainId, objectName, valueId'
when 'maxdynamicdomlink' then 'attributeName, domainWhereClause, objectName'
when 'maxendpointdtl' then 'endPoint, property'
when 'maxgroup' then 'maxgroupGroup'
when 'maxinterrorextract' then 'extractFileId'
when 'maxintmsgtrk' then 'messageId'
when 'maxintmsgtrkdtl' then 'internalMessageId, status'
when 'maxintobjapp' then 'application, objectStructure, useWith'
when 'maxlicappaccess' then 'applicationName'
when 'maxlicense' then 'licenseNum'
when 'maxlicprdkeylist' then 'productName'
when 'maxlicpurchdet' then 'uniqueId'
when 'maxlicstatus' then 'licenseStatus'
when 'maxprop' then 'propertyName'
when 'maxpropvalue' then 'propertyName, serverHost, server'
when 'maxrecordlock' then 'editTime, lockSessionId, objectId, objectName'
when 'maxrole' then 'maxroleRole'
when 'maxrowstamp' then 'tableName'
when 'maxservsecurity' then 'maxservsecurityMethod, service'
when 'maxtoken' then 'temporaryToken, userIdentity'
when 'maxuser' then 'maxuserUser'
when 'maxuserstatus' then 'maxUserStatusId'
when 'measurement' then 'measurement'
when 'measurepoint' then 'point, site'
when 'measureunit' then 'unitOfMeasure, organization, site'
when 'meter' then 'meter'
when 'metergroup' then 'meterGroup'
when 'meteringroup' then 'meteringroupGroup, meter'
when 'meterreading' then 'meterReadingId, site'
when 'mfmailcfg' then 'configurationId'
when 'mfmailst' then 'uniqueId'
when 'mfmailstcfg' then 'configuration, status'
when 'mfmailstvalcfg' then 'uniqueId'
when 'mfmailtrack' then 'uniqueId'
when 'mfmailwf' then 'uniqueId'
when 'mfmailwfnodecfg' then 'configuration, nodeId'
when 'mfmailwfvalcfg' then 'uniqueId'
when 'modavail' then 'uniqueid'
when 'mr' then 'requisition, site'
when 'mrcost' then 'mrCostLineId, site'
when 'mrline' then 'lineId, site'
when 'mrstatus' then 'changeSequence, site'
when 'multiassetlocci' then 'multiId'
when 'multiassetloccipr' then 'uniqueId'
when 'mxodmapp' then 'optimizationModelName'
when 'mxodmapppkg' then 'optimizationModelName'
when 'namedusers' then 'uniqueId'
when 'nonworktime' then 'endDate, startDate'
when 'objectappauth' then 'integrationContext, objectappauthObject'
when 'omp' then 'gUId'
when 'ompcirln' then 'cIGUId, oMPGUId'
when 'organization' then 'organizationId'
when 'paletteitem' then 'control'
when 'pdspec' then 'attribute, referenceObjectId, referenceObjectName, pdspecSection'
when 'perscommodity' then 'commodityCode, itemSet, storeroom, organization, person, site'
when 'person' then 'person'
when 'personancestor' then 'ancestor, person'
when 'personcal' then 'organization, person'
when 'persongroup' then 'personGroup, rowStamp'
when 'persongroupteam' then 'personGroup, person, personGroupMember, useForOrganization, useForSite, rowStamp'
when 'personstatus' then 'statusDate, person, status'
when 'phone' then 'person, phone, type'
when 'pluscassetstatus' then 'uniqueId'
when 'pluscdsassetlink' then 'uniqueId'
when 'pluscdsconfig' then 'uniqueId'
when 'pluscdsinstr' then 'assetFunction, dataSheet, revision'
when 'pluscdspoint' then 'uniqueId'
when 'pluscdsstatus' then 'uniqueId'
when 'pluscjpdatasheet' then 'uniqueId'
when 'pluscjpstatus' then 'uniqueId'
when 'pluscpmextdate' then 'uniqueId'
when 'pluscspotcheck' then 'uniqueId'
when 'plusctemplate' then 'organization, assetTemplate'
when 'plusctpasset' then 'uniqueId'
when 'plusctpdatasheet' then 'uniqueId'
when 'plusctphistory' then 'uniqueId'
when 'plusctpmeter' then 'meter, organization, template'
when 'plusctpsparepart' then 'uniqueId'
when 'plusctpspec' then 'attribute, organization, plusctpspecSection, template'
when 'pluscwods' then 'uniqueId'
when 'pluscwodsinstr' then 'uniqueId'
when 'pluscwodspoint' then 'uniqueId'
when 'plusdsplan' then 'dataSheet, revision'
when 'pm' then 'pM, site, rowStamp'
when 'pmancestor' then 'ancestor, pM, site'
when 'pmforecast' then 'lifeToDateCounter, pM, site'
when 'pmforecastjp' then 'lifeToDateCounter, pM, route, routeStop, site'
when 'pmforecastlabor' then 'uniqueId'
when 'pmforecastmaterial' then 'uniqueId'
when 'pmforecastservice' then 'uniqueId'
when 'pmforecasttool' then 'uniqueId'
when 'pmmeter' then 'meter, pM, site'
when 'pmseasons' then 'endDay, endMonth, pM, site, startDay, startMonth'
when 'pmsequence' then 'pmsequenceSequence, pM, site'
when 'po' then 'pO, revision, site'
when 'pocost' then 'costLineId'
when 'poecomstatus' then 'pOEComStatusId'
when 'pointwo' then 'measurementPoint, site, workOrder'
when 'poline' then 'id'
when 'portlet' then 'portletId'
when 'portletdisplay' then 'uniqueId'
when 'postatus' then 'postAtUSId'
when 'poterm' then 'potERMid'
when 'ppcraftrate' then 'craft, organization, premiumPayCode'
when 'pplaborrate' then 'craft, labor, organization, premiumPayCode'
when 'pr' then 'pR, site'
when 'prcost' then 'prCostLineId'
when 'precaution' then 'precaution, site'
when 'premiumpay' then 'organization, premiumPayCode'
when 'pricalc' then 'formulaIndex, site'
when 'prline' then 'prlineId'
when 'procobj' then 'process'
when 'procrule' then 'processRule'
when 'productupdate' then 'uniqueId'
when 'propertyassoc' then 'internalContractType, propertyId'
when 'propertydefault' then 'contractType, organization, propertyId'
when 'prstatus' then 'pRStatusId'
when 'prterm' then 'pRTermId'
when 'qualcraftskill' then 'craft, organization, qualification, skillLevel'
when 'qualification' then 'organization, qualification'
when 'qualstatus' then 'changedDate, organization, qualification'
when 'query' then 'application, queryName, owner'
when 'quotationline' then 'quotationLineId, line, rFQ, site, vendor'
when 'reconcompfilter' then 'filterType, reconcompfilterRule, reconcompfilterSequence'
when 'reconlink' then 'uniqueId'
when 'reconmultilink' then 'uniqueId'
when 'reconresult' then 'uniqueId'
when 'reconrule' then 'reconruleRule, ruleType'
when 'reconruleclause' then 'reconruleclauseRule, ruleType, reconruleclauseSequence'
when 'recontask' then 'reconciliationTask'
when 'recontaskcomp' then 'comparison, task'
when 'recontaskfilter' then 'recontaskfilterFilter'
when 'recontaskfltrval' then 'uniqueId'
when 'recontasklink' then 'link, task'
when 'recordtimezone' then 'objectId, objectName'
when 'relatedrecord' then 'relatedRecordId, rowStamp'
when 'relatedsla' then 'sLAChild, sLAParent'
when 'relation' then 'relationship'
when 'relationrules' then 'relationshipNum, sourceClassification, targetClassification'
when 'relationrulesext' then 'uniqueId'
when 'reordermutex' then 'location, mR, site, type'
when 'reorderpad' then 'item, itemSet, location, mrLine, mR, site, reorderpadUser, wpItemId'
when 'repfacauth' then 'repfacauthGroup, repairFacility, site'
when 'report' then 'application, reportFileName'
when 'reportadhoc' then 'applicationName, reportFileName'
when 'reportadhoccalc' then 'uniqueId'
when 'reportadhocfield' then 'applicationName, fieldValue, objectId, reportFileName'
when 'reportadhocsum' then 'application, attributeName, objectId, reportFileName, summaryType'
when 'reportappauth' then 'application, reportappauthGroup, reportType'
when 'reportauth' then 'application, reportauthGroup, reportFileName'
when 'reportdepend' then 'dependentReportName, reportName'
when 'reportdesign' then 'reportName'
when 'reportds' then 'dataSourceName'
when 'reportdsparam' then 'dataSourceName'
when 'reportexpvalue' then 'expressionId'
when 'reportfileexport' then 'fileType'
when 'reporthyperlinkqueryurl' then 'hyperlinkParamKey, sessionId'
when 'reportjob' then 'uniqueId'
when 'reportlabel' then 'labelKey, reportName'
when 'reportlistcfg' then 'application, layoutId, reportFileName'
when 'reportlookup' then 'application, parameterName, reportFilename'
when 'reportosauth' then 'reportosauthGroup, reportObjectStructure'
when 'reportoutput' then 'jobNumber'
when 'reportoutputauth' then 'senderEmail, jobNumber'
when 'reportoutputcnt' then 'jobNumber'
when 'reportparam' then 'parameterName, reportName'
when 'reportprocreserve' then 'application, reportprocreserveDay, reportFileName, startReserve'
when 'reportprocsched' then 'applicationName, reportprocschedDay, reportFileName, startTime'
when 'reportrunlock' then 'reportRunQueueId'
when 'reportrunparam' then 'uniqueId'
when 'reportrunqueue' then 'uniqueId'
when 'reportsched' then 'cronTaskName, cronTaskInstanceName'
when 'reportsecattkey' then 'seqNumber'
when 'reportusagelog' then 'uniqueId'
when 'resultsetcols' then 'resultSetColSId'
when 'rfq' then 'rFQ, site'
when 'rfqline' then 'rfqLine'
when 'rfqstatus' then 'rFQ, rfqStatus, site'
when 'rfqterm' then 'rFQTermId'
when 'rfqvendor' then 'rFQ, site, vendor'
when 'rfqvendorterm' then 'rFQVendorTermId'
when 'route_stop' then 'route, stopAddedToRoute, site'
when 'routes' then 'route, site'
when 'rsconfig' then 'configId'
when 'safetylexicon' then 'safetyLexiconId, site'
when 'safetyplan' then 'safetyPlan, site'
when 'scconfig' then 'groupName, userId'
when 'schedule' then 'contractLine, contract, organization, revision, scheduleNum, scheduleRevision'
when 'scheduleline' then 'organization, paymentSchedule, uniqueId'
when 'scriptlaunchpoint' then 'script, launchPoint'
when 'sctemplate' then 'uniqueId'
when 'securityrestrict' then 'application, attribute, securityrestrictGroup, securityrestrictObject, typeRestriction, type'
when 'serviceaddress' then 'addressCode, organization'
when 'servrectrans' then 'service'
when 'sets' then 'setsSet'
when 'sfwlicense' then 'license'
when 'sfwline' then 'line, contract, organization, revision'
when 'shift' then 'organization, shift'
when 'shiftpatternday' then 'organization, sequenceOfPatternDay, shift'
when 'shipment' then 'fromSite, shipmentNum'
when 'shipmentline' then 'shipmentId, shipmentLineID, site'
when 'site' then 'site'
when 'siteauth' then 'siteauthGroup, site'
when 'siteecom' then 'organization, site, vendor'
when 'skdaction' then 'actionName, frame, objectName, schedulerObjectName, useWith'
when 'skdactivity' then 'activityId, objectIdentifier, objectName, projectId'
when 'skdactivityqbe' then 'site, skdactivityqbeWork'
when 'skdappletext' then 'extensionName'
when 'skdassetlocquery' then 'projectName, dataSource'
when 'skdcapacityplanparam' then 'templateName'
when 'skdcompliance' then 'scheduleComplianceEnd, scheduleProjectId, scheduleComplianceStart'
when 'skdcompliancewolist' then 'projectId, woUniqueIdentifier'
when 'skdconstraint' then 'projectId'
when 'skdcost' then 'contentUniqueId'
when 'skdcosttemp' then 'contentUniqueId'
when 'skddatagroup' then 'objectGroupName, schedulerObjectName'
when 'skdextracapacity' then 'craft, projectId'
when 'skdgvpref' then 'projectName, userId'
when 'skdlaborhrs' then 'contentUniqueId'
when 'skdlaborhrstemp' then 'contentUniqueId'
when 'skdlabormodparam' then 'templateName'
when 'skdobject' then 'dataGroupName, objectName, schedulerObjectName'
when 'skdobjectmgr' then 'objectName, purposeOfThisObjectManager, schedulerObjectName'
when 'skdodmapp' then 'uniqueId'
when 'skdodmemsg' then 'uniqueId'
when 'skdodmerun' then 'uniqueId'
when 'skdorigindestmatrix' then 'fromServiceAddress, fromWorkLocation, organization, toServiceAddress, toWorkLocation'
when 'skdpmfocost' then 'contentUniqueId'
when 'skdpmfocosttemp' then 'contentUniqueId'
when 'skdpmforecast' then 'lifeToDateCounter, pM, site, scheduleProjectId'
when 'skdpmforecastjp' then 'lifeToDateCounter, pM, route, stopAddedToRoute, site, scheduleProjectId'
when 'skdproject' then 'keyName, scenario'
when 'skdprojectassts' then 'asset, schedule, dataSource, queryName, site'
when 'skdprojectemwo' then 'name, scenario'
when 'skdprojectobj' then 'skdprojectobjObject, schedule, dataSource, queryName'
when 'skdprojectscenario' then 'odmAppName, name, scenario'
when 'skdprojectshifts' then 'schedule, organization, shift'
when 'skdproperty' then 'propertyName, schedulerObjectName'
when 'skdpropertymap' then 'objectName, propertyName, schedulerObjectName'
when 'skdquery' then 'projectName, dataSource, queryName'
when 'skdreservation' then 'objectId, objectName, activityId, projectId, resourceId'
when 'skdreslevelparam' then 'templateName'
when 'skdresobject' then 'activityGroup, resourceTypeObjectName'
when 'skdresource' then 'resourceId, objectId, objectName, projectNumber'
when 'skdresourceuse' then 'objectIdentifier, objectName, referenceObjectName, projectNumber'
when 'skdresourceview' then 'nameOfTheResourceView'
when 'skdspatialparam' then 'templateName'
when 'skduserprop' then 'schedulerProjectName, propertyName, schedulerObjectName, userIdentifier'
when 'sla' then 'sLA'
when 'slaassetloc' then 'asset, type, location, site, sLA'
when 'slacommitments' then 'commitment, sLA'
when 'slacontract' then 'contract, sLA'
when 'slakpi' then 'kPI, sLA'
when 'slarecords' then 'ownerId, ownerTable, sLA'
when 'slroute' then 'uniqueId'
when 'slrtraveltime' then 'uniqueId'
when 'sms' then 'smsAddress, personIdentifier, type'
when 'solution' then 'solution'
when 'solutionspec' then 'attribute, solutionspecSection, solution'
when 'solutionstatus' then 'uniqueId'
when 'sparepart' then 'sparePartId'
when 'splexiconlink' then 'safetyLexiconId, site, workAsset'
when 'sprelatedasset' then 'site, spRelatedAsset'
when 'spworkasset' then 'site, spWorkAsset'
when 'swcacct' then 'accountId'
when 'swcallbuyer' then 'operatorId'
when 'swcauditrules' then 'swcauditrulesid'
when 'swcbusstatus' then 'siteIdP1, recordClassP2, recordKeyP3'
when 'swcbuyerdept' then 'buyerdeptPrimaryKey'
when 'swcchglocattr' then 'attributeName, objectName'
when 'swcchgloccode' then 'site, location'
when 'swcchgloccodehist' then 'uniqueId'
when 'swcchtemp' then 'uniqueId'
when 'swcclaim' then 'swcclaimid'
when 'swcclaimaudit' then 'swcclaimauditid'
when 'swcclaimdetails' then 'swcclaimdetailsid'
when 'swcconaccess' then 'swcConAccessId'
when 'swccontacctmap' then 'uniqueId'
when 'swcconttaskmap' then 'organization, contract, taskCode'
when 'swccpv' then 'cPVId'
when 'swccpvdetails' then 'cpvDetailId'
when 'swccronextact' then 'swccronextactid'
when 'swccronextacthist' then 'swccronextacthistid'
when 'swccrsecurity' then 'workTeam, swccrsecurityUser'
when 'swcdependency' then 'uniqueId'
when 'swcdept' then 'departmentId'
when 'swcdispatchwo' then 'dispatchSystem, serviceContract, serviceDepartment, serviceType'
when 'swcdistbatch' then 'organisation, batch'
when 'swcdistbatchstatus' then 'swcdistbatchstatusid'
when 'swcdistdetail' then 'organization, distribution'
when 'swcdistexlwo' then 'organisation, distributionDetails, workOrder, workOrderOrganisation, workOrderSite'
when 'swcdiststatus' then 'swcdiststatusid'
when 'swcdistwo' then 'organisation, distributionBatch, workOrder, organisationSwc, site'
when 'swcdistwoact' then 'organisation, distributionBatch, transactionId, transactionType'
when 'swcfmisbuyer' then 'swcbuyerId'
when 'swcfmisbuyerpo' then 'buyerId, buyerDescription, swcFMISBuyerPoiD, operatorId'
when 'swcfmiscontractpo' then 'swcfmiscontractpoid'
when 'swcfrmorder' then 'site, externalReference, workOrder'
when 'swcgroupauth' then 'uniqueId'
when 'swchierancestor' then 'orgid, searchHierarchy, code, type'
when 'swchierarchy' then 'organisation, code, type'
when 'swchierrole' then 'swchierroleid'
when 'swcinspectcode' then 'uniqueId, riskCode'
when 'swclabtrans_comparision' then 'uniqueId'
when 'swclga' then 'lgaCode'
when 'swcloccallinst' then 'siteid, type, location, sortOrder'
when 'swclochazdetail' then 'hazardId'
when 'swclocprodlvl' then 'swclocprodlvlid'
when 'swclocservdef' then 'siteid, assessedPriority, location, serviceType, workCategory, workType'
when 'swcoprbuyer' then 'swcoprbuyerid'
when 'swcpagequery' then 'lpqsid'
when 'swcproblemtype' then 'problemType'
when 'swcprobtypeprod' then 'problemType, product'
when 'swcprodlvl' then 'swcprodlvlLevel, product'
when 'swcprojpnum' then 'uniqueId'
when 'swcrdomlookup' then 'swcrdomlookupid'
when 'swcrrtrate' then 'item, swcrrtrateMax, swcrrtrateMin, unitcost'
when 'swcservcontdept' then 'organization, serviceContract, serviceDepartment'
when 'swcservitemvendor' then 'itemSetId, lgaCode, serviceItem'
when 'swcservmap' then 'swcservmapid'
when 'swcservswap' then 'serviceSwapId'
when 'swcservswapbypass' then 'swcservswapbypassid'
when 'swcsralog' then 'swcsralogid'
when 'swcsrapt' then 'organisation, crontaskName, instanceName, problemType'
when 'swcwoactplan' then 'uniqueId'
when 'swcwoext' then 'swcwoextid, workorderid'
when 'synonymdomain' then 'synonymdomainDomain, internalValue, organization, site, synonymdomainValue'
when 'tableexttplt' then 'ownerId'
when 'taglock' then 'site, id'
when 'tagout' then 'site, tagOut'
when 'tamitdpahwm' then 'uniqueId'
when 'tamitswprtnum' then 'cCId, partNumber'
when 'tax' then 'effectiveDate, organization, taxCode, taxCodeIdentifier'
when 'taxorder' then 'organization, tableName'
when 'taxtype' then 'organization, taxCodeIdentifier'
when 'tdtversion' then 'tdtoolkitLanguage, tdtoolkitPmpname, tdtoolkitVersion'
when 'templatestatus' then 'templateStatusId'
when 'term' then 'termUId'
when 'ticket' then 'ticketClass, serviceRequest'
when 'ticketspec' then 'attribute, ticketspecClass, ticketspecSection, ticket'
when 'timezonerule' then 'timezoneruleObject, organization, process, site'
when 'tkownerhistory' then 'tkownerhistoryClass, tkownerhistoryDate, ticket'
when 'tkserviceaddress' then 'tkserviceaddressClass, serviceRequest'
when 'tkstatus' then 'tKStatusId'
when 'tktemplate' then 'template'
when 'tktemplatespec' then 'attribute, tktemplatespecClass, tktemplatespecSection, template'
when 'tktempltactivity' then 'tKTempltActivityId'
when 'tktempltactyspec' then 'attribute, referenceObjectId, referenceObjectName, template'
when 'tloamassetgrp' then 'uniqueId'
when 'tloamdpaancestor' then 'uniqueId'
when 'tloamdpahwm' then 'uniqueId'
when 'tloamprmdflt' then 'defaultName'
when 'tloamsoftware' then 'uniqueIdTLoam'
when 'tloamswcatalog' then 'uniqueId'
when 'tloamswrel' then 'uniqueId'
when 'toolqual' then 'tool, itemSet, organization, qualification'
when 'tooltrans' then 'tool, site, toolTransId'
when 'userpurgl' then 'organization, userpurglUser'
when 'vendorstatus' then 'vendorStatusId'
when 'warrantyasset' then 'assetId, contract, orgId, revision, uniqueId'
when 'warrantyline' then 'line, contract, organization, revision'
when 'wfaction' then 'actionID, process, processRevision'
when 'wfactivation' then 'ownerId, ownerTable, process'
when 'wfapptoolbar' then 'application, wfapptoolbarSequence'
when 'wfasgngroup' then 'groupNumber, nodeId, process, revision, workflowId'
when 'wfassignment' then 'assignment, nodeId, process, processRevision, workflowId'
when 'wfcallstack' then 'callSequence, workflowId'
when 'wfcondition' then 'nodeId, process, processRevision'
when 'wfinput' then 'nodeId, process, processRevision'
when 'wfinstance' then 'workflowId'
when 'wfinteraction' then 'nodeId, processName, processRevision'
when 'wfnode' then 'nodeId, process, processRevision'
when 'wfnotification' then 'process, processRevision, uniqueId'
when 'wfprocess' then 'process, processRevision'
when 'wfrevision' then 'mainProcess, process, activationNumber'
when 'wfstart' then 'nodeId, process, processRevision'
when 'wfstop' then 'nodeId, process, processRevision'
when 'wfsubprocess' then 'nodeId, process, processRevision'
when 'wftask' then 'nodeId, process, processRevision'
when 'wftransaction' then 'transId'
when 'wfwaitlist' then 'event, nodeId, process, processRevision'
when 'wmassigntmp' then 'uniqueId'
when 'wmmatch' then 'uniqueId'
when 'wmmatchcrw' then 'uniqueId'
when 'woancestor' then 'ancestor, site, workOrder'
when 'wocontract' then 'uniqueId'
when 'wogen' then 'runId, runOrder, site'
when 'wohazard' then 'hazard, site, workOrder, safetyDataSource'
when 'wohazardprec' then 'hazard, precaution, site, workOrder, sourceOfSafety'
when 'wolockout' then 'wolockoutid'
when 'womatstatussync' then 'item, itemSet, storeroom, site'
when 'wometer' then 'site, wOMeterId, workOrder'
when 'woownerhistory' then 'ownDate, site, workOrder'
when 'woprecaution' then 'precautionId, site, workOrder, safetyDataSource'
when 'worelext' then 'site, workOrder'
when 'worklog' then 'worklogId'
when 'workorder' then 'site, workOrder, rowStamp'
when 'workorderspec' then 'attribute, workorderspecSection, site, workOrder'
when 'workperiod' then 'calendar, organization, shift, workDate'
when 'workpriority' then 'priority, site'
when 'worktype' then 'workTypeId'
when 'workview' then 'workviewClass, record, site'
when 'workzone' then 'organization, workZone'
when 'wosafetylink' then 'site, workLinkId'
when 'wosafetyplan' then 'site, workOrder'
when 'woserviceaddress' then 'site, workorderNumber'
when 'wostatus' then 'wOStatusId'
when 'wotaglock' then 'site, id'
when 'wotagout' then 'site, tagoutId, workOrder, safetyDataSource'
when 'wotaskrelation' then 'uniqueId'
when 'wpeditsetting' then 'organization, status'
when 'wpitem' then 'wPitEMid'
when 'wplabor' then 'site, workOrder, wpLaborId'
when 'numericdomain' then 'domainId, domainValue, site, organization'
else businessKeyColumn
end
where SystemCode like 'maximo%'
and SourceTableName in ('ADDRESS', 'ALNDOMAIN', 'ASSET', 'ASSETATTRIBUTE', 'ASSETMETER', 'ASSETSPEC', 'CLASSIFICATION', 'CLASSSTRUCTURE', 'CONTRACT', 'DOCLINKS', 'FAILURECODE', 'FAILUREREPORT', 'FINCNTRL', 'JOBLABOR', 'JOBPLAN', 'LABOR', 'LABTRANS', 'LOCANCESTOR', 'LOCATIONMETER', 'LOCATIONS', 'LOCATIONSPEC', 'LOCHIERARCHY', 'LOCOPER', 'LONGDESCRIPTION', 'MATUSETRANS', 'MAXINTMSGTRK', 'MULTIASSETLOCCI', 'PERSON', 'PERSONGROUP', 'PERSONGROUPTEAM', 'PHONE', 'PM', 'RELATEDRECORD', 'ROUTE_STOP', 'ROUTES', 'SERVRECTRANS', 'SWCBUSSTATUS', 'SWCHIERARCHY', 'SWCLGA', 'SWCPROBLEMTYPE', 'SWCWOEXT', 'SYNONYMDOMAIN', 'TICKET', 'TOOLTRANS', 'WOANCESTOR', 'WORKLOG', 'WORKORDER', 'WORKORDERSPEC', 'WOSTATUS', 'DOCINFO', 'ACCOUNTDEFAULTS', 'ACTCI', 'ACTCIRELATION', 'ACTCISPEC', 'ACTION', 'ACTIONGROUP', 'ACTIONSCFG', 'ALTITEM', 'AMCREW', 'AMCREWLABOR', 'AMCREWLABPOS', 'AMCREWMODAVAIL', 'AMCREWQUAL', 'AMCREWSTATHIS', 'AMCREWT', 'AMCREWTOOL', 'AMCREWTOOLSQ', 'AMCREWWOLAB', 'AMCREWWORKZONE', 'AMCREWWOTL', 'AMCTCRAFT', 'AMCTQUAL', 'AMCTSTATHIST', 'AMCTTOOL', 'APPDOCTYPE', 'APPLICATIONAUTH', 'ARCHIVE', 'AREASAFFECTED', 'ASSETANCESTOR', 'ASSETFEASPECHIST', 'ASSETFEATURE', 'ASSETFEATUREHIST', 'ASSETFEATURESPEC', 'ASSETHIERARCHY', 'ASSETHISTORY', 'ASSETLOCCOMM', 'ASSETLOCRELATION', 'ASSETLOCRELHIST', 'ASSETLOCUSERCUST', 'ASSETMNTSKD', 'ASSETOPSKD', 'ASSETSPECHIST', 'ASSETSTATUS', 'ASSETTOPOCACHE', 'ASSETTRANS', 'ASSETWORKZONE', 'ASSIGNMENT', 'ASSIGNREPLOC', 'ASTMSOVER', 'ASTSPECMSOVER', 'ATTENDANCE', 'AUTOATTRUPDATE', 'AUTOSCRIPTVARS', 'BBOARDAUDIENCE', 'BBOARDMSGSTATUS', 'BBSTATUSHISTORY', 'BILLTOSHIPTO', 'BOOKMARK', 'BULLETINBOARD', 'CALENDAR', 'CALENDARBREAK', 'CDMCITYPES', 'CHARPOINTACTION', 'CHARTOFACCOUNTS', 'CI', 'CIRELATION', 'CIRELATIONHIS', 'CISPEC', 'CISPECHIS', 'CISTATUS', 'CITEMPLATE', 'CITYPESTATUS', 'CLASSANCESTOR', 'CLASSSPEC', 'CLASSSPECUSEWITH', 'CLASSUSEWITH', 'COLLECTDETAILS', 'COLLECTION', 'COLLECTIONAUTH', 'COMMITGROUP', 'COMMITPERSON', 'COMMLOG', 'COMMLOGDOCS', 'COMMODITIES', 'COMMTEMPLATE', 'COMMTEMPLATEDOCS', 'COMMTMPLTSENDTO', 'COMPANIES', 'COMPANYACCDEF', 'COMPCOMMODITY', 'COMPCONTACT', 'COMPCONTACTMSTR', 'COMPMASTER', 'CONDITION', 'CONTASSETMETER', 'CONTCOMMODITY', 'CONTLINEASSET', 'CONTLINEMETER', 'CONTRACTASSET', 'CONTRACTAUTH', 'CONTRACTDEFAULT', 'CONTRACTLEASE', 'CONTRACTLINE', 'CONTRACTMASTER', 'CONTRACTPROPERTY', 'CONTRACTPURCH', 'CONTRACTSFW', 'CONTRACTSTATUS', 'CONTRACTSWLIC', 'CONTRACTTERM', 'CONTRACTTYPE', 'CONTRACTTYPETERM', 'CONTSFWLIC', 'CONVERSION', 'COSTTYPE', 'CRAFT', 'CRAFTRATE', 'CRAFTSKILL', 'CRONTASKHISTORY', 'CURRENCY', 'DEFAULTQUERY', 'DEPHISTORY', 'DEPLOYEDASSET', 'DEPRECIATION', 'DEPSCHED', 'DEPSCHEDHISTORY', 'DEPSCHEDPERIODS', 'DEPTRANS', 'DMSAPISETTING', 'DOCTYPES', 'DPACOMMDEVICE', 'DPACOMPUTER', 'DPACPU', 'DPADISK', 'DPADISPLAY', 'DPAFILE', 'DPAIMAGEDEVICE', 'DPAIPX', 'DPALOGICALDRIVE', 'DPAMEDIAADAPTER', 'DPANETADAPTER', 'DPANETDEVCARD', 'DPANETDEVICE', 'DPANETPRINTER', 'DPAOS', 'DPASOFTWARE', 'DPASWSUITE', 'DPATCPIP', 'DPAUSERINFO', 'EMAIL', 'ESCALATION', 'ESCNOTIFICATION', 'ESCREFPOINT', 'ESCREPEATTRACK', 'ESCSTATUS', 'EVENTRESPONSE', 'EXCHANGE', 'EXCLUDEPASSWORD', 'FACONFIG', 'FAILURELIST', 'FAILUREREMARK', 'FAVITEM', 'FEATURES', 'FEATURESPEC', 'FEATURESTATUS', 'FINANCIALPERIODS', 'GLAUTH', 'GLCOMPONENTS', 'GLCONFIGURE', 'GROUPUSER', 'GRPREASSIGNAUTH', 'HAZARD', 'HAZARDPREC', 'IBMCONTENTCATALOG', 'IBMCONTENTRECEIPTS', 'IMPROFILE', 'INBCOMMSECURITY', 'INBOUNDCOMM', 'INBOUNDCOMMCFG', 'INBXCONFIG', 'INVBALANCES', 'INVCOST', 'INVENTORY', 'INVLIFOFIFOCOST', 'INVLOT', 'INVOICE', 'INVOICECOST', 'INVOICELINE', 'INVOICEMATCH', 'INVOICESTATUS', 'INVOICETERM', 'INVOICETRANS', 'INVRESERVE', 'INVSTATUS', 'INVTRANS', 'INVUSE', 'INVUSELINE', 'INVUSELINESPLIT', 'INVUSESTATUS', 'INVVENDOR', 'ITEM', 'ITEMCONDITION', 'ITEMORGINFO', 'ITEMORGSTATUS', 'ITEMSPEC', 'ITEMSTATUS', 'ITEMSTRUCT', 'JOBITEM', 'JOBPLANCLASS', 'JOBPLANSPEC', 'JOBTASK', 'JOBTASKSPEC', 'JPASSETSPLINK', 'JPTASKRELATION', 'KPIAUTH', 'KPIGCONFIG', 'KPIHISTORY', 'KPILCONFIG', 'KPIMAIN', 'KPIOEE', 'KPISCHEDULE', 'KPITEMPLATE', 'KPITEMPLATEMAIN', 'KPITEMPLATEVAR', 'KPITEMPLATEVARVALUE', 'KPITRENDCFG', 'LABORAUTH', 'LABORCERTHIST', 'LABORCRAFTRATE', 'LABORQUAL', 'LABORQUALSTATUS', 'LABORSTATUS', 'LABORWORKZONE', 'LANGUAGE', 'LAUNCHPOINTVARS', 'LAYOUT', 'LBSLOCATION', 'LIMITTOLERANCE', 'LINEARREFMETHOD', 'LNRRECALIB', 'LNRRECALIBNONAF', 'LOCATIONMNTSKD', 'LOCATIONOPSKD', 'LOCATIONWORKZONE', 'LOCAUTH', 'LOCKOUT', 'LOCLEADTIME', 'LOCMETERREADING', 'LOCSTATUS', 'LOCSYSTEM', 'LOGINBLOCK', 'LOGINTRACKING', 'MAPMANAGER', 'MAPSITES', 'MAPTIP', 'MAPTIPDEFAULTS', 'MAPTIPMENU', 'MASTERPM', 'MASTERPMMETER', 'MASTERPMSEASONS', 'MASTERPMSEQ', 'MATRECTRANS', 'MAXASYNCJOB', 'MAXASYNCJOBMSG', 'MAXASYNCJOBPARAM', 'MAXDOMAINLINK', 'MAXDOMVALCOND', 'MAXDYNAMICDOMLINK', 'MAXENDPOINTDTL', 'MAXGROUP', 'MAXINTERROREXTRACT', 'MAXINTMSGTRKDTL', 'MAXINTOBJAPP', 'MAXLICAPPACCESS', 'MAXLICENSE', 'MAXLICPRDKEYLIST', 'MAXLICPURCHDET', 'MAXLICSTATUS', 'MAXPROP', 'MAXPROPVALUE', 'MAXRECORDLOCK', 'MAXROLE', 'MAXROWSTAMP', 'MAXSERVSECURITY', 'MAXTOKEN', 'MAXUSER', 'MAXUSERSTATUS', 'MEASUREMENT', 'MEASUREPOINT', 'MEASUREUNIT', 'METER', 'METERGROUP', 'METERINGROUP', 'METERREADING', 'MFMAILCFG', 'MFMAILST', 'MFMAILSTCFG', 'MFMAILSTVALCFG', 'MFMAILTRACK', 'MFMAILWF', 'MFMAILWFNODECFG', 'MFMAILWFVALCFG', 'MODAVAIL', 'MR', 'MRCOST', 'MRLINE', 'MRSTATUS', 'MULTIASSETLOCCIPR', 'MXODMAPP', 'MXODMAPPPKG', 'NAMEDUSERS', 'NONWORKTIME', 'OBJECTAPPAUTH', 'OMP', 'OMPCIRLN', 'ORGANIZATION', 'PALETTEITEM', 'PDSPEC', 'PERSCOMMODITY', 'PERSONANCESTOR', 'PERSONCAL', 'PERSONSTATUS', 'PLUSCASSETSTATUS', 'PLUSCDSASSETLINK', 'PLUSCDSCONFIG', 'PLUSCDSINSTR', 'PLUSCDSPOINT', 'PLUSCDSSTATUS', 'PLUSCJPDATASHEET', 'PLUSCJPSTATUS', 'PLUSCPMEXTDATE', 'PLUSCSPOTCHECK', 'PLUSCTEMPLATE', 'PLUSCTPASSET', 'PLUSCTPDATASHEET', 'PLUSCTPHISTORY', 'PLUSCTPMETER', 'PLUSCTPSPAREPART', 'PLUSCTPSPEC', 'PLUSCWODS', 'PLUSCWODSINSTR', 'PLUSCWODSPOINT', 'PLUSDSPLAN', 'PMANCESTOR', 'PMFORECAST', 'PMFORECASTJP', 'PMFORECASTLABOR', 'PMFORECASTMATERIAL', 'PMFORECASTSERVICE', 'PMFORECASTTOOL', 'PMMETER', 'PMSEASONS', 'PMSEQUENCE', 'PO', 'POCOST', 'POECOMSTATUS', 'POINTWO', 'POLINE', 'PORTLET', 'PORTLETDISPLAY', 'POSTATUS', 'POTERM', 'PPCRAFTRATE', 'PPLABORRATE', 'PR', 'PRCOST', 'PRECAUTION', 'PREMIUMPAY', 'PRICALC', 'PRLINE', 'PROCOBJ', 'PROCRULE', 'PRODUCTUPDATE', 'PROPERTYASSOC', 'PROPERTYDEFAULT', 'PRSTATUS', 'PRTERM', 'QUALCRAFTSKILL', 'QUALIFICATION', 'QUALSTATUS', 'QUERY', 'QUOTATIONLINE', 'RECONCOMPFILTER', 'RECONLINK', 'RECONMULTILINK', 'RECONRESULT', 'RECONRULE', 'RECONRULECLAUSE', 'RECONTASK', 'RECONTASKCOMP', 'RECONTASKFILTER', 'RECONTASKFLTRVAL', 'RECONTASKLINK', 'RECORDTIMEZONE', 'RELATEDSLA', 'RELATION', 'RELATIONRULES', 'RELATIONRULESEXT', 'REORDERMUTEX', 'REORDERPAD', 'REPFACAUTH', 'REPORT', 'REPORTADHOC', 'REPORTADHOCCALC', 'REPORTADHOCFIELD', 'REPORTADHOCSUM', 'REPORTAPPAUTH', 'REPORTAUTH', 'REPORTDEPEND', 'REPORTDESIGN', 'REPORTDS', 'REPORTDSPARAM', 'REPORTEXPVALUE', 'REPORTFILEEXPORT', 'REPORTHYPERLINKQUERYURL', 'REPORTJOB', 'REPORTLABEL', 'REPORTLISTCFG', 'REPORTLOOKUP', 'REPORTOSAUTH', 'REPORTOUTPUT', 'REPORTOUTPUTAUTH', 'REPORTOUTPUTCNT', 'REPORTPARAM', 'REPORTPROCRESERVE', 'REPORTPROCSCHED', 'REPORTRUNLOCK', 'REPORTRUNPARAM', 'REPORTRUNQUEUE', 'REPORTSCHED', 'REPORTSECATTKEY', 'REPORTUSAGELOG', 'RESULTSETCOLS', 'RFQ', 'RFQLINE', 'RFQSTATUS', 'RFQTERM', 'RFQVENDOR', 'RFQVENDORTERM', 'RSCONFIG', 'SAFETYLEXICON', 'SAFETYPLAN', 'SCCONFIG', 'SCHEDULE', 'SCHEDULELINE', 'SCRIPTLAUNCHPOINT', 'SCTEMPLATE', 'SECURITYRESTRICT', 'SERVICEADDRESS', 'SETS', 'SFWLICENSE', 'SFWLINE', 'SHIFT', 'SHIFTPATTERNDAY', 'SHIPMENT', 'SHIPMENTLINE', 'SITE', 'SITEAUTH', 'SITEECOM', 'SKDACTION', 'SKDACTIVITY', 'SKDACTIVITYQBE', 'SKDAPPLETEXT', 'SKDASSETLOCQUERY', 'SKDCAPACITYPLANPARAM', 'SKDCOMPLIANCE', 'SKDCOMPLIANCEWOLIST', 'SKDCONSTRAINT', 'SKDCOST', 'SKDCOSTTEMP', 'SKDDATAGROUP', 'SKDEMAVAILRES', 'SKDEXTRACAPACITY', 'SKDGVPREF', 'SKDLABORHRS', 'SKDLABORHRSTEMP', 'SKDLABORMODPARAM', 'SKDOBJECT', 'SKDOBJECTMGR', 'SKDODMAPP', 'SKDODMEMSG', 'SKDODMERUN', 'SKDORIGINDESTMATRIX', 'SKDPMFOCOST', 'SKDPMFOCOSTTEMP', 'SKDPMFORECAST', 'SKDPMFORECASTJP', 'SKDPROJECT', 'SKDPROJECTASSTS', 'SKDPROJECTEMWO', 'SKDPROJECTOBJ', 'SKDPROJECTPUBLISH', 'SKDPROJECTSCENARIO', 'SKDPROJECTSHIFTS', 'SKDPROJECTSTATUS', 'SKDPROPERTY', 'SKDPROPERTYMAP', 'SKDQUERY', 'SKDRESERVATION', 'SKDRESLEVELPARAM', 'SKDRESOBJECT', 'SKDRESOURCE', 'SKDRESOURCEUSE', 'SKDRESOURCEVIEW', 'SKDSPATIALPARAM', 'SKDUSERPROP', 'SKDWORKPLANEXTCAP', 'SLA', 'SLAASSETLOC', 'SLACOMMITMENTS', 'SLACONTRACT', 'SLAKPI', 'SLARECORDS', 'SLROUTE', 'SLRTRAVELTIME', 'SMS', 'SOLUTION', 'SOLUTIONSPEC', 'SOLUTIONSTATUS', 'SPAREPART', 'SPLEXICONLINK', 'SPRELATEDASSET', 'SPWORKASSET', 'SWCACCT', 'SWCALLBUYER', 'SWCAUDITRULES', 'SWCBUYERDEPT', 'SWCCCAUDIT', 'SWCCHGLOCATTR', 'SWCCHGLOCCODE', 'SWCCHGLOCCODEHIST', 'SWCCHTEMP', 'SWCCLAIM', 'SWCCLAIMAUDIT', 'SWCCLAIMDETAILS', 'SWCCONACCESS', 'SWCCONTACCTMAP', 'SWCCONTTASKMAP', 'SWCCPV', 'SWCCPVDETAILS', 'SWCCRONEXTACT', 'SWCCRONEXTACTHIST', 'SWCCRSECURITY', 'SWCDEPENDENCY', 'SWCDEPT', 'SWCDISPATCHWO', 'SWCDISTBATCH', 'SWCDISTBATCHSTATUS', 'SWCDISTDETAIL', 'SWCDISTEXLWO', 'SWCDISTSTATUS', 'SWCDISTWO', 'SWCDISTWOACT', 'SWCEXTFMISINVOICE', 'SWCFMISBUYER', 'SWCFMISBUYERPO', 'SWCFMISCONTRACTPO', 'SWCFMISWOMATPROCESSING', 'SWCFRMORDER', 'SWCGISNAVIGATE', 'SWCGROUPAUTH', 'SWCHIERANCESTOR', 'SWCHIERARCHY_BCKUP', 'SWCHIERROLE', 'SWCINSPECTCODE', 'SWCINVOICESENT', 'SWCLABTRANS_COMPARISION', 'SWCLATESTUSERLOGIN', 'SWCLOCCALLINST', 'SWCLOCHAZDETAIL', 'SWCLOCPRODLVL', 'SWCLOCSERVDEF', 'SWCOPRBUYER', 'SWCPAGEQUERY', 'SWCPROBTYPEPROD', 'SWCPRODLVL', 'SWCPROJACT', 'SWCPROJPNUM', 'SWCRDOMLOOKUP', 'SWCRRTRATE', 'SWCSERVCONTDEPT', 'SWCSERVITEMVENDOR', 'SWCSERVMAP', 'SWCSERVSWAP', 'SWCSERVSWAPBYPASS', 'SWCSRALOG', 'SWCSRAPT', 'SWCWOACTPLAN', 'SWCXLLOADPROCESSING', 'TABLEEXTTPLT', 'TAGLOCK', 'TAGOUT', 'TAMITDPAHWM', 'TAMITSWPRTNUM', 'TAX', 'TAXORDER', 'TAXTYPE', 'TDTVERSION', 'TEMPLATESTATUS', 'TERM', 'TICKETSPEC', 'TIMEZONERULE', 'TKOWNERHISTORY', 'TKSERVICEADDRESS', 'TKSTATUS', 'TKTEMPLATE', 'TKTEMPLATESPEC', 'TKTEMPLTACTIVITY', 'TKTEMPLTACTYSPEC', 'TLOAMASSETGRP', 'TLOAMDPAANCESTOR', 'TLOAMDPAHWM', 'TLOAMPRMDFLT', 'TLOAMSOFTWARE', 'TLOAMSWCATALOG', 'TLOAMSWREL', 'TOOLQUAL', 'USERPURGL', 'VENDORSTATUS', 'WARRANTYASSET', 'WARRANTYLINE', 'WFACTION', 'WFACTIVATION', 'WFAPPTOOLBAR', 'WFASGNGROUP', 'WFASSIGNMENT', 'WFCALLSTACK', 'WFCONDITION', 'WFINPUT', 'WFINSTANCE', 'WFINTERACTION', 'WFNODE', 'WFNOTIFICATION', 'WFPROCESS', 'WFREVISION', 'WFSTART', 'WFSTOP', 'WFSUBPROCESS', 'WFTASK', 'WFTRANSACTION', 'WFWAITLIST', 'WMASSIGNTMP', 'WMMATCH', 'WMMATCHCRW', 'WOCONTRACT', 'WOGEN', 'WOHAZARD', 'WOHAZARDPREC', 'WOLOCKOUT', 'WOMATSTATUSSYNC', 'WOMETER', 'WOOWNERHISTORY', 'WOPRECAUTION', 'WORELEXT', 'WORKPERIOD', 'WORKPRIORITY', 'WORKTYPE', 'WORKVIEW', 'WORKZONE', 'WOSAFETYLINK', 'WOSAFETYPLAN', 'WOSERVICEADDRESS', 'WOTAGLOCK', 'WOTAGOUT', 'WOTASKRELATION', 'WPEDITSETTING', 'WPITEM', 'WPLABOR', 'NUMERICDOMAIN')
""")

#removing ExtendedProperties for cleansed tables requiring history
ExecuteStatement("""
update dbo.extractLoadManifest set
ExtendedProperties = NULL
where systemCode like 'maximo%'
and SourceTableName in ('PERSONGROUP', 'PERSONGROUPTEAM', 'PM', 'RELATEDRECORD', 'WORKORDER', 'ASSET', 'LOCATIONS')
""")


