EXEC CTL.CreateSource @ProjectName = 'EDDiS', 
@StartStageName = 'Raw to Synapse', 
@EndStageName = 'Raw to Synapse', 
@SourceName = 'eddis_EDDIS_OWNER_ADDRESSCONTACT', --
@SourceObjectName = 'EDDIS_OWNER.ADDRESSCONTACT', 
@SourceType = 'BLOB Storage (json)', --BLOB Storage (json.gz)
@DataLoadMode = '', --
@SourceSecretName = '', 
@DLRawSecret = 'datalake-SasToken', 
@DLStagedSecret = 'datalake-SasToken', 
@DBProcessor = '', 
@StageDBSecret = 'AzureSqlDatabase-SQLDB', --
@DLRawSubFolder = 'eddis/EDDIS_OWNER_ADDRESSCONTACT', 
@DLRawType = 'BLOB Storage (json)', -- BLOB Storage (json.gz)
@DLStagedMainFolder = 'eddis', 
@DLStagedSubFolder = 'EDDIS_OWNER_ADDRESSCONTACT', --
@DLStagedType = 'BLOB Storage (csv)', -- sql server or synapse
@DLObjectGrain = 'Day', 
@SourceCommand = '', 
@DLRawtoStageCommand = '', 
@DLStagetoDBCommand = '/build/curated/compliance/compliance-curated', --
@TargetObjectType = '', 
@TargetOverride = '', 
@BusinessKeyColumn = '', 
@WatermarkColumn = '', 
@TrackChanges = '', 
@AdditionalProperty = '', 
@IsAuditTable = '', 
@SoftDeleteSource = ''


EXEC CTL.CreateSource @ProjectName = 'EDDiS', 
@StartStageName = 'Raw to Synapse', 
@EndStageName = 'Raw to Synapse', 
@SourceName = 'eddis_EDDIS_OWNER_ADDRESSCONTACT', --
@SourceObjectName = 'EDDIS_OWNER.ADDRESSCONTACT', 
@SourceType = 'BLOB Storage (json)', --BLOB Storage (json.gz)
@DataLoadMode = 'TRUNCATE-LOAD', --
@SourceSecretName = '', 
@DLRawSecret = 'datalake-SasToken', 
@DLStagedSecret = 'datalake-SasToken', 
@DBProcessor = '', 
@StageDBSecret = 'AzureSynpase-SQLPOOL0', --
@DLRawSubFolder = 'eddis/EDDIS_OWNER_ADDRESSCONTACT', 
@DLRawType = 'BLOB Storage (json)', -- BLOB Storage (json.gz)
@DLStagedMainFolder = 'eddis', 
@DLStagedSubFolder = 'EDDIS_OWNER_ADDRESSCONTACT', --
@DLStagedType = 'BLOB Storage (json)', -- sql server or synapse
@DLObjectGrain = 'Day', 
@SourceCommand = '', 
@DLRawtoStageCommand = '', 
@DLStagetoDBCommand = '/build/curated/compliance/compliance-curated', --
@TargetObjectType = 'Synapse', 
@TargetOverride = '', 
@BusinessKeyColumn = '', 
@WatermarkColumn = '', 
@TrackChanges = '', 
@AdditionalProperty = '', 
@IsAuditTable = '', 
@SoftDeleteSource = ''


EXEC CTL.CreateSource @ProjectName = 'EDDiS', 
@StartStageName = 'Raw to Synapse', 
@EndStageName = 'Raw to Synapse', 
@SourceName = 'eddis_EDDIS_OWNER_CHANNELDATA', 
@SourceObjectName = 'EDDIS_OWNER.CHANNELDATA', 
@SourceType = 'BLOB Storage (json)', 
@DataLoadMode = 'TRUNCATE-LOAD', 
@SourceSecretName = '', 
@DLRawSecret = 'datalake-SasToken', 
@DLStagedSecret = 'datalake-SasToken', 
@DBProcessor = '', 
@StageDBSecret = '', 
@DLRawSubFolder = 'eddis/EDDIS_OWNER_CHANNELDATA', 
@DLRawType = 'BLOB Storage (json)', 
@DLStagedMainFolder = 'eddis', 
@DLStagedSubFolder = 'EDDIS_OWNER_CHANNELDATA', 
@DLStagedType = 'BLOB Storage (json)', 
@DLObjectGrain = 'Day', 
@SourceCommand = '', 
@DLRawtoStageCommand = '', 
@DLStagetoDBCommand = '', 
@TargetObjectType = 'Synapse', 
@TargetOverride = '', 
@BusinessKeyColumn = '', 
@WatermarkColumn = '', 
@TrackChanges = 'No', 
@AdditionalProperty = '', 
@IsAuditTable = '', 
@SoftDeleteSource = ''

