name: $(Build.BuildId).$(date:yyyyMMdd)

trigger:
  branches:
    include: [ 'develop', 'test', 'preprod', 'main' ]
  paths:
    include: [ 'ADS-Databases', 'DataFactory', 'Databricks', 'Includes/dls/raw/cleansed_csv' ] 
stages:
- stage: BuildStage
  jobs:
    - job: WindowsAgent
      pool: 
        vmImage: 'windows-2019'
      steps:
      #========================
      # DEPENDANCIES 
      #========================
      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'
      - task: Npm@1
        inputs:
          command: 'install'
          workingDir: '$(Build.Repository.LocalPath)/DevOps/.pipelines'
          verbose: true
        displayName: 'Install npm package'
      #========================
      # BUILD 
      #========================
      - task: Npm@1
        inputs:
          command: 'custom'
          workingDir: '$(Build.Repository.LocalPath)//DevOps/.pipelines'
          customCommand: 'run build export $(Build.Repository.LocalPath)/DataFactory /subscriptions/e59a4313-66c3-4db6-842d-6154c5e08205/resourceGroups/rg-swcnonprod01-daf-dev-01/providers/Microsoft.DataFactory/factories/adf-swcnonprod01-daf-dev-01 "ArmTemplate"'
        displayName: 'Generate ADF ARM template'
      - task: MSBuild@1
        displayName: 'Build ControlDB'
        enabled: true 
        inputs:
          solution: ADS-Databases/CntrlDb/CntrlDb.sqlproj
      #========================
      # PUBLISH
      #========================
      - task: PublishBuildArtifacts@1
        displayName: 'Publish ADF'
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/DevOps/.pipelines/ArmTemplate'
          ArtifactName: 'ADF'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Databricks'
        inputs:
          PathtoPublish: 'Databricks'
          ArtifactName: 'Databricks'
      - task: PublishBuildArtifacts@1
        displayName: 'Publish ControlDB'
        enabled: true
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/ADS-Databases/CntrlDB/bin/Debug'
          ArtifactName: ControlDB
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Includes'
        enabled: true
        inputs:
          PathtoPublish: '$(Build.Repository.LocalPath)/Includes'
          ArtifactName: Includes
