name: $(Build.BuildId).$(date:yyyyMMdd)

pr:
  branches:
    include:
    - main        #
    - test
    - develop

  paths:
    include:
    - AzureResources/*
    - DevOps/Pipelines/*

trigger: none
  # branches:
  #   include:
  #   - main
  #   - develop
  # paths:
  #   include:
  #   - AzureResources/arm-*
  #   - DevOps/Pipelines/azure-platform-deploy-pipeline-cicd.yml
  #   exclude:
  #   - DevOps/Pipelines/iac-create-keyvaults.yml

pool:
  vmImage: ubuntu-latest

stages:
# ---------------------------------------------------------------------------
# Build artifacts
- stage: 'build' # leave main artifact build stage as 'build'
  variables:
  - template: Variables/deployment-variables.yml
  jobs:
  # Use this section to pull in or out build jobs
  - template: Templates/job-copy-arm.yml
  - ${{ if eq(variables['controldb'], true) }}:  
    - template: Templates/job-build-controldb.yml
# ---------------------------------------------------------------------------
# Release to Non-Production - Develop
- template: Templates/stage-azure-pipelines-deployment.yml
  parameters:
    stage_name: 'develop'
    variable_template_name: npe-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

# ---------------------------------------------------------------------------
# Release to Non-Production - Test Environment
- template: Templates/stage-azure-pipelines-deployment.yml
  parameters:
    stage_name: 'test'
    variable_template_name: npe-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/test'))

# ---------------------------------------------------------------------------
# Release to Non-Production - PreProd Environment
- template: Templates/stage-azure-pipelines-deployment.yml
  parameters:
    #dependencies: ['non_prod'] # Used to define any stage dependencies
    stage_name: 'preprod'
    variable_template_name: prd-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    