name: $(Build.BuildId).$(date:yyyyMMdd)

pr:
  branches:
    include:
    - main
    - develop
    - test
  paths:
    include:
    - Databricks/notebooks/*

trigger:
  branches:
    include:
    - test
    - develop
  paths:
    include:
    - Databricks/notebooks/*

pool: Daf-Self-Hosted-Preprod-Linux

stages:
# ---------------------------------------------------------------------------
# Build artifacts
- stage: 'build'
  jobs:
  # Use this section to pull in or out build jobs
  - template: Templates/job-copy-databricks_notebooks.yml
# --------------------------------------------------------------------------
# Release to Non-Production - Dev Environment
- template: Templates/stage-databricks-integration.yml
  parameters:
    stage_name: 'dev'
    variable_template_name: dev-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

# ---------------------------------------------------------------------------
# Release to Non-Production - Test Environment
- template: Templates/stage-databricks-integration.yml
  parameters:
    stage_name: 'test'
    variable_template_name: test-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/test'))


# ---------------------------------------------------------------------------
# Release to Production - PreProd Environment
- template: Templates/stage-databricks-integration.yml
  parameters:
    stage_name: 'preprod'
    variable_template_name: preprd-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/preprod'))