name: $(Build.BuildId).$(date:yyyyMMdd)

pr:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - Databricks/notebooks/*

trigger:
  branches:
    include:
    - master
    - develop
  paths:
    include:
    - Databricks/notebooks/*

pool:
  vmImage: ubuntu-latest

stages:
# ---------------------------------------------------------------------------
# Build artifacts
- stage: 'build'
  jobs:
  # Use this section to pull in or out build jobs
  - template: Templates/job-copy-databricks_notebooks.yml
# ---------------------------------------------------------------------------
# Release to Non-Production
- template: Templates/stage-databricks-integration.yml
  parameters:
    stage_name: 'non_prod'
    variable_template_name: npe-variables
<<<<<<< HEAD
    # run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/sl-devops'))
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
=======
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/sl-devops'))
    # run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
>>>>>>> c6a3b949500c2979f1fd89a6554c12499c72edc7

# ---------------------------------------------------------------------------
# Release to Production
- template: Templates/stage-databricks-integration.yml
  parameters:
    stage_name: 'prod'
    variable_template_name: prd-variables
    # run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/sl-devops'))
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))