name: $(Build.BuildId).$(date:yyyyMMdd)

pr:
  branches:
    include:
    - main
    - develop
    - test

trigger: none
  # branches:
  #   exclude:
  #   - '*' 

pool: Daf-Self-Pool01
# vmImage: ubuntu-latest

stages:
- stage: 'build'
  jobs:
  - template: Templates/job-copy-arm.yml

# ---------------------------------------------------------------------------
# Release to Non-Prod - Dev.
- stage: deploy_to_dev
  dependsOn: 'build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
  variables:
  - template: Variables/dev-variables.yml
  jobs:
  - job: 'deploy_to_dev'
    steps:
    - download: current
      artifact: arm_templates
    
    - task: AzureResourceGroupDeployment@2
      inputs:
        # azureSubscription cannot be a stage scoped variable
        azureSubscription: ${{ variables.azdoresourceconnection }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourcegroupname }}
        location: ${{ variables.location }}
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/arm_templates/arm-initial-keyvault.json'
        overrideParameters: '-location ${{ variables.location }} -keyVaultName ${{ variables.azurekeyvaultname }} -subnetId $(internalSubnetId)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy AKV to non prod'

    - task: AzureCLI@2
      displayName: 'Add sp to ACL policy'
      name: add_sp_to_acl_policy
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az keyvault set-policy --name "${{ variables.azurekeyvaultname }}" --secret-permissions set delete list get --object-id "${{ variables.spobjectid }}"

    - task: AzureCLI@2
      displayName: 'Set PAL'
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az account show
          az extension add --name managementpartner
          $partner = az managementpartner show | ConvertFrom-Json 
          if ($null -eq $partner) { 
              az managementpartner create --partner-id 1158331 
          }  
          else { 
              az managementpartner update --partner-id 1158331 
          }
          Write-Host "Verifying partner Id"
          az managementpartner show

# -----------------------------------------------------------------------------
# Release to Non-Prod - Test
- stage: deploy_to_test
  dependsOn: 'build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/test'))
  variables:
  - template: Variables/test-variables.yml
  jobs:
  - job: 'deploy_to_test'
    steps:
    - download: current
      artifact: arm_templates
    - task: AzureResourceGroupDeployment@2
      inputs:
        # azureSubscription cannot be a stage scoped variable
        azureSubscription: ${{ variables.azdoresourceconnection }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourcegroupname }}
        location: ${{ variables.location }}
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/arm_templates/arm-initial-keyvault.json'
        overrideParameters: '-location ${{ variables.location }} -keyVaultName ${{ variables.azurekeyvaultname }} -subnetId $(internalSubnetId)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy AKV to non prod'

    - task: AzureCLI@2
      displayName: 'Add sp to ACL policy'
      name: add_sp_to_acl_policy
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az keyvault set-policy --name "${{ variables.azurekeyvaultname }}" --secret-permissions set delete list get --object-id "${{ variables.spobjectid }}"

    - task: AzureCLI@2
      displayName: 'Set PAL'
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az account show
          az extension add --name managementpartner
          $partner = az managementpartner show | ConvertFrom-Json 
          if ($null -eq $partner) { 
              az managementpartner create --partner-id 1158331 
          }  
          else { 
              az managementpartner update --partner-id 1158331 
          }
          Write-Host "Verifying partner Id"
          az managementpartner show

# ----------------------------------------------------------------------------
# Release to Pre-Prod
- stage: deploy_to_preprd
  dependsOn: 'build'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/bruno-sandbox'))
  variables:
  - template: Variables/preprd-variables.yml
  jobs:
  - job: 'deploy_to_preprd'
    steps:
    - download: current
      artifact: arm_templates
   
    - task: AzureResourceGroupDeployment@2
      inputs:
        # azureSubscription cannot be a stage scoped variable
        azureSubscription: ${{ variables.azdoresourceconnection }}
        action: 'Create Or Update Resource Group'
        resourceGroupName: ${{ variables.resourcegroupname }}
        location: ${{ variables.location }}
        templateLocation: 'Linked artifact'
        csmFile: '$(Pipeline.Workspace)/arm_templates/arm-initial-keyvault.json'
        overrideParameters: '-location ${{ variables.location }} -keyVaultName ${{ variables.azurekeyvaultname }} -subnetId $(internalSubnetId)'
        deploymentMode: 'Incremental'
      displayName: 'Deploy AKV to prod'

    - task: AzureCLI@2
      displayName: 'Add sp to ACL policy'
      name: add_sp_to_acl_policy
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az keyvault set-policy --name "${{ variables.azurekeyvaultname }}" --secret-permissions set delete list get --object-id "${{ variables.spobjectid }}"

    - task: AzureCLI@2
      displayName: 'Set PAL'
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          az account show
          az extension add --name managementpartner
          $partner = az managementpartner show | ConvertFrom-Json 
          if ($null -eq $partner) { 
              az managementpartner create --partner-id 1158331 
          }  
          else { 
              az managementpartner update --partner-id 1158331 
          }
          Write-Host "Verifying partner Id"
          az managementpartner show