name: $(Build.BuildId).$(date:yyyyMMdd)

pr:
  branches:
    include:
    - main
    - develop
    - test

schedules:
- cron: "0 0 8 * *"
  displayName: Daily midnight build
  branches:
    include:
    - main
    - develop
  

pool:
  vmImage: ubuntu-latest

stages:
# ---------------------------------------------------------------------------
# Release to Non-Production - Dev
- template: Templates/stage-rotate-secrets.yml
  parameters:
    stage_name: 'non_prod'
    variable_template_name: npe-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

# ---------------------------------------------------------------------------
# Release to Non-Production - Test
- template: Templates/stage-rotate-secrets.yml
  parameters:
    stage_name: 'non_prod'
    variable_template_name: npe-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/test'))

# ---------------------------------------------------------------------------
# Release to Non-Production - PreProd
- template: Templates/stage-rotate-secrets.yml
  parameters:
    stage_name: 'preprod'
    variable_template_name: preprd-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))