name: $(Build.BuildId).$(date:yyyyMMdd)

pr:
  branches:
    include:
    - master
    - develop

schedules:
- cron: "0 0 8 * *"
  displayName: Daily midnight build
  branches:
    include:
    # - master
    - develop
  

pool:
  vmImage: ubuntu-latest

stages:
# ---------------------------------------------------------------------------
# Release to Non-Production
- template: Templates/stage-rotate-secrets.yml
  parameters:
    stage_name: 'non_prod'
    variable_template_name: npe-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))

# ---------------------------------------------------------------------------
# Release to Production
- template: Templates/stage-rotate-secrets.yml
  parameters:
    stage_name: 'prod'
    variable_template_name: prd-variables
    run_condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))