variables:
  # Used in service naming
  - name: prefix
    value: staubswc
  # The default resource group region name
  - name: location
    value: australiaeast
  # environment name used in service naming
  - name: environment
    value: dev
  # Resource group name
  - name: resourcegroupname
    value: rg-swcnonprod01-daf-dev-01
  # username for SQL Server Control DB
  - name: azuresqlserverun
    value: sqladmin
  # Name of the service connection in Azure Devops
  - name: azdoresourceconnection
    value: azure-rg-dev-serviceconnection
  # The service principal object ID (Not App ID)... Use 'az ad sp show --id <<app-id>> --query "objectId" -o tsv'
  - name: spobjectid
    value: 5f94952e-aed6-47c0-8db3-a5e464f71e30
  # Store account type for BLOB Storage e.g. Standard_LRS)
  - name: storageAccountType
    value: Standard_LRS
  # Tagging.
  - name: applytags
    value: false
  - name: tags
    value: CostCenter=DataAndAI \
          Environment=NonProduction \
          Owner=jackson.staub@insight.com
  # ------------------------------------------------
  # Service names for environment
  # ------------------------------------------------
  # Name of Azure SQL Server and EDW Database
  - name: azuresqlservername
    value: ${{ lower(variables.prefix) }}-${{ lower(variables.environment) }}-asql
  - name: azureedwdbname
    value: EDW
  # Name of key vault for this environment
  - name: azurekeyvaultname
    value: $(PREFIX)-$(ENVIRONMENT)-AKV
  # Setup secret rotation interval in days
  - name: secretrotationinterval 
    value: 30
  # Name of Log Analytics workspace name
  - name: loganalyticsworkspacename
    value: $(PREFIX)-$(ENVIRONMENT)-ALA
  - name: logstorageaccountname
    value: ${{ replace(lower(variables.prefix),'-','') }}${{ replace(lower(variables.environment),'-','') }}salogs
  # Name of Azure SQL Server and catalog name
  # Data Lake storage account names, commonly split
  # into zones. Ensure it is a comma delimited list
  # as it is split into an array within the ARM 
  # template.
  - name: blobstorageaccountnames
    value: ${{ replace(lower(variables.prefix),'-','') }}${{ replace(lower(variables.environment),'-','') }}saraw, ${{ replace(lower(variables.prefix),'-','') }}${{ replace(lower(variables.environment),'-','') }}sacurated
  - name: datalakestorageaccountnames
    value: ${{ replace(lower(variables.prefix),'-','') }}${{ replace(lower(variables.environment),'-','') }}adls
  # Container or file system names within storage account
  # Used to iterate in ARM template
  - name: logzonename
    value: databricks
  - name: zonenames
    value: raw, cleansed, curated
    # value: raw, stage, sandbox
  # Databricks workspace name for this enironment
  - name: DATABRICKSWORKSPACENAME #databricksworkspacename
    value: $(PREFIX)-$(ENVIRONMENT)-ADBWS
  # Data Factory service name for this environment
  - name: datafactoryname
    value: $(PREFIX)-$(ENVIRONMENT)-ADF
  # Data Factory self hosted integrated runtime name
  - name: datafactoryshirname
    value: $(PREFIX)-SHIR
  # Flag to specify whether Data Factory requires Git Integration
  - name: isRepoEnabled
    value: true  
  # ------------------------------------------------
  # Log Analytics related
  # ------------------------------------------------
  - name: loganalyticssku
    value: PerGB2018
  - name: loganalyticsretention
    value: 30  
  # ------------------------------------------------
  # Databricks related
  # ------------------------------------------------
  - name: nsgname
    value: $(PREFIX)-$(ENVIRONMENT)-NSG
  - name: nsgid
    value: 
  - name: vnetresourcegroupname
    value: rg-swcnonprod01-network-01
  - name: vnetName
    value: vnet-swcnonprod01-ae-01
  - name: vnetid
    value: /subscriptions/e59a4313-66c3-4db6-842d-6154c5e08205/resourceGroups/rg-swcnonprod01-network-01/providers/Microsoft.Network/virtualNetworks/vnet-swcnonprod01-ae-01
  - name: publicsubnetcidr
    value: 10.97.47.192/26        #10.1.2.0/24
  - name: privatesubnetcidr
    value: 10.97.47.128/26        #10.1.1.0/24
  #- name: DATABRICKSWORKSPACENAME
  #  value: swc-dbwc-dev-01
  - name: custompublicsubnetname
    value: snet-swcnonprod01-ae-daf-dev-dbwpublic-01
  - name: customprivatesubnetname
    value: snet-swcnonprod01-ae-daf-dev-dbwprivate-01
  - name: databrickspricingtier
    value: premium
  - name: databricksclustername
    value: etl-cluster
  - name: sparkClusterVersion
    value: 7.0.x-scala2.12
  - name: databricksdrivernodetypeid
    value: Standard_D3_v2
  - name: databricksnodetypeid
    value: Standard_F4s
  - name: databricksworkers
    value: 2
  - name: databricksautotermination
    value: 10

  # ------------------------------------------------
  # Synapse Analytics related
  # ------------------------------------------------
  - name: synapseworkspacename
    value: syn${{ lower(variables.environmentinitial) }}${{ lower(variables.applicationname) }}adm${{ lower(variables.locationnumber) }}${{ lower(variables.resourcecount) }}
  - name: defaultDataLakeStorageAccountName
    value: staubswcdevadls           #st${{ lower(variables.environmentinitial) }}${{ lower(variables.applicationname) }}lake${{ lower(variables.locationnumber) }}${{ lower(variables.resourcecount) }}
  - name: defaultDataLakeStorageFilesystemName
    value: synapse
  - name: synapsesqlAdministratorLogin
    value: sqladminuser
  - name: synapsesqlPoolName
    value: syn${{ lower(variables.environmentinitial) }}${{ lower(variables.applicationname) }}adm${{ lower(variables.locationnumber) }}${{ lower(variables.resourcecount) }}sqlpool
  #------------------------------------------------
