variables:
  # Used in service naming
  - name: prefix
    value: sl
  # The default resource group region name
  - name: location
    value: australiaeast
  # environment name used in service naming
  - name: environment
    value: nonprod
  # username for SQL Server Control DB
  - name: azuresqlserverun
    value: sqladmin
  # Name of the service connection in Azure Devops
  - name: azdoresourceconnection
    value: SP-Stephen_Lundall-Insight
  # Set the pricing tier for Databricks
  - name: databricksPricingTier
    value: standard
  # The service principal object ID (Not App ID)
  - name: spobjectid
    value: a1860bea-6cf3-4c01-8659-e7ec4977c6a7
  # Store account type for BLOB Storage e.g. Standard_LRS)
  - name: storageAccountType
    value: Standard_LRS

  # ------------------------------------------------
  # Service names for environment
  # ------------------------------------------------
  # Name of key vault for this environment
  - name: azurekeyvaultname
    value: $(PREFIX)-kv-$(ENVIRONMENT)
  # Data Lake storage account names, commonly split
  # into zones. Ensure it is a comma delimited list
  # as it is split into an array within the ARM 
  # template.
  - name: datalakestorageaccountnames
    value: $(PREFIX)saraw$(ENVIRONMENT), $(PREFIX)sastage$(ENVIRONMENT), $(PREFIX)sasandbox$(ENVIRONMENT)
  # Container or file system names within storage account
  # Used to iterate in ARM template
  - name: zonenames
    value: raw, stage, sandbox
  # Databricks workspace name for this enironment
  - name: databricksworkspacename
    value: $(PREFIX)-dbws-$(ENVIRONMENT)
  # Data Factory service name for this environment
  - name: datafactoryname
    value: $(PREFIX)-df-$(ENVIRONMENT)
  # Data Factory self hosted integrated runtime name
  - name: datafactoryshirname
    value: $(PREFIX)-shir-$(ENVIRONMENT)
  # Azure SQL Server Name
  - name: azuresqlservername
    value: $(PREFIX)-asql-$(ENVIRONMENT)

  # ------------------------------------------------
  # Databricks related
  # ------------------------------------------------
  - name: databricksclustername
    value: etl-cluster
  - name: sparkClusterVersion
    value: 6.2.x-scala2.11
  - name: databricksdrivernodetypeid
    value: Standard_D3_v2
  - name: databricksnodetypeid
    value: Standard_F4s
  - name: databricksworkers
    value: 2
  - name: databricksautotermination
    value: 10
  - name: vnetName
    value: 
  - name: customVirtualNetworkId
    value: 
  - name: publicSubnetCidr
    value:  
  - name: privateSubnetCidr
    value: 
  - name: customPublicSubnetName
    value: 
  - name: customPrivateSubnetName
    value: 