variables:
  # Used in service naming
  - name: prefix
    value: PSC-SYD
  # The default resource group region name
  - name: location
    value: australiaeast
  # environment name used in service naming
  - name: environment
    value: NPE
  # Resource group name
  - name: resourcegroupname
    value: $(PREFIX)-$(ENVIRONMENT)-ARG
  # username for SQL Server Control DB
  - name: azuresqlserverun
    value: sqladmin
  # Name of the service connection in Azure Devops
  - name: azdoresourceconnection
    value: PSC_NPE_DataEstate
  # Set the pricing tier for Databricks
  - name: databricksPricingTier
    value: standard
  # The service principal object ID (Not App ID) use az ad sp show --id <app-id> --query "objectId" --output tsv
  - name: spobjectid
    value: 9d773319-08cc-4775-bf74-19861826635b
  # Store account type for BLOB Storage e.g. Standard_LRS)
  - name: storageAccountType
    value: Standard_LRS
  # Tagging
  - name: applytags
    value: true
  - name: tags
    value: CostCenter=DataAndAnalytics \
          Environment=Non-Production \
          Owner=Michael.Clover@dpcwagov.onmicrosoft.com
  # ------------------------------------------------
  # Service names for environment
  # ------------------------------------------------
  # Name of Azure SQL Server and EDW Database
  - name: azuresqlservername
    value: lower($(PREFIX)-$(ENVIRONMENT))-asql
  - name: azureedwdbname
    value: PSC_EDW
  # Name of key vault for this environment
  - name: azurekeyvaultname
    value: $(PREFIX)-$(ENVIRONMENT)-AKV
  # Name of Log Analytics workspace name
  - name: loganalyticsworkspacename
    value: $(PREFIX)-$(ENVIRONMENT)-ALA
  # Name of Azure SQL Server and catalog name
  # Data Lake storage account names, commonly split
  # into zones. Ensure it is a comma delimited list
  # as it is split into an array within the ARM 
  # template.
  - name: logstorageaccountname
    value: replace(lower($(PREFIX)$(ENVIRONMENT)),'-','')salogs
  - name: blobstorageaccountnames
    value: replace(lower($(PREFIX)$(ENVIRONMENT)),'-','')saraw, replace(lower($(PREFIX)$(ENVIRONMENT)),'-','')sacurated
  - name: datalakestorageaccountnames
    value: replace(lower($(PREFIX)$(ENVIRONMENT)),'-','')adls
    # value: $(PREFIX)saraw$(ENVIRONMENT), $(PREFIX)sastage$(ENVIRONMENT), $(PREFIX)sasandbox$(ENVIRONMENT)
  # Container or file system names within storage account
  # Used to iterate in ARM template
  - name: logzonename
    value: databricks
  - name: zonenames
    value: raw, curated
    # value: raw, stage, sandbox
  # Databricks workspace name for this enironment
  - name: databricksworkspacename
    value: $(PREFIX)-$(ENVIRONMENT)-ADBWS
  # Data Factory service name for this environment
  - name: datafactoryname
    value: $(PREFIX)-$(ENVIRONMENT)-ADF
  # Data Factory self hosted integrated runtime name
  - name: datafactoryshirname
    value: lower($(PREFIX)-$(ENVIRONMENT))-shir

  # ------------------------------------------------
  # Log Analytics related
  # ------------------------------------------------
  - name: loganalyticssku
    value: PerGB2018
  - name: loganalyticsretention
    value: 30  
  # ------------------------------------------------
  # Databricks related
  # ------------------------------------------------
  - name: nsgid
    value: 
  - name: vnetName
    value: 
  - name: vnetid
    value: 
  - name: publicsubnetcidr
    value:  
  - name: privatesubnetcidr
    value: 
  - name: custompublicsubnetname
    value: 
  - name: customprivatesubnetname
    value: 
  - name: databrickspricingtier
    value: premium
  - name: databricksclustername
    value: etl-cluster
  - name: sparkClusterVersion
    value: 7.0.x-scala2.12
  - name: databricksdrivernodetypeid
    value: Standard_D3_v2
  - name: databricksnodetypeid
    value: Standard_F4s
  - name: databricksworkers
    value: 2
  - name: databricksautotermination
    value: 10