variables:
  # Used in service naming
  - name: prefix
    value: sl
  - name: location
    value: AustraliaSouthEast
  - name: environment
    value: prod
  - name: azuresqlserverun
    value: sqladmin
  - name: azdoresourceconnection
    value: SP-Stephen_Lundall-Insight
  - name: databricksPricingTier
    value: standard
  - name: spobjectid
    value: a1860bea-6cf3-4c01-8659-e7ec4977c6a7
  - name: storageAccountType
    value: standard

# ------------------------------------------------
  # Service names for environment
  # ------------------------------------------------
  # Name of key vault for this environment
  - name: azurekeyvaultname
    value: $(PREFIX)-kv-$(ENVIRONMENT)
  # Data Lake storage account names, commonly split
  # into zones. Ensure it is a comma delimited list
  # as it is split into an array within the ARM 
  # template.
  - name: datalakestorageaccountnames
    value: $(PREFIX)saraw$(ENVIRONMENT), $(PREFIX)sastage$(ENVIRONMENT), $(PREFIX)sasandbox$(ENVIRONMENT)
  # Container or file system names within storage account
  # Used to iterate in ARM template
  - name: zonenames
    value: raw, stage, sandbox
  # Databricks workspace name for this enironment
  - name: databricksworkspacename
    value: $(PREFIX)-dbws-$(ENVIRONMENT)
  # Data Factory service name for this environment
  - name: datafactoryname
    value: $(PREFIX)-df-$(ENVIRONMENT)
  # Data Factory self hosted integrated runtime name
  - name: datafactoryshirname
    value: $(PREFIX)-shir-$(ENVIRONMENT)
  # Azure SQL Server Name
  - name: azuresqlservername
    value: $(PREFIX)-asql-$(ENVIRONMENT)

  # ------------------------------------------------
  # Databricks VNet related
  # ------------------------------------------------
  - name: databricksclustername
    value: etl-cluster
  - name: sparkClusterVersion
    value: 6.2.x-scala2.11
  - name: databricks_driver_node_type_id
    value: Standard_F8
  - name: databricks_node_type_id
    value: Standard_D3_v2
  - name: databricks_workers
    value: 8
  - name: databricks_autotermination
    value: 10
  - name: vnetName
    value: 
  - name: customVirtualNetworkId
    value: 
  - name: publicSubnetCidr
    value:  
  - name: privateSubnetCidr
    value: 
  - name: customPublicSubnetName
    value: 
  - name: customPrivateSubnetName
    value: 
