# Databricks notebook source
RBAC_UC1 = [
    {
        "Name" : "DataAnalystAdvUsr"
        ,"ExistingGroup" : "True"
        ,"OtherCommands" : [
        ]
        ,"TableFilter" : [
            "raw.access*"
            ,"raw.isu*"
            ,"raw.crm*"
            ,"raw.hydra_tlotparcel"
            ,"raw.hydra_tsystemarea"
            ,"cleansed.access*"
            ,"cleansed.isu*"
            ,"cleansed.crm*"
            ,"cleansed.hydra_tlotparcel"
            ,"cleansed.hydra_tsystemarea"
            ,"curated.dimaccountbusinesspartner"
            ,"curated.dimbusinesspartner"
            ,"curated.dimbusinesspartneraddress"
            ,"curated.dimbusinesspartnergroup"
            ,"curated.dimbusinesspartnerrelation"
            ,"curated.dimcontract"
            ,"curated.dimcontractaccount"
            ,"curated.dimcontracthistory"
            ,"curated.dimdate"
            ,"curated.dimdevice"
            ,"curated.dimdevicecharacteristics"
            ,"curated.dimdevicehistory"
            ,"curated.dimdeviceinstallationhistory"
            ,"curated.dimdisconnectiondocument"
            ,"curated.diminstallation"
            ,"curated.diminstallationfacts"
            ,"curated.diminstallationhistory"
            ,"curated.dimlocation"
            ,"curated.dimmeterconsumptionbillingdocument"
            ,"curated.dimmeterconsumptionbillinglineitem"
            ,"curated.dimproperty"
            ,"curated.dimpropertylot"
            ,"curated.dimpropertyrelation"
            ,"curated.dimpropertyservice"
            ,"curated.dimpropertytypehistory"
            ,"curated.dimregisterhistory"
            ,"curated.dimregisterinstallationhistory"
            ,"curated.dimsewernetwork"
            ,"curated.dimstormwaternetwork"
            ,"curated.dimwaternetwork"
            ,"curated.factbilledwaterconsumption"
            ,"curated.factmonthlyapportionedconsumption"
            ,"curated.viewbusinesspartner"
            ,"curated.viewbusinesspartnergroup"
            ,"curated.viewcontract"
            ,"curated.viewcontractaccount"
            ,"curated.viewdevice"
            ,"curated.viewdevicecharacteristics"
            ,"curated.viewinstallation"
            ,"curated.viewproperty"
            ,"curated.viewpropertyrelation"
            ,"curated.viewpropertyservice"
            ,"semantic.dimaccountbusinesspartner"
            ,"semantic.dimbusinesspartner"
            ,"semantic.dimbusinesspartneraddress"
            ,"semantic.dimbusinesspartnergroup"
            ,"semantic.dimbusinesspartnerrelation"
            ,"semantic.dimcontract"
            ,"semantic.dimcontractaccount"
            ,"semantic.dimcontracthistory"
            ,"semantic.dimdate"
            ,"semantic.dimdevice"
            ,"semantic.dimdevicecharacteristics"
            ,"semantic.dimdevicehistory"
            ,"semantic.dimdeviceinstallationhistory"
            ,"semantic.dimdisconnectiondocument"
            ,"semantic.diminstallation"
            ,"semantic.diminstallationfacts"
            ,"semantic.diminstallationhistory"
            ,"semantic.dimlocation"
            ,"semantic.dimmeterconsumptionbillingdocument"
            ,"semantic.dimmeterconsumptionbillinglineitem"
            ,"semantic.dimproperty"
            ,"semantic.dimpropertylot"
            ,"semantic.dimpropertyrelation"
            ,"semantic.dimpropertyservice"
            ,"semantic.dimpropertytypehistory"
            ,"semantic.dimregisterhistory"
            ,"semantic.dimregisterinstallationhistory"
            ,"semantic.dimsewernetwork"
            ,"semantic.dimstormwaternetwork"
            ,"semantic.dimwaternetwork"
            ,"semantic.factbilledwaterconsumption"
            ,"semantic.factmonthlyapportionedconsumption"
            ,"semantic.viewbusinesspartner"
            ,"semantic.viewbusinesspartnergroup"
            ,"semantic.viewcontract"
            ,"semantic.viewcontractaccount"
            ,"semantic.viewdevice"
            ,"semantic.viewdevicecharacteristics"
            ,"semantic.viewinstallation"
            ,"semantic.viewproperty"
            ,"semantic.viewpropertyrelation"
            ,"semantic.viewpropertyservice"
        ]
        ,"Users" : []
        ,"AADGroups" : []
    }
]

# COMMAND ----------


