

CREATE View [Avetmiss].[Location]
AS

SELECT  [AvetmissLocationSK]
, [LocationID]
, [LocationCode]
, [LocationOrganisationCode]
, [LocationName]
, [LocationDescription]
, [LocationSuburb]
, [LocationPostCode]
, [AddressLine1]
, [AddressLine2]
, [Suburb]
, [AusState]
, [PostCode]
, [Active]
, [InstituteID]
, [InstituteCode]
, [InstituteName]
, [InstituteDescription]
, [RTOCode]
, [InstituteAddressLine1]
, [InstituteAddressLine2]
, [InstituteSuburb]
, [InstituteAusState]
, [InstitutePostcode]
, [RegionID]
, [RegionName]
, [_DLCuratedZoneTimeStamp]
, [_RecordStart]
, [_RecordEnd]
, [_RecordDeleted]
, [_RecordCurrent]
  FROM [compliance].[AvetmissLocation]