CREATE TABLE [tsEChecklist].[ChecklistActionsInvalidRecords] (
    [CheckListId]             INT                                                 NULL,
    [InstanceId]              INT                                                 NULL,
    [TaskNo]                  INT                                                 NULL,
    [ActionedDate]            DATETIME                                            NULL,
    [CreationDate]            DATETIME                                            NULL,
    [Actioner]                NVARCHAR (MAX)                                      NULL,
    [TaskName]                NVARCHAR (MAX)                                      NULL,
    [TaskOwner]               NVARCHAR (MAX)                                      NULL,
    [InitiatedDate]           DATETIME                                            NULL,
    [InitiatedBy]             NVARCHAR (MAX)                                      NULL,
    [HighestStatusId]         INT                                                 NULL,
    [SkillPoint]              NVARCHAR (MAX)                                      NULL,
    [Location]                NVARCHAR (MAX)                                      NULL,
    [FundingType]             NVARCHAR (MAX)                                      NULL,
    [AttendanceMode]          NVARCHAR (MAX)                                      NULL,
    [CostCentre]              NVARCHAR (MAX)                                      NULL,
    [VTO]                     NVARCHAR (MAX) MASKED WITH (FUNCTION = 'default()') NULL,
    [CourseCode]              NVARCHAR (MAX)                                      NULL,
    [Calocc]                  NVARCHAR (MAX)                                      NULL,
    [OfferType]               NVARCHAR (MAX)                                      NULL,
    [LearnerNo]               NVARCHAR (MAX)                                      NULL,
    [DOB]                     NVARCHAR (MAX) MASKED WITH (FUNCTION = 'default()') NULL,
    [FirstName]               NVARCHAR (MAX) MASKED WITH (FUNCTION = 'default()') NULL,
    [LastName]                NVARCHAR (MAX) MASKED WITH (FUNCTION = 'default()') NULL,
    [Quantity]                NVARCHAR (MAX)                                      NULL,
    [StartDate]               NVARCHAR (MAX)                                      NULL,
    [EndDate]                 NVARCHAR (MAX)                                      NULL,
    [Year]                    NVARCHAR (MAX)                                      NULL,
    [Month]                   NVARCHAR (MAX)                                      NULL,
    [Day]                     NVARCHAR (MAX)                                      NULL,
    [Term]                    NVARCHAR (MAX)                                      NULL,
    [ChangeType]              NVARCHAR (MAX)                                      NULL,
    [Marketing]               NVARCHAR (MAX)                                      NULL,
    [StatusName]              NVARCHAR (MAX)                                      NULL,
    [TaskStatusName]          NVARCHAR (MAX)                                      NULL,
    [Final_ChecklistStatus]   NVARCHAR (MAX)                                      NULL,
    [_RecordStart]            DATETIME                                            NULL,
    [_RecordEnd]              DATETIME                                            NULL,
    [_RecordDeleted]          INT                                                 NULL,
    [_RecordCurrent]          INT                                                 NULL,
    [_DLCuratedZoneTimeStamp] DATETIME                                            NULL
);





