CREATE TABLE [edw].[EBS_EnrolmentsAndFees] (
    [Region]                     VARCHAR (100)   NULL,
    [SubRegion]                  VARCHAR (8000)  NULL,
    [Location]                   VARCHAR (10)    NULL,
    [LearnerNo]                  VARCHAR (20)    NULL,
    [PersonCode]                 NUMERIC (10)    NULL,
    [Surname]                    VARCHAR (50)    NULL,
    [FirstName]                  VARCHAR (50)    NULL,
    [USI]                        VARCHAR (10)    NULL,
    [DateUSIverified]            DATETIME2 (7)   NULL,
    [DateOfBirth]                DATETIME2 (7)   NULL,
    [AgeAtEnrolment]             INT             NULL,
    [CampusName]                 VARCHAR (40)    NULL,
    [FacultyName]                VARCHAR (100)   NULL,
    [CourseCode]                 VARCHAR (20)    NULL,
    [CalOccCode]                 VARCHAR (10)    NULL,
    [CourseName]                 VARCHAR (255)   NULL,
    [EnrolmentStartDate]         DATETIME2 (7)   NULL,
    [EnrolmentEndDate]           DATETIME2 (7)   NULL,
    [ProgressCode]               VARCHAR (10)    NULL,
    [ProgressDate]               DATETIME2 (7)   NULL,
    [Progress]                   VARCHAR (40)    NULL,
    [ReasonCode]                 VARCHAR (40)    NULL,
    [ProgressReason]             VARCHAR (1000)  NULL,
    [FundingSource]              VARCHAR (5)     NULL,
    [FundingDescription]         VARCHAR (1000)  NULL,
    [CommitmentIdentifier]       VARCHAR (12)    NULL,
    [CID_Status]                 VARCHAR (40)    NULL,
    [A_T_Flag]                   VARCHAR (240)   NULL,
    [ApprenticeTrainee]          VARCHAR (1000)  NULL,
    [ApprenticeTraineeType]      VARCHAR (1000)  NULL,
    [TCID]                       VARCHAR (10)    NULL,
    [UIO_ID]                     NUMERIC (10)    NULL,
    [OfferingType]               VARCHAR (10)    NULL,
    [OfferingTypeDesc]           VARCHAR (1000)  NULL,
    [OfferingCode]               VARCHAR (240)   NULL,
    [TeachingSection]            VARCHAR (100)   NULL,
    [TSN_StudentFee]             NUMERIC (15, 2) NULL,
    [TSN_FeeTypeIndicator]       VARCHAR (40)    NULL,
    [TSN_FeeTypeIndicatorDesc]   VARCHAR (1000)  NULL,
    [FeeWaivers]                 VARCHAR (8000)  NULL,
    [EnrolmentWaivers]           VARCHAR (8000)  NULL,
    [EBS_CurrentFee]             NUMERIC (38, 2) NULL,
    [ebsFeeExist]                VARCHAR (1)     NOT NULL,
    [WhoToPay]                   VARCHAR (10)    NULL,
    [PostCode]                   VARCHAR (4)     NULL,
    [ResidentialState]           VARCHAR (32)    NULL,
    [ResidentialLocality]        VARCHAR (50)    NULL,
    [HighestPostSchoolQual]      VARCHAR (1)     NULL,
    [PostSchoolQualification]    VARCHAR (1000)  NULL,
    [WelfareStatus]              VARCHAR (1)     NULL,
    [PrimaryCRN]                 VARCHAR (10)    NULL,
    [SecondaryCRN]               VARCHAR (10)    NULL,
    [QualificationLevel]         VARCHAR (1000)  NULL,
    [NationalCourseCode]         VARCHAR (20)    NULL,
    [RESIDENTIAL_STATUS]         VARCHAR (10)    NULL,
    [ResidentialStatus]          VARCHAR (1000)  NULL,
    [CurrEMPstatus]              VARCHAR (2)     NULL,
    [EmploymentStatus]           VARCHAR (1000)  NULL,
    [WorksInNSW]                 VARCHAR (240)   NULL,
    [ESPclient]                  VARCHAR (1)     NULL,
    [ESPOrganistaion]            VARCHAR (3)     NULL,
    [EmploymentServicesProvider] VARCHAR (1000)  NULL,
    [ESPreferral]                VARCHAR (1)     NULL,
    [ESPReferralIDentifier]      VARCHAR (10)    NULL,
    [IndigenousStatus]           VARCHAR (1000)  NULL,
    [Disability]                 VARCHAR (1000)  NULL,
    [DisabilityAssessment]       VARCHAR (1000)  NULL,
    [PU_ID]                      NUMERIC (10)    NULL,
    [PersonalEmail]              VARCHAR (100)   NULL,
    [TAFEemail]                  VARCHAR (128)   NULL,
    [TAFEID]                     VARCHAR (30)    NULL,
    [Mobile]                     VARCHAR (22)    NULL,
    [DataLoadDate]               DATETIME        NOT NULL,
    [OfferingStart]              DATETIME2 (7)   NULL,
    [OfferingEnd]                DATETIME2 (7)   NULL,
    [DtApplied]                  DATETIME2 (7)   NULL,
    [DtEnrolled]                 DATETIME2 (7)   NULL,
    [FacultyCode]                VARCHAR (30)    NULL,
    [ProgressType]               VARCHAR (1)     NULL,
    [DateFirstActive]            DATETIME2 (7)   NULL,
    [UniqueID]                   BIGINT          IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_EnrolmentsAndFee] PRIMARY KEY CLUSTERED ([UniqueID] ASC)
);



