CREATE TABLE [edw].[eChecklist_dbo_checklists_tasks] (
    [CheckListId]                     INT            NULL,
    [TaskNo]                          INT            NULL,
    [TaskName]                        VARCHAR (100)  NULL,
    [TaskOwnerLong]                   VARCHAR (100)  NULL,
    [TaskOwnerShort]                  VARCHAR (10)   NULL,
    [TaskInstructions]                VARCHAR (MAX)  NULL,
    [RecommendedActioners]            VARCHAR (2000) NULL,
    [RecommendedActionersAreOptional] BIT            NULL,
    [ActionerHint]                    VARCHAR (100)  NULL,
    [AllowMultiUserSelect]            BIT            NULL,
    [Controls]                        VARCHAR (MAX)  NULL,
    [NumDDLControls]                  SMALLINT       NULL,
    [NumDateControls]                 SMALLINT       NULL,
    [NumPeopleControls]               SMALLINT       NULL,
    [NumTextBoxControls]              SMALLINT       NULL,
    [NumCheckBoxControls]             SMALLINT       NULL,
    [CCInitiatorIfRejected]           BIT            NULL,
    [PreReqTask]                      INT            NULL,
    [LastModifiedBy]                  VARCHAR (50)   NULL,
    [LastModifiedDate]                SMALLDATETIME  NULL,
    [PostCommentBoxTxt]               VARCHAR (MAX)  NULL,
    [CntrlValToIncludeInCustomRprt1]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt2]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt3]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt4]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt5]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt6]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt7]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt8]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt9]  VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt10] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt11] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt12] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt13] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt14] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt15] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt16] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt17] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt18] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt19] VARCHAR (50)   NULL,
    [CntrlValToIncludeInCustomRprt20] VARCHAR (50)   NULL,
    [_DLRawZoneTimeStamp]             DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]         DATETIME2 (7)  NULL,
    [_RecordStart]                    DATETIME2 (7)  NULL,
    [_RecordEnd]                      DATETIME2 (7)  NULL,
    [_RecordCurrent]                  INT            NULL,
    [_RecordDeleted]                  INT            NULL
);



