CREATE TABLE [edw].[eChecklist_dbo_checklists_instances] (
    [InstanceId]              INT            NULL,
    [CheckListId]             INT            NULL,
    [InstanceName]            VARCHAR (2019) NULL,
    [InitiatedBy]             VARCHAR (50)   NULL,
    [InitiatedDate]           SMALLDATETIME  NULL,
    [StatusId]                INT            NULL,
    [HighestStatusId]         INT            NULL,
    [GUID]                    VARCHAR (100)  NULL,
    [ArchivedBy]              VARCHAR (50)   NULL,
    [ArchivedDate]            SMALLDATETIME  NULL,
    [CancelledBy]             VARCHAR (50)   NULL,
    [CancelledDate]           SMALLDATETIME  NULL,
    [NS1]                     VARCHAR (100)  NULL,
    [NS2]                     VARCHAR (100)  NULL,
    [NS3]                     VARCHAR (100)  NULL,
    [NS4]                     VARCHAR (100)  NULL,
    [NS5]                     VARCHAR (100)  NULL,
    [NS6]                     VARCHAR (100)  NULL,
    [NS7]                     VARCHAR (100)  NULL,
    [NS8]                     VARCHAR (100)  NULL,
    [NS9]                     VARCHAR (100)  NULL,
    [NS10]                    VARCHAR (100)  NULL,
    [NS11]                    VARCHAR (100)  NULL,
    [NS12]                    VARCHAR (100)  NULL,
    [NS13]                    VARCHAR (100)  NULL,
    [NS14]                    VARCHAR (100)  NULL,
    [NS15]                    VARCHAR (100)  NULL,
    [NS16]                    VARCHAR (100)  NULL,
    [NS17]                    VARCHAR (100)  NULL,
    [NS18]                    VARCHAR (100)  NULL,
    [NS19]                    VARCHAR (100)  NULL,
    [NS20]                    VARCHAR (100)  NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordCurrent]          INT            NULL,
    [_RecordDeleted]          INT            NULL
);



