CREATE TABLE [edw].[eChecklist_dbo_checklists_tasks] (
    [CheckListId]                     INT            NULL,
    [TaskNo]                          INT            NULL,
    [TaskName]                        VARCHAR (100)  NULL,
    [TaskOwnerLong]                   VARCHAR (100)  NULL,
    [TaskOwnerShort]                  VARCHAR (10)   NULL,
    [TaskInstructions]                VARCHAR (MAX)  NULL,
    [RecommendedActioners]            VARCHAR (2000) NULL,
    [RecommendedActionersAreOptional] BIT            NULL,
    [ActionerHint]                    VARCHAR (100)  NULL,
    [AllowMultiUserSelect]            BIT            NULL,
    [Controls]                        VARCHAR (MAX)  NULL,
    [NumDDLControls]                  SMALLINT       NULL,
    [NumDateControls]                 SMALLINT       NULL,
    [NumPeopleControls]               SMALLINT       NULL,
    [NumTextBoxControls]              SMALLINT       NULL,
    [NumCheckBoxControls]             SMALLINT       NULL,
    [CCInitiatorIfRejected]           BIT            NULL,
    [PreReqTask]                      INT            NULL,
    [LastModifiedBy]                  VARCHAR (50)   NULL,
    [LastModifiedDate]                SMALLDATETIME  NULL,
    [PostCommentBoxTxt]               VARCHAR (MAX)  NULL,
    [ControlValToIncludeInCustomRprt1]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt2]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt3]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt4]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt5]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt6]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt7]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt8]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt9]  VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt10] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt11] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt12] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt13] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt14] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt15] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt16] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt17] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt18] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt19] VARCHAR (50)   NULL,
    [ControlValToIncludeInCustomRprt20] VARCHAR (50)   NULL,
    [_DLRawZoneTimeStamp]             DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]         DATETIME2 (7)  NULL,
    [_RecordStart]                    DATETIME2 (7)  NULL,
    [_RecordEnd]                      DATETIME2 (7)  NULL,
    [_RecordCurrent]                  INT            NULL,
    [_RecordDeleted]                  INT            NULL
);



