CREATE TABLE [edw].[OneEBS_EBS_0165_UIO_LINKS] (
    [CASCADE_SPECIAL_DETAILS] VARCHAR (1)    NULL,
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [UIO_ID_FROM]             NUMERIC (10)   NULL,
    [UIO_ID_TO]               NUMERIC (10)   NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [CALOCC_CODE_FROM]        VARCHAR (10)   NULL,
    [CALOCC_CODE_TO]          VARCHAR (10)   NULL,
    [CREATE_APP_UNIT]         VARCHAR (1)    NULL,
    [DELIVERY_DATE]           DATETIME2 (7)           NULL,
    [EXPLODE]                 VARCHAR (1)    NULL,
    [MANDATORY]               VARCHAR (1)    NULL,
    [UI_CODE_FROM]            VARCHAR (20)   NULL,
    [UI_CODE_TO]              VARCHAR (20)   NULL,
    [WEEK_NUMBER]             NUMERIC (3)    NULL,
    [SEQUENCENUMBER]          NUMERIC (10)   NULL,
    [IS_AVAILABLE]            VARCHAR (1)    NULL,
    [AVAILABLE_FROM]          DATETIME2 (7)           NULL,
    [AVAILABLE_TO]            DATETIME2 (7)           NULL,
    [DEFAULT_PROGRESS_CODE]   VARCHAR (10)   NULL,
    [IS_CORE]                 VARCHAR (1)    NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

