CREATE TABLE [edw].[OneEBS_EBS_0165_VISA_SUBCLASSES] (
    [IS_FEE_APPLICABLE]        VARCHAR (1)                                       NULL,
    [START_DATE]               DATETIME2 (7)                                              NULL,
    [END_DATE]                 DATETIME2 (7)                                              NULL,
    [CREATED_BY]               VARCHAR (30)                                      NULL,
    [CREATED_DATE]             DATETIME2 (7)                                              NULL,
    [UPDATED_BY]               VARCHAR (30)                                      NULL,
    [UPDATED_DATE]             DATETIME2 (7)                                              NULL,
    [INSTITUTION_CONTEXT_ID]   NUMERIC (10)                                      NULL,
    [ID]                       NUMERIC (10)                                      NULL,
    [CODE]                     VARCHAR (10)                                      NULL,
    [DESCRIPTION]              VARCHAR (240)                                     NULL,
    [VISA_TYPE]                VARCHAR (40) MASKED WITH (FUNCTION = 'default()') NULL,
    [VISA_CLASS]               VARCHAR (40) MASKED WITH (FUNCTION = 'default()') NULL,
    [IS_ACTIVE]                VARCHAR (1)                                       NULL,
    [IS_TEMPORARY_VISA_HOLDER] VARCHAR (1)                                       NULL,
    [IS_ENROLMENT_APPLICABLE]  VARCHAR (1)                                       NULL,
    [IS_TUITION_FEE]           VARCHAR (1)                                       NULL,
    [_transaction_date]        DATETIME2 (7)                                          NULL,
    [year]                     NVARCHAR (MAX)                                    NULL,
    [month]                    NVARCHAR (MAX)                                    NULL,
    [day]                      NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]      DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp]  DATETIME2 (7)                                     NULL,
    [_RecordStart]             DATETIME2 (7)                                     NULL,
    [_RecordEnd]               DATETIME2 (7)                                     NULL,
    [_RecordDeleted]           INT                                               NULL,
    [_RecordCurrent]           INT                                               NULL
);

