CREATE TABLE [edw].[OneEBS_EBS_0165_RC_REPORTS] (
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)   NULL,
    [IS_DIGITAL_SIGNATURE_SUPPORTED] NUMERIC (1)    NULL,
    [IS_BULK_REPORTING_ALLOWED]      VARCHAR (1)    NULL,
    [ALTERNATIVE_CONTEXT]            VARCHAR (30)   NULL,
    [ID]                             NUMERIC (10)   NULL,
    [NAME]                           VARCHAR (100)  NULL,
    [DISPLAY_NAME]                   VARCHAR (100)  NULL,
    [PATH]                           VARCHAR (255)  NULL,
    [DESCRIPTION]                    VARCHAR (512)  NULL,
    [IS_VISIBLE]                     NUMERIC (1)    NULL,
    [CREATED_BY]                     VARCHAR (30)   NULL,
    [CREATED_DATE]                   DATETIME2 (7)           NULL,
    [UPDATED_BY]                     VARCHAR (30)   NULL,
    [UPDATED_DATE]                   DATETIME2 (7)           NULL,
    [AGENT_CONTEXT]                  VARCHAR (50)   NULL,
    [APPLICATION]                    VARCHAR (30)   NULL,
    [CONTEXT]                        VARCHAR (30)   NULL,
    [PRINTER_SELECTION]              VARCHAR (30)   NULL,
    [SAVE_FORMAT]                    VARCHAR (10)   NULL,
    [SUB_CONTEXT]                    VARCHAR (50)   NULL,
    [GEN_SEQ_NO]                     VARCHAR (1)    NULL,
    [_transaction_date]              DATETIME2 (7)       NULL,
    [year]                           NVARCHAR (MAX) NULL,
    [month]                          NVARCHAR (MAX) NULL,
    [day]                            NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)  NULL,
    [_RecordStart]                   DATETIME2 (7)  NULL,
    [_RecordEnd]                     DATETIME2 (7)  NULL,
    [_RecordDeleted]                 INT            NULL,
    [_RecordCurrent]                 INT            NULL
);

