CREATE TABLE [edw].[OneEBS_EBS_0165_FEES_LIST_TEMP] (
    [FEE_RECORD_CODE]                NUMERIC (10)                                         NULL,
    [CALOCC_CALENDAR_TYPE]           VARCHAR (10)                                         NULL,
    [CALOCC_OCCURRENCE_CODE]         VARCHAR (10)                                         NULL,
    [AMOUNT]                         NUMERIC (15, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [FEE_DATE]                       DATETIME2 (7)                                                 NULL,
    [DESCRIPTION]                    VARCHAR (240)                                        NULL,
    [UPDATED_BY]                     VARCHAR (30)                                         NULL,
    [UPDATED_DATE]                   DATETIME2 (7)                                                 NULL,
    [CREATED_BY]                     VARCHAR (30)                                         NULL,
    [CREATED_DATE]                   DATETIME2 (7)                                                 NULL,
    [SFT_STUDENT_FEE_REF]            NUMERIC (10)                                         NULL,
    [STATUS]                         VARCHAR (1)                                          NULL,
    [FES_PERSON_CODE]                NUMERIC (10)                                         NULL,
    [FES_RECORD_TYPE]                VARCHAR (1)                                          NULL,
    [FES_UINS_CODE]                  VARCHAR (20)                                         NULL,
    [FES_UIO_CTYPE]                  VARCHAR (10)                                         NULL,
    [FES_UIO_CALOCC]                 VARCHAR (10)                                         NULL,
    [FES_FEE_TYPE]                   VARCHAR (6)                                          NULL,
    [FES_WHO_TO_PAY]                 VARCHAR (10)                                         NULL,
    [FES_BAL_TO_UPDATE]              NUMERIC (1)                                          NULL,
    [FES_SPONSOR_CODE]               VARCHAR (30)                                         NULL,
    [FES_GROSS_AMOUNT]               NUMERIC (15, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [FES_WAIVER_TYPE]                VARCHAR (10)                                         NULL,
    [FES_WAIVER_CTYPE]               VARCHAR (10)                                         NULL,
    [FES_WAIVER_CALOCC]              VARCHAR (10)                                         NULL,
    [FES_TAX_FLAG]                   VARCHAR (1)                                          NULL,
    [FES_ASSOCIATED_RECORD]          NUMERIC (10)                                         NULL,
    [FES_VAT_AMOUNT]                 NUMERIC (7, 2) MASKED WITH (FUNCTION = 'default()')  NULL,
    [FES_VAT_CODE]                   VARCHAR (2)                                          NULL,
    [FES_VAT_RATE]                   NUMERIC (6, 2)                                       NULL,
    [FES_FUNDING_YEAR]               VARCHAR (10)                                         NULL,
    [FES_RECEIPT_NO]                 VARCHAR (20)                                         NULL,
    [REG_REGISTRATION_CODE]          NUMERIC (10)                                         NULL,
    [PAYMENT_METHOD]                 VARCHAR (10) MASKED WITH (FUNCTION = 'default()')    NULL,
    [TILL_CODE]                      VARCHAR (10)                                         NULL,
    [BOARD_CODE]                     VARCHAR (10)                                         NULL,
    [EXAM_CODE]                      VARCHAR (20)                                         NULL,
    [BOARD_OCCURRENCE]               VARCHAR (10)                                         NULL,
    [EXAM_SERIES]                    VARCHAR (10)                                         NULL,
    [INVOICE_NUMBER]                 NUMERIC (10) MASKED WITH (FUNCTION = 'default()')    NULL,
    [INV_RUN_NUMBER]                 NUMERIC (10)                                         NULL,
    [INV_RUN_DATE]                   DATETIME2 (7)                                                 NULL,
    [ZERO_VALUE_FLAG]                VARCHAR (1)                                          NULL,
    [RUL_CODE]                       NUMERIC (10)                                         NULL,
    [FEE_VALUE_NUMBER]               NUMERIC (10)                                         NULL,
    [WAIVER_VALUE_NUMBER]            NUMERIC (10)                                         NULL,
    [DATE_PRINTED]                   DATETIME2 (7)                                                 NULL,
    [NOTES_ID]                       NUMERIC (10)                                         NULL,
    [Z_READ_DATE]                    DATETIME2 (7)                                                 NULL,
    [INSTALMENT_ID]                  NUMERIC (10)                                         NULL,
    [EPAYMENT_TRANSACTION_ID]        VARCHAR (20) MASKED WITH (FUNCTION = 'default()')    NULL,
    [EPAYMENT_STATUS_CODE]           VARCHAR (10) MASKED WITH (FUNCTION = 'default()')    NULL,
    [EPAYMENT_STATUS]                VARCHAR (1)                                          NULL,
    [EPAYMENT_EXTERNAL_REF]          VARCHAR (50) MASKED WITH (FUNCTION = 'default()')    NULL,
    [ID]                             NUMERIC (10)                                         NULL,
    [MATCHED_FEE_RECORD_CODE]        NUMERIC (10)                                         NULL,
    [INTERNAL_INVOICE_CODE]          VARCHAR (20) MASKED WITH (FUNCTION = 'default()')    NULL,
    [INTERNAL_INVOICE_DATE]          DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')            NULL,
    [Z_READ_BATCH_ID]                NUMERIC (10)                                         NULL,
    [TRANSACTION_ID]                 NUMERIC (10)                                         NULL,
    [TRANSACTION_TYPE]               VARCHAR (30)                                         NULL,
    [TRANSACTION_DATE]               DATETIME2 (7)                                                 NULL,
    [PROCESSED_STATE]                NUMERIC (10)                                         NULL,
    [ORDER_NUMBER]                   VARCHAR (30)                                         NULL,
    [ACCOUNT_CODE]                   VARCHAR (255) MASKED WITH (FUNCTION = 'default()')   NULL,
    [PERSON_FINANCIALLY_RESPONSIBLE] NUMERIC (10)                                         NULL,
    [HAS_APPEARED_ON_ASSIST_REPORT]  VARCHAR (1)                                          NULL,
    [IS_DOUBTFUL]                    VARCHAR (1)                                          NULL,
    [IS_PREPAYMENT]                  VARCHAR (1)                                          NULL,
    [EXTERNAL_REFUND_PAYMENT_REF]    VARCHAR (50) MASKED WITH (FUNCTION = 'default()')    NULL,
    [EXTERNAL_REFUND_PAYMENT_DATE]   DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')            NULL,
    [INVOICE_GROUP_ID]               VARCHAR (20) MASKED WITH (FUNCTION = 'default()')    NULL,
    [IS_GIFT]                        VARCHAR (1)                                          NULL,
    [NUMBER_OF_REMINDERS]            NUMERIC (3)                                          NULL,
    [TENDERED_AMOUNT]                NUMERIC (15, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [REJECTED_PAYMENT]               VARCHAR (1)                                          NULL,
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)                                         NULL,
    [WAS_REFUND_CANCELLED]           VARCHAR (1)                                          NULL,
    [REFUND_CANCELLATION_REASON]     VARCHAR (40)                                         NULL,
    [UIO_RESERVATION_ID]             NUMERIC (10)                                         NULL,
    [_transaction_date]              DATETIME2 (7)                                             NULL,
    [year]                           NVARCHAR (MAX)                                       NULL,
    [month]                          NVARCHAR (MAX)                                       NULL,
    [day]                            NVARCHAR (MAX)                                       NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)                                        NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)                                        NULL,
    [_RecordStart]                   DATETIME2 (7)                                        NULL,
    [_RecordEnd]                     DATETIME2 (7)                                        NULL,
    [_RecordDeleted]                 INT                                                  NULL,
    [_RecordCurrent]                 INT                                                  NULL
);

