CREATE TABLE [edw].[OneEBS_EBS_0165_USERS] (
    [CURRENT_INSTITUTION_CONTEXT] NUMERIC (10)                                       NULL,
    [INSTITUTION_CONTEXT_ID]      NUMERIC (10)                                       NULL,
    [LOCKED_UNTIL]                DATETIME2 (7)                                               NULL,
    [FAILED_LOGIN_ATTEMPTS]       NUMERIC (12)                                       NULL,
    [PASSWORD_CAN_EXPIRE]         VARCHAR (1)                                        NULL,
    [ID]                          NUMERIC (10)                                       NULL,
    [GROUP_ID]                    NUMERIC (10)                                       NULL,
    [NAME]                        VARCHAR (30)                                       NULL,
    [PASS]                        VARCHAR (128) MASKED WITH (FUNCTION = 'default()') NULL,
    [STATUS]                      NUMERIC (1)                                        NULL,
    [STUDENT_OR_TUTOR_ID]         NUMERIC (10)                                       NULL,
    [DIALINUSERNAME]              VARCHAR (256) MASKED WITH (FUNCTION = 'default()') NULL,
    [ENABLED]                     NUMERIC (1)                                        NULL,
    [HAVEAUDIO]                   NUMERIC (1)                                        NULL,
    [HAVEVIDEO]                   NUMERIC (1)                                        NULL,
    [INMEETING]                   NUMERIC (1)                                        NULL,
    [IPADDRESS]                   VARCHAR (15) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PERSON_ID]                   NUMERIC (10)                                       NULL,
    [DEFAULTEMAIL]                NUMERIC (10)                                       NULL,
    [CANCHANGEEMAIL]              NUMERIC (1)                                        NULL,
    [PASSEXPIRYDATE]              DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')          NULL,
    [EBS_PERSON_CODE]             NUMERIC (10)                                       NULL,
    [CREATED_BY]                  VARCHAR (30)                                       NULL,
    [CREATED_DATE]                DATETIME2 (7)                                               NULL,
    [LDAP_PATH]                   VARCHAR (512)                                      NULL,
    [AUTHENTICATION_TYPE]         VARCHAR (10)                                       NULL,
    [DEFAULT_ROLE]                VARCHAR (40)                                       NULL,
    [GROUP_ID2]                   NUMERIC (10)                                       NULL,
    [USER_KEY]                    VARCHAR (40)                                       NULL,
    [ENC_METHOD]                  NUMERIC (10)                                       NULL,
    [DEFAULT_AGENT_ROLE]          VARCHAR (20)                                       NULL,
    [EXTERNAL_REF]                VARCHAR (256)                                      NULL,
    [_DLRawZoneTimeStamp]         DATETIME2 (7)                                      NULL,
    [_DLTrustedZoneTimeStamp]     DATETIME2 (7)                                      NULL,
    [_RecordStart]                DATETIME2 (7)                                      NULL,
    [_RecordEnd]                  DATETIME2 (7)                                      NULL,
    [_RecordDeleted]              INT                                                NULL,
    [_RecordCurrent]              INT                                                NULL
);

