CREATE TABLE [edw].[OneEBS_EBS_0165_ORG_UNIT_PEOPLE] (
    [INSTITUTION_CONTEXT_ID]        NUMERIC (10)   NULL,
    [USER_4]                        VARCHAR (240)  NULL,
    [USER_5]                        VARCHAR (240)  NULL,
    [USER_6]                        VARCHAR (240)  NULL,
    [USER_7]                        VARCHAR (240)  NULL,
    [USER_8]                        VARCHAR (240)  NULL,
    [USER_9]                        VARCHAR (240)  NULL,
    [USER_10]                       VARCHAR (240)  NULL,
    [INCLUDE_IN_DATA_RETURN]        VARCHAR (1)    NULL,
    [PEOPLE_UNITS_ID]               NUMERIC (10)   NULL,
    [WORK_PLACEMENT_CONFIRMED_DATE] DATETIME2 (7)           NULL,
    [ID]                            NUMERIC (10)   NULL,
    [ORG_UNIT_CODE]                 VARCHAR (30)   NULL,
    [PERSON_CODE]                   NUMERIC (10)   NULL,
    [START_DATE]                    DATETIME2 (7)           NULL,
    [END_DATE]                      DATETIME2 (7)           NULL,
    [ADDRESS_CODE]                  NUMERIC (10)   NULL,
    [POSITION]                      VARCHAR (40)   NULL,
    [PRIMARY_CONTACT]               VARCHAR (1)    NULL,
    [TYPE]                          VARCHAR (40)   NULL,
    [CREATED_BY]                    VARCHAR (30)   NULL,
    [CREATED_DATE]                  DATETIME2 (7)           NULL,
    [UPDATED_BY]                    VARCHAR (30)   NULL,
    [UPDATED_DATE]                  DATETIME2 (7)           NULL,
    [USER_1]                        VARCHAR (240)  NULL,
    [USER_2]                        VARCHAR (240)  NULL,
    [USER_3]                        VARCHAR (240)  NULL,
    [_transaction_date]             DATETIME2 (7)       NULL,
    [year]                          NVARCHAR (MAX) NULL,
    [month]                         NVARCHAR (MAX) NULL,
    [day]                           NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]           DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]       DATETIME2 (7)  NULL,
    [_RecordStart]                  DATETIME2 (7)  NULL,
    [_RecordEnd]                    DATETIME2 (7)  NULL,
    [_RecordDeleted]                INT            NULL,
    [_RecordCurrent]                INT            NULL
);

