CREATE TABLE [edw].[OneEBS_EBS_0165_ROLES] (
    [APP_ID]                  VARCHAR (20)   NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)  NULL,
    [GROUP_ID]                NUMERIC (10)   NULL,
    [GROUP_ID2]               NUMERIC (10)   NULL,
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [OBJECT_ID]               NUMERIC (10)   NULL,
    [PERSON_CODE]             NUMERIC (10)   NULL,
    [ROLE]                    VARCHAR (20)   NULL,
    [ROLE_ID]                 NUMERIC (10)   NULL,
    [TYPE]                    VARCHAR (20)   NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)  NULL,
    [_transaction_date]       DATETIME2 (7)  NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

