CREATE TABLE [edw].[OneEBS_EBS_0165_MODES_OF_PROVISION] (
    [PROVISION_CODE]          NUMERIC (2)    NULL,
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [MOA_CODE]                VARCHAR (10)   NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [FES_SHORT_DESCRIPTION]   VARCHAR (13)   NULL,
    [FES_LONG_DESCRIPTION]    VARCHAR (40)   NULL,
    [FES_NOTIONAL_HOURS]      NUMERIC (6, 2) NULL,
    [FES_FTE]                 NUMERIC (3, 2) NULL,
    [FES_ACTIVE]              VARCHAR (1)    NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

