CREATE TABLE [edw].[OneEBS_EBS_0165_WAIVER_TYPES] (
    [WAIVER_CODE]                VARCHAR (10)   NULL,
    [LONG_DESCRIPTION]           VARCHAR (40)   NULL,
    [SHORT_DESCRIPTION]          VARCHAR (13)   NULL,
    [LOWER_AGE_LIMIT]            NUMERIC (3)    NULL,
    [UPPER_AGE_LIMIT]            NUMERIC (3)    NULL,
    [STAFF_WAIVER]               VARCHAR (1)    NULL,
    [DISABILITY_DEPENDENCIES]    VARCHAR (1)    NULL,
    [EXCLUSIVE_WAIVER]           VARCHAR (1)    NULL,
    [CREATED_BY]                 VARCHAR (30)   NULL,
    [CREATED_DATE]               DATETIME2 (7)           NULL,
    [UPDATED_BY]                 VARCHAR (30)   NULL,
    [UPDATED_DATE]               DATETIME2 (7)           NULL,
    [EXCLUSIVE_FEE]              VARCHAR (1)    NULL,
    [USER_1]                     VARCHAR (240)  NULL,
    [USER_2]                     VARCHAR (240)  NULL,
    [USER_3]                     VARCHAR (240)  NULL,
    [USER_4]                     VARCHAR (240)  NULL,
    [USER_5]                     VARCHAR (240)  NULL,
    [USER_6]                     VARCHAR (240)  NULL,
    [USER_7]                     VARCHAR (240)  NULL,
    [USER_8]                     VARCHAR (240)  NULL,
    [USER_9]                     VARCHAR (240)  NULL,
    [USER_10]                    VARCHAR (240)  NULL,
    [FEE_EXEMPTION]              VARCHAR (1)    NULL,
    [INSTITUTION_CONTEXT_ID]     NUMERIC (10)   NULL,
    [IS_ONCE_PER_CALENDAR_YEAR]  VARCHAR (1)    NULL,
    [IS_FEE_HELP_APPLICABLE]     VARCHAR (1)    NULL,
    [IS_VET_FEE_HELP_APPLICABLE] VARCHAR (1)    NULL,
    [_transaction_date]          DATETIME2 (7)       NULL,
    [year]                       NVARCHAR (MAX) NULL,
    [month]                      NVARCHAR (MAX) NULL,
    [day]                        NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]        DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]    DATETIME2 (7)  NULL,
    [_RecordStart]               DATETIME2 (7)  NULL,
    [_RecordEnd]                 DATETIME2 (7)  NULL,
    [_RecordDeleted]             INT            NULL,
    [_RecordCurrent]             INT            NULL
);

