CREATE TABLE [edw].[OneEBS_EBS_0165_ATTACHED_WAIVER_VALUES] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [ATTACHMENT_ID]           NUMERIC (10)   NULL,
    [CHARGE_LEVEL]            VARCHAR (1)    NULL,
    [RUL_CODE]                NUMERIC (10)   NULL,
    [REGISTRATION_CODE]       NUMERIC (10)   NULL,
    [WAIVER_VALUE_NUMBER]     NUMERIC (10)   NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [EVIDENCE_ACCEPTED]       VARCHAR (1)    NULL,
    [NOTES_ID]                NUMERIC (10)   NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

