CREATE TABLE [edw].[OneEBS_EBS_0165_COURSE_ASSESSMENTS] (
    [ID]                       NUMERIC (10)                                      NULL,
    [OBJECT_TYPE]              VARCHAR (3)                                       NULL,
    [OBJECT_ID]                NUMERIC (10)                                      NULL,
    [DESCRIPTION]              VARCHAR (250)                                     NULL,
    [CRS_ASSESSMENT_TYPE]      VARCHAR (10)                                      NULL,
    [HE_ASSESSMENT_SEQUENCE]   NUMERIC (2)                                       NULL,
    [WEIGHTING_PERCENT]        NUMERIC (6, 3)                                    NULL,
    [DUE_DATE]                 DATETIME2 (7)                                              NULL,
    [GRADING_SCHEME_ID]        NUMERIC (10)                                      NULL,
    [NZQA_ID]                  NUMERIC (10)                                      NULL,
    [LOCATION_CODE]            VARCHAR (10)                                      NULL,
    [OWNING_ORGANISATION]      VARCHAR (30)                                      NULL,
    [REQUIRED_THEORY_HOURS]    NUMERIC (5, 2)                                    NULL,
    [REQUIRED_PRACTICAL_HOURS] NUMERIC (5, 2)                                    NULL,
    [PLANNED_START_DATE]       DATETIME2 (7)                                              NULL,
    [PLANNED_END_DATE]         DATETIME2 (7)                                              NULL,
    [NUMBER_OF_RESITS]         NUMERIC (3)                                       NULL,
    [ALLOW_AEGROTATS]          VARCHAR (1)                                       NULL,
    [ALLOW_EXTENSIONS]         VARCHAR (1)                                       NULL,
    [FES_ACTIVE]               VARCHAR (1)                                       NULL,
    [FES_USER_1]               VARCHAR (240)                                     NULL,
    [FES_USER_2]               VARCHAR (240)                                     NULL,
    [FES_USER_3]               VARCHAR (240)                                     NULL,
    [FES_USER_4]               VARCHAR (240)                                     NULL,
    [FES_USER_5]               VARCHAR (240)                                     NULL,
    [FES_USER_6]               VARCHAR (240)                                     NULL,
    [FES_USER_7]               VARCHAR (240)                                     NULL,
    [FES_USER_8]               VARCHAR (240)                                     NULL,
    [FES_USER_9]               VARCHAR (240)                                     NULL,
    [FES_USER_10]              VARCHAR (240)                                     NULL,
    [FES_USER_11]              VARCHAR (240)                                     NULL,
    [FES_USER_12]              VARCHAR (240)                                     NULL,
    [CREATED_BY]               VARCHAR (30)                                      NULL,
    [CREATED_DATE]             DATETIME2 (7)                                              NULL,
    [UPDATED_BY]               VARCHAR (30)                                      NULL,
    [UPDATED_DATE]             DATETIME2 (7)                                              NULL,
    [MARKS_OUT_OF]             NUMERIC (5)                                       NULL,
    [MUST_PASS]                VARCHAR (1)                                       NULL,
    [ASSESSMENT_CODE]          VARCHAR (20)                                      NULL,
    [IS_MANDATORY]             VARCHAR (1)                                       NULL,
    [MIN_PASS_MARK]            VARCHAR (10) MASKED WITH (FUNCTION = 'default()') NULL,
    [MANDATORY_ENROL]          VARCHAR (1)                                       NULL,
    [REQUIRES_OUTCOME]         VARCHAR (1)                                       NULL,
    [ASSESSMENT_INSTRUCTIONS]  VARCHAR (2000)                                    NULL,
    [ASSESSOR_INSTRUCTIONS]    VARCHAR (2000)                                    NULL,
    [HAS_BEST_RESULT]          VARCHAR (1)                                       NULL,
    [INSTITUTION_CONTEXT_ID]   NUMERIC (10)                                      NULL,
    [SORT_ORDER]               NUMERIC (4)                                       NULL,
    [_transaction_date]        DATETIME2 (7)                                          NULL,
    [year]                     NVARCHAR (MAX)                                    NULL,
    [month]                    NVARCHAR (MAX)                                    NULL,
    [day]                      NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]      DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp]  DATETIME2 (7)                                     NULL,
    [_RecordStart]             DATETIME2 (7)                                     NULL,
    [_RecordEnd]               DATETIME2 (7)                                     NULL,
    [_RecordDeleted]           INT                                               NULL,
    [_RecordCurrent]           INT                                               NULL
);

