CREATE TABLE [edw].[OneEBS_EBS_0165_REGISTER_EVENT_DETAILS_SLOTS] (
    [INSTITUTION_CONTEXT_ID]   NUMERIC (10)                                         NULL,
    [ID]                       NUMERIC (10)                                         NULL,
    [REGISTER_EVENT_ID]        NUMERIC (10)                                         NULL,
    [REGISTER_EVENT_DETAIL_ID] NUMERIC (10)                                         NULL,
    [SESSION_CODE]             VARCHAR (10)                                         NULL,
    [REGISTER_EVENT_SLOT_ID]   NUMERIC (10)                                         NULL,
    [OBJECT_TYPE]              VARCHAR (10)                                         NULL,
    [OBJECT_ID]                NUMERIC (10)                                         NULL,
    [PLANNED_START_DATE]       DATETIME2 (7)                                                 NULL,
    [PLANNED_END_DATE]         DATETIME2 (7)                                                 NULL,
    [BREAK]                    NUMERIC (10)                                         NULL,
    [ACTUAL_START_DATE]        DATETIME2 (7)                                                 NULL,
    [ACTUAL_END_DATE]          DATETIME2 (7)                                                 NULL,
    [ADDITIONAL_TIME]          NUMERIC (10)                                         NULL,
    [USAGE_CODE]               VARCHAR (1)                                          NULL,
    [CONTRACT_ID]              NUMERIC (10)                                         NULL,
    [CONTRACT_STATUS_ID]       NUMERIC (10)                                         NULL,
    [AMOUNT_CLAIMED]           NUMERIC (10, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [CREATED_BY]               VARCHAR (30)                                         NULL,
    [CREATED_DATE]             DATETIME2 (7)                                                 NULL,
    [UPDATED_BY]               VARCHAR (30)                                         NULL,
    [UPDATED_DATE]             DATETIME2 (7)                                                 NULL,
    [HAS_MESSAGE_BEEN_SENT]    VARCHAR (1)                                          NULL,
    [ASSOCIATED_BEHAVIOUR_ID]  NUMERIC (10)                                         NULL,
    [IS_ABSENCE_JUSTIFIED]     VARCHAR (1)                                          NULL,
    [_transaction_date]        DATETIME2 (7)                                             NULL,
    [year]                     NVARCHAR (MAX)                                       NULL,
    [month]                    NVARCHAR (MAX)                                       NULL,
    [day]                      NVARCHAR (MAX)                                       NULL,
    [_DLRawZoneTimeStamp]      DATETIME2 (7)                                        NULL,
    [_DLTrustedZoneTimeStamp]  DATETIME2 (7)                                        NULL,
    [_RecordStart]             DATETIME2 (7)                                        NULL,
    [_RecordEnd]               DATETIME2 (7)                                        NULL,
    [_RecordDeleted]           INT                                                  NULL,
    [_RecordCurrent]           INT                                                  NULL
);

