CREATE TABLE [edw].[OneEBS_EBS_0165_PEOPLE_UNITS_VSL] (
    [ATTENDANCE_MODE]              VARCHAR (40)    NULL,
    [CREATED_BY]                   VARCHAR (30)    NULL,
    [CREATED_DATE]                 DATETIME2 (7)   NULL,
    [ECAF_DATE]                    DATETIME2 (7)   NULL,
    [ECAF_ID]                      VARCHAR (10)    NULL,
    [ECAF_STATUS]                  VARCHAR (40)    NULL,
    [ID]                           NUMERIC (10)    NULL,
    [INSTITUTION_CONTEXT_ID]       NUMERIC (10)    NULL,
    [IS_TUITION_ASSURANCE]         VARCHAR (1)     NULL,
    [MANDATORY_SELF_PAY_AMOUNT]    NUMERIC (15, 2) NULL,
    [ORIGINAL_AMOUNT_CHARGED]      NUMERIC (7, 2)  NULL,
    [ORIGINAL_AMOUNT_PAID_UPFRONT] NUMERIC (7, 2)  NULL,
    [ORIGINAL_LOAN_AMOUNT]         NUMERIC (7, 2)  NULL,
    [ORIGINAL_LOAN_FEE]            NUMERIC (7, 2)  NULL,
    [PEOPLE_UNITS_ID]              NUMERIC (10)    NULL,
    [REMISSION_REASON]             VARCHAR (40)    NULL,
    [UPDATED_BY]                   VARCHAR (30)    NULL,
    [UPDATED_DATE]                 DATETIME2 (7)   NULL,
    [_transaction_date]            DATETIME2 (7)   NULL,
    [_DLRawZoneTimeStamp]          DATETIME2 (7)   NULL,
    [year]                         NVARCHAR (MAX)  NULL,
    [month]                        NVARCHAR (MAX)  NULL,
    [day]                          NVARCHAR (MAX)  NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME2 (7)   NULL,
    [_RecordStart]                 DATETIME2 (7)   NULL,
    [_RecordEnd]                   DATETIME2 (7)   NULL,
    [_RecordDeleted]               INT             NULL,
    [_RecordCurrent]               INT             NULL
);

