CREATE TABLE [edw].[OneEBS_EBS_0165_FEE_VALUES] (
    [FEE_VALUE_NUMBER]              NUMERIC (10)                                        NULL,
    [FEE_TYPE_CODE]                 VARCHAR (6)                                         NULL,
    [CHARGE_LEVEL]                  VARCHAR (1)                                         NULL,
    [UNIT_INSTANCE_CODE]            VARCHAR (20)                                        NULL,
    [CALOCC_CTYPE]                  VARCHAR (10)                                        NULL,
    [CALOCC_CODE]                   VARCHAR (10)                                        NULL,
    [CP_FLAG_DEL]                   VARCHAR (1)                                         NULL,
    [AMOUNT_PAYABLE]                NUMERIC (7, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [VAT_CODE]                      VARCHAR (2)                                         NULL,
    [TRANSACTION_TYPE]              VARCHAR (1)                                         NULL,
    [ACCOUNT_CODE]                  VARCHAR (40) MASKED WITH (FUNCTION = 'default()')   NULL,
    [FUNDING_YEAR]                  VARCHAR (10)                                        NULL,
    [START_DATE]                    DATETIME2 (7)                                                NULL,
    [END_DATE]                      DATETIME2 (7)                                                NULL,
    [BOARD_CODE]                    VARCHAR (10)                                        NULL,
    [BOARD_OCCURRENCE]              VARCHAR (10)                                        NULL,
    [SERIES]                        VARCHAR (10)                                        NULL,
    [DEFAULT_INCLUDE]               VARCHAR (1)                                         NULL,
    [OVERSEAS_AMOUNT]               NUMERIC (7, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [EXAM_CODE]                     VARCHAR (20)                                        NULL,
    [CFACS_PRODUCT_ID]              VARCHAR (20)                                        NULL,
    [PAYEES]                        NUMERIC (8, 2)                                      NULL,
    [PRICE_BAND_ID]                 NUMERIC (10)                                        NULL,
    [PRICE_BAND_VALUE]              NUMERIC (10)                                        NULL,
    [UIO_ID]                        NUMERIC (10)                                        NULL,
    [CREATED_BY]                    VARCHAR (30)                                        NULL,
    [CREATED_DATE]                  DATETIME2 (7)                                                NULL,
    [UPDATED_BY]                    VARCHAR (30)                                        NULL,
    [UPDATED_DATE]                  DATETIME2 (7)                                                NULL,
    [NO_OF_OVERSEAS_PAYERS]         NUMERIC (5) MASKED WITH (FUNCTION = 'default()')    NULL,
    [IS_STUDYLINK]                  VARCHAR (1)                                         NULL,
    [DOMESTIC_FCR_AMOUNT]           NUMERIC (7, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [FEE_CALCULATION_METHOD]        VARCHAR (10)                                        NULL,
    [ALLOW_REFUND]                  VARCHAR (1)                                         NULL,
    [ROUNDING_MULTIPLE]             NUMERIC (7, 2)                                      NULL,
    [MIN_VALUE]                     NUMERIC (7, 2)                                      NULL,
    [USER_1]                        VARCHAR (240)                                       NULL,
    [USER_2]                        VARCHAR (240)                                       NULL,
    [USER_3]                        VARCHAR (240)                                       NULL,
    [USER_4]                        VARCHAR (240)                                       NULL,
    [USER_5]                        VARCHAR (240)                                       NULL,
    [USER_6]                        VARCHAR (240)                                       NULL,
    [USER_7]                        VARCHAR (240)                                       NULL,
    [USER_8]                        VARCHAR (240)                                       NULL,
    [USER_9]                        VARCHAR (240)                                       NULL,
    [USER_10]                       VARCHAR (240)                                       NULL,
    [CHARGE_ONCE]                   VARCHAR (40)                                        NULL,
    [IS_TEMP_VISA_HOLDER_FEE]       VARCHAR (1)                                         NULL,
    [GL_COMPONENT_1]                VARCHAR (30)                                        NULL,
    [GL_COMPONENT_2]                VARCHAR (30)                                        NULL,
    [GL_COMPONENT_3]                VARCHAR (30)                                        NULL,
    [GL_COMPONENT_4]                VARCHAR (30)                                        NULL,
    [GL_COMPONENT_5]                VARCHAR (30)                                        NULL,
    [UNIT_OF_STUDY_CODE]            VARCHAR (10)                                        NULL,
    [INSTITUTION_CONTEXT_ID]        NUMERIC (10)                                        NULL,
    [ROLL_FORWARD_SOURCE_FV_NUMBER] NUMERIC (10)                                        NULL,
    [IS_ELIGIBLE_FOR_FEES_FREE]     VARCHAR (1)                                         NULL,
    [_transaction_date]             DATETIME2 (7)                                            NULL,
    [year]                          NVARCHAR (MAX)                                      NULL,
    [month]                         NVARCHAR (MAX)                                      NULL,
    [day]                           NVARCHAR (MAX)                                      NULL,
    [_DLRawZoneTimeStamp]           DATETIME2 (7)                                       NULL,
    [_DLTrustedZoneTimeStamp]       DATETIME2 (7)                                       NULL,
    [_RecordStart]                  DATETIME2 (7)                                       NULL,
    [_RecordEnd]                    DATETIME2 (7)                                       NULL,
    [_RecordDeleted]                INT                                                 NULL,
    [_RecordCurrent]                INT                                                 NULL
);

