CREATE TABLE [edw].[OneEBS_EBS_0165_GRADING_SCHEME_GRADES] (
    [NOMINAL_GRADE]                  NUMERIC (11, 3) NULL,
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)    NULL,
    [WEIGHTING]                      NUMERIC (6, 2)  NULL,
    [POINTS]                         NUMERIC (10, 2) NULL,
    [IS_DEFAULT_WITHDRAWAL_GRADE]    VARCHAR (1)     NULL,
    [IS_DEFAULT_NONSTARTER_GRADE]    VARCHAR (1)     NULL,
    [IS_EXCLUDED_FROM_DOCUMENTATION] VARCHAR (1)     NULL,
    [IS_PASS]                        VARCHAR (1)     NULL,
    [IS_EXTERNAL_GRADE]              VARCHAR (1)     NULL,
    [IS_ACTIVE]                      VARCHAR (1)     NULL,
    [IS_FAILED_FINAL]                VARCHAR (1)     NULL,
    [DEFAULT_FAILED_GRADE]           VARCHAR (1)     NULL,
    [IS_NIL_GRADE]                   VARCHAR (1)     NULL,
    [IS_NOT_COMPLETE_GRADE]          VARCHAR (1)     NULL,
    [INTERNALLY_MARKED]              VARCHAR (1)     NULL,
    [IS_DEFAULT_AUTO_CREDIT]         VARCHAR (1)     NULL,
    [STATE_COMPLETION_CODE]          VARCHAR (10)    NULL,
    [PROGRESS_CODE]                  VARCHAR (10)    NULL,
    [ID]                             NUMERIC (10)    NULL,
    [GRADING_SCHEME_ID]              NUMERIC (10)    NULL,
    [GRADE]                          VARCHAR (10)    NULL,
    [MIN_GRADE]                      NUMERIC (11, 3) NULL,
    [MAX_GRADE]                      NUMERIC (11, 3) NULL,
    [INTERNAL_SCORE]                 NUMERIC (10, 2) NULL,
    [SDR_COMPLETION_CODE]            VARCHAR (40)    NULL,
    [DESCRIPTION]                    VARCHAR (100)   NULL,
    [CREATED_BY]                     VARCHAR (30)    NULL,
    [CREATED_DATE]                   DATETIME2 (7)            NULL,
    [UPDATED_BY]                     VARCHAR (30)    NULL,
    [UPDATED_DATE]                   DATETIME2 (7)            NULL,
    [_transaction_date]              DATETIME2 (7)        NULL,
    [year]                           NVARCHAR (MAX)  NULL,
    [month]                          NVARCHAR (MAX)  NULL,
    [day]                            NVARCHAR (MAX)  NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)   NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)   NULL,
    [_RecordStart]                   DATETIME2 (7)   NULL,
    [_RecordEnd]                     DATETIME2 (7)   NULL,
    [_RecordDeleted]                 INT             NULL,
    [_RecordCurrent]                 INT             NULL
);

