CREATE TABLE [edw].[OneEBS_EBS_0165_NOTES_TOPICS] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [ID]                      NUMERIC (10)   NULL,
    [TOPIC_CODE]              VARCHAR (20)   NULL,
    [SHORT_DESCRIPTION]       VARCHAR (13)   NULL,
    [LONG_DESCRIPTION]        VARCHAR (40)   NULL,
    [LINKED_ROLE_1]           NUMERIC (10)   NULL,
    [LINKED_ROLE_2]           NUMERIC (10)   NULL,
    [IS_ACTIVE]               VARCHAR (1)    NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

