CREATE TABLE [edw].[OneEBS_EBS_0165_COMMUNICATIONS] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [IS_ACTIVE]               VARCHAR (1)    NULL,
    [HAS_BEEN_PRINTED]        VARCHAR (1)    NULL,
    [ID]                      NUMERIC (10)   NULL,
    [LEARNER_ID]              NUMERIC (10)   NULL,
    [FORMAT]                  VARCHAR (40)   NULL,
    [RECIPIENT]               VARCHAR (200)  NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [SUBJECT]                 VARCHAR (1000) NULL,
    [BODY]                    NVARCHAR (MAX) NULL,
    [SOURCE_ID]               NUMERIC (10)   NULL,
    [SOURCE]                  VARCHAR (30)   NULL,
    [BLOB_ID]                 NUMERIC (10)   NULL,
    [PARENT_ID]               NUMERIC (10)   NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [FORMAT_TYPE]             VARCHAR (40)   NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

