CREATE TABLE [edw].[OneEBS_EBS_0165_FEES_LIST_SPECIAL] (
    [ID]                        NUMERIC (10)                                       NULL,
    [FEES_LIST_ID]              NUMERIC (10)                                       NULL,
    [BANK_ID]                   NUMERIC (10)                                       NULL,
    [ACCOUNT_NAME]              VARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [CHEQUE_NUMBER]             VARCHAR (100)                                      NULL,
    [CARD_TYPE]                 VARCHAR (30) MASKED WITH (FUNCTION = 'default()')  NULL,
    [CARD_HOLDER_NAME]          VARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [STATEMENT_DETAILS]         VARCHAR (100)                                      NULL,
    [REFERENCE_NUMBER]          VARCHAR (100)                                      NULL,
    [DATE_BANKED]               DATETIME2 (7)                                               NULL,
    [GL_ACCOUNT]                VARCHAR (30) MASKED WITH (FUNCTION = 'default()')  NULL,
    [COST_CENTRE]               VARCHAR (30)                                       NULL,
    [SUB_ACCOUNT]               VARCHAR (30) MASKED WITH (FUNCTION = 'default()')  NULL,
    [AUTHORISED_BY]             VARCHAR (100)                                      NULL,
    [PAYER_AUTHORISATION_NO]    VARCHAR (100)                                      NULL,
    [DEBTOR_NAME]               VARCHAR (100)                                      NULL,
    [DEBTOR_ID]                 VARCHAR (100)                                      NULL,
    [PAYEE_NAME]                VARCHAR (100)                                      NULL,
    [SWIFT_NUMBER]              VARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [NOTES_ID]                  NUMERIC (10)                                       NULL,
    [CREATED_BY]                VARCHAR (30)                                       NULL,
    [CREATED_DATE]              DATETIME2 (7)                                               NULL,
    [UPDATED_BY]                VARCHAR (30)                                       NULL,
    [UPDATED_DATE]              DATETIME2 (7)                                               NULL,
    [USER_1]                    VARCHAR (240)                                      NULL,
    [USER_2]                    VARCHAR (240)                                      NULL,
    [USER_3]                    VARCHAR (240)                                      NULL,
    [USER_4]                    VARCHAR (240)                                      NULL,
    [USER_5]                    VARCHAR (240)                                      NULL,
    [USER_6]                    VARCHAR (240)                                      NULL,
    [USER_7]                    VARCHAR (240)                                      NULL,
    [USER_8]                    VARCHAR (240)                                      NULL,
    [USER_9]                    VARCHAR (240)                                      NULL,
    [USER_10]                   VARCHAR (240)                                      NULL,
    [ELECTRONIC_PAYMENT_REF_NO] VARCHAR (30) MASKED WITH (FUNCTION = 'default()')  NULL,
    [INSTITUTION_CONTEXT_ID]    NUMERIC (10)                                       NULL,
    [_transaction_date]         DATETIME2 (7)                                           NULL,
    [year]                      NVARCHAR (MAX)                                     NULL,
    [month]                     NVARCHAR (MAX)                                     NULL,
    [day]                       NVARCHAR (MAX)                                     NULL,
    [_DLRawZoneTimeStamp]       DATETIME2 (7)                                      NULL,
    [_DLTrustedZoneTimeStamp]   DATETIME2 (7)                                      NULL,
    [_RecordStart]              DATETIME2 (7)                                      NULL,
    [_RecordEnd]                DATETIME2 (7)                                      NULL,
    [_RecordDeleted]            INT                                                NULL,
    [_RecordCurrent]            INT                                                NULL
);

