CREATE TABLE [edw].[OneEBS_EBS_0165_PROGRESS_CODES] (
    [IS_REENGAGEMENT_ALLOWED]        VARCHAR (1)    NULL,
    [IS_INCLUDED_IN_VFH_EXPORT]      VARCHAR (1)    NULL,
    [INCLUDE_IN_ULN_SUBMISSION]      VARCHAR (1)    NULL,
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)   NULL,
    [REQUIRES_INVOICE_NOTICE]        VARCHAR (1)    NULL,
    [AUTOPRGRSS_FROM_WHEN_ZERO_FEES] VARCHAR (1)    NULL,
    [TYPE_NAME]                      VARCHAR (10)   NULL,
    [STUDENT_STATUS]                 VARCHAR (1)    NULL,
    [TYPE_CODE]                      VARCHAR (6)    NULL,
    [PROGRESS_COMMENT]               VARCHAR (240)  NULL,
    [CREATE_ATTAINMENT]              VARCHAR (1)    NULL,
    [CREATED_BY]                     VARCHAR (30)   NULL,
    [CREATED_DATE]                   DATETIME2 (7)           NULL,
    [UPDATED_BY]                     VARCHAR (30)   NULL,
    [UPDATED_DATE]                   DATETIME2 (7)           NULL,
    [FES_SHORT_DESCRIPTION]          VARCHAR (13)   NULL,
    [FES_LONG_DESCRIPTION]           VARCHAR (40)   NULL,
    [FES_ACTIVE]                     VARCHAR (1)    NULL,
    [IS_VISIBLE]                     VARCHAR (1)    NULL,
    [IS_PENDING]                     VARCHAR (1)    NULL,
    [SDR_COMPLETION_INDICATOR]       VARCHAR (10)   NULL,
    [HAS_COMPLETED]                  VARCHAR (1)    NULL,
    [ROLE_DEFS_ID]                   NUMERIC (10)   NULL,
    [DATA_RETURN]                    VARCHAR (1)    NULL,
    [REQUIRES_OUTCOME]               VARCHAR (1)    NULL,
    [GENERATE_FEES]                  VARCHAR (1)    NULL,
    [_transaction_date]              DATETIME2 (7)       NULL,
    [year]                           NVARCHAR (MAX) NULL,
    [month]                          NVARCHAR (MAX) NULL,
    [day]                            NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)  NULL,
    [_RecordStart]                   DATETIME2 (7)  NULL,
    [_RecordEnd]                     DATETIME2 (7)  NULL,
    [_RecordDeleted]                 INT            NULL,
    [_RecordCurrent]                 INT            NULL
);

