CREATE TABLE [edw].[OneEBS_EBS_0165_ORGANISATION_UNITS] (
    [DO_NOT_PHONE]                VARCHAR (1)                                        NULL,
    [DO_NOT_FAX]                  VARCHAR (1)                                        NULL,
    [DO_NOT_EMAIL]                VARCHAR (1)                                        NULL,
    [DO_NOT_POSTAL_MAIL]          VARCHAR (1)                                        NULL,
    [DO_NOT_BULK_EMAIL]           VARCHAR (1)                                        NULL,
    [DO_NOT_BULK_POSTAL_MAIL]     VARCHAR (1)                                        NULL,
    [EXCLUDE_FROM_MONDAS_EXPORT]  VARCHAR (1)                                        NULL,
    [FAX_CODE]                    VARCHAR (22)                                       NULL,
    [FES_ACTIVE]                  VARCHAR (1)                                        NULL,
    [FES_DEPARTMENT_HEAD]         NUMERIC (10)                                       NULL,
    [FES_FULL_NAME]               VARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [FES_SHORT_NAME]              VARCHAR (13)                                       NULL,
    [MAIN_ACTIVITY]               VARCHAR (10)                                       NULL,
    [MAIN_RISK_FACTOR]            VARCHAR (40)                                       NULL,
    [NOTES_ID]                    NUMERIC (10)                                       NULL,
    [NUMBER_EMPLOYEES]            NUMERIC (10)                                       NULL,
    [POST_CODE]                   VARCHAR (32)                                       NULL,
    [REGION_COUNTY_STATE]         VARCHAR (32)                                       NULL,
    [SPONSOR]                     VARCHAR (1)                                        NULL,
    [TELEPHONE_NUMBER]            VARCHAR (22) MASKED WITH (FUNCTION = 'default()')  NULL,
    [USER_1]                      VARCHAR (240)                                      NULL,
    [USER_2]                      VARCHAR (240)                                      NULL,
    [USER_3]                      VARCHAR (240)                                      NULL,
    [USER_4]                      VARCHAR (240)                                      NULL,
    [USER_5]                      VARCHAR (240)                                      NULL,
    [USER_6]                      VARCHAR (240)                                      NULL,
    [WEB_SITE]                    VARCHAR (1024)                                     NULL,
    [SHOW_IN_CM]                  VARCHAR (1)                                        NULL,
    [SIC_CODE]                    VARCHAR (15)                                       NULL,
    [HEALTH_SAFETY_CERT_EXP_DATE] DATETIME2 (7) MASKED WITH (FUNCTION = 'default()') NULL,
    [LEVEL_OF_ENGAGEMENT]         VARCHAR (10)                                       NULL,
    [TRAINING_TYPE]               VARCHAR (10)                                       NULL,
    [CUSTOMER_SATISFACTION]       VARCHAR (10)                                       NULL,
    [SHOW_IN_CA]                  VARCHAR (1)                                        NULL,
    [USER_7]                      VARCHAR (240)                                      NULL,
    [USER_8]                      VARCHAR (240)                                      NULL,
    [USER_9]                      VARCHAR (240)                                      NULL,
    [USER_10]                     VARCHAR (240)                                      NULL,
    [USER_11]                     VARCHAR (240)                                      NULL,
    [USER_12]                     VARCHAR (240)                                      NULL,
    [USER_13]                     VARCHAR (240)                                      NULL,
    [USER_14]                     VARCHAR (240)                                      NULL,
    [USER_15]                     VARCHAR (240)                                      NULL,
    [USER_16]                     VARCHAR (240)                                      NULL,
    [ID]                          NUMERIC (10)                                       NULL,
    [INSTITUTION_CONTEXT_ID]      NUMERIC (10)                                       NULL,
    [A2C_CENTRE_ID]               NUMERIC (10)                                       NULL,
    [EMPLOYER_REFERENCE_NUMBER]   VARCHAR (9)                                        NULL,
    [UKPRN]                       NUMERIC (8)                                        NULL,
    [IS_SMALL_EMPLOYER]           VARCHAR (1)                                        NULL,
    [HEALTH_SAFETY_STATUS]        VARCHAR (40) MASKED WITH (FUNCTION = 'default()')  NULL,
    [DATE_EMPLOYER_APPROVED]      DATETIME2 (7)                                      NULL,
    [DATE_EMPLOYER_LAST_VETTED]   DATETIME2 (7)                                      NULL,
    [DATE_EMPLOYER_DUE_VETTED]    DATETIME2 (7)                                      NULL,
    [CDA_APPLICATION_TYPE]        VARCHAR (40)                                       NULL,
    [DATE_CDA_LAST_VETTED]        DATETIME2 (7)                                      NULL,
    [LIABILITY_INS_RENEW_DATE]    DATETIME2 (7)                                      NULL,
    [LIABILITY_INS_EXPIRY_DATE]   DATETIME2 (7) MASKED WITH (FUNCTION = 'default()') NULL,
    [SOC_CODE_1]                  VARCHAR (40)                                       NULL,
    [SOC_CODE_2]                  VARCHAR (40)                                       NULL,
    [SOC_CODE_3]                  VARCHAR (40)                                       NULL,
    [SOC_CODE_4]                  VARCHAR (40)                                       NULL,
    [IS_APPROVED_FOR_INVOICING]   VARCHAR (1)                                        NULL,
    [COST_CENTRE_COMPONENT]       VARCHAR (3)                                        NULL,
    [ORGANISATION_CODE]           VARCHAR (30)                                       NULL,
    [INTERNAL_OR_EXTERNAL]        VARCHAR (8)                                        NULL,
    [ORGANISATION_TYPE]           VARCHAR (40)                                       NULL,
    [CREATED_BY]                  VARCHAR (30)                                       NULL,
    [CREATED_DATE]                DATETIME2 (7)                                      NULL,
    [UPDATED_BY]                  VARCHAR (30)                                       NULL,
    [UPDATED_DATE]                DATETIME2 (7)                                      NULL,
    [ADDRESS_LINE_1]              VARCHAR (32) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_2]              VARCHAR (32) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_3]              VARCHAR (32) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ANNUAL_TURNOVER]             NUMERIC (10)                                       NULL,
    [BTEC_CENTRE]                 VARCHAR (5)                                        NULL,
    [BTEC_SUB_CENTRE]             VARCHAR (1)                                        NULL,
    [BUSINESS_SECTOR]             VARCHAR (40)                                       NULL,
    [CENTRE_NUMBER]               NUMERIC (5)                                        NULL,
    [CFACS_NAME_CODE]             VARCHAR (8)                                        NULL,
    [CG_CENTRE]                   VARCHAR (6)                                        NULL,
    [CG_SUB_CENTRE]               VARCHAR (1)                                        NULL,
    [CONTACT_NAME]                VARCHAR (80)                                       NULL,
    [COUNTRY]                     VARCHAR (32)                                       NULL,
    [CP_PARTNER_CODE]             VARCHAR (10)                                       NULL,
    [_transaction_date]           DATETIME2 (7)                                      NULL,
    [year]                        NVARCHAR (MAX)                                     NULL,
    [month]                       NVARCHAR (MAX)                                     NULL,
    [day]                         NVARCHAR (MAX)                                     NULL,
    [_DLRawZoneTimeStamp]         DATETIME2 (7)                                      NULL,
    [_DLTrustedZoneTimeStamp]     DATETIME2 (7)                                      NULL,
    [_RecordStart]                DATETIME2 (7)                                      NULL,
    [_RecordEnd]                  DATETIME2 (7)                                      NULL,
    [_RecordDeleted]              INT                                                NULL,
    [_RecordCurrent]              INT                                                NULL
);






GO

