CREATE TABLE [edw].[OneEBS_EBS_0165_TILLS] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [LEGACY_TILL_CODE]        VARCHAR (3)    NULL,
    [ID]                      NUMERIC (10)   NULL,
    [PC_NAME]                 VARCHAR (80)   NULL,
    [PC_DESCRIPTION]          VARCHAR (255)  NULL,
    [EFTPOS_TERMINAL_ID]      VARCHAR (16)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [TILL_CODE]               VARCHAR (10)   NULL,
    [ORGANISATION_CODE]       VARCHAR (30)   NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

