CREATE TABLE [edw].[OneEBS_EBS_0165_FEE_CATEGORIES] (
    [AUTOPROGRESS_ONLY_IF_ZERO_FEES] VARCHAR (1)                                       NULL,
    [FEE_CATEGORY_CODE]              VARCHAR (10)                                      NULL,
    [LONG_DESCRIPTION]               VARCHAR (40)                                      NULL,
    [TRANSACTION_TYPE]               VARCHAR (1)                                       NULL,
    [PRIORITY]                       NUMERIC (5)                                       NULL,
    [ACCOUNT_CODE]                   VARCHAR (40) MASKED WITH (FUNCTION = 'default()') NULL,
    [GL_COMPONENT_1]                 VARCHAR (30)                                      NULL,
    [GL_COMPONENT_2]                 VARCHAR (30)                                      NULL,
    [GL_COMPONENT_3]                 VARCHAR (30)                                      NULL,
    [GL_COMPONENT_4]                 VARCHAR (30)                                      NULL,
    [TAX_CODE]                       VARCHAR (2)                                       NULL,
    [ALLOW_REFUND]                   VARCHAR (1)                                       NULL,
    [CHARGE_ONCE]                    VARCHAR (40)                                      NULL,
    [ROLE_DEFS_ID]                   NUMERIC (10)                                      NULL,
    [IS_ENFORCEABLE_DEBT]            VARCHAR (1)                                       NULL,
    [IS_ACTIVE]                      VARCHAR (1)                                       NULL,
    [IS_ELIGIBLE_FOR_INSTALMENTS]    VARCHAR (1)                                       NULL,
    [CREATED_BY]                     VARCHAR (30)                                      NULL,
    [CREATED_DATE]                   DATETIME2 (7)                                              NULL,
    [UPDATED_BY]                     VARCHAR (30)                                      NULL,
    [UPDATED_DATE]                   DATETIME2 (7)                                              NULL,
    [IS_GIFT]                        VARCHAR (1)                                       NULL,
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)                                      NULL,
    [_transaction_date]              DATETIME2 (7)                                          NULL,
    [year]                           NVARCHAR (MAX)                                    NULL,
    [month]                          NVARCHAR (MAX)                                    NULL,
    [day]                            NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)                                     NULL,
    [_RecordStart]                   DATETIME2 (7)                                     NULL,
    [_RecordEnd]                     DATETIME2 (7)                                     NULL,
    [_RecordDeleted]                 INT                                               NULL,
    [_RecordCurrent]                 INT                                               NULL
);

