CREATE TABLE [edw].[OneEBS_EBS_0165_UIO_INSTALMENT_PLANS] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [ID]                      NUMERIC (10)   NULL,
    [UIO_ID]                  NUMERIC (10)   NULL,
    [START_DATE]              DATETIME2 (7)           NULL,
    [END_DATE]                DATETIME2 (7)           NULL,
    [DESCRIPTION]             VARCHAR (13)   NULL,
    [INTERVAL]                VARCHAR (30)   NULL,
    [NUMBER_OF_SLOTS]         NUMERIC (3)    NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

