CREATE TABLE [edw].[OneEBS_EBS_0165_PEOPLE] (
    [STAFF_USER_4]                   VARCHAR (240)                                      NULL,
    [STAFF_USER_5]                   VARCHAR (240)                                      NULL,
    [STAFF_USER_6]                   VARCHAR (240)                                      NULL,
    [STUDENT_STAFF_TUTOR]            NUMERIC (10)                                       NULL,
    [TERTIARY_PERSON_CODE]           VARCHAR (15)                                       NULL,
    [TITLE]                          VARCHAR (8)                                        NULL,
    [TREFNO]                         VARCHAR (9)                                        NULL,
    [UCAS_RECORD]                    VARCHAR (1)                                        NULL,
    [UCAS_RD_NUMBER]                 NUMERIC (4)                                        NULL,
    [UCAS_NUMBER]                    VARCHAR (9)                                        NULL,
    [ULI]                            VARCHAR (13)                                       NULL,
    [UNIQUE_LEARN_NO]                NUMERIC (10)                                       NULL,
    [UNSPEC_CANDIDATE_NO]            VARCHAR (30)                                       NULL,
    [UK_RESIDENT]                    VARCHAR (1)                                        NULL,
    [UPN]                            VARCHAR (13)                                       NULL,
    [UNCONFIRMED]                    VARCHAR (1)                                        NULL,
    [USE_EMAIL]                      VARCHAR (1)                                        NULL,
    [USE_LL]                         VARCHAR (1)                                        NULL,
    [USE_SMS]                        VARCHAR (1)                                        NULL,
    [YEAR_LEFT]                      NUMERIC (4)                                        NULL,
    [CAFID]                          NUMERIC (10)                                       NULL,
    [FES_NOK_CONT_REL]               VARCHAR (30)                                       NULL,
    [STUDENT_VISA]                   VARCHAR (1)                                        NULL,
    [DISC_LEARN_SUP_TYPE1]           VARCHAR (2)                                        NULL,
    [DISC_LEARN_SUP_TYPE2]           VARCHAR (2)                                        NULL,
    [DISC_LEARN_SUP_TYPE3]           VARCHAR (2)                                        NULL,
    [DISC_LEARN_SUP_TYPE4]           VARCHAR (2)                                        NULL,
    [ELIGENHANC_1]                   VARCHAR (2)                                        NULL,
    [ELIGENHANC_2]                   VARCHAR (2)                                        NULL,
    [LOCAL_MONITOR_1]                VARCHAR (12)                                       NULL,
    [LOCAL_MONITOR_2]                VARCHAR (12)                                       NULL,
    [NES_LSC_NO]                     VARCHAR (5)                                        NULL,
    [HEALTHTD]                       VARCHAR (1)                                        NULL,
    [LONE_PAR]                       VARCHAR (1)                                        NULL,
    [WELSHUND]                       VARCHAR (1)                                        NULL,
    [WELSHRWR]                       VARCHAR (1)                                        NULL,
    [MIGRANTW]                       VARCHAR (1)                                        NULL,
    [HOURS_WK]                       NUMERIC (3)                                        NULL,
    [EMPLSIZE]                       VARCHAR (1)                                        NULL,
    [DISADV_UPLIFT]                  VARCHAR (2)                                        NULL,
    [DISABILITY_2]                   VARCHAR (2)                                        NULL,
    [LRS_ABILITY_TO_SHARE]           VARCHAR (1)                                        NULL,
    [LRS_VERIFICATION_TYPE]          VARCHAR (3)                                        NULL,
    [LRS_OTHER_VERIFICATION_DESC]    VARCHAR (240)                                      NULL,
    [ULN_RECEIVED]                   DATETIME2 (7)                                               NULL,
    [PLACE_OF_BIRTH]                 VARCHAR (35)                                       NULL,
    [LRS_UPDATED_DATE]               DATETIME2 (7)                                               NULL,
    [EXC_DELETE_FILE]                VARCHAR (1)                                        NULL,
    [ILA_REF_NO]                     VARCHAR (11)                                       NULL,
    [LRS_VALIDATION_ERRORS]          NUMERIC (10)                                       NULL,
    [LRS_ADDRESS_CODE]               NUMERIC (10)                                       NULL,
    [FIRST_TERTIARY_YEAR]            NUMERIC (4)                                        NULL,
    [DIS_ACCESSED]                   VARCHAR (1)                                        NULL,
    [LAST_SCHOOL_YEAR]               NUMERIC (4)                                        NULL,
    [FINISH_THIS_YEAR]               VARCHAR (1)                                        NULL,
    [IRD_NO]                         NUMERIC (9)                                        NULL,
    [MAX_EXEMPT_FEE]                 NUMERIC (5)                                        NULL,
    [NZ_ETHNICITY_1]                 VARCHAR (10) MASKED WITH (FUNCTION = 'default()')  NULL,
    [NZ_ETHNICITY_2]                 VARCHAR (10) MASKED WITH (FUNCTION = 'default()')  NULL,
    [NZ_ETHNICITY_3]                 VARCHAR (10) MASKED WITH (FUNCTION = 'default()')  NULL,
    [EXTERNAL_ID]                    VARCHAR (10)                                       NULL,
    [STUDYLINK_IDENTIFIER]           NUMERIC (9)                                        NULL,
    [PREVIOUS_FORENAME]              VARCHAR (240)                                      NULL,
    [RESIDENTIAL_STATUS]             VARCHAR (10)                                       NULL,
    [VERIFICATION_NAME_DOB]          VARCHAR (10)                                       NULL,
    [VERIFICATION_RESIDENTIAL]       VARCHAR (10)                                       NULL,
    [VERIFICATION_ALT_NAME_DOB]      VARCHAR (10)                                       NULL,
    [PREFERRED_NAME_FORMAT]          VARCHAR (20)                                       NULL,
    [NZ_FUNDING]                     VARCHAR (5)                                        NULL,
    [DATE_OF_DEATH]                  DATETIME2 (7)                                               NULL,
    [FEES_PAID]                      VARCHAR (1)                                        NULL,
    [ULN_STATUS]                     VARCHAR (1)                                        NULL,
    [LEARNER_UPDATE_REQUIRED]        VARCHAR (1)                                        NULL,
    [IWI_1]                          VARCHAR (4)                                        NULL,
    [IWI_2]                          VARCHAR (4)                                        NULL,
    [IWI_3]                          VARCHAR (4)                                        NULL,
    [PASSPORT_NO]                    VARCHAR (20) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PASSPORT_EXPIRY_DATE]           DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')          NULL,
    [PASSPORT_ISSUE_COUNTRY]         VARCHAR (10) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PERSONAL_EMAIL]                 VARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [CONTACT_METHODS]                NUMERIC (4)                                        NULL,
    [BAD_DEBT]                       VARCHAR (40)                                       NULL,
    [VALIDATION_LEVEL]               VARCHAR (40)                                       NULL,
    [FES_USER_31]                    VARCHAR (240)                                      NULL,
    [FES_USER_32]                    VARCHAR (240)                                      NULL,
    [FES_USER_33]                    VARCHAR (240)                                      NULL,
    [FES_USER_34]                    VARCHAR (240)                                      NULL,
    [FES_USER_35]                    VARCHAR (240)                                      NULL,
    [FES_USER_36]                    VARCHAR (240)                                      NULL,
    [FES_USER_37]                    VARCHAR (240)                                      NULL,
    [FES_USER_38]                    VARCHAR (240)                                      NULL,
    [FES_USER_39]                    VARCHAR (240)                                      NULL,
    [FES_USER_40]                    VARCHAR (240)                                      NULL,
    [FES_USER_41]                    VARCHAR (240)                                      NULL,
    [FES_USER_42]                    VARCHAR (240)                                      NULL,
    [FES_USER_43]                    VARCHAR (240)                                      NULL,
    [FES_USER_44]                    VARCHAR (240)                                      NULL,
    [FES_USER_45]                    VARCHAR (240)                                      NULL,
    [FES_USER_46]                    VARCHAR (240)                                      NULL,
    [FES_USER_47]                    VARCHAR (240)                                      NULL,
    [FES_USER_48]                    VARCHAR (240)                                      NULL,
    [FES_USER_49]                    VARCHAR (240)                                      NULL,
    [FES_USER_50]                    VARCHAR (240)                                      NULL,
    [CAN_ENROL]                      VARCHAR (1)                                        NULL,
    [DISC_LEARN_SUP_TYPE5]           VARCHAR (2)                                        NULL,
    [RESIDENCY_GRANTED_DATE]         DATETIME2 (7)                                               NULL,
    [LEARN_DIFF_ASSMT]               VARCHAR (1)                                        NULL,
    [DISABLED_ALLOWANCE]             VARCHAR (1)                                        NULL,
    [TRAINEE_CODE]                   VARCHAR (10)                                       NULL,
    [CONCESSION_CODE]                VARCHAR (5)                                        NULL,
    [CONCESSION_CODE_EXPIRY]         DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')          NULL,
    [FEE_EXEMPTION]                  VARCHAR (1)                                        NULL,
    [PRIOR_EDUCATION_ACHIEVEMENT]    VARCHAR (3)                                        NULL,
    [HAS_PRIOR_ACHIEVEMENT]          VARCHAR (1)                                        NULL,
    [PRIOR_EDUCATION_LOCATION]       VARCHAR (3)                                        NULL,
    [HOME_LANGUAGE]                  VARCHAR (10)                                       NULL,
    [INDIGENOUS_STATUS]              VARCHAR (2)                                        NULL,
    [CURRENT_SCHOOL_LEVEL]           VARCHAR (2)                                        NULL,
    [IS_AT_SCHOOL]                   VARCHAR (1)                                        NULL,
    [EXPORT_ACCEPTANCE_DATE]         DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')          NULL,
    [REGISTRATION_NO]                VARCHAR (20)                                       NULL,
    [INTERNATIONAL_NO]               VARCHAR (20)                                       NULL,
    [PHOTO_PERMISSION]               VARCHAR (10)                                       NULL,
    [TYPE_OF_INTERNET_ACCESS]        VARCHAR (10)                                       NULL,
    [TYPE_OF_CARE]                   VARCHAR (10)                                       NULL,
    [CARE_PER_WEEK]                  VARCHAR (10)                                       NULL,
    [MEDICAL_NO]                     VARCHAR (20) MASKED WITH (FUNCTION = 'default()')  NULL,
    [IMMUNISATION_EVIDENCE_TYPE]     VARCHAR (10)                                       NULL,
    [IMMUNISATION_VERIFICATION_TYPE] VARCHAR (10)                                       NULL,
    [IMMUNISATION_VERIFY_DATE]       DATETIME2 (7)                                               NULL,
    [OTHER_SCHOOLS_ATTENDED]         VARCHAR (2000)                                     NULL,
    [ROLL_CLASS]                     VARCHAR (20)                                       NULL,
    [RELIGIOUS_INSTRUCTION_GROUP]    VARCHAR (20)                                       NULL,
    [SCHOLASTIC_YEAR]                VARCHAR (20)                                       NULL,
    [HOUSE]                          VARCHAR (20)                                       NULL,
    [IS_EXCHANGE_STUDENT]            VARCHAR (1)                                        NULL,
    [IS_BOARDER]                     VARCHAR (1)                                        NULL,
    [SECOND_LANG_SUPPORT_REQUIRED]   VARCHAR (1)                                        NULL,
    [SECOND_LANG_PHASE]              VARCHAR (10)                                       NULL,
    [SECOND_LANG_ASSESSMENT_DATE]    DATETIME2 (7)                                               NULL,
    [TAX_FILE_NO]                    VARCHAR (20) MASKED WITH (FUNCTION = 'default()')  NULL,
    [MODE_OF_ENTRY]                  VARCHAR (10)                                       NULL,
    [MODE_OF_ATTENDANCE]             VARCHAR (10)                                       NULL,
    [ENTITLEMENT_LIMIT]              NUMERIC (9, 2)                                     NULL,
    [ENTITLEMENT_USED]               NUMERIC (9, 2)                                     NULL,
    [ENTITLEMENT_BALANCE]            NUMERIC (9, 2)                                     NULL,
    [ENTITLEMENT_AS_AT_DATE]         DATETIME2 (7)                                               NULL,
    [ENTITLEMENT_VERIFIED_DATE]      DATETIME2 (7)                                               NULL,
    [BOARD_OF_STUDIES_NO]            VARCHAR (20)                                       NULL,
    [IS_HOME_LANG_NOT_ENGLISH]       VARCHAR (1)                                        NULL,
    [IS_ELIGIBLE_FOR_FREE_TRAVEL]    VARCHAR (1)                                        NULL,
    [DISTANCE_FROM_HOME]             NUMERIC (5, 2)                                     NULL,
    [AUTHORITY_TO_ENROL_NO]          VARCHAR (20)                                       NULL,
    [AUTHORITY_TO_ENROL_EXPIRY_DATE] DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')          NULL,
    [ASSES_FORM_NO]                  VARCHAR (20)                                       NULL,
    [ASSES_FORM_EXPIRY_DATE]         DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')          NULL,
    [DATE_FIRST_ENROLLED]            DATETIME2 (7)                                               NULL,
    [PREFERRED_FIRST_NAME]           VARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [PREFERRED_FAMILY_NAME]          VARCHAR (100)                                      NULL,
    [POSITION]                       VARCHAR (10)                                       NULL,
    [REFERABLE]                      VARCHAR (1)                                        NULL,
    [ENTITLEMENT_ID]                 VARCHAR (10)                                       NULL,
    [HIGHER_EDUCATION_SUPPORT_NO]    VARCHAR (10)                                       NULL,
    [HAS_AUTHORITY_TO_PUBLISH]       VARCHAR (1)                                        NULL,
    [RELIGION]                       VARCHAR (40)                                       NULL,
    [PREVIOUS_SCHOOL_ATTEND_DATES]   VARCHAR (40)                                       NULL,
    [HOME_LANGUAGE_OTHER]            VARCHAR (40)                                       NULL,
    [PREVIOUS_SCHOOL_TYPE]           VARCHAR (40)                                       NULL,
    [IS_RETURNING_FROM_OVERSEAS]     VARCHAR (1)                                        NULL,
    [RETURNED_FROM_OVERSEAS_DATE]    DATETIME2 (7)                                               NULL,
    [IS_ACCELERATED_STUDENT]         VARCHAR (1)                                        NULL,
    [IS_STUDENT_ON_LEARNING_PATH]    VARCHAR (1)                                        NULL,
    [IS_CENSUS_SCHOOL]               VARCHAR (1)                                        NULL,
    [IS_INTENSIVE_ENGLISH_CENTRE]    VARCHAR (1)                                        NULL,
    [HAS_HEALTH_CARE_CARD]           VARCHAR (1)                                        NULL,
    [ELECTRONIC_PAYMENT_REF_NO]      VARCHAR (30) MASKED WITH (FUNCTION = 'default()')  NULL,
    [OCCUPATION]                     VARCHAR (132)                                      NULL,
    [OCCUPATION_GROUP]               VARCHAR (40)                                       NULL,
    [LEVEL_OF_EDUCATION]             VARCHAR (40)                                       NULL,
    [LEVEL_OF_QUALIFICATION]         VARCHAR (40)                                       NULL,
    [PREV_UKPRN]                     NUMERIC (8)                                        NULL,
    [PREV_LEARNER_REF]               VARCHAR (12)                                       NULL,
    [HAS_HEALTHCARE_PLAN]            VARCHAR (1)                                        NULL,
    [PRIOR_ED_LEVEL]                 VARCHAR (2)                                        NULL,
    [PRIOR_ATTAIN_YEAR]              VARCHAR (4)                                        NULL,
    [PARENT_EDUCATION_1]             VARCHAR (2)                                        NULL,
    [PARENT_EDUCATION_2]             VARCHAR (2)                                        NULL,
    [IS_RETURNING_STUDENT]           VARCHAR (1)                                        NULL,
    [IS_ENTITLEMENT_REQUESTED]       VARCHAR (1)                                        NULL,
    [POST_SCHOOL_QUALS]              VARCHAR (1)                                        NULL,
    [HIGHEST_POST_SCHOOL_QUAL]       VARCHAR (1)                                        NULL,
    [DISABILITY_ASSESSMENT_TYPE]     VARCHAR (1)                                        NULL,
    [RESIDENTIAL_STATUS_2]           VARCHAR (1)                                        NULL,
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)                                       NULL,
    [PREDICTED_SCORE]                NUMERIC (12, 2)                                    NULL,
    [SECONDARY_QUALIFICATION]        VARCHAR (2)                                        NULL,
    [IS_ACTIVE]                      VARCHAR (1)                                        NULL,
    [RESIDENTIAL_STATUS_UPDATED]     DATETIME2 (7)                                               NULL,
    [PERSON_CODE]                    NUMERIC (10)                                       NULL,
    [FORENAME]                       VARCHAR (50)                                       NULL,
    [MIDDLE_NAMES]                   VARCHAR (240)                                      NULL,
    [SURNAME]                        VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [CREATED_BY]                     VARCHAR (30)                                       NULL,
    [CREATED_DATE]                   DATETIME2 (7)                                               NULL,
    [UPDATED_BY]                     VARCHAR (30)                                       NULL,
    [UPDATED_DATE]                   DATETIME2 (7)                                               NULL,
    [AGE_RANGE]                      VARCHAR (40)                                       NULL,
    [ALS_COST_CEILING]               NUMERIC (9, 2)                                     NULL,
    [AVAILABILITY_CODE]              VARCHAR (10)                                       NULL,
    [AVATAR_IMAGE_LOCATION]          VARCHAR (500)                                      NULL,
    [CAN_ACCESS_NETWORK]             VARCHAR (1)                                        NULL,
    [CFACS_NAME_CODE]                VARCHAR (8)                                        NULL,
    [CG_CANDIDATE_NAME]              VARCHAR (30)                                       NULL,
    [CG_ENROL_NO]                    VARCHAR (7)                                        NULL,
    [CG_PREV_ENROL]                  VARCHAR (7)                                        NULL,
    [CNX_CARDHOLDER_ID]              NUMERIC (12) MASKED WITH (FUNCTION = 'default()')  NULL,
    [COLLEGE_EMAIL]                  VARCHAR (128) MASKED WITH (FUNCTION = 'default()') NULL,
    [COLLEGE_LOGIN]                  VARCHAR (30)                                       NULL,
    [COLLEGE_START_DATE]             DATETIME2 (7)                                               NULL,
    [COMMENTS]                       VARCHAR (2000)                                     NULL,
    [CONTRACT_HOURS]                 NUMERIC (6, 2)                                     NULL,
    [CONTACT_HOURS]                  NUMERIC (6, 2)                                     NULL,
    [COUNTRY_OF_DOMICILE]            VARCHAR (10)                                       NULL,
    [CREATE_BORROWER]                VARCHAR (1)                                        NULL,
    [CURRENT_APP_DESC]               VARCHAR (240)                                      NULL,
    [CURREMPSTATUS]                  VARCHAR (2)                                        NULL,
    [DATECURREMPCHG]                 DATETIME2 (7)                                               NULL,
    [DATE_OF_BIRTH]                  DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')          NULL,
    [DATE_UK_ENTRY]                  DATETIME2 (7)                                               NULL,
    [DISABILITY]                     VARCHAR (2)                                        NULL,
    [EMA_ID]                         VARCHAR (12)                                       NULL,
    [EMA_COURSE_TYPE]                VARCHAR (40)                                       NULL,
    [EMPLOY_STATUS_BEGIN]            VARCHAR (2)                                        NULL,
    [ETHNICITY]                      VARCHAR (10) MASKED WITH (FUNCTION = 'default()')  NULL,
    [EX_MAILSHOT]                    VARCHAR (1)                                        NULL,
    [FES_COUNTRY_OF_BIRTH]           VARCHAR (10)                                       NULL,
    [FES_NEXT_OF_KIN]                VARCHAR (30)                                       NULL,
    [FES_NOK_CONTACT_NO]             VARCHAR (22)                                       NULL,
    [FES_SEC_PERSON_CODE]            VARCHAR (20)                                       NULL,
    [FES_STAFF_CODE]                 VARCHAR (15)                                       NULL,
    [FES_USER_1]                     VARCHAR (240)                                      NULL,
    [FES_USER_2]                     VARCHAR (240)                                      NULL,
    [FES_USER_3]                     VARCHAR (240)                                      NULL,
    [FES_USER_4]                     VARCHAR (240)                                      NULL,
    [FES_USER_5]                     VARCHAR (240)                                      NULL,
    [FES_USER_6]                     VARCHAR (240)                                      NULL,
    [FES_USER_7]                     VARCHAR (240)                                      NULL,
    [FES_USER_8]                     VARCHAR (240)                                      NULL,
    [FES_USER_9]                     VARCHAR (240)                                      NULL,
    [FES_USER_10]                    VARCHAR (240)                                      NULL,
    [FES_USER_11]                    VARCHAR (240)                                      NULL,
    [FES_USER_12]                    VARCHAR (240)                                      NULL,
    [FES_USER_13]                    VARCHAR (240)                                      NULL,
    [FES_USER_14]                    VARCHAR (240)                                      NULL,
    [FES_USER_15]                    VARCHAR (240)                                      NULL,
    [FES_USER_16]                    VARCHAR (240)                                      NULL,
    [FES_USER_17]                    VARCHAR (240)                                      NULL,
    [FES_USER_18]                    VARCHAR (240)                                      NULL,
    [FES_USER_19]                    VARCHAR (240)                                      NULL,
    [FES_USER_20]                    VARCHAR (240)                                      NULL,
    [FES_USER_21]                    VARCHAR (240)                                      NULL,
    [FES_USER_22]                    VARCHAR (240)                                      NULL,
    [FES_USER_23]                    VARCHAR (240)                                      NULL,
    [FES_USER_24]                    VARCHAR (240)                                      NULL,
    [FES_USER_25]                    VARCHAR (240)                                      NULL,
    [FES_USER_26]                    VARCHAR (240)                                      NULL,
    [FES_USER_27]                    VARCHAR (240)                                      NULL,
    [FES_USER_28]                    VARCHAR (240)                                      NULL,
    [FES_USER_29]                    VARCHAR (240)                                      NULL,
    [FES_USER_30]                    VARCHAR (240)                                      NULL,
    [F_LANG]                         VARCHAR (1)                                        NULL,
    [GC_CANDIDATE_NO]                NUMERIC (4)                                        NULL,
    [GC_UCI]                         VARCHAR (13)                                       NULL,
    [GC_ALT_CAND_NO]                 NUMERIC (4)                                        NULL,
    [GC_QUALIFIER]                   VARCHAR (1)                                        NULL,
    [GC_ALT_CENTRE_NO]               VARCHAR (5)                                        NULL,
    [HUSID]                          VARCHAR (13)                                       NULL,
    [INITIALS]                       VARCHAR (10)                                       NULL,
    [INTERNAL_CAND]                  VARCHAR (1)                                        NULL,
    [INTERNAL_TEL_EXT]               VARCHAR (20)                                       NULL,
    [IS_PHOTO_SHAREABLE]             VARCHAR (1)                                        NULL,
    [IS_PROFILE_SHAREABLE]           VARCHAR (1)                                        NULL,
    [KNOWN_AS]                       VARCHAR (30)                                       NULL,
    [LEARNING_DIFFICULTY]            VARCHAR (2)                                        NULL,
    [LEARN_DIFF]                     VARCHAR (10)                                       NULL,
    [MARITAL_STATUS]                 VARCHAR (40)                                       NULL,
    [MOBILE_PHONE_NUMBER]            VARCHAR (22) MASKED WITH (FUNCTION = 'default()')  NULL,
    [MULTIPLE_CONTRACT_NUMBER]       NUMERIC (1)                                        NULL,
    [NATIONALITY]                    VARCHAR (10)                                       NULL,
    [NAT_IDEN]                       VARCHAR (3)                                        NULL,
    [NCFE_CANDIDATE_NO]              NUMERIC (15)                                       NULL,
    [NCFE_PREV_NO]                   NUMERIC (15)                                       NULL,
    [NETWORK_USERID]                 VARCHAR (30)                                       NULL,
    [NI_NUMBER]                      VARCHAR (10)                                       NULL,
    [NOTES]                          NUMERIC (10)                                       NULL,
    [ON_PAYROLL]                     VARCHAR (1)                                        NULL,
    [ORGANISATION_CODE_1]            VARCHAR (30)                                       NULL,
    [ORGANISATION_CODE_2]            VARCHAR (30)                                       NULL,
    [OVERSEAS]                       VARCHAR (1)                                        NULL,
    [PREVIOUS_SURNAME]               VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [PRIMARY_DISABILITY]             VARCHAR (10)                                       NULL,
    [PRIOR_ATTAIN_LEVEL]             VARCHAR (2)                                        NULL,
    [PRIOR_LEARNER_STATUS]           VARCHAR (2)                                        NULL,
    [RSA_NUMBER]                     VARCHAR (8)                                        NULL,
    [SCHOOL]                         VARCHAR (10)                                       NULL,
    [SCOTVEC]                        VARCHAR (9)                                        NULL,
    [SEX]                            VARCHAR (1)                                        NULL,
    [SIR_ENROL_HIGH_TEACH_QUAL]      VARCHAR (2)                                        NULL,
    [SIR_HIGHEST_QUAL]               VARCHAR (1)                                        NULL,
    [SIR_HIGHEST_QUAL_PA]            VARCHAR (2)                                        NULL,
    [SIR_QTEACH_STATUS]              VARCHAR (1)                                        NULL,
    [SIR_STAFF_CODE]                 VARCHAR (12)                                       NULL,
    [SIR_TEACH_QUAL_1]               VARCHAR (2)                                        NULL,
    [SIR_TEACH_QUAL_2]               VARCHAR (2)                                        NULL,
    [SIR_TEACH_QUAL_3]               VARCHAR (2)                                        NULL,
    [SIR_TEACH_QUAL_4]               VARCHAR (2)                                        NULL,
    [SIR_TEACH_TRNG_1]               VARCHAR (2)                                        NULL,
    [SIR_TEACH_TRNG_2]               VARCHAR (2)                                        NULL,
    [SIR_TEACH_TRNG_3]               VARCHAR (2)                                        NULL,
    [SIR_TRAIN_SLDD]                 VARCHAR (1)                                        NULL,
    [SNAME16]                        VARCHAR (50)                                       NULL,
    [STAFF_USER_1]                   VARCHAR (240)                                      NULL,
    [STAFF_USER_2]                   VARCHAR (240)                                      NULL,
    [STAFF_USER_3]                   VARCHAR (240)                                      NULL,
    [_transaction_date]              DATETIME2 (7)                                           NULL,
    [year]                           NVARCHAR (MAX)                                     NULL,
    [month]                          NVARCHAR (MAX)                                     NULL,
    [day]                            NVARCHAR (MAX)                                     NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)                                      NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)                                      NULL,
    [_RecordStart]                   DATETIME2 (7)                                      NULL,
    [_RecordEnd]                     DATETIME2 (7)                                      NULL,
    [_RecordDeleted]                 INT                                                NULL,
    [_RecordCurrent]                 INT                                                NULL
);

