CREATE TABLE [edw].[OneEBS_EBS_0165_PEOPLE_CENTRELINK] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [FES_USER_1]              VARCHAR (240)  NULL,
    [FES_USER_2]              VARCHAR (240)  NULL,
    [FES_USER_3]              VARCHAR (240)  NULL,
    [FES_USER_4]              VARCHAR (240)  NULL,
    [FES_USER_5]              VARCHAR (240)  NULL,
    [FES_USER_6]              VARCHAR (240)  NULL,
    [FES_USER_7]              VARCHAR (240)  NULL,
    [FES_USER_8]              VARCHAR (240)  NULL,
    [FES_USER_9]              VARCHAR (240)  NULL,
    [FES_USER_10]             VARCHAR (240)  NULL,
    [FES_USER_11]             VARCHAR (240)  NULL,
    [FES_USER_12]             VARCHAR (240)  NULL,
    [ID]                      NUMERIC (10)   NULL,
    [PERSON_CODE]             NUMERIC (10)   NULL,
    [CRN]                     VARCHAR (10)   NULL,
    [SECONDARY_CRN]           VARCHAR (10)   NULL,
    [CRN_CONFIRM_DATE]        DATETIME2 (7)           NULL,
    [DVA_NO]                  VARCHAR (23)   NULL,
    [ORG_TYPE]                VARCHAR (10)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [DVA_CONFIRM_DATE]        DATETIME2 (7)           NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

