CREATE TABLE [edw].[OneEBS_EBS_0165_SCHOOLS] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)                                       NULL,
    [SCHOOL_CODE]             VARCHAR (10)                                       NULL,
    [FULL_NAME]               VARCHAR (100) MASKED WITH (FUNCTION = 'default()') NULL,
    [SHORT_NAME]              VARCHAR (13)                                       NULL,
    [ADDRESS_LINE_1]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_2]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_3]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_4]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()')  NULL,
    [TOWN]                    VARCHAR (30)                                       NULL,
    [REGION]                  VARCHAR (32)                                       NULL,
    [COUNTRY]                 VARCHAR (40)                                       NULL,
    [UK_POST_CODE_PT1]        VARCHAR (4)                                        NULL,
    [UK_POST_CODE_PT2]        VARCHAR (4)                                        NULL,
    [TELEPHONE]               VARCHAR (22) MASKED WITH (FUNCTION = 'default()')  NULL,
    [FAX]                     VARCHAR (22)                                       NULL,
    [EMAIL_ADDRESS]           VARCHAR (128) MASKED WITH (FUNCTION = 'default()') NULL,
    [HEAD_TITLE]              VARCHAR (8)                                        NULL,
    [HEAD_INITIALS]           VARCHAR (10)                                       NULL,
    [HEAD_SURNAME]            VARCHAR (30) MASKED WITH (FUNCTION = 'default()')  NULL,
    [SCHOOL_TYPE]             VARCHAR (10)                                       NULL,
    [CREATED_BY]              VARCHAR (30)                                       NULL,
    [CREATED_DATE]            DATETIME2 (7)                                               NULL,
    [UPDATED_BY]              VARCHAR (30)                                       NULL,
    [UPDATED_DATE]            DATETIME2 (7)                                               NULL,
    [FES_ACTIVE]              VARCHAR (1)                                        NULL,
    [SCHOOL_TYPE_NO]          VARCHAR (2)                                        NULL,
    [START_DATE]              DATETIME2 (7)                                               NULL,
    [END_DATE]                DATETIME2 (7)                                               NULL,
    [REPORTS_TO]              VARCHAR (10)                                       NULL,
    [DIOCESE]                 VARCHAR (5)                                        NULL,
    [CATEGORY]                VARCHAR (15)                                       NULL,
    [_transaction_date]       DATETIME2 (7)                                           NULL,
    [year]                    NVARCHAR (MAX)                                     NULL,
    [month]                   NVARCHAR (MAX)                                     NULL,
    [day]                     NVARCHAR (MAX)                                     NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)                                      NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)                                      NULL,
    [_RecordStart]            DATETIME2 (7)                                      NULL,
    [_RecordEnd]              DATETIME2 (7)                                      NULL,
    [_RecordDeleted]          INT                                                NULL,
    [_RecordCurrent]          INT                                                NULL
);

