CREATE TABLE [edw].[OneEBS_EBS_0165_PEOPLE_UNITS_SPECIAL] (
    [ID]                             NUMERIC (10)                                     NULL,
    [PEOPLE_UNITS_ID]                NUMERIC (10)                                     NULL,
    [START_DATE]                     DATETIME2 (7)                                             NULL,
    [END_DATE]                       DATETIME2 (7)                                             NULL,
    [MOA_CODE]                       VARCHAR (10)                                     NULL,
    [NO_OF_HOURS]                    NUMERIC (7, 2)                                   NULL,
    [NO_OF_WEEKS]                    NUMERIC (3)                                      NULL,
    [POSSIBLE_HOURS]                 NUMERIC (7, 2)                                   NULL,
    [AIM_START]                      DATETIME2 (7)                                             NULL,
    [AIM_END]                        DATETIME2 (7)                                             NULL,
    [STUDENT_TYPE]                   VARCHAR (10)                                     NULL,
    [FUNDING_YEAR]                   VARCHAR (10)                                     NULL,
    [FUNDING_STREAM]                 VARCHAR (2)                                      NULL,
    [FUND_SOURCE_1]                  VARCHAR (10)                                     NULL,
    [FUND_SOURCE_2]                  VARCHAR (10)                                     NULL,
    [DELIVERY_MODE]                  VARCHAR (10)                                     NULL,
    [MAIN_DEL_METHOD]                VARCHAR (10)                                     NULL,
    [EMPLOYER_ROLE]                  VARCHAR (10)                                     NULL,
    [RESIT]                          VARCHAR (10)                                     NULL,
    [RELATED_OCCUPATION]             VARCHAR (4)                                      NULL,
    [SECTOR_FRAMEWORK]               VARCHAR (3)                                      NULL,
    [EXP_GUIDED_HRS]                 NUMERIC (8, 2)                                   NULL,
    [ACT_GUIDED_HRS]                 NUMERIC (8, 2)                                   NULL,
    [FUNDING_MOA]                    VARCHAR (10)                                     NULL,
    [TAUGHT_HRS]                     NUMERIC (5)                                      NULL,
    [STUDY_HRS]                      NUMERIC (5)                                      NULL,
    [DISTANCE_GLH]                   NUMERIC (5)                                      NULL,
    [ENHANCED_GLH]                   NUMERIC (5)                                      NULL,
    [APL_HRS]                        NUMERIC (5)                                      NULL,
    [FUNDING_EXPIRY_DATE]            DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')        NULL,
    [UNITS_FOR_FULL_QUAL]            NUMERIC (2)                                      NULL,
    [AWARD_FLAG]                     VARCHAR (1)                                      NULL,
    [ESF_START_DATE]                 DATETIME2 (7)                                             NULL,
    [PLANNED_END_DATE]               DATETIME2 (7)                                             NULL,
    [FUNDING_END_DATE]               DATETIME2 (7)                                             NULL,
    [SECTOR_SUPPORT]                 VARCHAR (2)                                      NULL,
    [PRIOR_EMPLOY_STATUS]            VARCHAR (2)                                      NULL,
    [EMPLOYMENT_STATUS]              VARCHAR (2)                                      NULL,
    [PRIOR_UNEMPLOY_LENGTH]          VARCHAR (2)                                      NULL,
    [EMPLOYER_TYPE]                  VARCHAR (2)                                      NULL,
    [GENDER_STEREOTYPE]              VARCHAR (5)                                      NULL,
    [CO_FINANCE_ACTIVITY]            VARCHAR (5)                                      NULL,
    [ESF_DELIVERY_MODE]              VARCHAR (4)                                      NULL,
    [SUPPORT_MEASURES]               VARCHAR (5)                                      NULL,
    [LEARNER_BACKGROUND]             VARCHAR (2)                                      NULL,
    [DIS_SUPPORT_MEASURES]           VARCHAR (2)                                      NULL,
    [PROJ_DOSSIER_NO]                VARCHAR (9)                                      NULL,
    [LOCAL_PROJ_NO]                  NUMERIC (3)                                      NULL,
    [LEARNER_BACKGROUND_2]           NUMERIC (2)                                      NULL,
    [LEARNER_BACKGROUND_3]           NUMERIC (2)                                      NULL,
    [NATIONALITY]                    VARCHAR (4)                                      NULL,
    [HEQUALS]                        VARCHAR (2)                                      NULL,
    [NEW_ENTRANT]                    VARCHAR (1)                                      NULL,
    [HE_PROGYEAR_TP]                 VARCHAR (1)                                      NULL,
    [HE_EARLY_MODE]                  VARCHAR (2)                                      NULL,
    [HE_LEVEL]                       VARCHAR (2)                                      NULL,
    [HE_COMPLETE_YEAR]               VARCHAR (1)                                      NULL,
    [HE_FTE]                         NUMERIC (5, 1)                                   NULL,
    [YEAR_OF_PROGRAM]                NUMERIC (2)                                      NULL,
    [FEE_BAND]                       VARCHAR (2)                                      NULL,
    [HE_SOURCE_FEES]                 VARCHAR (2)                                      NULL,
    [TERM_TIME_ACC]                  VARCHAR (1)                                      NULL,
    [OCC_CODE]                       VARCHAR (4)                                      NULL,
    [LAST_INST]                      VARCHAR (7)                                      NULL,
    [YEAR_LAST_INST]                 NUMERIC (4)                                      NULL,
    [ALEVELS]                        VARCHAR (2)                                      NULL,
    [ALEVEL_SCORE]                   NUMERIC (2)                                      NULL,
    [SCE_HIGHERS]                    VARCHAR (2)                                      NULL,
    [SCOT_HIGH_POINTS]               NUMERIC (2)                                      NULL,
    [VOC_QUALS]                      VARCHAR (2)                                      NULL,
    [LEAVE_REASON]                   VARCHAR (2)                                      NULL,
    [PROP_NOT_TAUGHT]                NUMERIC (4, 1)                                   NULL,
    [PROP_SCLASS1]                   NUMERIC (4, 1)                                   NULL,
    [PROP_SCLASS2]                   NUMERIC (4, 1)                                   NULL,
    [PROP_SCLASS3]                   NUMERIC (4, 1)                                   NULL,
    [SOCIO_ECO_IND]                  NUMERIC (1)                                      NULL,
    [CREATED_BY]                     VARCHAR (30)                                     NULL,
    [CREATED_DATE]                   DATETIME2 (7)                                             NULL,
    [UPDATED_BY]                     VARCHAR (30)                                     NULL,
    [UPDATED_DATE]                   DATETIME2 (7)                                             NULL,
    [BROK_CONT_NO]                   VARCHAR (10)                                     NULL,
    [ASL_PROVISION_TYPE]             VARCHAR (2)                                      NULL,
    [PLANNED_CREDIT]                 NUMERIC (3) MASKED WITH (FUNCTION = 'default()') NULL,
    [CREDIT_ACHIEVED]                NUMERIC (3) MASKED WITH (FUNCTION = 'default()') NULL,
    [PROG_TYPE]                      VARCHAR (2)                                      NULL,
    [PROG_ENTRY_ROUTE]               VARCHAR (2)                                      NULL,
    [FRANCHISING]                    VARCHAR (10)                                     NULL,
    [DELIVERY_PROVIDER]              VARCHAR (30)                                     NULL,
    [DELIVERY_POST_CODE_PT1]         VARCHAR (4)                                      NULL,
    [DELIVERY_POST_CODE_PT2]         VARCHAR (4)                                      NULL,
    [NVQ_ACHIEVE_DATE]               DATETIME2 (7)                                             NULL,
    [EMPLOYER_NAME]                  VARCHAR (30)                                     NULL,
    [EMPLOYER_POST_CODE_PT1]         VARCHAR (4)                                      NULL,
    [EMPLOYER_POST_CODE_PT2]         VARCHAR (4)                                      NULL,
    [NATIONAL_MONITOR_1]             VARCHAR (3)                                      NULL,
    [NATIONAL_MONITOR_2]             VARCHAR (3)                                      NULL,
    [LOCAL_MONITOR_1]                VARCHAR (12)                                     NULL,
    [LOCAL_MONITOR_2]                VARCHAR (12)                                     NULL,
    [END_REASON]                     NUMERIC (2)                                      NULL,
    [PROP_FUND_REMAINING]            NUMERIC (3)                                      NULL,
    [DISTANCE_FUNDING]               NUMERIC (5)                                      NULL,
    [ADD_LEARN_NEED]                 NUMERIC (2)                                      NULL,
    [LOCATION_CODE]                  VARCHAR (10)                                     NULL,
    [DISTANCE_LEARNING_FACTOR]       NUMERIC (4, 3)                                   NULL,
    [NATIONAL_SKILLS_ACADEMY]        VARCHAR (2)                                      NULL,
    [PLANNED_GROUP_BASED_HOURS]      NUMERIC (5)                                      NULL,
    [PLANNED_ONE_TO_ONE_CONTACT]     NUMERIC (5)                                      NULL,
    [EMPLOYMENT_OUTCOME]             NUMERIC (2)                                      NULL,
    [USER_1]                         VARCHAR (240)                                    NULL,
    [USER_2]                         VARCHAR (240)                                    NULL,
    [USER_3]                         VARCHAR (240)                                    NULL,
    [USER_4]                         VARCHAR (240)                                    NULL,
    [USER_5]                         VARCHAR (240)                                    NULL,
    [USER_6]                         VARCHAR (240)                                    NULL,
    [ER_ENHANCED_FUNDING]            VARCHAR (2)                                      NULL,
    [CONTRACTING_ORG_CODE]           VARCHAR (5)                                      NULL,
    [FUNDING_CATEGORY]               VARCHAR (1)                                      NULL,
    [COURSE_CLASSIFICATION]          VARCHAR (4)                                      NULL,
    [COURSE_EFTS_FACTOR]             NUMERIC (6, 5)                                   NULL,
    [FUNDING_STATUS]                 NUMERIC (1)                                      NULL,
    [NATIONAL_MONITOR_3]             VARCHAR (3)                                      NULL,
    [ACT_PROG_ROUTE]                 VARCHAR (2)                                      NULL,
    [APPRENTICESHIP_PATHWAY]         VARCHAR (3)                                      NULL,
    [FIRST_STEPS_INDICATOR]          VARCHAR (1)                                      NULL,
    [RESTARTED]                      VARCHAR (1)                                      NULL,
    [ADD_SOCIAL_NEED]                VARCHAR (1)                                      NULL,
    [IS_WORKPLACE_LEARNING]          VARCHAR (1)                                      NULL,
    [HAS_STUDY_LOAN]                 VARCHAR (1)                                      NULL,
    [RPL_FUND_FACTOR]                NUMERIC (2)                                      NULL,
    [OTHER_FUND_FACTOR]              NUMERIC (3)                                      NULL,
    [ORIG_LEARN_START_DATE]          DATETIME2 (7)                                             NULL,
    [NATIONAL_MONITOR_4]             VARCHAR (3)                                      NULL,
    [PLANNED_EEP_HOURS]              NUMERIC (4)                                      NULL,
    [IS_CORE_AIM]                    VARCHAR (1)                                      NULL,
    [WORK_PROGRAMME_PARTICIPATION]   VARCHAR (1)                                      NULL,
    [PERCENTAGE_ONLINE_DELIVERY]     VARCHAR (2)                                      NULL,
    [APPRENTICESHIP_TRAILBLAZER_STD] VARCHAR (5)                                      NULL,
    [ELQ]                            VARCHAR (1)                                      NULL,
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)                                     NULL,
    [ADDITIONAL_DELIVERY_HOURS]      NUMERIC (4)                                      NULL,
    [CONTRACT_REFERENCE_NUMBER]      VARCHAR (20)                                     NULL,
    [FAMILY_ENGLISH_MATHS_LANGUAGE]  VARCHAR (1)                                      NULL,
    [HE_POST_CODE1]                  VARCHAR (4)                                      NULL,
    [HE_POST_CODE2]                  VARCHAR (4)                                      NULL,
    [HE_CENTRE]                      VARCHAR (10)                                     NULL,
    [HOUSEHOLD_SITUATION_1]          VARCHAR (2)                                      NULL,
    [HOUSEHOLD_SITUATION_2]          VARCHAR (2)                                      NULL,
    [ASSESSMENT_ORGANISATION_ID]     VARCHAR (7)                                      NULL,
    [COHORT_REFERENCE_NUMBER]        VARCHAR (20)                                     NULL,
    [AIM_TYPE]                       NUMERIC (1)                                      NULL,
    [DEVOLVED_AREA_MONITORING_1]     VARCHAR (3)                                      NULL,
    [DEVOLVED_AREA_MONITORING_2]     VARCHAR (3)                                      NULL,
    [DEVOLVED_AREA_MONITORING_3]     VARCHAR (3)                                      NULL,
    [DEVOLVED_AREA_MONITORING_4]     VARCHAR (3)                                      NULL,
    [END_POINT_ASSESSMENT_DATE]      DATETIME2 (7)                                             NULL,
    [USE_EAD_TO_UPDATE_ACH_DATE]     VARCHAR (1)                                      NULL,
    [NATIONAL_MONITOR_5]             VARCHAR (3)                                      NULL,
    [NATIONAL_MONITOR_6]             VARCHAR (3)                                      NULL,
    [PLANNED_HOURS]                  NUMERIC (4)                                      NULL,
    [_transaction_date]              DATETIME2 (7)                                         NULL,
    [year]                           NVARCHAR (MAX)                                   NULL,
    [month]                          NVARCHAR (MAX)                                   NULL,
    [day]                            NVARCHAR (MAX)                                   NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)                                    NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)                                    NULL,
    [_RecordStart]                   DATETIME2 (7)                                    NULL,
    [_RecordEnd]                     DATETIME2 (7)                                    NULL,
    [_RecordDeleted]                 INT                                              NULL,
    [_RecordCurrent]                 INT                                              NULL
);

