CREATE TABLE [edw].[OneEBS_EBS_0165_UI_LINKS] (
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)   NULL,
    [ID]                             NUMERIC (10)   NULL,
    [UI_CODE_FROM]                   VARCHAR (20)   NULL,
    [UI_CODE_TO]                     VARCHAR (20)   NULL,
    [LINK_TYPE]                      VARCHAR (10)   NULL,
    [CREATED_BY]                     VARCHAR (30)   NULL,
    [CREATED_DATE]                   DATETIME2 (7)           NULL,
    [UPDATED_BY]                     VARCHAR (30)   NULL,
    [UPDATED_DATE]                   DATETIME2 (7)           NULL,
    [START_DATE]                     DATETIME2 (7)           NULL,
    [END_DATE]                       DATETIME2 (7)           NULL,
    [PROGRESS_WEIGHT]                NUMERIC (6, 2) NULL,
    [DEFAULT_PROGRESS_CODE]          VARCHAR (10)   NULL,
    [TARGET_WEIGHT]                  NUMERIC (3)    NULL,
    [IS_CORE]                        VARCHAR (1)    NULL,
    [IS_EXCLUDED_FROM_AWARD_CALC]    VARCHAR (1)    NULL,
    [IS_GRADE_AWARD_OUTCOME_CONTRIB] VARCHAR (1)    NULL,
    [SEQUENCENUMBER]                 NUMERIC (10)   NULL,
    [_transaction_date]              DATETIME2 (7)       NULL,
    [year]                           NVARCHAR (MAX) NULL,
    [month]                          NVARCHAR (MAX) NULL,
    [day]                            NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)  NULL,
    [_RecordStart]                   DATETIME2 (7)  NULL,
    [_RecordEnd]                     DATETIME2 (7)  NULL,
    [_RecordDeleted]                 INT            NULL,
    [_RecordCurrent]                 INT            NULL
);

