CREATE TABLE [edw].[OneEBS_EBS_0165_AWARDS_ORIGINAL] (
    [ID]                            NUMERIC (10)                                     NULL,
    [CODE]                          VARCHAR (20)                                     NULL,
    [TITLE]                         VARCHAR (60)                                     NULL,
    [DESCRIPTION]                   VARCHAR (240)                                    NULL,
    [SDR_QUALIFICATION_CODE]        VARCHAR (6)                                      NULL,
    [USER_1]                        VARCHAR (240)                                    NULL,
    [USER_2]                        VARCHAR (240)                                    NULL,
    [USER_3]                        VARCHAR (240)                                    NULL,
    [USER_4]                        VARCHAR (240)                                    NULL,
    [USER_5]                        VARCHAR (240)                                    NULL,
    [USER_6]                        VARCHAR (240)                                    NULL,
    [USER_7]                        VARCHAR (240)                                    NULL,
    [USER_8]                        VARCHAR (240)                                    NULL,
    [USER_9]                        VARCHAR (240)                                    NULL,
    [USER_10]                       VARCHAR (240)                                    NULL,
    [USER_11]                       VARCHAR (240)                                    NULL,
    [USER_12]                       VARCHAR (240)                                    NULL,
    [IS_ACTIVE]                     VARCHAR (1)                                      NULL,
    [CREATED_BY]                    VARCHAR (30)                                     NULL,
    [CREATED_DATE]                  DATETIME2 (7)                                             NULL,
    [UPDATED_BY]                    VARCHAR (30)                                     NULL,
    [UPDATED_DATE]                  DATETIME2 (7)                                             NULL,
    [COURSE_CREDITS]                NUMERIC (3) MASKED WITH (FUNCTION = 'default()') NULL,
    [SDR_REGISTER_LEVEL]            NUMERIC (10)                                     NULL,
    [TRANSCRIPT_ID]                 NUMERIC (10)                                     NULL,
    [AWARD_CATEGORY_CODE]           VARCHAR (3)                                      NULL,
    [GRADING_SCHEME_ID]             NUMERIC (10)                                     NULL,
    [NATIONAL_CODE]                 VARCHAR (20)                                     NULL,
    [SPECIALISATION]                VARCHAR (1000)                                   NULL,
    [CONFIGURABLE_STATUS_ID]        NUMERIC (10)                                     NULL,
    [PUBLISHED]                     VARCHAR (1)                                      NULL,
    [REGULATION_SCHEME_ID]          NUMERIC (10)                                     NULL,
    [INSTITUTION_CONTEXT_ID]        NUMERIC (10)                                     NULL,
    [COUNT_OUTCOMES_MULTIPLE_TIMES] VARCHAR (1)                                      NULL,
    [_transaction_date]             DATETIME2 (7)                                         NULL,
    [year]                          NVARCHAR (MAX)                                   NULL,
    [month]                         NVARCHAR (MAX)                                   NULL,
    [day]                           NVARCHAR (MAX)                                   NULL,
    [_DLRawZoneTimeStamp]           DATETIME                                         NULL,
    [_DLTrustedZoneTimeStamp]       DATETIME                                         NULL,
    [_RecordStart]                  DATETIME                                         NULL,
    [_RecordEnd]                    DATETIME                                         NULL,
    [_RecordDeleted]                INT                                              NULL,
    [_RecordCurrent]                INT                                              NULL
);

