CREATE TABLE [edw].[OneEBS_EBS_0165_UI_ACCREDITATION] (
    [ACCREDITATION_AUTHORITY]   VARCHAR (10)   NULL,
    [APPLICATION]               VARCHAR (2000) NULL,
    [ARTICULATION_ARRANGEMENT]  VARCHAR (2000) NULL,
    [ASSESSMENT_STRATEGIES]     VARCHAR (2000) NULL,
    [CONSULTATION]              VARCHAR (2000) NULL,
    [COPYRIGHT_ACKNOWLEDGEMENT] VARCHAR (2000) NULL,
    [CREATED_BY]                VARCHAR (30)   NULL,
    [CREATED_DATE]              DATETIME2 (7)  NULL,
    [DAYS_CURRENCY]             NUMERIC (4)    NULL,
    [FRANCHISING]               VARCHAR (2000) NULL,
    [ID]                        NUMERIC (10)   NULL,
    [INSTITUTION_CONTEXT_ID]    NUMERIC (10)   NULL,
    [LICENSING_INFORMATION]     VARCHAR (2000) NULL,
    [ONGOING_MONITORING]        VARCHAR (2000) NULL,
    [OUTCOMES]                  VARCHAR (2000) NULL,
    [PHYSICAL_RESOURCES]        VARCHAR (2000) NULL,
    [SUBMISSION_TYPE]           VARCHAR (10)   NULL,
    [UNIT_INSTANCE_CODE]        VARCHAR (20)   NULL,
    [UPDATED_BY]                VARCHAR (30)   NULL,
    [UPDATED_DATE]              DATETIME2 (7)  NULL,
    [_transaction_date]         DATETIME2 (7)       NULL,
    [_DLRawZoneTimeStamp]       DATETIME2 (7)  NULL,
    [year]                      NVARCHAR (MAX) NULL,
    [month]                     NVARCHAR (MAX) NULL,
    [day]                       NVARCHAR (MAX) NULL,
    [_DLTrustedZoneTimeStamp]   DATETIME2 (7)  NULL,
    [_RecordStart]              DATETIME2 (7)  NULL,
    [_RecordEnd]                DATETIME2 (7)  NULL,
    [_RecordDeleted]            INT            NULL,
    [_RecordCurrent]            INT            NULL
);

