CREATE TABLE [edw].[OneEBS_EBS_0165_INSTALMENT_PLANS] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)                                         NULL,
    [ID]                      NUMERIC (10)                                         NULL,
    [PLAN_ID]                 NUMERIC (10)                                         NULL,
    [PERSON_CODE]             NUMERIC (10)                                         NULL,
    [CREATED_BY]              VARCHAR (30)                                         NULL,
    [CREATED_DATE]            DATETIME2 (7)                                                 NULL,
    [UPDATED_BY]              VARCHAR (30)                                         NULL,
    [UPDATED_DATE]            DATETIME2 (7)                                                 NULL,
    [AMOUNT]                  NUMERIC (15, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [DUE_DATE]                DATETIME2 (7)                                                 NULL,
    [EPAYMENT_EXTERNAL_REF]   VARCHAR (50) MASKED WITH (FUNCTION = 'default()')    NULL,
    [EPAYMENT_STATUS]         VARCHAR (1)                                          NULL,
    [EPAYMENT_STATUS_CODE]    VARCHAR (10) MASKED WITH (FUNCTION = 'default()')    NULL,
    [EPAYMENT_TRANSACTION_ID] VARCHAR (20) MASKED WITH (FUNCTION = 'default()')    NULL,
    [INTERNAL_INVOICE_CODE]   VARCHAR (20) MASKED WITH (FUNCTION = 'default()')    NULL,
    [INTERNAL_INVOICE_DATE]   DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')            NULL,
    [MATCHED_FEE_RECORD_CODE] NUMERIC (10)                                         NULL,
    [PAID]                    VARCHAR (1)                                          NULL,
    [_transaction_date]       DATETIME2 (7)                                             NULL,
    [year]                    NVARCHAR (MAX)                                       NULL,
    [month]                   NVARCHAR (MAX)                                       NULL,
    [day]                     NVARCHAR (MAX)                                       NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)                                        NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)                                        NULL,
    [_RecordStart]            DATETIME2 (7)                                        NULL,
    [_RecordEnd]              DATETIME2 (7)                                        NULL,
    [_RecordDeleted]          INT                                                  NULL,
    [_RecordCurrent]          INT                                                  NULL
);

