CREATE TABLE [edw].[OneEBS_EBS_0165_ATTAINMENTS] (
    [ATTAINMENT_CODE]              NUMERIC (10)                                        NULL,
    [ATYPE_ATTAINMENT_TYPE_CODE]   VARCHAR (10)                                        NULL,
    [TOPIC_TOPIC_CODE]             VARCHAR (10)                                        NULL,
    [DESCRIPTION]                  VARCHAR (240)                                       NULL,
    [OUTCOME]                      VARCHAR (6)                                         NULL,
    [MARK]                         NUMERIC (6, 2)                                      NULL,
    [CATS_LEVEL]                   VARCHAR (1)                                         NULL,
    [DATE_CONFERRED]               DATETIME2 (7)                                                NULL,
    [DATE_AWARDED]                 DATETIME2 (7)                                                NULL,
    [GRADE]                        VARCHAR (255)                                       NULL,
    [CREATED_BY]                   VARCHAR (30)                                        NULL,
    [CREATED_DATE]                 DATETIME2 (7)                                                NULL,
    [UPDATED_BY]                   VARCHAR (30)                                        NULL,
    [UPDATED_DATE]                 DATETIME2 (7)                                                NULL,
    [PER_PERSON_CODE]              NUMERIC (10)                                        NULL,
    [CATS_CREDITS]                 NUMERIC (6, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [FES_THIS_INST]                VARCHAR (1)                                         NULL,
    [FES_QUALIFICATION_AIM]        VARCHAR (8)                                         NULL,
    [FES_YEAR_ACHIEVED]            NUMERIC (4)                                         NULL,
    [FES_EXAM_BOARD]               VARCHAR (10)                                        NULL,
    [FES_EXAM_TYPE]                VARCHAR (10)                                        NULL,
    [FES_PREDICTED_GRADE]          VARCHAR (30)                                        NULL,
    [FES_GRADE_ISR]                VARCHAR (3)                                         NULL,
    [FES_ISR]                      VARCHAR (1)                                         NULL,
    [FES_NCVQ_REF]                 VARCHAR (20)                                        NULL,
    [FES_NCVQ_LEVEL]               NUMERIC (1)                                         NULL,
    [FES_FUNDING_YEAR]             VARCHAR (10)                                        NULL,
    [LOCAL_QOE]                    VARCHAR (10)                                        NULL,
    [USER_1]                       VARCHAR (240)                                       NULL,
    [USER_2]                       VARCHAR (240)                                       NULL,
    [USER_3]                       VARCHAR (240)                                       NULL,
    [USER_4]                       VARCHAR (240)                                       NULL,
    [USER_5]                       VARCHAR (240)                                       NULL,
    [USER_6]                       VARCHAR (240)                                       NULL,
    [PEOPLE_UNITS_ID]              NUMERIC (10)                                        NULL,
    [SDR_QUALIFICATION_CODE]       VARCHAR (6)                                         NULL,
    [MAIN_SUBJECT_1]               VARCHAR (4)                                         NULL,
    [MAIN_SUBJECT_2]               VARCHAR (4)                                         NULL,
    [MAIN_SUBJECT_3]               VARCHAR (4)                                         NULL,
    [DATA_RETURN]                  VARCHAR (1)                                         NULL,
    [SDR_COMPLETION_RETURN_STATUS] VARCHAR (1)                                         NULL,
    [COURSE_CREDITS]               NUMERIC (4) MASKED WITH (FUNCTION = 'default()')    NULL,
    [SDR_COURSE_CODE]              VARCHAR (30)                                        NULL,
    [THEORY_HOURS]                 NUMERIC (10)                                        NULL,
    [PRACTICAL_HOURS]              NUMERIC (10)                                        NULL,
    [AWARD_ID]                     NUMERIC (10)                                        NULL,
    [AWARD_STATUS]                 VARCHAR (40)                                        NULL,
    [SDR_REGISTER_LEVEL]           VARCHAR (2)                                         NULL,
    [GRADING_SCHEME_ID]            NUMERIC (10)                                        NULL,
    [USER_7]                       VARCHAR (240)                                       NULL,
    [USER_8]                       VARCHAR (240)                                       NULL,
    [USER_9]                       VARCHAR (240)                                       NULL,
    [USER_10]                      VARCHAR (240)                                       NULL,
    [USER_11]                      VARCHAR (240)                                       NULL,
    [USER_12]                      VARCHAR (240)                                       NULL,
    [USER_13]                      VARCHAR (240)                                       NULL,
    [USER_14]                      VARCHAR (240)                                       NULL,
    [USER_15]                      VARCHAR (240)                                       NULL,
    [USER_16]                      VARCHAR (240)                                       NULL,
    [USER_17]                      VARCHAR (240)                                       NULL,
    [USER_18]                      VARCHAR (240)                                       NULL,
    [PRINT_COUNT]                  NUMERIC (10)                                        NULL,
    [ASSESSMENT_PROGRESS]          NUMERIC (5, 2)                                      NULL,
    [CONFIGURABLE_STATUS_ID]       NUMERIC (10)                                        NULL,
    [NZQA_EXPORT_BATCH]            NUMERIC (10)                                        NULL,
    [USER_19]                      VARCHAR (240)                                       NULL,
    [USER_20]                      VARCHAR (240)                                       NULL,
    [USER_21]                      VARCHAR (240)                                       NULL,
    [USER_22]                      VARCHAR (240)                                       NULL,
    [USER_23]                      VARCHAR (240)                                       NULL,
    [USER_24]                      VARCHAR (240)                                       NULL,
    [USER_25]                      VARCHAR (240)                                       NULL,
    [USER_26]                      VARCHAR (240)                                       NULL,
    [USER_27]                      VARCHAR (240)                                       NULL,
    [USER_28]                      VARCHAR (240)                                       NULL,
    [USER_29]                      VARCHAR (240)                                       NULL,
    [USER_30]                      VARCHAR (240)                                       NULL,
    [NZQA_ID]                      NUMERIC (10)                                        NULL,
    [PREVIOUS_FAILED_FINAL_RESULT] VARCHAR (30)                                        NULL,
    [AGGREGATE_SCORE]              NUMERIC (13, 10)                                    NULL,
    [ADJUSTED_GRADE]               VARCHAR (30)                                        NULL,
    [LINKED_CAR_ID]                NUMERIC (10)                                        NULL,
    [EXPIRY_DATE]                  DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')           NULL,
    [USER_31]                      VARCHAR (240)                                       NULL,
    [USER_32]                      VARCHAR (240)                                       NULL,
    [USER_33]                      VARCHAR (240)                                       NULL,
    [USER_34]                      VARCHAR (240)                                       NULL,
    [USER_35]                      VARCHAR (240)                                       NULL,
    [USER_36]                      VARCHAR (240)                                       NULL,
    [RECOGNITION_TYPE]             VARCHAR (10)                                        NULL,
    [ORGANISATION_TYPE]            VARCHAR (40)                                        NULL,
    [ORGANISATION_CODE]            VARCHAR (30)                                        NULL,
    [EXPORTED_DATE]                DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')           NULL,
    [AUTOCREDIT_STATUS]            VARCHAR (1)                                         NULL,
    [HAS_MUST_PASS_ELEMENT_FAILED] VARCHAR (1)                                         NULL,
    [SOURCE]                       VARCHAR (10)                                        NULL,
    [SOURCE_ID]                    NUMERIC (10)                                        NULL,
    [INSTITUTION_CONTEXT_ID]       NUMERIC (10)                                        NULL,
    [IS_CONDONED]                  VARCHAR (1)                                         NULL,
    [TARGET_GRADE]                 VARCHAR (255)                                       NULL,
    [WORKING_TO_GRADE]             VARCHAR (255)                                       NULL,
    [EXTERNAL_PREDICTED_GRADE]     VARCHAR (30)                                        NULL,
    [POINTS]                       NUMERIC (10, 2)                                     NULL,
    [AMENDED_AGGREGATE_SCORE]      NUMERIC (13, 10)                                    NULL,
    [AAS_REQUESTED_BY]             NUMERIC (10)                                        NULL,
    [AAS_AUTHORISED_BY]            NUMERIC (10)                                        NULL,
    [SITTING]                      VARCHAR (2)                                         NULL,
    [HESA_QUAL_TYPE]               VARCHAR (2)                                         NULL,
    [INCLUDE_IN_HESA]              VARCHAR (1)                                         NULL,
    [_transaction_date]            DATETIME2 (7)                                            NULL,
    [year]                         NVARCHAR (MAX)                                      NULL,
    [month]                        NVARCHAR (MAX)                                      NULL,
    [day]                          NVARCHAR (MAX)                                      NULL,
    [_DLRawZoneTimeStamp]          DATETIME2 (7)                                       NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME2 (7)                                       NULL,
    [_RecordStart]                 DATETIME2 (7)                                       NULL,
    [_RecordEnd]                   DATETIME2 (7)                                       NULL,
    [_RecordDeleted]               INT                                                 NULL,
    [_RecordCurrent]               INT                                                 NULL
);

