CREATE TABLE [edw].[OneEBS_EBS_0165_PEOPLE_UIO] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [START_DATE]              DATETIME2 (7)           NULL,
    [END_DATE]                DATETIME2 (7)           NULL,
    [STATUS]                  NUMERIC (1)    NULL,
    [PERSON_RIGHT]            NUMERIC (1)    NULL,
    [OBS_TYPE]                VARCHAR (20)   NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [ID]                      NUMERIC (10)   NULL,
    [PERSON_CODE]             NUMERIC (10)   NULL,
    [UIO_ID]                  NUMERIC (10)   NULL,
    [TEACH_ALL_LEARNERS]      VARCHAR (1)    NULL,
    [TYPE]                    VARCHAR (10)   NULL,
    [TUTORGROUP_ID]           NUMERIC (10)   NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

