CREATE TABLE [edw].[OneEBS_EBS_0165_FEES_LIST_ALLOCATED] (
    [INSTITUTION_CONTEXT_ID]       NUMERIC (10)                                         NULL,
    [ORIG_RECEIPT_FEE_RECORD_CODE] NUMERIC (10)                                         NULL,
    [ID]                           NUMERIC (10)                                         NULL,
    [FEE_RECORD_CODE]              NUMERIC (10)                                         NULL,
    [FEE_VALUE_NUMBER]             NUMERIC (10)                                         NULL,
    [PERSON_CODE]                  NUMERIC (10)                                         NULL,
    [STATUS]                       VARCHAR (1)                                          NULL,
    [AMOUNT_TEMP]                  NUMERIC (22) MASKED WITH (FUNCTION = 'default()')    NULL,
    [TYPE]                         VARCHAR (30)                                         NULL,
    [RECONCILED_BY]                VARCHAR (30)                                         NULL,
    [RECONCILED_DATE]              DATETIME2 (7)                                                 NULL,
    [CREATED_BY]                   VARCHAR (30)                                         NULL,
    [CREATED_DATE]                 DATETIME2 (7)                                                 NULL,
    [UPDATED_BY]                   VARCHAR (30)                                         NULL,
    [UPDATED_DATE]                 DATETIME2 (7)                                                 NULL,
    [AMOUNT]                       NUMERIC (15, 2) MASKED WITH (FUNCTION = 'default()') NULL,
    [VAT_CODE]                     VARCHAR (2)                                          NULL,
    [VAT_AMOUNT]                   NUMERIC (7, 2) MASKED WITH (FUNCTION = 'default()')  NULL,
    [VAT_RATE]                     NUMERIC (6, 2)                                       NULL,
    [_transaction_date]            DATETIME2 (7)                                             NULL,
    [year]                         NVARCHAR (MAX)                                       NULL,
    [month]                        NVARCHAR (MAX)                                       NULL,
    [day]                          NVARCHAR (MAX)                                       NULL,
    [_DLRawZoneTimeStamp]          DATETIME2 (7)                                        NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME2 (7)                                        NULL,
    [_RecordStart]                 DATETIME2 (7)                                        NULL,
    [_RecordEnd]                   DATETIME2 (7)                                        NULL,
    [_RecordDeleted]               INT                                                  NULL,
    [_RecordCurrent]               INT                                                  NULL
);

