CREATE TABLE [edw].[OneEBS_EBS_0165_CONFIGURABLE_STATUSES] (
    [INSTITUTION_CONTEXT_ID]   NUMERIC (10)   NULL,
    [INCLUDE_IN_DATA_RETURN]   VARCHAR (1)    NULL,
    [ID]                       NUMERIC (10)   NULL,
    [STATUS_CODE]              VARCHAR (20)   NULL,
    [SHORT_DESCRIPTION]        VARCHAR (13)   NULL,
    [LONG_DESCRIPTION]         VARCHAR (40)   NULL,
    [ACTIVE]                   VARCHAR (1)    NULL,
    [CONTRIBS_COURSE_OUTCOMES] VARCHAR (1)    NULL,
    [LEARNER_VIEWABLE]         VARCHAR (1)    NULL,
    [CREATED_BY]               VARCHAR (30)   NULL,
    [CREATED_DATE]             DATETIME2 (7)           NULL,
    [UPDATED_BY]               VARCHAR (30)   NULL,
    [UPDATED_DATE]             DATETIME2 (7)           NULL,
    [LINKED_ROLE]              NUMERIC (10)   NULL,
    [STATUS_TYPE]              VARCHAR (10)   NULL,
    [CONTRIBS_AWARD_OUTCOMES]  VARCHAR (1)    NULL,
    [SUBMIT_TO_NZQA]           VARCHAR (1)    NULL,
    [INCLUDED_IN_SDR]          VARCHAR (1)    NULL,
    [BAD_DEBT_CHECK]           VARCHAR (1)    NULL,
    [IS_PUBLISHABLE]           VARCHAR (1)    NULL,
    [CAN_UPDATE_PROGRESS]      VARCHAR (1)    NULL,
    [_transaction_date]        DATETIME2 (7)       NULL,
    [year]                     NVARCHAR (MAX) NULL,
    [month]                    NVARCHAR (MAX) NULL,
    [day]                      NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]      DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]  DATETIME2 (7)  NULL,
    [_RecordStart]             DATETIME2 (7)  NULL,
    [_RecordEnd]               DATETIME2 (7)  NULL,
    [_RecordDeleted]           INT            NULL,
    [_RecordCurrent]           INT            NULL
);

