CREATE TABLE [edw].[OneEBS_EBS_0165_VERIFIERS] (
    [ID]                      NUMERIC (10)   NULL,
    [LOW_VALUE]               VARCHAR (40)   NULL,
    [RV_DOMAIN]               VARCHAR (40)   NULL,
    [ABBREVIATION]            VARCHAR (10)   NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)  NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)  NULL,
    [FRANCHISING_TYPE]        VARCHAR (1)    NULL,
    [OPS_MASTER]              VARCHAR (1)    NULL,
    [FES_SHORT_DESCRIPTION]   VARCHAR (13)   NULL,
    [FES_LONG_DESCRIPTION]    VARCHAR (1000) NULL,
    [SIR_VALUE]               VARCHAR (10)   NULL,
    [FES_ACTIVE]              VARCHAR (1)    NULL,
    [ROLE_DEFS_ID]            NUMERIC (10)   NULL,
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

