CREATE TABLE [edw].[OneEBS_EBS_0165_REGISTER_EVENT_SLOTS] (
    [MAXIMUM_LEARNERS]        NUMERIC (4)    NULL,
    [TIMETABLE_PERIODS_ID]    NUMERIC (10)   NULL,
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)   NULL,
    [ID]                      NUMERIC (10)   NULL,
    [REGISTER_EVENT_ID]       NUMERIC (10)   NULL,
    [SESSION_CODE]            VARCHAR (10)   NULL,
    [STARTDATE]               DATETIME2 (7)           NULL,
    [ENDDATE]                 DATETIME2 (7)           NULL,
    [BREAK]                   NUMERIC (10)   NULL,
    [SLOT_STATUS]             VARCHAR (10)   NULL,
    [CREATED_BY]              VARCHAR (30)   NULL,
    [CREATED_DATE]            DATETIME2 (7)           NULL,
    [UPDATED_BY]              VARCHAR (30)   NULL,
    [UPDATED_DATE]            DATETIME2 (7)           NULL,
    [REISSUED_BY]             VARCHAR (30)   NULL,
    [REISSUED_DATE]           DATETIME2 (7)           NULL,
    [REISSUED_COUNT]          NUMERIC (3)    NULL,
    [IS_ROLL_CALL]            VARCHAR (1)    NULL,
    [_transaction_date]       DATETIME2 (7)       NULL,
    [year]                    NVARCHAR (MAX) NULL,
    [month]                   NVARCHAR (MAX) NULL,
    [day]                     NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)  NULL,
    [_RecordStart]            DATETIME2 (7)  NULL,
    [_RecordEnd]              DATETIME2 (7)  NULL,
    [_RecordDeleted]          INT            NULL,
    [_RecordCurrent]          INT            NULL
);

