CREATE TABLE [edw].[OneEBS_EBS_0165_ADDRESSES] (
    [OWNER_REF]                    VARCHAR (30)                                       NULL,
    [OWNER_TYPE]                   VARCHAR (6)                                        NULL,
    [ADDRESS_CODE]                 NUMERIC (10)                                       NULL,
    [ADDRESS_TYPE]                 VARCHAR (8) MASKED WITH (FUNCTION = 'default()')   NULL,
    [START_DATE]                   DATETIME2 (7)                                      NULL,
    [END_DATE]                     DATETIME2 (7)                                      NULL,
    [ADDRESS_LINE_1]               VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_2]               VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_3]               VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_4]               VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ADDRESS_LINE_5]               VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [TOWN]                         VARCHAR (50)                                       NULL,
    [TELEPHONE]                    VARCHAR (22) MASKED WITH (FUNCTION = 'default()')  NULL,
    [UK_POST_CODE_PT1]             VARCHAR (4)                                        NULL,
    [UK_POST_CODE_PT2]             VARCHAR (4)                                        NULL,
    [INTERNATIONAL_POST_CODE]      VARCHAR (20)                                       NULL,
    [FAX]                          VARCHAR (22)                                       NULL,
    [REGION]                       VARCHAR (32)                                       NULL,
    [COUNTRY]                      VARCHAR (40)                                       NULL,
    [EMAIL_ADDRESS]                VARCHAR (128) MASKED WITH (FUNCTION = 'default()') NULL,
    [EXTENSION_TEL_NO]             VARCHAR (10)                                       NULL,
    [CREATED_BY]                   VARCHAR (30)                                       NULL,
    [CREATED_DATE]                 DATETIME2 (7)                                      NULL,
    [UPDATED_BY]                   VARCHAR (30)                                       NULL,
    [UPDATED_DATE]                 DATETIME2 (7)                                      NULL,
    [MAILSORT_CODE]                VARCHAR (5)                                        NULL,
    [FES_CONTACT_NAME]             VARCHAR (40)                                       NULL,
    [FES_TELEPHONE_LINE_2]         VARCHAR (22) MASKED WITH (FUNCTION = 'default()')  NULL,
    [EASTING]                      VARCHAR (20)                                       NULL,
    [NORTHING]                     VARCHAR (20)                                       NULL,
    [NOTES_ID]                     NUMERIC (10)                                       NULL,
    [OLIB_ADDRNO]                  NUMERIC (10)                                       NULL,
    [PERSON_CODE]                  NUMERIC (10)                                       NULL,
    [UCAS_RECORD]                  VARCHAR (1)                                        NULL,
    [UCAS_RD_NUMBER]               NUMERIC (4)                                        NULL,
    [USER_1]                       VARCHAR (240)                                      NULL,
    [USER_2]                       VARCHAR (240)                                      NULL,
    [USER_3]                       VARCHAR (240)                                      NULL,
    [USER_4]                       VARCHAR (240)                                      NULL,
    [USER_5]                       VARCHAR (240)                                      NULL,
    [USER_6]                       VARCHAR (240)                                      NULL,
    [ACCOMMODATION_TYPE]           VARCHAR (1)                                        NULL,
    [REGION_AREA]                  VARCHAR (3)                                        NULL,
    [FUNDING_YEAR]                 VARCHAR (10)                                       NULL,
    [INSTITUTION_CONTEXT_ID]       NUMERIC (10)                                       NULL,
    [UNIQUE_DELIVERY_POINT_REF_NO] NUMERIC (15)                                       NULL,
    [LOCATION_TYPE]                VARCHAR (40)                                       NULL,
    [COUNTRY_CODE]                 VARCHAR (40)                                       NULL,
    [LATITUDE]                     NUMERIC (9, 6)                                     NULL,
    [LONGITUDE]                    NUMERIC (9, 6)                                     NULL,
    [TERRITORIAL_AUTHORITY_CODE]   VARCHAR (40)                                       NULL,
    [_transaction_date]            DATETIME2 (7)                                           NULL,
    [year]                         NVARCHAR (MAX)                                     NULL,
    [month]                        NVARCHAR (MAX)                                     NULL,
    [day]                          NVARCHAR (MAX)                                     NULL,
    [_DLRawZoneTimeStamp]          DATETIME2 (7)                                      NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME2 (7)                                      NULL,
    [_RecordStart]                 DATETIME2 (7)                                      NULL,
    [_RecordEnd]                   DATETIME2 (7)                                      NULL,
    [_RecordDeleted]               INT                                                NULL,
    [_RecordCurrent]               INT                                                NULL
);

