CREATE TABLE [edw].[OneEBS_EBS_0165_WAIVER_VALUES] (
    [IS_ELIGIBLE_FOR_FEES_FREE] VARCHAR (1)    NULL,
    [ROUNDING_FACTOR]           VARCHAR (1)    NULL,
    [CREATED_BY]                VARCHAR (30)   NULL,
    [CREATED_DATE]              DATETIME2 (7)           NULL,
    [UPDATED_BY]                VARCHAR (30)   NULL,
    [UPDATED_DATE]              DATETIME2 (7)           NULL,
    [SP_VISIBLE]                VARCHAR (1)    NULL,
    [SP_EVIDENCE_STATEMENT]     VARCHAR (240)  NULL,
    [SP_PUBLIC_WAIVER_CODE]     VARCHAR (10)   NULL,
    [USER_1]                    VARCHAR (240)  NULL,
    [USER_2]                    VARCHAR (240)  NULL,
    [USER_3]                    VARCHAR (240)  NULL,
    [USER_4]                    VARCHAR (240)  NULL,
    [USER_5]                    VARCHAR (240)  NULL,
    [USER_6]                    VARCHAR (240)  NULL,
    [USER_7]                    VARCHAR (240)  NULL,
    [USER_8]                    VARCHAR (240)  NULL,
    [USER_9]                    VARCHAR (240)  NULL,
    [USER_10]                   VARCHAR (240)  NULL,
    [INSTITUTION_CONTEXT_ID]    NUMERIC (10)   NULL,
    [WAIVER_VALUE_NUMBER]       NUMERIC (10)   NULL,
    [WAIVER_CODE]               VARCHAR (10)   NULL,
    [CALOCC_CODE]               VARCHAR (10)   NULL,
    [CALOCC_CTYPE]              VARCHAR (10)   NULL,
    [START_DATE]                DATETIME2 (7)           NULL,
    [END_DATE]                  DATETIME2 (7)           NULL,
    [CALC_CRITERIA]             VARCHAR (1)    NULL,
    [CALC_VALUE]                NUMERIC (6, 2) NULL,
    [_transaction_date]         DATETIME2 (7)       NULL,
    [year]                      NVARCHAR (MAX) NULL,
    [month]                     NVARCHAR (MAX) NULL,
    [day]                       NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]       DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]   DATETIME2 (7)  NULL,
    [_RecordStart]              DATETIME2 (7)  NULL,
    [_RecordEnd]                DATETIME2 (7)  NULL,
    [_RecordDeleted]            INT            NULL,
    [_RecordCurrent]            INT            NULL
);

