CREATE TABLE [edw].[OneEBS_EBS_0165_REGISTER_EVENTS] (
    [HAS_BEEN_MOVED_WHILST_LOCKED] VARCHAR (1)    NULL,
    [REGION_ORGANISATION_UNIT_ID]  NUMERIC (10)   NULL,
    [ID]                           NUMERIC (10)   NULL,
    [SESSION_CODE]                 VARCHAR (10)   NULL,
    [EVENT_TYPE]                   VARCHAR (10)   NULL,
    [EVENT_CODE]                   VARCHAR (40)   NULL,
    [DESCRIPTION]                  VARCHAR (200)  NULL,
    [LEAD_MARKING]                 NUMERIC (3)    NULL,
    [REGISTER_WEEK_PATTERNS_ID]    NUMERIC (10)   NULL,
    [REQUIRES_ATTENTION]           VARCHAR (1)    NULL,
    [CREATED_BY]                   VARCHAR (30)   NULL,
    [CREATED_DATE]                 DATETIME2 (7)           NULL,
    [UPDATED_BY]                   VARCHAR (30)   NULL,
    [UPDATED_DATE]                 DATETIME2 (7)           NULL,
    [USER_1]                       VARCHAR (255)  NULL,
    [USER_2]                       VARCHAR (255)  NULL,
    [USER_3]                       VARCHAR (255)  NULL,
    [USER_4]                       VARCHAR (255)  NULL,
    [USER_5]                       VARCHAR (255)  NULL,
    [USER_6]                       VARCHAR (255)  NULL,
    [PROVIDER_ORGANISATION_CODE]   VARCHAR (30)   NULL,
    [IS_FOR_EMA]                   VARCHAR (1)    NULL,
    [REGISTER_TYPE]                VARCHAR (10)   NULL,
    [REGISTER_TYPE_START_DATE]     DATETIME2 (7)           NULL,
    [INSTITUTION_CONTEXT_ID]       NUMERIC (10)   NULL,
    [TIMETABLES_ID]                NUMERIC (10)   NULL,
    [_transaction_date]            DATETIME2 (7)       NULL,
    [year]                         NVARCHAR (MAX) NULL,
    [month]                        NVARCHAR (MAX) NULL,
    [day]                          NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]          DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME2 (7)  NULL,
    [_RecordStart]                 DATETIME2 (7)  NULL,
    [_RecordEnd]                   DATETIME2 (7)  NULL,
    [_RecordDeleted]               INT            NULL,
    [_RecordCurrent]               INT            NULL
);

