CREATE TABLE [edw].[OneEBS_EBS_0165_PEOPLE_ASR] (
    [HAS_DOC_DEGREE]                 VARCHAR (1)                                       NULL,
    [DOC_DEGREE_LOCATION]            VARCHAR (40)                                      NULL,
    [DOC_DEGREE_ACHIEVED_SINCE_17]   VARCHAR (40)                                      NULL,
    [HAS_MSTR_DEGREE]                VARCHAR (1)                                       NULL,
    [MSTR_DEGREE_LOCATION]           VARCHAR (40)                                      NULL,
    [MSTR_DEGREE_ACHIEVED_SINCE_17]  VARCHAR (40)                                      NULL,
    [HAS_GRAD_DIPLOMA]               VARCHAR (1)                                       NULL,
    [GRAD_DIPLOMA_LOCATION]          VARCHAR (40)                                      NULL,
    [GRAD_DIPLOMA_ACHIEVED_SINCE_17] VARCHAR (40)                                      NULL,
    [ID]                             NUMERIC (10)                                      NULL,
    [PERSON_CODE]                    NUMERIC (10)                                      NULL,
    [HAS_BACH_OR_HIGHER_DEGREE_008]  VARCHAR (1)                                       NULL,
    [HAS_ADV_DIP_OR_ASSOC_DEG_410]   VARCHAR (1)                                       NULL,
    [HAS_DIP_OR_ASSOC_DIP_420]       VARCHAR (1)                                       NULL,
    [HAS_CERT_IV_OR_AD_CERT_TEC_511] VARCHAR (1)                                       NULL,
    [HAS_CERT_III_OR_TRADE_CERT_514] VARCHAR (1)                                       NULL,
    [HAS_CERT_II_521]                VARCHAR (1)                                       NULL,
    [HAS_CERT_I_524]                 VARCHAR (1)                                       NULL,
    [HAS_OTHER_CERT_990]             VARCHAR (1)                                       NULL,
    [HOME_TELEPHONE_NUMBER]          VARCHAR (20) MASKED WITH (FUNCTION = 'default()') NULL,
    [WORK_TELEPHONE_NUMBER]          VARCHAR (20) MASKED WITH (FUNCTION = 'default()') NULL,
    [CREATED_BY]                     VARCHAR (30)                                      NULL,
    [CREATED_DATE]                   DATETIME2 (7)                                              NULL,
    [UPDATED_BY]                     VARCHAR (30)                                      NULL,
    [UPDATED_DATE]                   DATETIME2 (7)                                              NULL,
    [INSTITUTION_CONTEXT_ID]         NUMERIC (10)                                      NULL,
    [SURVEY_CONTACT_STATUS]          VARCHAR (40)                                      NULL,
    [_transaction_date]              DATETIME2 (7)                                          NULL,
    [year]                           NVARCHAR (MAX)                                    NULL,
    [month]                          NVARCHAR (MAX)                                    NULL,
    [day]                            NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]            DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME2 (7)                                     NULL,
    [_RecordStart]                   DATETIME2 (7)                                     NULL,
    [_RecordEnd]                     DATETIME2 (7)                                     NULL,
    [_RecordDeleted]                 INT                                               NULL,
    [_RecordCurrent]                 INT                                               NULL
);

