CREATE TABLE [edw].[OneEBS_EBS_0165_VISAS] (
    [ID]                      NUMERIC (10)                                      NULL,
    [PERSON_CODE]             NUMERIC (10)                                      NULL,
    [VISA_TYPE]               VARCHAR (40) MASKED WITH (FUNCTION = 'default()') NULL,
    [ISSUE_DATE]              DATETIME2 (7)                                              NULL,
    [EXPIRY_DATE]             DATETIME2 (7) MASKED WITH (FUNCTION = 'default()')         NULL,
    [CONDITIONS]              VARCHAR (2000)                                    NULL,
    [PERMIT_LABEL_NO]         VARCHAR (40)                                      NULL,
    [VISA_LABEL_NO]           VARCHAR (40) MASKED WITH (FUNCTION = 'default()') NULL,
    [STATUS]                  VARCHAR (40)                                      NULL,
    [CREATED_BY]              VARCHAR (30)                                      NULL,
    [CREATED_DATE]            DATETIME2 (7)                                              NULL,
    [UPDATED_BY]              VARCHAR (30)                                      NULL,
    [UPDATED_DATE]            DATETIME2 (7)                                              NULL,
    [BLOB_ID]                 NUMERIC (10)                                      NULL,
    [INZ_FILE_CREATED]        VARCHAR (1)                                       NULL,
    [USER_1]                  VARCHAR (240)                                     NULL,
    [USER_2]                  VARCHAR (240)                                     NULL,
    [USER_3]                  VARCHAR (240)                                     NULL,
    [USER_4]                  VARCHAR (240)                                     NULL,
    [USER_5]                  VARCHAR (240)                                     NULL,
    [USER_6]                  VARCHAR (240)                                     NULL,
    [USER_7]                  VARCHAR (240)                                     NULL,
    [USER_8]                  VARCHAR (240)                                     NULL,
    [USER_9]                  VARCHAR (240)                                     NULL,
    [USER_10]                 VARCHAR (240)                                     NULL,
    [USER_11]                 VARCHAR (240)                                     NULL,
    [USER_12]                 VARCHAR (240)                                     NULL,
    [USER_13]                 VARCHAR (240)                                     NULL,
    [USER_14]                 VARCHAR (240)                                     NULL,
    [USER_15]                 VARCHAR (240)                                     NULL,
    [USER_16]                 VARCHAR (240)                                     NULL,
    [USER_17]                 VARCHAR (240)                                     NULL,
    [USER_18]                 VARCHAR (240)                                     NULL,
    [USER_19]                 VARCHAR (240)                                     NULL,
    [USER_20]                 VARCHAR (240)                                     NULL,
    [VISA_SUB_CLASS]          VARCHAR (10) MASKED WITH (FUNCTION = 'default()') NULL,
    [VISA_HOLDER_CODE]        VARCHAR (10) MASKED WITH (FUNCTION = 'default()') NULL,
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)                                      NULL,
    [_transaction_date]       DATETIME2 (7)                                          NULL,
    [year]                    NVARCHAR (MAX)                                    NULL,
    [month]                   NVARCHAR (MAX)                                    NULL,
    [day]                     NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)                                     NULL,
    [_RecordStart]            DATETIME2 (7)                                     NULL,
    [_RecordEnd]              DATETIME2 (7)                                     NULL,
    [_RecordDeleted]          INT                                               NULL,
    [_RecordCurrent]          INT                                               NULL
);

