CREATE TABLE [edw].[OneEBS_EBS_0165_FEE_TYPES] (
    [FEE_TYPE_CODE]               VARCHAR (6)                                       NULL,
    [CREATED_BY]                  VARCHAR (30)                                      NULL,
    [CREATED_DATE]                DATETIME2 (7)                                              NULL,
    [UPDATED_BY]                  VARCHAR (30)                                      NULL,
    [UPDATED_DATE]                DATETIME2 (7)                                              NULL,
    [TUITION_TYPE_FEE]            VARCHAR (1)                                       NULL,
    [FES_SHORT_DESCRIPTION]       VARCHAR (13)                                      NULL,
    [FES_LONG]                    VARCHAR (40)                                      NULL,
    [FES_VAT_CODE]                VARCHAR (2)                                       NULL,
    [FES_ACCOUNT_CODE]            VARCHAR (40) MASKED WITH (FUNCTION = 'default()') NULL,
    [FES_TRANSACTION_TYPE]        VARCHAR (1)                                       NULL,
    [FES_ISR]                     VARCHAR (1)                                       NULL,
    [LATE_FEE]                    VARCHAR (1)                                       NULL,
    [REFERRAL_FEE]                VARCHAR (1)                                       NULL,
    [PRIORITY]                    NUMERIC (5)                                       NULL,
    [INCLUDE_IN_RETURN]           VARCHAR (1)                                       NULL,
    [SDR_TYPE]                    VARCHAR (1)                                       NULL,
    [ALLOW_REFUND]                VARCHAR (1)                                       NULL,
    [ROUNDING_MULTIPLE]           NUMERIC (7, 2)                                    NULL,
    [MIN_VALUE]                   NUMERIC (7, 2)                                    NULL,
    [USER_1]                      VARCHAR (240)                                     NULL,
    [USER_2]                      VARCHAR (240)                                     NULL,
    [USER_3]                      VARCHAR (240)                                     NULL,
    [USER_4]                      VARCHAR (240)                                     NULL,
    [USER_5]                      VARCHAR (240)                                     NULL,
    [USER_6]                      VARCHAR (240)                                     NULL,
    [USER_7]                      VARCHAR (240)                                     NULL,
    [USER_8]                      VARCHAR (240)                                     NULL,
    [USER_9]                      VARCHAR (240)                                     NULL,
    [USER_10]                     VARCHAR (240)                                     NULL,
    [CHARGE_ONCE]                 VARCHAR (40)                                      NULL,
    [ROLE_DEFS_ID]                NUMERIC (10)                                      NULL,
    [IS_ENFORCEABLE_DEBT]         VARCHAR (1)                                       NULL,
    [IS_TEMP_VISA_HOLDER_FEE]     VARCHAR (1)                                       NULL,
    [ENROLMENT_DURATION]          NUMERIC (4)                                       NULL,
    [IS_ELIGIBLE_FOR_INSTALMENTS] VARCHAR (1)                                       NULL,
    [IS_GIFT]                     VARCHAR (1)                                       NULL,
    [GL_COMPONENT_1]              VARCHAR (30)                                      NULL,
    [GL_COMPONENT_2]              VARCHAR (30)                                      NULL,
    [GL_COMPONENT_3]              VARCHAR (30)                                      NULL,
    [GL_COMPONENT_4]              VARCHAR (30)                                      NULL,
    [FEE_CATEGORY_CODE]           VARCHAR (10)                                      NULL,
    [IS_ACTIVE]                   VARCHAR (1)                                       NULL,
    [INSTITUTION_CONTEXT_ID]      NUMERIC (10)                                      NULL,
    [IS_ELIGIBLE_FOR_FEES_FREE]   VARCHAR (1)                                       NULL,
    [_transaction_date]           DATETIME2 (7)                                          NULL,
    [year]                        NVARCHAR (MAX)                                    NULL,
    [month]                       NVARCHAR (MAX)                                    NULL,
    [day]                         NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]         DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp]     DATETIME2 (7)                                     NULL,
    [_RecordStart]                DATETIME2 (7)                                     NULL,
    [_RecordEnd]                  DATETIME2 (7)                                     NULL,
    [_RecordDeleted]              INT                                               NULL,
    [_RecordCurrent]              INT                                               NULL
);

