CREATE TABLE [edw].[OneEBS_EBS_0165_LOCATIONS] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)                                      NULL,
    [COUNTRY_CODE]            VARCHAR (40)                                      NULL,
    [IS_AVAILABLE_IN_ESP]     VARCHAR (1)                                       NULL,
    [ORGANISATION_CODE]       VARCHAR (30)                                      NULL,
    [ADDRESS_LINE_3]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()') NULL,
    [ADDRESS_LINE_4]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()') NULL,
    [TOWN]                    VARCHAR (30)                                      NULL,
    [REGION]                  VARCHAR (32)                                      NULL,
    [UK_POST_CODE_PT1]        VARCHAR (4)                                       NULL,
    [UK_POST_CODE_PT2]        VARCHAR (4)                                       NULL,
    [SITE_CODE]               VARCHAR (10)                                      NULL,
    [SP_LOCATION_URL]         VARCHAR (240)                                     NULL,
    [SP_DIRECTIONS_URL]       VARCHAR (512)                                     NULL,
    [FES_ACTIVE]              VARCHAR (1)                                       NULL,
    [INSTCAMP]                VARCHAR (1)                                       NULL,
    [USER_1]                  VARCHAR (255)                                     NULL,
    [USER_2]                  VARCHAR (255)                                     NULL,
    [USER_3]                  VARCHAR (255)                                     NULL,
    [USER_4]                  VARCHAR (255)                                     NULL,
    [USER_5]                  VARCHAR (255)                                     NULL,
    [USER_6]                  VARCHAR (255)                                     NULL,
    [IS_INCIDENT]             VARCHAR (1)                                       NULL,
    [LOCATION_CODE]           VARCHAR (10)                                      NULL,
    [CREATED_BY]              VARCHAR (30)                                      NULL,
    [CREATED_DATE]            DATETIME2 (7)                                              NULL,
    [UPDATED_BY]              VARCHAR (30)                                      NULL,
    [UPDATED_DATE]            DATETIME2 (7)                                              NULL,
    [FES_SHORT_DESCRIPTION]   VARCHAR (13)                                      NULL,
    [FES_LONG_DESCRIPTION]    VARCHAR (40)                                      NULL,
    [ADDRESS_LINE_1]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()') NULL,
    [ADDRESS_LINE_2]          VARCHAR (32) MASKED WITH (FUNCTION = 'default()') NULL,
    [_transaction_date]       DATETIME2 (7)                                          NULL,
    [year]                    NVARCHAR (MAX)                                    NULL,
    [month]                   NVARCHAR (MAX)                                    NULL,
    [day]                     NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)                                     NULL,
    [_RecordStart]            DATETIME2 (7)                                     NULL,
    [_RecordEnd]              DATETIME2 (7)                                     NULL,
    [_RecordDeleted]          INT                                               NULL,
    [_RecordCurrent]          INT                                               NULL
);

