CREATE TABLE [edw].[OneEBS_EBS_0165_WEB_CONFIG] (
    [INSTITUTION_CONTEXT_ID]  NUMERIC (10)                                      NULL,
    [ID]                      NUMERIC (10)                                      NULL,
    [CAN_BE_OVERRIDDEN]       VARCHAR (1)                                       NULL,
    [PARAMETER]               VARCHAR (40)                                      NULL,
    [PARAMETER_VALUE]         VARCHAR (255)                                     NULL,
    [APP_ID]                  VARCHAR (40)                                      NULL,
    [AREA_CODE]               VARCHAR (40) MASKED WITH (FUNCTION = 'default()') NULL,
    [DESCRIPTION]             VARCHAR (255)                                     NULL,
    [DATA_TYPE]               VARCHAR (3)                                       NULL,
    [VERIFIER]                VARCHAR (40)                                      NULL,
    [LINK_URL]                VARCHAR (255)                                     NULL,
    [LINK_DESCRIPTION]        VARCHAR (40)                                      NULL,
    [NON_NULLABLE]            VARCHAR (2)                                       NULL,
    [CREATED_BY]              VARCHAR (30)                                      NULL,
    [CREATED_DATE]            DATETIME2 (7)                                              NULL,
    [UPDATED_BY]              VARCHAR (30)                                      NULL,
    [UPDATED_DATE]            DATETIME2 (7)                                              NULL,
    [VISIBLE]                 NUMERIC (1)                                       NULL,
    [PRODUCT_MODULE_ID]       NUMERIC (10)                                      NULL,
    [RESTRICT_TO_LICENCE]     VARCHAR (20)                                      NULL,
    [DISPLAY_ORDER]           NUMERIC (5, 2)                                    NULL,
    [RESTRICT_BY_INST_TYPE]   VARCHAR (20)                                      NULL,
    [MIN_VALUE]               VARCHAR (20)                                      NULL,
    [MAX_VALUE]               VARCHAR (20)                                      NULL,
    [VALIDATION_PATTERN]      VARCHAR (128)                                     NULL,
    [_transaction_date]       DATETIME2 (7)                                          NULL,
    [year]                    NVARCHAR (MAX)                                    NULL,
    [month]                   NVARCHAR (MAX)                                    NULL,
    [day]                     NVARCHAR (MAX)                                    NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)                                     NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)                                     NULL,
    [_RecordStart]            DATETIME2 (7)                                     NULL,
    [_RecordEnd]              DATETIME2 (7)                                     NULL,
    [_RecordDeleted]          INT                                               NULL,
    [_RecordCurrent]          INT                                               NULL
);

