CREATE TABLE [edw].[OneEBS_EBS_0165_USAGES] (
    [INSTITUTION_CONTEXT_ID]       NUMERIC (10)   NULL,
    [IS_NOT_AVAILABLE_IN_AGENT]    VARCHAR (1)    NULL,
    [IS_NOT_OVERWRITABLE_IN_AGENT] VARCHAR (1)    NULL,
    [ID]                           NUMERIC (10)   NULL,
    [USAGE_CODE]                   VARCHAR (1)    NULL,
    [OBJECT_TYPE]                  VARCHAR (10)   NULL,
    [DESCRIPTION]                  VARCHAR (40)   NULL,
    [IS_POSITIVE]                  VARCHAR (1)    NULL,
    [IS_DEFAULT_USAGE]             VARCHAR (1)    NULL,
    [ALTERNATE_KEY]                VARCHAR (1)    NULL,
    [POSITIVE_FOR_EMA]             VARCHAR (1)    NULL,
    [FES_ACTIVE]                   VARCHAR (1)    NULL,
    [CREATED_BY]                   VARCHAR (30)   NULL,
    [CREATED_DATE]                 DATETIME2 (7)           NULL,
    [UPDATED_BY]                   VARCHAR (30)   NULL,
    [UPDATED_DATE]                 DATETIME2 (7)           NULL,
    [IS_LATE]                      VARCHAR (1)    NULL,
    [IS_NOT_IN_CLASS]              VARCHAR (1)    NULL,
    [BG_COLOUR]                    VARCHAR (10)   NULL,
    [SELECTION_ORDER]              NUMERIC (2)    NULL,
    [IS_PARTIAL]                   VARCHAR (1)    NULL,
    [_transaction_date]            DATETIME2 (7)       NULL,
    [year]                         NVARCHAR (MAX) NULL,
    [month]                        NVARCHAR (MAX) NULL,
    [day]                          NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]          DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME2 (7)  NULL,
    [_RecordStart]                 DATETIME2 (7)  NULL,
    [_RecordEnd]                   DATETIME2 (7)  NULL,
    [_RecordDeleted]               INT            NULL,
    [_RecordCurrent]               INT            NULL
);

