CREATE TABLE [edw].[OneEBS_EBS_0165_CALENDAR_OCCURRENCES] (
    [INSTITUTION_CONTEXT_ID]   NUMERIC (10)   NULL,
    [LOCATION_CODE]            VARCHAR (10)   NULL,
    [CTYPE_CALENDAR_TYPE_CODE] VARCHAR (10)   NULL,
    [OCCURRENCE_CODE]          VARCHAR (10)   NULL,
    [START_DATE]               DATETIME2 (7)           NULL,
    [END_DATE]                 DATETIME2 (7)           NULL,
    [FES_SHORT_DESCRIPTION]    VARCHAR (13)   NULL,
    [FES_LONG_DESCRIPTION]     VARCHAR (40)   NULL,
    [ROLL_FWD_CALOCC_CODE]     VARCHAR (10)   NULL,
    [ROLL_FORWARD]             VARCHAR (1)    NULL,
    [CREATED_BY]               VARCHAR (30)   NULL,
    [CREATED_DATE]             DATETIME2 (7)           NULL,
    [UPDATED_BY]               VARCHAR (30)   NULL,
    [UPDATED_DATE]             DATETIME2 (7)           NULL,
    [_transaction_date]        DATETIME2 (7)       NULL,
    [year]                     NVARCHAR (MAX) NULL,
    [month]                    NVARCHAR (MAX) NULL,
    [day]                      NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]      DATETIME2 (7)  NULL,
    [_DLTrustedZoneTimeStamp]  DATETIME2 (7)  NULL,
    [_RecordStart]             DATETIME2 (7)  NULL,
    [_RecordEnd]               DATETIME2 (7)  NULL,
    [_RecordDeleted]           INT            NULL,
    [_RecordCurrent]           INT            NULL
);

