CREATE TABLE [edw].[Prada_Unit_UNIT_ENROLMENTS_FINALS] (
    [ID_PC]                          NUMERIC (18)   NULL,
    [ID_UUIO]                        NUMERIC (18)   NULL,
    [ID_CUIO]                        NUMERIC (18)   NULL,
    [ID_CPU]                         VARCHAR (50)   NULL,
    [ID_UPU]                         NUMERIC (18)   NULL,
    [INSTITUTE]                      NUMERIC (18)   NULL,
    [DELIVERY_LOC]                   VARCHAR (10)   NULL,
    [CLIENT_ID]                      VARCHAR (10)   NULL,
    [SUBJECT_ID]                     VARCHAR (12)   NULL,
    [PROGRAM_ID]                     VARCHAR (15)   NULL,
    [START_DATE]                     DATE           NULL,
    [END_DATE]                       DATE           NULL,
    [DELIVERY_MODE]                  NUMERIC (18)   NULL,
    [OUTCOME_NATIONAL]               VARCHAR (2)    NULL,
    [SCHED_HOURS]                    NUMERIC (18)   NULL,
    [FUNDING_NAT]                    VARCHAR (2)    NULL,
    [COMMEN_PROG]                    VARCHAR (1)    NULL,
    [TRAINING_CONTRACT]              VARCHAR (10)   NULL,
    [CLIENT_ID_APPREN]               VARCHAR (10)   NULL,
    [STUDY_REASON]                   NUMERIC (18)   NULL,
    [VET_IN_SCHOOL_FLAG]             VARCHAR (1)    NULL,
    [FUNDING_SPECIFIC]               VARCHAR (10)   NULL,
    [OUTCOME_ID_TRAINING]            VARCHAR (3)    NULL,
    [UNIT_PU_ID]                     NUMERIC (18)   NULL,
    [FUNDING_SOURCE]                 VARCHAR (12)   NULL,
    [RECOGNITION_TYPE]               VARCHAR (3)    NULL,
    [COURSE_PU_ID]                   NUMERIC (18)   NULL,
    [PERSON_CODE]                    NUMERIC (18)   NULL,
    [DATE_AWARDED]                   DATE           NULL,
    [COMMITMENT_ID]                  VARCHAR (12)   NULL,
    [PURCHASING_CONTRACT_ID]         VARCHAR (12)   NULL,
    [PURCHASING_CONTRACT_SCHED]      VARCHAR (3)    NULL,
    [HOURS_ATTENDED]                 NUMERIC (18)   NULL,
    [CALOCC_CODE]                    VARCHAR (10)   NULL,
    [PARENT_ID]                      NUMERIC (18)   NULL,
    [SPONSOR_ORG_CODE]               VARCHAR (50)   NULL,
    [UNIT_OFFERING_TYPE]             VARCHAR (10)   NULL,
    [UNIT_OFFERING_TYPE_DESC]        VARCHAR (50)   NULL,
    [PROGRESS_STATUS]                VARCHAR (2)    NULL,
    [PROGRESS_CODE]                  VARCHAR (10)   NULL,
    [PROGRESS_REASON]                VARCHAR (20)   NULL,
    [PROGRESS_DATE]                  DATE           NULL,
    [COURSE_PROGRESS_STATUS]         VARCHAR (2)    NULL,
    [COURSE_PROGRESS_CODE]           VARCHAR (10)   NULL,
    [COURSE_PROGRESS_REASON]         VARCHAR (20)   NULL,
    [COURSE_PROGRESS_DATE]           DATE           NULL,
    [COURSE_FUNDING_SOURCE]          VARCHAR (12)   NULL,
    [COURSE_DATE_AWARDED]            VARCHAR (10)   NULL,
    [TAFE_DELIVERY_MODE]             VARCHAR (15)   NULL,
    [COURSE_UIO_ID]                  NUMERIC (18)   NULL,
    [UNIT_UIO_ID]                    NUMERIC (18)   NULL,
    [AWARD_STATUS]                   VARCHAR (20)   NULL,
    [NO_ACA_HISTORY]                 VARCHAR (1)    NULL,
    [CLIENTID_MISS]                  VARCHAR (1)    NULL,
    [COURSE10]                       VARCHAR (10)   NULL,
    [ENROLCOUNT]                     NUMERIC (18)   NULL,
    [YEAR_CSEAWARDED]                NUMERIC (18)   NULL,
    [VALIDUNIT]                      NUMERIC (18)   NULL,
    [FINALUNIT]                      NUMERIC (18)   NULL,
    [PASSUNIT]                       NUMERIC (18)   NULL,
    [FAILUNIT]                       NUMERIC (18)   NULL,
    [WDRAWUNIT]                      NUMERIC (18)   NULL,
    [RPLUNIT]                        NUMERIC (18)   NULL,
    [NONASSUNIT]                     NUMERIC (18)   NULL,
    [CTUNIT]                         NUMERIC (18)   NULL,
    [OUT70UNIT]                      NUMERIC (18)   NULL,
    [OUT51UNIT]                      NUMERIC (18)   NULL,
    [OUT52UNIT]                      NUMERIC (18)   NULL,
    [OUT81UNIT]                      NUMERIC (18)   NULL,
    [OUT82UNIT]                      NUMERIC (18)   NULL,
    [OUT61UNIT]                      NUMERIC (18)   NULL,
    [OUT60UNIT]                      NUMERIC (18)   NULL,
    [ASH]                            NUMERIC (18)   NULL,
    [RPLASH]                         NUMERIC (18)   NULL,
    [TRNGASH]                        NUMERIC (18)   NULL,
    [ASH71]                          NUMERIC (18)   NULL,
    [FINALASH]                       NUMERIC (18)   NULL,
    [COUNTUNIT]                      NUMERIC (18)   NULL,
    [REPORT_DATE]                    VARCHAR (10)   NULL,
    [EXTRACT_DATE]                   VARCHAR (10)   NULL,
    [LOAD_DATE]                      DATE           NULL,
    [ENROLMENT_YEAR]                 NUMERIC (18)   NULL,
    [TRAINEE_CODE_INTERSTATE]        VARCHAR (12)   NULL,
    [MAXIMUM_HOURS_INTERSTATE]       NUMERIC (18)   NULL,
    [CLIENT_TUITION_FEE_INTERSTATE]  NUMERIC (18)   NULL,
    [FEE_CONCESSION_TYPE_INTERSTATE] VARCHAR (10)   NULL,
    [SEM1]                           VARCHAR (1)    NULL,
    [SEM2]                           VARCHAR (1)    NULL,
    [SEM3]                           VARCHAR (1)    NULL,
    [SEM1HRS]                        NUMERIC (6)    NULL,
    [SEM2HRS]                        NUMERIC (6)    NULL,
    [YRHRS1]                         NUMERIC (8)    NULL,
    [YRHRSINT]                       NUMERIC (8)    NULL,
    [YRHRS]                          NUMERIC (8)    NULL,
    [ADVD]                           VARCHAR (1)    NULL,
    [CLAS]                           VARCHAR (1)    NULL,
    [SELF]                           VARCHAR (1)    NULL,
    [ELEC]                           VARCHAR (1)    NULL,
    [BLND]                           VARCHAR (1)    NULL,
    [DIST]                           VARCHAR (1)    NULL,
    [ONJB]                           VARCHAR (1)    NULL,
    [ONJD]                           VARCHAR (1)    NULL,
    [SIMU]                           VARCHAR (1)    NULL,
    [MISD]                           VARCHAR (1)    NULL,
    [OTHD]                           VARCHAR (1)    NULL,
    [DELU]                           VARCHAR (1)    NULL,
    [year]                           NVARCHAR (MAX) NULL,
    [month]                          NVARCHAR (MAX) NULL,
    [day]                            NVARCHAR (MAX) NULL,
    [_DLRawZoneTimeStamp]            DATETIME       NULL,
    [_DLTrustedZoneTimeStamp]        DATETIME       NULL,
    [_RecordStart]                   DATETIME       NULL,
    [_RecordEnd]                     DATETIME       NULL,
    [_RecordDeleted]                 INT            NULL,
    [_RecordCurrent]                 INT            NULL
);

