CREATE TABLE [edw].[Prada_Unit_UNIT_INSTANCES] (
    [ID_UUI]                    VARCHAR (40)  NULL,
    [ID_UNIT]                   VARCHAR (30)  NULL,
    [INSTITUTE]                 VARCHAR (4)   NULL,
    [UNIT_CATEGORY]             VARCHAR (10)  NULL,
    [CTYPE_CALENDAR_TYPE_CODE]  VARCHAR (10)  NULL,
    [FES_UNIT_INSTANCE_CODE]    VARCHAR (25)  NULL,
    [FES_ACTIVE]                VARCHAR (3)   NULL,
    [FES_ENROL_FLAG]            VARCHAR (3)   NULL,
    [FES_SHORT_DESCRIPTION]     VARCHAR (50)  NULL,
    [FES_LONG_DESCRIPTION]      VARCHAR (200) NULL,
    [TGA_COURSE_NAME]           VARCHAR (200) NULL,
    [FES_STATUS]                VARCHAR (15)  NULL,
    [RELEASE_NUM]               VARCHAR (4)   NULL,
    [ANIMAL_USE]                NUMERIC (18)  NULL,
    [ANIMAL_USE_DESCRIPTION]    VARCHAR (50)  NULL,
    [PRODUCT_SUBJECT]           VARCHAR (200) NULL,
    [UI_ID]                     NUMERIC (18)  NULL,
    [UI_TYPE]                   VARCHAR (3)   NULL,
    [NZSCED]                    VARCHAR (8)   NULL,
    [GRADING_SCHEME_ID]         NUMERIC (18)  NULL,
    [VERSION_NUMBER]            NUMERIC (18)  NULL,
    [MAXIMUM_HOURS]             NUMERIC (18)  NULL,
    [STEM_VALUE]                VARCHAR (25)  NULL,
    [UI_LEVEL]                  VARCHAR (10)  NULL,
    [RAM_CATEGORY]              VARCHAR (4)   NULL,
    [IS_VET_FEE_HELP]           VARCHAR (3)   NULL,
    [IS_FEE_HELP]               VARCHAR (3)   NULL,
    [IS_BOS_COURSE]             VARCHAR (3)   NULL,
    [ANZSIC_NUM]                VARCHAR (8)   NULL,
    [COURSE_OCCUPATION]         VARCHAR (10)  NULL,
    [INTERNATIONAL_COURSE_CODE] VARCHAR (20)  NULL,
    [NATIONAL_COURSE_CODE]      VARCHAR (25)  NULL,
    [COURSE_CODE]               VARCHAR (25)  NULL,
    [TAFE_COURSE_CODE]          VARCHAR (25)  NULL,
    [COURSE_EFTSL_FACTOR]       NUMERIC (18)  NULL,
    [IS_VOCATIONAL]             VARCHAR (3)   NULL,
    [ANZSIC_NAM]                VARCHAR (100) NULL,
    [ANZSCO_NAM]                VARCHAR (100) NULL,
    [FIELD_OF_EDUCATION_NAM]    VARCHAR (100) NULL,
    [RAM_NAM]                   VARCHAR (30)  NULL,
    [PROGRAM_AREA_NUM]          VARCHAR (4)   NULL,
    [SPONSOR_NUM]               VARCHAR (4)   NULL,
    [PROGRAM_AREA_NAM]          VARCHAR (50)  NULL,
    [SPONSOR_NAM]               VARCHAR (50)  NULL,
    [RECOMMENDED_USAGE]         VARCHAR (20)  NULL,
    [EXTRACT_DATE]              NUMERIC (18)  NULL,
    [SCOPE_APPROVED]            VARCHAR (1)   NULL,
    [LOAD_DATE]                 DATE          NULL,
    [UPDATE_DATE]               DATE          NULL,
    [_DLRawZoneTimeStamp]       DATETIME      NULL,
    [_DLTrustedZoneTimeStamp]   DATETIME      NULL
);

