CREATE TABLE [edw].[Prada_Unit_COURSE_ENROLMENTS] (
    [ID_PC]                        NUMERIC (18)    NULL,
    [ID_UIO]                       NUMERIC (18)    NULL,
    [ID_CPU]                       NUMERIC (18)    NULL,
    [ID_FAC]                       NUMERIC (18)    NULL,
    [INSTITUTE]                    NUMERIC (18)    NULL,
    [CALOCC_CODE]                  VARCHAR (10)    NULL,
    [COMMITMENT_IDENTIFIER]        VARCHAR (12)    NULL,
    [DATE_OFFER_START]             DATE            NULL,
    [DATE_OFFER_END]               DATE            NULL,
    [DATE_AWARDED]                 DATE            NULL,
    [FES_MOA_CODE]                 VARCHAR (10)    NULL,
    [FES_UNIT_INSTANCE_CODE]       VARCHAR (25)    NULL,
    [FES_YEAR_ACHIEVED]            NUMERIC (18)    NULL,
    [NZ_FUNDING]                   VARCHAR (5)     NULL,
    [OFFERING_TYPE]                VARCHAR (10)    NULL,
    [PROGRESS_CODE]                VARCHAR (10)    NULL,
    [PROGRESS_REASON]              VARCHAR (60)    NULL,
    [PROGRESS_STATUS]              VARCHAR (1)     NULL,
    [YEAR_GRADUATED]               NUMERIC (18)    NULL,
    [client_id_pu]                 VARCHAR (10)    NULL,
    [delivery_loc]                 VARCHAR (10)    NULL,
    [program_id]                   VARCHAR (10)    NULL,
    [COURSE10]                     VARCHAR (10)    NULL,
    [year_award_completed]         NUMERIC (18)    NULL,
    [award_flag]                   VARCHAR (1)     NULL,
    [enrolcountpu]                 NUMERIC (18)    NULL,
    [progress_rank]                NUMERIC (18)    NULL,
    [CLIENT_ID]                    VARCHAR (10)    NULL,
    [FUNDING_NAT]                  VARCHAR (2)     NULL,
    [ENROLCOUNT]                   NUMERIC (18)    NULL,
    [validtot]                     NUMERIC (18)    NULL,
    [validunitflag]                NUMERIC (18)    NULL,
    [STARTYY]                      VARCHAR (10)    NULL,
    [ENDYY]                        VARCHAR (10)    NULL,
    [RES_COUNTRY]                  VARCHAR (50)    NULL,
    [hqual]                        NUMERIC (18)    NULL,
    [NUM]                          NUMERIC (18)    NULL,
    [AGEGRP]                       VARCHAR (17)    NULL,
    [course_code]                  VARCHAR (10)    NULL,
    [UNIT_CATEGORY]                VARCHAR (8)     NULL,
    [STATUS]                       VARCHAR (14)    NULL,
    [RAM_CATEGORY]                 VARCHAR (4)     NULL,
    [TRAINING_PACKAGE_NUM]         VARCHAR (10)    NULL,
    [PM]                           NUMERIC (18)    NULL,
    [HIGHED]                       NUMERIC (18)    NULL,
    [SL15V2FLAG]                   VARCHAR (1)     NULL,
    [AWARD]                        VARCHAR (2)     NULL,
    [AWDNM]                        VARCHAR (48)    NULL,
    [CSENM]                        VARCHAR (100)   NULL,
    [FOE4]                         VARCHAR (4)     NULL,
    [RAM]                          NUMERIC (18)    NULL,
    [ANZSCO]                       VARCHAR (6)     NULL,
    [ISC]                          VARCHAR (34)    NULL,
    [NEWCSE]                       VARCHAR (10)    NULL,
    [ORDER]                        NUMERIC (18)    NULL,
    [trnghrs]                      NUMERIC (18)    NULL,
    [rplhrs]                       NUMERIC (18)    NULL,
    [totalhrs]                     NUMERIC (18)    NULL,
    [out71hrs]                     NUMERIC (18)    NULL,
    [GRADTOT]                      NUMERIC (18)    NULL,
    [ENRFLAG]                      NUMERIC (18)    NULL,
    [ENROLMENT_YEAR]               VARCHAR (4)     NULL,
    [GRAD]                         NUMERIC (18)    NULL,
    [res_postcode]                 NUMERIC (18)    NULL,
    [RESLGA]                       NUMERIC (18)    NULL,
    [pcnam]                        VARCHAR (43)    NULL,
    [lganam]                       VARCHAR (20)    NULL,
    [FUND]                         VARCHAR (5)     NULL,
    [COREFND]                      VARCHAR (1)     NULL,
    [functional_unit]              VARCHAR (30)    NULL,
    [SKILLSLIST]                   VARCHAR (1)     NULL,
    [CITIZENSHIP]                  NUMERIC (18)    NULL,
    [apprtrainee]                  VARCHAR (1)     NULL,
    [at_school]                    VARCHAR (1)     NULL,
    [labour_force]                 VARCHAR (4)     NULL,
    [res_suburb]                   VARCHAR (50)    NULL,
    [res_state]                    VARCHAR (3)     NULL,
    [prior_ed]                     VARCHAR (1)     NULL,
    [year_commence]                NUMERIC (18)    NULL,
    [year_complete]                NUMERIC (18)    NULL,
    [month_complete]               NUMERIC (18)    NULL,
    [COMMENCE_FLAG]                VARCHAR (1)     NULL,
    [REENROL_END]                  VARCHAR (5)     NULL,
    [fee_type]                     VARCHAR (1)     NULL,
    [LOCALITY]                     VARCHAR (50)    NULL,
    [LPC]                          VARCHAR (54)    NULL,
    [SA_STATE]                     VARCHAR (3)     NULL,
    [SA2_CODE]                     VARCHAR (10)    NULL,
    [SA2_NAME]                     VARCHAR (35)    NULL,
    [LGA_CODE]                     VARCHAR (10)    NULL,
    [LGA_NAME]                     VARCHAR (35)    NULL,
    [LGA4]                         NUMERIC (18)    NULL,
    [LGANM]                        VARCHAR (35)    NULL,
    [SA4_CODE]                     NUMERIC (18)    NULL,
    [SA4_NAME]                     VARCHAR (38)    NULL,
    [SSREGION]                     VARCHAR (40)    NULL,
    [ARIA11]                       VARCHAR (25)    NULL,
    [ARIA11B]                      VARCHAR (15)    NULL,
    [REGIONAL11]                   NUMERIC (18)    NULL,
    [RIND11]                       VARCHAR (19)    NULL,
    [HQUALN]                       VARCHAR (25)    NULL,
    [SECED]                        VARCHAR (20)    NULL,
    [DELIVERY_MODE_CSE]            VARCHAR (10)    NULL,
    [AVFUND]                       NUMERIC (18)    NULL,
    [JOB]                          VARCHAR (26)    NULL,
    [STSFUND]                      VARCHAR (3)     NULL,
    [STSFUNDGROUP]                 VARCHAR (3)     NULL,
    [LOADING]                      NUMERIC (18, 2) NULL,
    [EXTRACT_DATE]                 VARCHAR (10)    NULL,
    [SL15V3FLAG]                   VARCHAR (1)     NULL,
    [ID_NCC]                       VARCHAR (25)    NULL,
    [AGE]                          NUMERIC (18)    NULL,
    [FEE_ORIGINAL]                 SMALLMONEY      NULL,
    [FEE_ACTUAL]                   SMALLMONEY      NULL,
    [FEE_PAID]                     SMALLMONEY      NULL,
    [WAIVER_CODES]                 VARCHAR (50)    NULL,
    [AWARD_DESCRIPTION]            VARCHAR (75)    NULL,
    [AWARD_ID]                     NUMERIC (18)    NULL,
    [WHO_TO_PAY]                   VARCHAR (20)    NULL,
    [FINALTOT]                     NUMERIC (18)    NULL,
    [UNITTOT]                      NUMERIC (18)    NULL,
    [FINALENROL]                   VARCHAR (3)     NULL,
    [SHELL_ENROL]                  VARCHAR (1)     NULL,
    [PROGRESS_DATE]                DATE            NULL,
    [PASSTOT]                      NUMERIC (18)    NULL,
    [FAILTOT]                      NUMERIC (18)    NULL,
    [WDRAWTOT]                     NUMERIC (18)    NULL,
    [REPORT_DATE]                  VARCHAR (10)    NULL,
    [avetcount]                    NUMERIC (18)    NULL,
    [POPULATION]                   NUMERIC (18)    NULL,
    [SCORE]                        NUMERIC (18)    NULL,
    [RANK]                         NUMERIC (18)    NULL,
    [DECILE]                       NUMERIC (18)    NULL,
    [PERCENTILE]                   NUMERIC (18)    NULL,
    [SL16V4FLAG]                   VARCHAR (1)     NULL,
    [LOAD_DATE]                    DATE            NULL,
    [MIN_CORE]                     NUMERIC (18)    NULL,
    [MIN_UOC]                      NUMERIC (18)    NULL,
    [SPONSOR_ORG_CODE]             VARCHAR (50)    NULL,
    [CTONLY]                       VARCHAR (1)     NULL,
    [RPLONLY]                      VARCHAR (1)     NULL,
    [SS_STATUS]                    VARCHAR (20)    NULL,
    [SS_SUBSIDY_AMOUNT]            SMALLMONEY      NULL,
    [SS_STANDARD_SUBSIDY_AMOUNT]   SMALLMONEY      NULL,
    [SS_LOADING_NEEDS]             SMALLMONEY      NULL,
    [SS_LOADING_LOC]               SMALLMONEY      NULL,
    [TRAINING_CONTRACT_IDENTIFIER] VARCHAR (10)    NULL,
    [SS_PROGRAM_STREAM]            VARCHAR (70)    NULL,
    [FEE_INSTALMENT]               SMALLMONEY      NULL,
    [FEE_ADJUSTMENT]               SMALLMONEY      NULL,
    [FEE_OUTSTANDING]              SMALLMONEY      NULL,
    [DATE_COMMENCE_SEMESTER]       VARCHAR (10)    NULL,
    [sem1totunit]                  NUMERIC (8)     NULL,
    [sem2totunit]                  NUMERIC (8)     NULL,
    [sem3totunit]                  NUMERIC (8)     NULL,
    [sem1totash]                   NUMERIC (8)     NULL,
    [sem2totash]                   NUMERIC (8)     NULL,
    [DELIVERY_MODE_UNIT]           VARCHAR (4)     NULL,
    [AVETMISS_FLAG]                VARCHAR (1)     NULL,
    [LTU_EVIDENCE]                 VARCHAR (1)     NULL,
    [WELFARE_STATUS]               VARCHAR (1)     NULL,
    [TOL]                          VARCHAR (1)     NULL,
    [TNW]                          VARCHAR (1)     NULL,
    [TAFE_DIGITAL]                 VARCHAR (1)     NULL,
    [STUDCTR]                      VARCHAR (1)     NULL,
    [VFH_COURSE]                   VARCHAR (1)     NULL,
    [FEE_HELP_FLAG]                VARCHAR (1)     NULL,
    [VSL_FLAG]                     VARCHAR (1)     NULL,
    [SUBSIDY_ADJUSTMENT]           NUMERIC (18)    NULL,
    [TRANSITIONED_FROM_ID]         NUMERIC (18)    NULL,
    [TRANSITIONED_FROM]            VARCHAR (20)    NULL,
    [TRANSITIONED_FROM_CALOCC]     VARCHAR (10)    NULL,
    [ORIGINAL_START_DATE]          DATE            NULL,
    [REGION]                       VARCHAR (25)    NULL,
    [OPEN]                         VARCHAR (1)     NULL,
    [OTEN]                         VARCHAR (1)     NULL,
    [overseas]                     VARCHAR (1)     NULL,
    [AWARD_STATUS]                 VARCHAR (20)    NULL,
    [FY]                           VARCHAR (1)     NULL,
    [CY]                           VARCHAR (1)     NULL,
    [SKILLSPOINT]                  VARCHAR (4)     NULL,
    [TRANSITION_FLAG]              VARCHAR (1)     NULL,
    [TRANCOUNT]                    VARCHAR (1)     NULL,
    [STUDY_REASON]                 VARCHAR (5)     NULL,
    [FUNDING_VFH]                  VARCHAR (35)    NULL,
    [WORKS_IN_NSW]                 VARCHAR (240)   NULL,
    [EMP_ALT_ORG_NAME]             VARCHAR (100)   NULL,
    [EMP_ALT_EMPLOYER_SUBURB]      VARCHAR (20)    NULL,
    [EMP_POSTCODE]                 VARCHAR (4)     NULL,
    [EMP_ORG_CODE]                 VARCHAR (30)    NULL,
    [EMP_ORG_TYPE]                 VARCHAR (100)   NULL,
    [EMPLOYER]                     VARCHAR (100)   NULL,
    [SEM]                          VARCHAR (1)     NULL,
    [ONLMTOTUNIT]                  NUMERIC (8)     NULL,
    [SBI_GROUP]                    VARCHAR (50)    NULL,
    [SBI_CATEGORY]                 VARCHAR (75)    NULL,
    [SBI_SUBCATEGORY]              VARCHAR (100)   NULL,
    [_DLRawZoneTimeStamp]          DATETIME        NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME        NULL
);

