CREATE TABLE [edw].[reference_master_reference_data] (
    [Seq_No]                  INT             NULL,
    [REFID]                   INT             NULL,
    [TABLE_NAME]              NVARCHAR (34)   NULL,
    [Ref_1]                   NVARCHAR (26)   NULL,
    [Ref_2]                   NVARCHAR (68)   NULL,
    [Ref_3]                   NVARCHAR (236)  NULL,
    [Ref_4]                   NVARCHAR (17)   NULL,
    [Ref_5]                   NVARCHAR (17)   NULL,
    [Ref_6]                   NVARCHAR (14)   NULL,
    [Ref_7]                   NVARCHAR (36)   NULL,
    [Ref_8]                   NVARCHAR (29)   NULL,
    [Ref_9]                   NVARCHAR (60)   NULL,
    [Ref_10]                  NVARCHAR (277)  NULL,
    [Ref_11]                  NVARCHAR (30)   NULL,
    [Ref_12]                  NVARCHAR (34)   NULL,
    [Ref_13]                  NVARCHAR (26)   NULL,
    [Ref_14]                  NVARCHAR (34)   NULL,
    [Ref_15]                  NVARCHAR (26)   NULL,
    [Ref_16]                  NVARCHAR (34)   NULL,
    [Ref_17]                  NVARCHAR (41)   NULL,
    [Ref_18]                  NVARCHAR (123)  NULL,
    [Ref_19]                  NVARCHAR (7)    NULL,
    [Ref_20]                  NVARCHAR (23)   NULL,
    [Ref_21]                  NVARCHAR (24)   NULL,
    [Ref_22]                  NVARCHAR (15)   NULL,
    [Ref_23]                  NVARCHAR (22)   NULL,
    [Ref_24]                  NVARCHAR (31)   NULL,
    [Ref_25]                  NVARCHAR (31)   NULL,
    [Ref_26]                  NVARCHAR (34)   NULL,
    [Ref_27]                  NVARCHAR (6)    NULL,
    [Ref_28]                  NVARCHAR (2000) NULL,
    [Ref_29]                  NVARCHAR (2000) NULL,
    [Ref_30]                  NVARCHAR (2000) NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)   NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)   NULL,
    [_RecordStart]            DATETIME2 (7)   NULL,
    [_RecordEnd]              DATETIME2 (7)   NULL,
    [_RecordCurrent]          INT             NULL,
    [_RecordDeleted]          INT             NULL
);



