CREATE TABLE [edw].[reference_date] (
    [DateKey]                      INT                                                NULL,
    [DateFullName]                 NVARCHAR (13) MASKED WITH (FUNCTION = 'default()') NULL,
    [FullDateAlternateKey]         DATE                                               NULL,
    [YearCode]                     INT                                                NULL,
    [YearDescription]              NVARCHAR (8)                                       NULL,
    [QuarterCode]                  INT                                                NULL,
    [QuarterDescription]           NVARCHAR (6)                                       NULL,
    [QuarterYearCode]              INT                                                NULL,
    [MonthNumberOfYearCode]        INT                                                NULL,
    [MonthYearCode]                INT                                                NULL,
    [MonthName]                    NVARCHAR (11)                                      NULL,
    [MonthYearDescription]         NVARCHAR (16)                                      NULL,
    [MonthLocalizedString]         NVARCHAR (8)                                       NULL,
    [DateLocalizedString]          NVARCHAR (12)                                      NULL,
    [DayNumberOfMonth]             INT                                                NULL,
    [NumberOfDaysInTheMonth]       INT                                                NULL,
    [DayNumberOfYear]              INT                                                NULL,
    [WeekNumberOfYear]             INT                                                NULL,
    [WeekYearCode]                 INT                                                NULL,
    [ISOWeekNumberOfYear]          INT                                                NULL,
    [ISOWeekYearCode]              INT                                                NULL,
    [WeekDay]                      INT                                                NULL,
    [WeekDayName]                  NVARCHAR (11)                                      NULL,
    [FiscalYearCode]               INT                                                NULL,
    [FiscalYearDescription]        NVARCHAR (8)                                       NULL,
    [FiscalQuarterCode]            INT                                                NULL,
    [FiscalQuarterYearCode]        INT                                                NULL,
    [FiscalQuarterDescription]     NVARCHAR (6)                                       NULL,
    [FiscalMonthCode]              INT                                                NULL,
    [FiscalMonthYearCode]          INT                                                NULL,
    [FiscalMonthDescription]       NVARCHAR (9)                                       NULL,
    [FiscalStartDate]              DATE                                               NULL,
    [FiscalEndDate]                DATE                                               NULL,
    [IsWeekDayCode]                INT                                                NULL,
    [IsWeekDayDescription]         NVARCHAR (8)                                       NULL,
    [IsPublicHolidayCode]          INT                                                NULL,
    [IsPublicHolidayDescription]   NVARCHAR (13)                                      NULL,
    [PublicHolidayFullDescription] NVARCHAR (25)                                      NULL,
    [CurrentYear]                  INT                                                NULL,
    [CurrentMonth]                 INT                                                NULL,
    [CurrentDay]                   INT                                                NULL,
    [_DLRawZoneTimeStamp]          DATETIME2 (7)                                      NULL,
    [_DLTrustedZoneTimeStamp]      DATETIME2 (7)                                      NULL,
    [_RecordStart]                 DATETIME2 (7)                                      NULL,
    [_RecordEnd]                   DATETIME2 (7)                                      NULL,
    [_RecordCurrent]               INT                                                NULL,
    [_RecordDeleted]               INT                                                NULL
);





