CREATE TABLE [edw].[UMD_TempTeachersMarks] (
    [Faculty]              VARCHAR (100)                                     NULL,
    [College]              VARCHAR (40)                                      NULL,
    [Teaching_Section]     VARCHAR (100)                                     NULL,
    [YEAR/PERIOD]          INT                                               NULL,
    [First_Name]           VARCHAR (50) MASKED WITH (FUNCTION = 'default()') NULL,
    [Last_Name]            VARCHAR (50) MASKED WITH (FUNCTION = 'default()') NULL,
    [cid]                  VARCHAR (12) MASKED WITH (FUNCTION = 'default()') NULL,
    [pu_id]                BIGINT                                            NULL,
    [PROD_START_DT]        DATETIME2 (7)                                     NULL,
    [PROD_END_DT]          DATETIME2 (7)                                     NULL,
    [PROD_CODE]            VARCHAR (20)                                      NULL,
    [PROD_NAME]            VARCHAR (100)                                     NULL,
    [PROD_CALOCC]          VARCHAR (10)                                      NULL,
    [LEARNER_NO]           VARCHAR (124)                                     NULL,
    [PRODUCT_OFFER_TYPE]   VARCHAR (10)                                      NULL,
    [unit_code]            VARCHAR (20)                                      NULL,
    [unit_calocc]          VARCHAR (10)                                      NULL,
    [Unit_type]            VARCHAR (40)                                      NULL,
    [Unit_Prog_Code]       VARCHAR (10)                                      NULL,
    [unit_start_dt]        DATETIME2 (7)                                     NULL,
    [unit_end_dt]          DATETIME2 (7)                                     NULL,
    [final_outcome]        VARCHAR (40)                                      NULL,
    [Final_Grade]          VARCHAR (255)                                     NULL,
    [GRADE_CODE]           VARCHAR (10)                                      NULL,
    [GRADING_CODE_DESC]    VARCHAR (240)                                     NULL,
    [UNIT_AWARDED_DATE]    DATETIME2 (7)                                     NULL,
    [UnitOutcome_Status]   VARCHAR (20)                                      NULL,
    [AWARD_STATUS]         VARCHAR (8)                                       NOT NULL,
    [assessment_count]     INT                                               NULL,
    [result_count]         INT                                               NULL,
    [results]              NVARCHAR (MAX)                                    NULL,
    [Teacher]              VARCHAR (MAX)                                     NULL,
    [Region]               VARCHAR (14)                                      NULL,
    [RTO]                  VARCHAR (20)                                      NULL,
    [EReportingPriority]   VARCHAR (1)                                       NOT NULL,
    [SWSI CLAIMABLE]       VARCHAR (13)                                      NOT NULL,
    [1220 Only]            INT                                               NULL,
    [CLAIM_STATUS]         VARCHAR (20)                                      NULL,
    [Prod_Prog_Reason]     VARCHAR (10)                                      NULL,
    [UNIT_PROGRESS_REASON] VARCHAR (40)                                      NULL,
    [uio_id]               BIGINT                                            NULL,
    [SLOC_LOCATION_CODE]   VARCHAR (10)                                      NULL,
    [PERSON_CODE]          BIGINT                                            NULL,
    [course_id]            BIGINT                                            NULL,
    [SkillsPoint]          VARCHAR (100)                                     NULL,
    [ADLogin]              VARCHAR (MAX)                                     NULL,
    [InsertedDate]         DATETIME                                          CONSTRAINT [DF_TempTeachersMarks_InsertedDate] DEFAULT (getdate()) NULL
);



