CREATE TABLE [edw].[UMD_FactUnenteredMarks] (
    [SkillsTeam]                  VARCHAR (100)                                      NULL,
    [College]                     VARCHAR (40)                                       NULL,
    [TeachingSection]             VARCHAR (100)                                      NULL,
    [CourseProductDescription]    VARCHAR (100)                                      NULL,
    [CourseProductCode]           VARCHAR (20)                                       NULL,
    [CourseCaloccCode]            VARCHAR (20)                                       NULL,
    [CourseProgressCode]          VARCHAR (20)                                       NULL,
    [CourseProgressReason]        VARCHAR (40)                                       NULL,
    [CourseStartDate]             DATE                                               NULL,
    [CourseEndDate]               DATE                                               NULL,
    [CourseOfferType]             VARCHAR (20)                                       NULL,
    [YearPeriod]                  INT                                                NULL,
    [eReportingPriority]          INT                                                NULL,
    [SWSiClaimable]               VARCHAR (20)                                       NULL,
    [CId]                         VARCHAR (20) MASKED WITH (FUNCTION = 'default()')  NULL,
    [ClaimStatus]                 VARCHAR (20)                                       NULL,
    [1220Only]                    CHAR (1)                                           NULL,
    [PUId]                        BIGINT                                             NULL,
    [LearnerNumber]               VARCHAR (20)                                       NULL,
    [FirstName]                   VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [LastName]                    VARCHAR (50) MASKED WITH (FUNCTION = 'default()')  NULL,
    [UnitProductCode]             VARCHAR (20)                                       NULL,
    [UnitCaloccCode]              VARCHAR (20)                                       NULL,
    [UnitType]                    VARCHAR (20)                                       NULL,
    [UnitProgressCode]            VARCHAR (20)                                       NULL,
    [UnitProgressReason]          VARCHAR (40)                                       NULL,
    [UnitStartDate]               DATE                                               NULL,
    [UnitEndDate]                 DATE                                               NULL,
    [FinalOutcome]                INT                                                NULL,
    [FinalGrade]                  VARCHAR (30)                                       NULL,
    [GradeCode]                   INT                                                NULL,
    [GradingCodeDescription]      VARCHAR (30)                                       NULL,
    [UnitAwardedDate]             DATE                                               NULL,
    [UnitOutcomeStatus]           VARCHAR (20)                                       NULL,
    [AwardStatus]                 VARCHAR (20)                                       NULL,
    [AssessmentCount]             INT                                                NULL,
    [ResultCount]                 INT                                                NULL,
    [Results]                     VARCHAR (1000)                                     NULL,
    [TeachersAssigned]            VARCHAR (MAX)                                      NULL,
    [Teacher]                     VARCHAR (MAX)                                      NULL,
    [Region]                      VARCHAR (40)                                       NULL,
    [RTOName]                     VARCHAR (60)                                       NULL,
    [DeliveryLocationDescription] VARCHAR (10)                                       NULL,
    [Latitude]                    DECIMAL (9, 6)                                     NULL,
    [Longitude]                   DECIMAL (9, 6)                                     NULL,
    [UnitEndDateAgeing]           INT                                                NULL,
    [CourseFundingSource]         VARCHAR (20)                                       NULL,
    [TeacherADUserName]           VARCHAR (MAX) MASKED WITH (FUNCTION = 'default()') NULL,
    [TeacherADEmail]              VARCHAR (MAX) MASKED WITH (FUNCTION = 'default()') NULL,
    [InsertedDate]                DATETIME                                           CONSTRAINT [DF_FactUnenteredMarks_InsertedDate] DEFAULT (getdate()) NULL
);



