CREATE TABLE [edw].[VCPexip_participant] (
    [av_id]                   NVARCHAR (MAX)                                      NULL,
    [bandwidth]               BIGINT                                              NULL,
    [call_direction]          NVARCHAR (MAX)                                      NULL,
    [call_quality]            NVARCHAR (MAX)                                      NULL,
    [call_uuid]               NVARCHAR (MAX)                                      NULL,
    [conference]              NVARCHAR (MAX)                                      NULL,
    [conference_name]         NVARCHAR (MAX)                                      NULL,
    [conversation_id]         NVARCHAR (MAX)                                      NULL,
    [disconnect_reason]       NVARCHAR (MAX)                                      NULL,
    [display_name]            NVARCHAR (MAX)                                      NULL,
    [duration]                BIGINT                                              NULL,
    [encryption]              NVARCHAR (MAX)                                      NULL,
    [end_time]                DATETIME                                            NULL,
    [has_media]               BIT                                                 NULL,
    [id]                      NVARCHAR (MAX)                                      NULL,
    [is_streaming]            BIT                                                 NULL,
    [license_count]           BIGINT                                              NULL,
    [license_type]            NVARCHAR (MAX)                                      NULL,
    [local_alias]             NVARCHAR (MAX)                                      NULL,
    [media_node]              NVARCHAR (MAX)                                      NULL,
    [parent_id]               NVARCHAR (MAX)                                      NULL,
    [presentation_id]         NVARCHAR (MAX)                                      NULL,
    [protocol]                NVARCHAR (MAX)                                      NULL,
    [proxy_node]              NVARCHAR (MAX)                                      NULL,
    [remote_address]          NVARCHAR (MAX) MASKED WITH (FUNCTION = 'default()') NULL,
    [remote_alias]            NVARCHAR (MAX)                                      NULL,
    [remote_port]             BIGINT                                              NULL,
    [resource_uri]            NVARCHAR (MAX)                                      NULL,
    [role]                    NVARCHAR (MAX)                                      NULL,
    [service_tag]             NVARCHAR (MAX)                                      NULL,
    [service_type]            NVARCHAR (MAX)                                      NULL,
    [signalling_node]         NVARCHAR (MAX)                                      NULL,
    [start_time]              NVARCHAR (MAX)                                      NULL,
    [system_location]         NVARCHAR (MAX)                                      NULL,
    [vendor]                  NVARCHAR (MAX)                                      NULL,
    [year]                    NVARCHAR (MAX)                                      NULL,
    [month]                   NVARCHAR (MAX)                                      NULL,
    [day]                     NVARCHAR (MAX)                                      NULL,
    [_DLRawZoneTimeStamp]     DATETIME2 (7)                                       NULL,
    [_DLTrustedZoneTimeStamp] DATETIME2 (7)                                       NULL,
    [_RecordStart]            DATETIME2 (7)                                       NULL,
    [_RecordEnd]              DATETIME2 (7)                                       NULL,
    [_RecordDeleted]          INT                                                 NULL,
    [_RecordCurrent]          INT                                                 NULL
);





