

Create   view [OneEBS].[Addresses] AS  
Select [OWNER_REF]
      ,[OWNER_TYPE]
      ,[ADDRESS_CODE]
      ,[ADDRESS_TYPE]
      ,[START_DATE]
      ,[END_DATE]
      ,[ADDRESS_LINE_1]
      ,[ADDRESS_LINE_2]
      ,[ADDRESS_LINE_3]
      ,[ADDRESS_LINE_4]
      ,[ADDRESS_LINE_5]
      ,[TOWN]
      ,[TELEPHONE]
      ,[UK_POST_CODE_PT1]
      ,[UK_POST_CODE_PT2]
      ,[INTERNATIONAL_POST_CODE]
      ,[FAX]
      ,[REGION]
      ,[COUNTRY]
      ,[EMAIL_ADDRESS]
      ,[EXTENSION_TEL_NO]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[MAILSORT_CODE]
      ,[FES_CONTACT_NAME]
      ,[FES_TELEPHONE_LINE_2]
      ,[EASTING]
      ,[NORTHING]
      ,[NOTES_ID]
      ,[OLIB_ADDRNO]
      ,[PERSON_CODE]
      ,[UCAS_RECORD]
      ,[UCAS_RD_NUMBER]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[ACCOMMODATION_TYPE]
      ,[REGION_AREA]
      ,[FUNDING_YEAR]
      ,[INSTITUTION_CONTEXT_ID]
      ,[UNIQUE_DELIVERY_POINT_REF_NO]
      ,[LOCATION_TYPE]
      ,[COUNTRY_CODE]
      ,[LATITUDE]
      ,[LONGITUDE]
      ,[TERRITORIAL_AUTHORITY_CODE] from edw.OneEBS_EBS_0165_ADDRESSES 
	  WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)