
Create   view [OneEBS].[Awards] AS  
Select [ID]
      ,[CODE]
      ,[TITLE]
      ,[DESCRIPTION]
      ,[SDR_QUALIFICATION_CODE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[USER_11]
      ,[USER_12]
      ,[IS_ACTIVE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[COURSE_CREDITS]
      ,[SDR_REGISTER_LEVEL]
      ,[TRANSCRIPT_ID]
      ,[AWARD_CATEGORY_CODE]
      ,[GRADING_SCHEME_ID]
      ,[NATIONAL_CODE]
      ,[SPECIALISATION]
      ,[CONFIGURABLE_STATUS_ID]
      ,[PUBLISHED]
      ,[REGULATION_SCHEME_ID]
      ,[INSTITUTION_CONTEXT_ID]
      ,[COUNT_OUTCOMES_MULTIPLE_TIMES] 
from edw.OneEBS_EBS_0165_AWARDS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)