CREATE VIEW OneEBS.Calendar_Occurences
AS
SELECT [INSTITUTION_CONTEXT_ID]
      ,[LOCATION_CODE]
      ,[CTYPE_CALENDAR_TYPE_CODE]
      ,[OCCURRENCE_CODE]
      ,[START_DATE]
      ,[END_DATE]
      ,[FES_SHORT_DESCRIPTION]
      ,[FES_LONG_DESCRIPTION]
      ,[ROLL_FWD_CALOCC_CODE]
      ,[ROLL_FORWARD]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
  FROM [edw].[OneEBS_EBS_0165_CALENDAR_OCCURRENCES]
  WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)