
Create   view [OneEBS].[Configurable_Statuses] AS  
Select [INSTITUTION_CONTEXT_ID]
      ,[INCLUDE_IN_DATA_RETURN]
      ,[ID]
      ,[STATUS_CODE]
      ,[SHORT_DESCRIPTION]
      ,[LONG_DESCRIPTION]
      ,[ACTIVE]
      ,[CONTRIBS_COURSE_OUTCOMES]
      ,[LEARNER_VIEWABLE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[LINKED_ROLE]
      ,[STATUS_TYPE]
      ,[CONTRIBS_AWARD_OUTCOMES]
      ,[SUBMIT_TO_NZQA]
      ,[INCLUDED_IN_SDR]
      ,[BAD_DEBT_CHECK]
      ,[IS_PUBLISHABLE]
      ,[CAN_UPDATE_PROGRESS] 
from edw.OneEBS_EBS_0165_CONFIGURABLE_STATUSES 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)