
Create   view [OneEBS].[Course_Assessments] AS  
Select [ID]
      ,[OBJECT_TYPE]
      ,[OBJECT_ID]
      ,[DESCRIPTION]
      ,[CRS_ASSESSMENT_TYPE]
      ,[HE_ASSESSMENT_SEQUENCE]
      ,[WEIGHTING_PERCENT]
      ,[DUE_DATE]
      ,[GRADING_SCHEME_ID]
      ,[NZQA_ID]
      ,[LOCATION_CODE]
      ,[OWNING_ORGANISATION]
      ,[REQUIRED_THEORY_HOURS]
      ,[REQUIRED_PRACTICAL_HOURS]
      ,[PLANNED_START_DATE]
      ,[PLANNED_END_DATE]
      ,[NUMBER_OF_RESITS]
      ,[ALLOW_AEGROTATS]
      ,[ALLOW_EXTENSIONS]
      ,[FES_ACTIVE]
      ,[FES_USER_1]
      ,[FES_USER_2]
      ,[FES_USER_3]
      ,[FES_USER_4]
      ,[FES_USER_5]
      ,[FES_USER_6]
      ,[FES_USER_7]
      ,[FES_USER_8]
      ,[FES_USER_9]
      ,[FES_USER_10]
      ,[FES_USER_11]
      ,[FES_USER_12]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[MARKS_OUT_OF]
      ,[MUST_PASS]
      ,[ASSESSMENT_CODE]
      ,[IS_MANDATORY]
      ,[MIN_PASS_MARK]
      ,[MANDATORY_ENROL]
      ,[REQUIRES_OUTCOME]
      ,[ASSESSMENT_INSTRUCTIONS]
      ,[ASSESSOR_INSTRUCTIONS]
      ,[HAS_BEST_RESULT]
      ,[INSTITUTION_CONTEXT_ID]
      ,[SORT_ORDER] 
from edw.OneEBS_EBS_0165_COURSE_ASSESSMENTS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)