
Create   view [OneEBS].[Disabilities] AS  
Select [ID]
      ,[DISABILITY_TYPE]
      ,[PER_PERSON_CODE]
      ,[START_DATE]
      ,[END_DATE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[ASSESSMENT_ID]
      ,[FES_ISR_DISABILITY]
      ,[FES_LONG_DESCRIPTION]
      ,[FES_SHORT_DESCRIPTION]
      ,[NOTES_ID]
      ,[PRIMARY_NEED]
      ,[SPECIAL_EXAM_NEEDS]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[USER_11]
      ,[USER_12]
      ,[USER_13]
      ,[USER_14]
      ,[USER_15]
      ,[USER_16]
      ,[USER_17]
      ,[USER_18]
      ,[USER_19]
      ,[USER_20]
      ,[USER_21]
      ,[USER_22]
      ,[USER_23]
      ,[USER_24]
      ,[USER_25]
      ,[USER_26]
      ,[USER_27]
      ,[USER_28]
      ,[USER_29]
      ,[USER_30]
      ,[USER_31]
      ,[USER_32]
      ,[IS_ASSISTANCE_REQUIRED]
      ,[INSTITUTION_CONTEXT_ID]
      ,[DATA_RETURN] 
from edw.OneEBS_EBS_0165_DISABILITIES 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)