
Create   view [OneEBS].[Fee_Types] AS  
Select [FEE_TYPE_CODE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[TUITION_TYPE_FEE]
      ,[FES_SHORT_DESCRIPTION]
      ,[FES_LONG]
      ,[FES_VAT_CODE]
      ,[FES_ACCOUNT_CODE]
      ,[FES_TRANSACTION_TYPE]
      ,[FES_ISR]
      ,[LATE_FEE]
      ,[REFERRAL_FEE]
      ,[PRIORITY]
      ,[INCLUDE_IN_RETURN]
      ,[SDR_TYPE]
      ,[ALLOW_REFUND]
      ,[ROUNDING_MULTIPLE]
      ,[MIN_VALUE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[CHARGE_ONCE]
      ,[ROLE_DEFS_ID]
      ,[IS_ENFORCEABLE_DEBT]
      ,[IS_TEMP_VISA_HOLDER_FEE]
      ,[ENROLMENT_DURATION]
      ,[IS_ELIGIBLE_FOR_INSTALMENTS]
      ,[IS_GIFT]
      ,[GL_COMPONENT_1]
      ,[GL_COMPONENT_2]
      ,[GL_COMPONENT_3]
      ,[GL_COMPONENT_4]
      ,[FEE_CATEGORY_CODE]
      ,[IS_ACTIVE]
      ,[INSTITUTION_CONTEXT_ID]
      ,[IS_ELIGIBLE_FOR_FEES_FREE] 
from edw.OneEBS_EBS_0165_FEE_TYPES 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)