
Create   view [OneEBS].[Fees_List_Special] AS  
Select [ID]
      ,[FEES_LIST_ID]
      ,[BANK_ID]
      ,[ACCOUNT_NAME]
      ,[CHEQUE_NUMBER]
      ,[CARD_TYPE]
      ,[CARD_HOLDER_NAME]
      ,[STATEMENT_DETAILS]
      ,[REFERENCE_NUMBER]
      ,[DATE_BANKED]
      ,[GL_ACCOUNT]
      ,[COST_CENTRE]
      ,[SUB_ACCOUNT]
      ,[AUTHORISED_BY]
      ,[PAYER_AUTHORISATION_NO]
      ,[DEBTOR_NAME]
      ,[DEBTOR_ID]
      ,[PAYEE_NAME]
      ,[SWIFT_NUMBER]
      ,[NOTES_ID]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[ELECTRONIC_PAYMENT_REF_NO]
      ,[INSTITUTION_CONTEXT_ID] 
from edw.OneEBS_EBS_0165_FEES_LIST_SPECIAL 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)