
Create   view [OneEBS].[Locations] AS  
Select [INSTITUTION_CONTEXT_ID]
      ,[COUNTRY_CODE]
      ,[IS_AVAILABLE_IN_ESP]
      ,[ORGANISATION_CODE]
      ,[ADDRESS_LINE_3]
      ,[ADDRESS_LINE_4]
      ,[TOWN]
      ,[REGION]
      ,[UK_POST_CODE_PT1]
      ,[UK_POST_CODE_PT2]
      ,[SITE_CODE]
      ,[SP_LOCATION_URL]
      ,[SP_DIRECTIONS_URL]
      ,[FES_ACTIVE]
      ,[INSTCAMP]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[IS_INCIDENT]
      ,[LOCATION_CODE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[FES_SHORT_DESCRIPTION]
      ,[FES_LONG_DESCRIPTION]
      ,[ADDRESS_LINE_1]
      ,[ADDRESS_LINE_2] 
from edw.OneEBS_EBS_0165_LOCATIONS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)