
Create   view [OneEBS].[Notes] AS  
Select [NOTES_ID]
      ,[NOTES]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[NOTES_TOPICS_ID]
      ,[REQUIRES_ACTION]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[USER_11]
      ,[USER_12]
      ,[USER_13]
      ,[USER_14]
      ,[USER_15]
      ,[USER_16]
      ,[USER_17]
      ,[USER_18]
      ,[USER_19]
      ,[USER_20]
      ,[USER_21]
      ,[USER_22]
      ,[USER_23]
      ,[USER_24]
      ,[INSTITUTION_CONTEXT_ID] 
from edw.OneEBS_EBS_0165_NOTES 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)