
Create   view [OneEBS].[Org_Unit_People] AS  
Select [INSTITUTION_CONTEXT_ID]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[INCLUDE_IN_DATA_RETURN]
      ,[PEOPLE_UNITS_ID]
      ,[WORK_PLACEMENT_CONFIRMED_DATE]
      ,[ID]
      ,[ORG_UNIT_CODE]
      ,[PERSON_CODE]
      ,[START_DATE]
      ,[END_DATE]
      ,[ADDRESS_CODE]
      ,[POSITION]
      ,[PRIMARY_CONTACT]
      ,[TYPE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3] 
from edw.OneEBS_EBS_0165_ORG_UNIT_PEOPLE 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)