


CREATE   view [OneEBS].[People_ASR] AS  
Select [HAS_DOC_DEGREE]
      ,[DOC_DEGREE_LOCATION]
      ,[DOC_DEGREE_ACHIEVED_SINCE_17]
      ,[HAS_MSTR_DEGREE]
      ,[MSTR_DEGREE_LOCATION]
      ,[MSTR_DEGREE_ACHIEVED_SINCE_17]
      ,[HAS_GRAD_DIPLOMA]
      ,[GRAD_DIPLOMA_LOCATION]
      ,[GRAD_DIPLOMA_ACHIEVED_SINCE_17]
      ,[ID]
      ,[PERSON_CODE]
      ,[HAS_BACH_OR_HIGHER_DEGREE_008]
      ,[HAS_ADV_DIP_OR_ASSOC_DEG_410]
      ,[HAS_DIP_OR_ASSOC_DIP_420]
      ,[HAS_CERT_IV_OR_AD_CERT_TEC_511]
      ,[HAS_CERT_III_OR_TRADE_CERT_514]
      ,[HAS_CERT_II_521]
      ,[HAS_CERT_I_524]
      ,[HAS_OTHER_CERT_990]
      ,[HOME_TELEPHONE_NUMBER]
      ,[WORK_TELEPHONE_NUMBER]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[INSTITUTION_CONTEXT_ID]
      ,[SURVEY_CONTACT_STATUS] 
from edw.OneEBS_EBS_0165_PEOPLE_ASR 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)