CREATE VIEW OneEBS.People_Units_Avetmiss
AS
SELECT [ID]
      ,[PEOPLE_UNITS_ID]
      ,[TRAINEE_CODE_INTERSTATE]
      ,[MAXIMUM_HOURS_INTERSTATE]
      ,[CLIENT_TUITION_FEE_INTERSTATE]
      ,[FEE_CONCESSION_TYPE_INTERSTATE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[INSTITUTION_CONTEXT_ID]
  FROM [edw].[OneEBS_EBS_0165_PEOPLE_UNITS_AVETMISS]
  where _RecordCurrent = 1 AND _RecordDeleted = 0