
Create   view [OneEBS].[People_Centrelink] AS  
Select [INSTITUTION_CONTEXT_ID]
      ,[FES_USER_1]
      ,[FES_USER_2]
      ,[FES_USER_3]
      ,[FES_USER_4]
      ,[FES_USER_5]
      ,[FES_USER_6]
      ,[FES_USER_7]
      ,[FES_USER_8]
      ,[FES_USER_9]
      ,[FES_USER_10]
      ,[FES_USER_11]
      ,[FES_USER_12]
      ,[ID]
      ,[PERSON_CODE]
      ,[CRN]
      ,[SECONDARY_CRN]
      ,[CRN_CONFIRM_DATE]
      ,[DVA_NO]
      ,[ORG_TYPE]
      ,[CREATED_DATE]
      ,[CREATED_BY]
      ,[UPDATED_DATE]
      ,[UPDATED_BY]
      ,[DVA_CONFIRM_DATE] 
from edw.OneEBS_EBS_0165_PEOPLE_CENTRELINK 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)