
Create   view [OneEBS].[People_Units_Centrelink] AS  
Select [ID]
      ,[PU_ID]
      ,[SOURCE]
      ,[INPUTREFID]
      ,[CRN]
      ,[CNFRMDATE]
      ,[PCC]
      ,[HCC]
      ,[SHC]
      ,[DECEASED]
      ,[BLIND]
      ,[OVER70]
      ,[WAR]
      ,[INST]
      ,[PCODE_PCODEMTCH]
      ,[NUMCHILD]
      ,[SCNDRYCRN]
      ,[PYMTTYPE]
      ,[PYMTSTATUS]
      ,[PYMTSTARTDATE]
      ,[PYMTENDDATE]
      ,[DATEPAIDTO]
      ,[MAXRATE]
      ,[RATERATIO]
      ,[RATETHOLD]
      ,[CUSTID]
      ,[ORGTYPE]
      ,[MTCHCODE]
      ,[GCH]
      ,[FIRSTNAME]
      ,[MIDDLENAME]
      ,[SURNAME]
      ,[DOB]
      ,[ADDR]
      ,[CNFRMID]
      ,[WWP]
      ,[POW]
      ,[DISABILITY]
      ,[SDA]
      ,[EYP]
      ,[MWC]
      ,[OIP]
      ,[SRD]
      ,[WDP]
      ,[APPLY_BENEFIT]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[WAVR_PYMT_ID]
      ,[INSTITUTION_CONTEXT_ID]
 
from edw.OneEBS_EBS_0165_PEOPLE_UNITS_CENTRELINK 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)