
Create   view [OneEBS].[Register_Event_Details] AS  
Select [UPDATED_BY]
      ,[UPDATED_DATE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[UNCONFIRMED_LEARNER]
      ,[ILP_ACTIVE]
      ,[ILP_CAN_OVERRIDE]
      ,[INTERVIEW_PU_ID]
      ,[INTERVIEW_PUG_ID]
      ,[INTERVIEW_STATUS]
      ,[PLANNED_DURATION_TOTAL]
      ,[MARKED_DURATION_TOTAL]
      ,[IS_CONTACT]
      ,[EXTERNAL_DETAIL_REF_NO]
      ,[EXTERNAL_SOURCE]
      ,[DETAIL_STATUS]
      ,[FILLING_METHOD_ID]
      ,[SCHOLASTIC_YEAR]
      ,[ROLL_CLASS]
      ,[INSTITUTION_CONTEXT_ID]
      ,[ID]
      ,[REGISTER_EVENT_ID]
      ,[SESSION_CODE]
      ,[OBJECT_TYPE]
      ,[OBJECT_ID]
      ,[ORGANISATION_CODE]
      ,[CREATEDBY_PERSON_CODE]
      ,[IS_CONFIRMED]
      ,[LOCATION_CODE]
      ,[TUTORGROUP_ID]
      ,[PROGRESS_CODE]
      ,[TEMP_PROGRESS_CODE]
      ,[TEMP_PROGRESS_DATE]
      ,[IS_FOR_LEARNERS]
      ,[IS_FOR_TUTORS]
      ,[IS_FOR_ADMINS]
      ,[PERSON_FUNCTION]
      ,[ROOM_LAYOUT_ID]
      ,[CREATED_BY]
      ,[CREATED_DATE] 
from edw.OneEBS_EBS_0165_REGISTER_EVENT_DETAILS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)