
Create   view [OneEBS].[Register_Events] AS  
Select [HAS_BEEN_MOVED_WHILST_LOCKED]
      ,[REGION_ORGANISATION_UNIT_ID]
      ,[ID]
      ,[SESSION_CODE]
      ,[EVENT_TYPE]
      ,[EVENT_CODE]
      ,[DESCRIPTION]
      ,[LEAD_MARKING]
      ,[REGISTER_WEEK_PATTERNS_ID]
      ,[REQUIRES_ATTENTION]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[PROVIDER_ORGANISATION_CODE]
      ,[IS_FOR_EMA]
      ,[REGISTER_TYPE]
      ,[REGISTER_TYPE_START_DATE]
      ,[INSTITUTION_CONTEXT_ID]
      ,[TIMETABLES_ID] 
from edw.OneEBS_EBS_0165_REGISTER_EVENTS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)