
Create   view [OneEBS].[Register_Event_Details_Slots] AS  
Select [INSTITUTION_CONTEXT_ID]
      ,[ID]
      ,[REGISTER_EVENT_ID]
      ,[REGISTER_EVENT_DETAIL_ID]
      ,[SESSION_CODE]
      ,[REGISTER_EVENT_SLOT_ID]
      ,[OBJECT_TYPE]
      ,[OBJECT_ID]
      ,[PLANNED_START_DATE]
      ,[PLANNED_END_DATE]
      ,[BREAK]
      ,[ACTUAL_START_DATE]
      ,[ACTUAL_END_DATE]
      ,[ADDITIONAL_TIME]
      ,[USAGE_CODE]
      ,[CONTRACT_ID]
      ,[CONTRACT_STATUS_ID]
      ,[AMOUNT_CLAIMED]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[HAS_MESSAGE_BEEN_SENT]
      ,[ASSOCIATED_BEHAVIOUR_ID]
      ,[IS_ABSENCE_JUSTIFIED] 
from edw.OneEBS_EBS_0165_REGISTER_EVENT_DETAILS_SLOTS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)