
Create   view [OneEBS].[Rooms] AS  
Select [ID]
      ,[ROOM_CODE]
      ,[SHORT_DESCRIPTION]
      ,[LONG_DESCRIPTION]
      ,[LOCATION_CODE]
      ,[CAPACITY]
      ,[COMMENTS]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[FES_ACTIVE]
      ,[MASTER_MAP]
      ,[DETAILS_MAP]
      ,[ORGANISATION_CODE_1]
      ,[ORGANISATION_CODE_2]
      ,[SQUARE_METRES]
      ,[ROOM_TYPE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[USER_11]
      ,[USER_12]
      ,[USER_13]
      ,[USER_14]
      ,[USER_15]
      ,[USER_16]
      ,[USER_17]
      ,[USER_18]
      ,[USER_19]
      ,[USER_20]
      ,[USER_21]
      ,[USER_22]
      ,[USER_23]
      ,[USER_24]
      ,[USER_25]
      ,[USER_26]
      ,[IS_EXTERNALLY_SOURCED]
      ,[IS_CHANGE_NOTIFIED]
      ,[INSTITUTION_CONTEXT_ID] 
from edw.OneEBS_EBS_0165_ROOMS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)