
Create   view [OneEBS].[Schools] AS  
Select [INSTITUTION_CONTEXT_ID]
      ,[SCHOOL_CODE]
      ,[FULL_NAME]
      ,[SHORT_NAME]
      ,[ADDRESS_LINE_1]
      ,[ADDRESS_LINE_2]
      ,[ADDRESS_LINE_3]
      ,[ADDRESS_LINE_4]
      ,[TOWN]
      ,[REGION]
      ,[COUNTRY]
      ,[UK_POST_CODE_PT1]
      ,[UK_POST_CODE_PT2]
      ,[TELEPHONE]
      ,[FAX]
      ,[EMAIL_ADDRESS]
      ,[HEAD_TITLE]
      ,[HEAD_INITIALS]
      ,[HEAD_SURNAME]
      ,[SCHOOL_TYPE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[FES_ACTIVE]
      ,[SCHOOL_TYPE_NO]
      ,[START_DATE]
      ,[END_DATE]
      ,[REPORTS_TO]
      ,[DIOCESE]
      ,[CATEGORY] 
from edw.OneEBS_EBS_0165_SCHOOLS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)