


CREATE   view [OneEBS].[UI_ACCREDITATION] AS  
Select [ACCREDITATION_AUTHORITY]
      ,[APPLICATION]
      ,[ARTICULATION_ARRANGEMENT]
      ,[ASSESSMENT_STRATEGIES]
      ,[CONSULTATION]
      ,[COPYRIGHT_ACKNOWLEDGEMENT]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[DAYS_CURRENCY]
      ,[FRANCHISING]
      ,[ID]
      ,[INSTITUTION_CONTEXT_ID]
      ,[LICENSING_INFORMATION]
      ,[ONGOING_MONITORING]
      ,[OUTCOMES]
      ,[PHYSICAL_RESOURCES]
      ,[SUBMISSION_TYPE]
      ,[UNIT_INSTANCE_CODE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
from edw.OneEBS_EBS_0165_UI_ACCREDITATION 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)