
Create   view [OneEBS].[Users] AS  
Select [CURRENT_INSTITUTION_CONTEXT]
      ,[INSTITUTION_CONTEXT_ID]
      ,[LOCKED_UNTIL]
      ,[FAILED_LOGIN_ATTEMPTS]
      ,[PASSWORD_CAN_EXPIRE]
      ,[ID]
      ,[GROUP_ID]
      ,[NAME]
      ,[PASS]
      ,[STATUS]
      ,[STUDENT_OR_TUTOR_ID]
      ,[DIALINUSERNAME]
      ,[ENABLED]
      ,[HAVEAUDIO]
      ,[HAVEVIDEO]
      ,[INMEETING]
      ,[IPADDRESS]
      ,[PERSON_ID]
      ,[DEFAULTEMAIL]
      ,[CANCHANGEEMAIL]
      ,[PASSEXPIRYDATE]
      ,[EBS_PERSON_CODE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[LDAP_PATH]
      ,[AUTHENTICATION_TYPE]
      ,[DEFAULT_ROLE]
      ,[GROUP_ID2]
      ,[USER_KEY]
      ,[ENC_METHOD]
      ,[DEFAULT_AGENT_ROLE]
      ,[EXTERNAL_REF] 
from edw.OneEBS_EBS_0165_USERS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)