
Create   view [OneEBS].[Visas] AS  
Select [ID]
      ,[PERSON_CODE]
      ,[VISA_TYPE]
      ,[ISSUE_DATE]
      ,[EXPIRY_DATE]
      ,[CONDITIONS]
      ,[PERMIT_LABEL_NO]
      ,[VISA_LABEL_NO]
      ,[STATUS]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[BLOB_ID]
      ,[INZ_FILE_CREATED]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[USER_11]
      ,[USER_12]
      ,[USER_13]
      ,[USER_14]
      ,[USER_15]
      ,[USER_16]
      ,[USER_17]
      ,[USER_18]
      ,[USER_19]
      ,[USER_20]
      ,[VISA_SUB_CLASS]
      ,[VISA_HOLDER_CODE]
      ,[INSTITUTION_CONTEXT_ID] 
from edw.OneEBS_EBS_0165_VISAS 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)