
Create   view [OneEBS].[Waiver_Types] AS  
Select [WAIVER_CODE]
      ,[LONG_DESCRIPTION]
      ,[SHORT_DESCRIPTION]
      ,[LOWER_AGE_LIMIT]
      ,[UPPER_AGE_LIMIT]
      ,[STAFF_WAIVER]
      ,[DISABILITY_DEPENDENCIES]
      ,[EXCLUSIVE_WAIVER]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[EXCLUSIVE_FEE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[FEE_EXEMPTION]
      ,[INSTITUTION_CONTEXT_ID]
      ,[IS_ONCE_PER_CALENDAR_YEAR]
      ,[IS_FEE_HELP_APPLICABLE]
      ,[IS_VET_FEE_HELP_APPLICABLE] 
from edw.OneEBS_EBS_0165_WAIVER_TYPES 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)