
Create   view [OneEBS].[Waiver_Values] AS  
Select [IS_ELIGIBLE_FOR_FEES_FREE]
      ,[ROUNDING_FACTOR]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[SP_VISIBLE]
      ,[SP_EVIDENCE_STATEMENT]
      ,[SP_PUBLIC_WAIVER_CODE]
      ,[USER_1]
      ,[USER_2]
      ,[USER_3]
      ,[USER_4]
      ,[USER_5]
      ,[USER_6]
      ,[USER_7]
      ,[USER_8]
      ,[USER_9]
      ,[USER_10]
      ,[INSTITUTION_CONTEXT_ID]
      ,[WAIVER_VALUE_NUMBER]
      ,[WAIVER_CODE]
      ,[CALOCC_CODE]
      ,[CALOCC_CTYPE]
      ,[START_DATE]
      ,[END_DATE]
      ,[CALC_CRITERIA]
      ,[CALC_VALUE] 
from edw.OneEBS_EBS_0165_WAIVER_VALUES 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)