
Create   view [OneEBS].[Web_Config] AS  
Select [INSTITUTION_CONTEXT_ID]
      ,[ID]
      ,[CAN_BE_OVERRIDDEN]
      ,[PARAMETER]
      ,[PARAMETER_VALUE]
      ,[APP_ID]
      ,[AREA_CODE]
      ,[DESCRIPTION]
      ,[DATA_TYPE]
      ,[VERIFIER]
      ,[LINK_URL]
      ,[LINK_DESCRIPTION]
      ,[NON_NULLABLE]
      ,[CREATED_BY]
      ,[CREATED_DATE]
      ,[UPDATED_BY]
      ,[UPDATED_DATE]
      ,[VISIBLE]
      ,[PRODUCT_MODULE_ID]
      ,[RESTRICT_TO_LICENCE]
      ,[DISPLAY_ORDER]
      ,[RESTRICT_BY_INST_TYPE]
      ,[MIN_VALUE]
      ,[MAX_VALUE]
      ,[VALIDATION_PATTERN] 
from edw.OneEBS_EBS_0165_WEB_CONFIG 
WHERE        (_RecordDeleted = 0) AND (_RecordCurrent = 1)