jobs:
- job: 'Databricks'
  steps:
  - bash: |
      mkdir -p "$(Build.ArtifactStagingDirectory)/databricks_notebooks"
      cp -r Databricks/notebooks/. "$(Build.ArtifactStagingDirectory)/databricks_notebooks/"
    displayName: 'Prepare Databricks Notebook Build Artifacts'


  - task: PublishBuildArtifacts 
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'databricks_notebooks'
      #publishLocation: 'Container' # Options: container, filePath
      #targetPath: # Required when publishLocation == FilePath
      #parallel: false # Optional
      #parallelCount: # Optional
      #fileCopyOptions: #Optional

  # - publish: $(Build.ArtifactStagingDirectory)
  #   artifact: databricks_notebooks
