parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required

jobs:
- job: 'deploy_control_db'
  dependsOn: deploy_arm
  pool:
    demands: msbuild
    vmImage: 'vs2017-win2016'
  steps:
  - download: current
    artifact: sql_cntrldb

  - task: AzureKeyVault@1
    displayName: 'Get Secrets'
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      keyVaultName: $(AZUREKEYVAULTNAME)
      secretsFilter: 'azuresqlserverpw'

  - task: SqlAzureDacpacDeployment@1
    displayName: 'Azure SQL DacpacTask'
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      ServerName: '$(AZURESQLSERVERNAME).database.windows.net'
      DatabaseName: ControlDB
      SqlUsername: $(AZURESQLSERVERUN)
      SqlPassword: '$(azuresqlserverpw)'
      DacpacFile: '$(Pipeline.Workspace)/sql_cntrldb/CntrlDb.dacpac'