  jobs:
  - job: 'cont'
    steps:

    - task: MSBuild@1
      displayName: 'Build ControlDB'
      continueOnError: 'true'
      inputs:
        solution: ADS-Databases/CntrlDB/CntrlDB.sqlproj

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: ADS-Databases/CntrlDB/bin/Debug
        artifactName: sql_Controldb
        artifactType: 'filepath' 
        fileSharePath: '\nt097qdevops01\shared'

