parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required

jobs:
- job: 'deploy_control_db'
  pool: Daf-Self-Hosted-Preprod-Win
  dependsOn: deploy_arm
  steps:

  - task: DownloadPipelineArtifact@2
    inputs:
      artifactName: sql_Controldb
      path: $(Build.ArtifactStagingDirectory)
      runVersion: latest
      source: specific
      project: 'DAF POC REPO1' 

  - task: AzureKeyVault@2
    displayName: 'Get Secrets'
    inputs:
      connectedServiceName: ${{ parameters.AzDoServiceConnection }}
      keyVaultName: $(AZUREKEYVAULTNAME)
      secretsFilter: 'AzureSQLServerPw'

  - task: SqlAzureDacpacDeployment@1
    displayName: 'Azure SQL DacpacTask'
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      ServerName: '$(AZURESQLSERVERNAME).database.windows.net'
      DatabaseName: ControlDB
      SqlUsername: $(AZURESQLSERVERUN)
      SqlPassword: '$(azuresqlserverpw)'
      DacpacFile: '$(Pipeline.Workspace)/sql_Controldb/CntrlDb.dacpac'