parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required

jobs:
- job: 'deploy_control_db'
  dependsOn: deploy_arm
  steps:
  
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: 'sql_Controldb' 

  - task: AzureKeyVault@2
    displayName: 'Get Secrets'
    inputs:
      connectedServiceName: ${{ parameters.AzDoServiceConnection }}
      keyVaultName: $(AZUREKEYVAULTNAME)
      secretsFilter: 'AzureSQLServerPw'

  - task: SqlAzureDacpacDeployment@1
    displayName: 'Azure SQL DacpacTask'
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      ServerName: '$(AZURESQLSERVERNAME).database.windows.net'
      DatabaseName: ControlDB
      SqlUsername: $(AZURESQLSERVERUN)
      SqlPassword: '$(azuresqlserverpw)'
      DacpacFile: '$(Pipeline.Workspace)/sql_Controldb/CntrlDb.dacpac'