# parameters:
# - name: AzDoServiceConnection # name of the parameter; required
#   type: string # data type of the parameter; required
parameters:
- name: variable_template_name
  type: string

variables:
- template: ../Variables/${{ parameters.variable_template_name }}.yml

jobs:
- job: 'deploy_control_db'
  dependsOn: deploy_arm
  pool:
    demands: msbuild
    vmImage: 'windows-2019'
  steps:
  - download: current
    artifact: sql_cntrldb

  - task: AzureKeyVault@1
    displayName: 'Get Secrets'
    inputs:
      azureSubscription: ${{ variables.azdoresourceconnection }}
      keyVaultName: ${{ variables.azurekeyvaultname}}
      secretsFilter: 'AzureSQLServerPw'

  - task: SqlAzureDacpacDeployment@1
    displayName: 'Azure SQL DacpacTask'
    inputs:
      azureSubscription: ${{ variables.azdoresourceconnection }}
      ServerName: '${{ variables.azuresqlservername }}.database.windows.net'
      DatabaseName: ControlDB
      SqlUsername: ${{ variables.azuresqlserverun }}
      SqlPassword: '$(AzureSQLServerPw)'
      DacpacFile: '$(Pipeline.Workspace)/sql_cntrldb/CntrlDb.dacpac'