parameters: 
  - name: data_factory_name
    type: string

jobs:
- job: 'DataFactory'
  steps:
  - bash: |
      mkdir -p "$(Build.ArtifactStagingDirectory)/adf_arm_templates"
      cp -r ${{ parameters.data_factory_name }}/. "$(Build.ArtifactStagingDirectory)/"
    displayName: 'Prepare Azure Resource Manager template Build Artifacts'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: adf_arm_templates
