# ---------------------------------------------------------------------------
# This template is called by azure-platform-deploy-pipeline-cicd.yml
# for each deployment stage.
#
# Pull in and out the different templates that deploy the ARM resources
# needed for your data platform solution. If your solution needs
# a service that is not yet included, build the required ARM template 
# (arm-[service-name-description].json) and step template 
# (step-deploy-arm-[service-name-description].yml). Reference the step template
# below.

parameters:
- name: dependencies
  type: object
  default: ['build']
- name: stage_name
  type: string
- name: variable_template_name
  type: string
- name: run_condition
  type: string

stages:
# ---------------------------------------------------------------------------
# Release to environment
# Only execute if PR into Develop
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.dependencies }}
  condition: ${{ parameters.run_condition }}
  variables:
  - template: ../Variables/${{ parameters.variable_template_name }}.yml
  jobs:
  # ---------------------------------------------------------------------------
  - job: 'deploy_synapse_db'
    steps:
    
    - task: DownloadBuildArtifacts@0
      inputs:
        artifactName: 'sql_Synapsedb' 

    - task: AzureKeyVault@1
      displayName: 'Get Secrets'
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        keyVaultName: $(AZUREKEYVAULTNAME)
        secretsFilter: 'daf-syn-d-sqlpoo-synapseadmin-password'
  
    - task: SqlAzureDacpacDeployment@1
      displayName: 'Synapse SQL DacpacTask'
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        ServerName: '$(SYNAPSESQLSERVERNAME).sql.azuresynapse.net'
        DatabaseName: $(SYNAPSEDWDBNAME)
        SqlUsername: $(SYNSQLPOOLRUN)
        SqlPassword: '$(daf-syn-d-sqlpoo-synapseadmin-password)'
        DacpacFile: '$(Pipeline.Workspace)/sql_Synapsedb/Synapse-Databases.dacpac'