# ---------------------------------------------------------------------------
# This template is called by azure-platform-deploy-pipeline-cicd.yml
# for each deployment stage.
#
# Pull in and out the different templates that deploy the ARM resources
# needed for your data platform solution. If your solution needs
# a service that is not yet included, build the required ARM template 
# (arm-[service-name-description].json) and step template 
# (step-deploy-arm-[service-name-description].yml). Reference the step template
# below.

parameters:
- name: dependencies
  type: object
  default: ['build']
- name: stage_name
  type: string
- name: variable_template_name
  type: string
- name: run_condition
  type: string

stages:
# ---------------------------------------------------------------------------
# Release to environment
# Only execute if PR into Develop
- stage: ${{ parameters.stage_name }}
  dependsOn: []
  condition: ${{ parameters.run_condition }}
  variables:
  - template: ../Variables/${{ parameters.variable_template_name }}.yml
  - template: ../Variables/deployment-variables.yml
  jobs:
  # ---------------------------------------------------------------------------
  # Modularise deployment artifacts into separate ARM scripts. Expose these
  # through templates. Introduce or remove templates from this build script
  # as needed for your deployment
  - job: 'deploy_arm'
    steps:
    # ------------------------------------------------------------------------
    # Rotate Secrets in Azure Key Vault
    # ------------------------------------------------------------------------
    - ${{ if eq(variables['secretrotation'], true) }}:  
      - template: step-rotate-secrets.yml
        parameters:
          AzDoServiceConnection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }} 
    
   
  
    