parameters:
- name: dependencies
  type: object
  default: ['build']
- name: stage_name
  type: string
- name: variable_template_name
  type: string
- name: run_condition
  type: string

stages:

- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.dependencies }}
  condition: ${{ parameters.run_condition }}
  variables:
  - template: ../Variables/${{ parameters.variable_template_name }}.yml
  jobs:
  - job: 'deploy_control_db'
    steps:

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: sql_Controldb
        path: $(Build.ArtifactStagingDirectory)    

    - task: AzureKeyVault@2
      displayName: 'Get Secrets'
      inputs:
        connectedServiceName: ${{ variables.azdoresourceconnection }}
        keyVaultName: $(AZUREKEYVAULTNAME)
        secretsFilter: 'AzureSQLServerPw'

    - task: SqlAzureDacpacDeployment@1
      displayName: 'Azure SQL DacpacTask'
      inputs:
        azureSubscription: ${{ variables.azdoresourceconnection }}
        ServerName: '$(AZURESQLSERVERNAME).database.windows.net'
        DatabaseName: ControlDB
        SqlUsername: $(AZURESQLSERVERUN)
        SqlPassword: '$(azuresqlserverpw)'
        DacpacFile: '$(Pipeline.Workspace)/sql_Controldb/CntrlDb.dacpac'
