parameters:
- name: dependencies
  type: object
  default: []
- name: stage_name
  type: string
- name: variable_template_name
  type: string
- name: run_condition
  type: string


stages:
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.dependencies }}
  condition: ${{ parameters.run_condition }}
  variables:
  - template: ../Variables/${{ parameters.variable_template_name }}.yml
  - template: ../Variables/deployment-variables.yml
  jobs:
  - job: 'rotate_secrets'
    steps:
    # ---------------------------------------------------------------------------
    # Rotate Azure Storage SAS and Connection strings in Key Vault
    - ${{ if or(eq(variables['azuredatalakestorage'], true),eq(variables['azureblobstorage'], true)) }}:
      - template: task-add-asa-auth-to-akv.yml
        parameters:
          service_connection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }}  
    # Rotate Databricks PAT tokens in Key Vault
    - ${{ if or(eq(variables['databricksvnet'], true), eq(variables['databricksnovnet'], true)) }}:
      - template: task-add-pat-to-akv.yml
        parameters:
          service_connection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }} 
          databricks_workspace_name: ${{ variables.databricksworkspacename }} 
