# ---------------------------------------------------------------------------
# This template is called by azure-vms-deploy-pipeline-cicd.yml
# for each deployment stage.
#
# Pull in and out the different templates that deploy the ARM resources
# needed for your data platform solution. If your solution needs
# a service that is not yet included, build the required ARM template 
# (arm-[service-name-description].json) and step template 
# (step-deploy-arm-[service-name-description].yml). Reference the step template
# below.

parameters:
- name: dependencies
  type: object
  default: ['build']
- name: stage_name
  type: string
- name: variable_template_name
  type: string
- name: run_condition
  type: string

stages:
# ---------------------------------------------------------------------------
# Release to environment
# Only execute if PR into Develop
- stage: ${{ parameters.stage_name }}
  dependsOn: ${{ parameters.dependencies }}
  condition: ${{ parameters.run_condition }}
  variables:
  - template: ../Variables/${{ parameters.variable_template_name }}.yml
  - template: ../Variables/deployment-variables.yml
  jobs:
  # ---------------------------------------------------------------------------
  # Modularise deployment artifacts into separate ARM scripts. Expose these
  # through templates. Introduce or remove templates from this build script
  # as needed for your deployment
  - job: 'deploy_arm'
    steps:
    - download: current
      artifact: arm_templates

    # ------------------------------------------------------------------------
    # Deploy Azure resources
    # ------------------------------------------------------------------------
    # Deploy Self-hosted Azure Devops Agent (Linux)
    - ${{ if eq(variables['vm_devops'], true) }}:
      - template: step-deploy-arm-vm.yml
        parameters:
          AzDoServiceConnection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }}
          vmSize: ${{ variables.vmSizeDevops }}
          vmName: ${{ variables.vmNameDevops }}
          OSVersion: ${{ variables.OSVersionDevops }}
          publisher: ${{ variables.publisherDevops }}
          offer: ${{ variables.offerDevops }}

    # Deploy Self-hosted Azure Devops Agent (Win)
    - ${{ if eq(variables['vm_devops'], true) }}:
      - template: step-deploy-arm-vm.yml
        parameters:
          AzDoServiceConnection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }}
          vmSize: ${{ variables.vmSizeDevops }}
          vmName: ${{ variables.vmNameDevops2 }}
          OSVersion: ${{ variables.OSVersion }}
          publisher: ${{ variables.publisher }}
          offer: ${{ variables.offer }}
    
    # Deploy Self-hosted Integration Runtime
    - ${{ if eq(variables['vm_adfruntime'], true) }}:
      - template: step-deploy-arm-vm.yml
        parameters:
          AzDoServiceConnection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }}
          vmSize: ${{ variables.vmSizeIR }}
          vmName: ${{ variables.vmNameIR }}
          OSVersion: ${{ variables.OSVersion }}
          publisher: ${{ variables.publisher }}
          offer: ${{ variables.offer }}
    
    # Deploy SLT
    - ${{ if eq(variables['vm_sqlslt'], true) }}:
      - template: step-deploy-arm-vm.yml
        parameters:
          AzDoServiceConnection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }}
          vmSize: ${{ variables.vmSizeSlt }}
          vmName: ${{ variables.vmNameSlt }}
          OSVersion: ${{ variables.OSVersionSlt }}
          publisher: ${{ variables.publisherSlt }}
          offer: ${{ variables.offerSlt }}

    
 
  
  
    