parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required
- name: resource_group
  type: string

steps:
  - task: AzureResourceGroupDeployment@2
    name: deploy_adls
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resource_group }}
      location: $(LOCATION)
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.ArtifactStagingDirectory)/arm_templates/arm-adls.json'
      overrideParameters: '-location $(LOCATION) -accountNames "$(DATALAKESTORAGEACCOUNTNAMES)" -zones "$(ZONENAMES)"'
      deploymentMode: 'Incremental'
      deploymentOutputs: 'armOutputs'
    displayName: 'Deploy ADLS for datalake'
