parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required
- name: resource_group
  type: string
- name: log_analytics
  type: boolean
- name: log_storage
  type: boolean

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resource_group }}
      location: $(LOCATION)
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/arm_templates/arm-datafactory-w-shir.json'
      overrideParameters: '-dataFactoryName $(DATAFACTORYNAME) -dataFactorySHIRName $(DATAFACTORYSHIRNAME) -location $(LOCATION)'
      deploymentMode: 'Incremental'
    displayName: 'Deploy Datafactory with Access Policies'

  # Add Data Factory MI to Key Vault Access Policies
  - template: task-add-mi-to-akv-access-policy.yml
    parameters:
      service_connection: ${{ parameters.AzDoServiceConnection }}
      resource_group: ${{ parameters.resource_group }}
      src_resource_name: $(DATAFACTORYNAME)
      key_valut_name: $(AZUREKEYVAULTNAME)
      secret_permissions: 'list get'

  # Add Data Factory MI to SQLServer Rbac
  - template: task-add-mi-to-resource-rbac.yml
    parameters:
      service_connection: ${{ parameters.AzDoServiceConnection }}
      resource_group: ${{ parameters.resource_group }}
      src_resource_name: $(DATAFACTORYNAME)
      trg_resource_name: $(AZURESQLSERVERNAME)
      role: 'Contributor'

# Create or update diagnostic settings to send to Log Analytics
  - ${{ if eq(parameters['log_analytics'], true) }}:
    - template: task-add-log-analytics-diagnostics.yml
      parameters:
        service_connection: ${{ parameters.AzDoServiceConnection }}
        resource_group: ${{ parameters.resource_group }}
        src_resource_name: $(DATAFACTORYNAME)
        log_analitics_name: $(LOGANALYTICSWORKSPACENAME)
        logs: |
          [
            {
              "category": "ActivityRuns",
              "enabled": true,
              "retentionPolicy":{
                "days": 30,
                "enabled": true
              }
            },
            {
              "category": "PipelineRuns",
              "enabled": true,
              "retentionPolicy": {
                "days": 30,
                "enabled": true
              }
            },
            {
              "category": "TriggerRuns",
              "enabled": true,
              "retentionPolicy": {
                "days": 30,
                "enabled": true
              }
            }
          ]
        metrics: |
          [
            {
              "category": "AllMetrics",
              "enabled": true,
              "retentionPolicy": {
                "days": 30,
                "enabled": true
              }
            }
          ]'

# Create or update diagnostic settings to archive to a storage account
  - ${{ if eq(parameters['log_storage'], true) }}:
    - template: task-add-log-storage-diagnostics.yml
      parameters:
        service_connection: ${{ parameters.AzDoServiceConnection }}
        resource_group: ${{ parameters.resource_group }}
        src_resource_name: $(DATAFACTORYNAME)
        log_storage_name: $(LOGSTORAGEACCOUNTNAME)
        logs: |
          [
            {
              "category": "ActivityRuns",
              "enabled": true,
              "retentionPolicy":{
                "days": 30,
                "enabled": true
              }
            },
            {
              "category": "PipelineRuns",
              "enabled": true,
              "retentionPolicy": {
                "days": 30,
                "enabled": true
              }
            },
            {
              "category": "TriggerRuns",
              "enabled": true,
              "retentionPolicy": {
                "days": 30,
                "enabled": true
              }
            }
          ]
        metrics: |
          [
            {
              "category": "AllMetrics",
              "enabled": true,
              "retentionPolicy": {
                "days": 30,
                "enabled": true
              }
            }
          ]'

# Create or update diagnostic settings to stream to even hub **This has yet to be built
