parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required
- name: resource_group
  type: string
- name: log_analytics
  type: boolean
- name: log_storage
  type: boolean

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resource_group }}
      location: $(LOCATION)
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/arm_templates/arm-datafactory-w-shir.json'
      overrideParameters: '-dataFactoryName $(DATAFACTORYNAME) -dataFactorySHIRName $(DATAFACTORYSHIRNAME) -location $(LOCATION) -isRepoEnabled $(ISREPOENABLED)'
      deploymentMode: 'Incremental'
    displayName: 'Deploy Datafactory with Access Policies'

  # Add Data Factory MI to Key Vault Access Policies
  - template: task-add-mi-to-akv-access-policy.yml
    parameters:
      service_connection: ${{ parameters.AzDoServiceConnection }}
      resource_group: ${{ parameters.resource_group }}
      src_resource_name: $(DATAFACTORYNAME)
      key_vault_name: $(AZUREKEYVAULTNAME)
      secret_permissions: 'list get'

  # Add Data Factory MI to SQLServer Rbac
  - template: task-add-mi-to-resource-rbac.yml
    parameters:
      service_connection: ${{ parameters.AzDoServiceConnection }}
      resource_group: ${{ parameters.resource_group }}
      src_resource_name: $(DATAFACTORYNAME)
      trg_resource_name: $(AZURESQLSERVERNAME)
      role: 'Contributor'
      
