# parameters:
# - name: AzDoServiceConnection # name of the parameter; required
#   type: string # data type of the parameter; required
# - name: resource_group
#   type: string

steps:
  - bash: |
      set -e

      # System info for debugging this pipeline if needed
      echo -e "Linux name:"
      uname -a
      echo
      echo -e "Working Directory:"
      echo "$(Build.Repository.LocalPath)"
      echo
      echo -e "List of files available:\n"
      ls -laR $(Build.Repository.LocalPath)
      echo
      echo -e "Pipeline workspace available:\n"
      ls -laR $(Pipeline.Workspace)
      echo -e "Environment variables:"
      env | sort
      echo
    displayName: 'Agent info'

  - task: AzureCLI@2
    displayName: 'Add sp to ACL policy'
    name: add_sp_to_acl_policy_sql
    inputs:
      azureSubscription: ${{ variables.azdoresourceconnection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        az keyvault set-policy --name "${{ variables.azurekeyvaultname }}" --secret-permissions set delete list get --object-id "${{ variables.spobjectid }}"

  - task: AzureKeyVault@1
    displayName: 'Get secrets'
    inputs:
      azureSubscription: ${{ variables.azdoresourceconnection }}
      keyVaultName: ${{ variables.azurekeyvaultname }}
      secretsFilter: 'AzureSQLServerPw'

  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: ${{ variables.azdoresourceconnection }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: '${{ variables.prefix }}-${{ variables.environment }}'
      location: ${{ variables.location }}
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/arm_templates/arm-sql-server-control-db.json'
      overrideParameters: '-location ${{ variables.location }} -prefix ${{ variables.prefix}} -environment ${{ variables.environment }} -AzureSqlServerUn ${{ variables.azuresqlserverun }} -AzureSqlServerPw $(AZURESQLSERVERPW)'
      deploymentMode: 'Incremental'
    displayName: 'Deploy Azure SQL Control DB'