parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required
- name: resource_group
  type: string
- name: databricksclustername
  type: string

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resource_group }}
      location: $(LOCATION)
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/arm_templates/arm-databricks-no-vnet-nsg.json'
      overrideParameters: '-location $(LOCATION) -prefix $(PREFIX) -environment $(ENVIRONMENT) -pricingTier $(DATABRICKSPRICINGTIER)'
      deploymentMode: 'Incremental'
      deploymentOutputs: 'databricksOutput'
    displayName: 'Deploy Databricks Workspace'

  - powershell: |
      Write-Host '$(databricksOutput)'
      $json = '$(databricksOutput)' | convertfrom-json
      $workspaceNameValue = $json.WorkspaceName.value
      Write-Host "##vso[task.setvariable variable=databricksWorkspaceName;isOutput=true]$workspaceNameValue"
    name: getWorkspaceName
    displayName: 'Extract ARM outputs'

  - template: step-databricks-create-add-pat-cluster.yml
    parameters:
      AzDoServiceConnection: ${{ parameters.AzDoServiceConnection }}
      resource_group: ${{ parameters.resource_group }}
      databricks_cluster_name: ${{ parameters.databricksclustername }}
