parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required
- name: resource_group
  type: string

steps:
- stage: ${{ parameters.stage_name }}
  dependsOn: []
  condition: ${{ parameters.run_condition }}
  variables:
  - template: ../Variables/${{ parameters.variable_template_name }}.yml
  - template: ../Variables/deployment-variables.yml
  jobs:
  # ---------------------------------------------------------------------------
  - job: 'rotate_secret'
    step:
    # Rotate Azure Storage SAS and Connection strings in Key Vault
    - ${{ if or(eq(variables['azuredatalakestorage'], true),eq(variables['azureblobstorage'], true)) }}:
      - template: task-add-asa-auth-to-akv.yml
        parameters:
          service_connection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }}  
    # Rotate Databricks PAT tokens in Key Vault
    - ${{ if or(if eq(variables['databricksvnet'], true), eq(variables['databricksnovnet'], true)) }}:
      - template: task-add-pat-to-akv.yml
        parameters:
          service_connection: ${{ variables.azdoresourceconnection }}
          resource_group: ${{ variables.resourcegroupname }} 
          databricks_workspace_name: ${{ variables.databricksworkspacename }} 
