parameters:
- name: AzDoServiceConnection # name of the parameter; required
  type: string # data type of the parameter; required
- name: resource_group
  type: string

steps:
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: ${{ parameters.AzDoServiceConnection }}
      action: 'Create Or Update Resource Group'
      resourceGroupName: ${{ parameters.resource_group }}
      location: $(LOCATION)
      templateLocation: 'Linked artifact'
      csmFile: '$(Build.ArtifactStagingDirectory)/arm_templates/arm-private-endpoints.json'
      overrideParameters: '-keyVaultName $(azurekeyvaultname) -subnetId $(internalSubnetId)'
      deploymentMode: 'Incremental'
      deploymentOutputs: 'armOutputs'
    displayName: 'Deploy Private Endpoints'
