# parameters:
# - name: AzDoServiceConnection # name of the parameter; required
#   type: string # data type of the parameter; required
# - name: resource_group
#   type: string
# - name: databricksclustername
#   type: string

steps: 
  - task: AzureResourceGroupDeployment@2
    inputs:
      azureSubscription: ${{ variables.azdoresourceconnection}}
      action: 'Create Or Update Resource Group'
      resourceGroupName: '${{ variables.prefix }}-${{ variables.environment }}'
      location: ${{ variables.location}}
      templateLocation: 'Linked artifact'
      csmFile: '$(Pipeline.Workspace)/arm_templates/arm-databricks-no-vnet-nsg.json'
      overrideParameters: '-location ${{ variables.location}} -prefix ${{ variables.prefix}} -environment ${{ variables.environment}} -pricingTier ${{ variables.databrickspricingtier}}'
      deploymentMode: 'Incremental'
      deploymentOutputs: 'databricksOutput'
    displayName: 'Deploy Databricks Workspace'

  - powershell: |
      Write-Host '$(databricksOutput)'
      $json = '$(databricksOutput)' | convertfrom-json
      $workspaceNameValue = $json.WorkspaceName.value
      Write-Host "##vso[task.setvariable variable=databricksWorkspaceName;isOutput=true]$workspaceNameValue"
    name: getWorkspaceName
    displayName: 'Extract ARM outputs'

  - template: step-databricks-create-add-pat-cluster.yml
    parameters:
      AzDoServiceConnection: ${{ variables.azdoresourceconnection}}
      resource_group: '${{ variables.prefix }}-${{ variables.environment }}'
      databricks_cluster_name: ${{ parameters.databricksclustername }}
