                    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
                  #             | Add Log Analytics Diagnostic Settings to a Resource |             #    
                  #             -------------------------------------------------------             #
                  #     This is a task level template script used to create and update log          #
                  #     analytics diagnostic settings to an azure resource.                         #
                  #                                                                                 #
                    # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

parameters: 
- name: service_connection
  type: string
- name: resource_group
  type: string
- name: src_resource_name
  type: string
- name: log_analitics_name
  type: string
- name: logs
  type: string
- name: metrics
  type: string

steps:
# Create or updatediagnostic settings for Log Analytics and Storage archiving
  - task: AzureCLI@2
    displayName: 'Create Log Analytics diagnostic settings for ${{ parameters.src_resource_name }}'
    inputs:
      azureSubscription: ${{ parameters.service_connection }}
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        src_resource_id=$(az resource list --name ${{ parameters.src_resource_name }} --resource-group ${{ parameters.resource_group }} --output tsv --query "[].id")
        echo "##vso[task.setvariable variable=src_resource_id]$src_resource_id"
        echo "Name: ${{ parameters.src_resource_name }}, Id: $src_resource_id"
        log_resource_id=$(az resource list --name ${{ parameters.log_analitics_name }} --resource-group ${{ parameters.resource_group }} --output tsv --query "[].id")
        echo "##vso[task.setvariable variable=log_resource_id]$log_resource_id"
        echo "Name: ${{ parameters.log_analitics_name }}, Id: $log_resource_id"

        # diagnostic_check=$(az monitor diagnostic-settings show --resource $src_resource_id --name ${{ parameters.src_resource_name }}-ala)
        echo "az monitor diagnostic-settings create --name ${{ replace(parameters.src_resource_name,'/','') }}-ala --resource $src_resource_id --logs '${{ parameters.logs }}' --metrics '${{ parameters.metrics }}' --storage-account $log_resource_id"
        if [ ! -z "$logs" ] && [ -z "$metrics" ]
          then
            az monitor diagnostic-settings create \
            --name "${{ replace(lower(parameters.src_resource_name),'/','') }}-ala" \
            --resource "$src_resource_id" \
            --logs '${{ parameters.logs }}' \
            --storage-account "$log_resource_id"
        elif [ ! -z "$metrics" ] && [ -z "$logs" ] 
          then 
            az monitor diagnostic-settings create \
            --name "${{ replace(lower(parameters.src_resource_name),'/','') }}-ala" \
            --resource "$src_resource_id" \
            --metrics '${{ parameters.metrics }}' \
            --storage-account "$log_resource_id"
        else
          az monitor diagnostic-settings create \
          --name "${{ replace(lower(parameters.src_resource_name),'/','') }}-ala" \
          --resource "$src_resource_id" \
          --logs '${{ parameters.logs }}' \
          --metrics '${{ parameters.metrics }}' \
          --storage-account "$log_resource_id"
        fi
