# Databricks notebook source
#config parameters
source = 'CRM' #either CRM or ISU
table = '0BP_DEF_ADDRESS_ATTR'

environment = 'test'
storage_account_name = "sablobdaftest01"
storage_account_access_key = dbutils.secrets.get(scope="TestScope",key="test-sablob-key")
containerName = "archive"


# COMMAND ----------

# MAGIC %run ../../includes/tableEvaluation

# COMMAND ----------

# DBTITLE 1,[Source] with mapping
# MAGIC %sql
# MAGIC select
# MAGIC businessPartnerNumber,
# MAGIC businessPartnerGUID,
# MAGIC addressNumber,
# MAGIC validFromDate,
# MAGIC validToDate,
# MAGIC titleCode,
# MAGIC businessPartnerName1,
# MAGIC businessPartnerName2,
# MAGIC businessPartnerName3,
# MAGIC coName,
# MAGIC cityName,
# MAGIC cityCode,
# MAGIC postalCode,
# MAGIC poBoxPostalCode,
# MAGIC companyPostalCode,
# MAGIC poBoxCode,
# MAGIC poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,
# MAGIC cityPoBoxCode,
# MAGIC streetName,
# MAGIC streetCode,
# MAGIC houseNumber,
# MAGIC houseNumber2,
# MAGIC streetType,
# MAGIC streetLine3,
# MAGIC streetLine4,
# MAGIC streetLine5,
# MAGIC building,
# MAGIC floorNumber,
# MAGIC appartmentNumber,
# MAGIC countryShortName,
# MAGIC stateCode,
# MAGIC personalAddressIndicator,
# MAGIC searchTerm1,
# MAGIC searchTerm2,
# MAGIC phoneNumber,
# MAGIC faxNumber,
# MAGIC addressTimeZone,
# MAGIC emailAddress,
# MAGIC uriAddress,
# MAGIC phoneNumberDisplayFormat,
# MAGIC faxDisplayFormat,
# MAGIC longitude,
# MAGIC latitude,
# MAGIC altitude,
# MAGIC precision,
# MAGIC communicationAddressNumber,
# MAGIC shortFormattedAddress,
# MAGIC shortFormattedAddress2,
# MAGIC addressLine0,
# MAGIC addressLine1,
# MAGIC addressLine2,
# MAGIC addressLine3,
# MAGIC addressLine4,
# MAGIC addressLine5,
# MAGIC addressLine6,
# MAGIC addressLine7,
# MAGIC addressLine8
# MAGIC from
# MAGIC (
# MAGIC SELECT
# MAGIC PARTNER as businessPartnerNumber,
# MAGIC PARTNER_GUID as businessPartnerGUID,
# MAGIC ADDRNUMBER as addressNumber,
# MAGIC DATE_FROM as validFromDate,
# MAGIC DATE_TO as validToDate,
# MAGIC TITLE as titleCode,
# MAGIC NAME1 as businessPartnerName1,
# MAGIC NAME2 as businessPartnerName2,
# MAGIC NAME3 as businessPartnerName3,
# MAGIC NAME_CO as coName,
# MAGIC CITY1 as cityName,
# MAGIC CITY_CODE as cityCode,
# MAGIC POST_CODE1 as postalCode,
# MAGIC POST_CODE2 as poBoxPostalCode,
# MAGIC POST_CODE3 as companyPostalCode,
# MAGIC PO_BOX as poBoxCode,
# MAGIC PO_BOX_NUM as poBoxWithoutNumberIndicator,
# MAGIC PO_BOX_LOC as poBoxCity,
# MAGIC CITY_CODE2 as cityPoBoxCode,
# MAGIC STREET as streetName,
# MAGIC STREETCODE as streetCode,
# MAGIC HOUSE_NUM1 as houseNumber,
# MAGIC HOUSE_NUM2 as houseNumber2,
# MAGIC STR_SUPPL1 as streetType,
# MAGIC STR_SUPPL2 as streetLine3,
# MAGIC STR_SUPPL3 as streetLine4,
# MAGIC LOCATION as streetLine5,
# MAGIC BUILDING as building,
# MAGIC FLOOR as floorNumber,
# MAGIC ROOMNUMBER as appartmentNumber,
# MAGIC COUNTRY as countryShortName,
# MAGIC REGION as stateCode,
# MAGIC PERS_ADDR as personalAddressIndicator,
# MAGIC SORT1 as searchTerm1,
# MAGIC SORT2 as searchTerm2,
# MAGIC TEL_NUMBER as phoneNumber,
# MAGIC FAX_NUMBER as faxNumber,
# MAGIC TIME_ZONE as addressTimeZone,
# MAGIC SMTP_ADDR as emailAddress,
# MAGIC URI_ADDR as uriAddress,
# MAGIC TELDISPLAY as phoneNumberDisplayFormat,
# MAGIC FAXDISPLAY as faxDisplayFormat,
# MAGIC LONGITUDE as longitude,
# MAGIC LATITUDE as latitude,
# MAGIC ALTITUDE as altitude,
# MAGIC PRECISID as precision,
# MAGIC ADDRCOMM as communicationAddressNumber,
# MAGIC ADDR_SHORT as shortFormattedAddress,
# MAGIC ADDR_SHORT_S as shortFormattedAddress2,
# MAGIC LINE0 as addressLine0,
# MAGIC LINE1 as addressLine1,
# MAGIC LINE2 as addressLine2,
# MAGIC LINE3 as addressLine3,
# MAGIC LINE4 as addressLine4,
# MAGIC LINE5 as addressLine5,
# MAGIC LINE6 as addressLine6,
# MAGIC LINE7 as addressLine7,
# MAGIC LINE8 as addressLine8
# MAGIC ,row_number() over (partition by PARTNER,ADDRNUMBER order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table}
# MAGIC )a where  a.rn = 1

# COMMAND ----------

# DBTITLE 1,[Verification] Count Check
# MAGIC %sql
# MAGIC select count (*) as RecordCount, 'Target' as TableName from cleansed.${vars.table}
# MAGIC union all
# MAGIC select count (*) as RecordCount, 'Source' as TableName from (select
# MAGIC businessPartnerNumber,
# MAGIC businessPartnerGUID,
# MAGIC addressNumber,
# MAGIC validFromDate,
# MAGIC validToDate,
# MAGIC titleCode,
# MAGIC businessPartnerName1,
# MAGIC businessPartnerName2,
# MAGIC businessPartnerName3,
# MAGIC coName,
# MAGIC cityName,
# MAGIC cityCode,
# MAGIC postalCode,
# MAGIC poBoxPostalCode,
# MAGIC companyPostalCode,
# MAGIC poBoxCode,
# MAGIC poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,
# MAGIC cityPoBoxCode,
# MAGIC streetName,
# MAGIC streetCode,
# MAGIC houseNumber,
# MAGIC houseNumber2,
# MAGIC streetType,
# MAGIC streetLine3,
# MAGIC streetLine4,
# MAGIC streetLine5,
# MAGIC building,
# MAGIC floorNumber,
# MAGIC appartmentNumber,
# MAGIC countryShortName,
# MAGIC stateCode,
# MAGIC personalAddressIndicator,
# MAGIC searchTerm1,
# MAGIC searchTerm2,
# MAGIC phoneNumber,
# MAGIC faxNumber,
# MAGIC addressTimeZone,
# MAGIC emailAddress,
# MAGIC uriAddress,
# MAGIC phoneNumberDisplayFormat,
# MAGIC faxDisplayFormat,
# MAGIC longitude,
# MAGIC latitude,
# MAGIC altitude,
# MAGIC precision,
# MAGIC communicationAddressNumber,
# MAGIC shortFormattedAddress,
# MAGIC shortFormattedAddress2,
# MAGIC addressLine0,
# MAGIC addressLine1,
# MAGIC addressLine2,
# MAGIC addressLine3,
# MAGIC addressLine4,
# MAGIC addressLine5,
# MAGIC addressLine6,
# MAGIC addressLine7,
# MAGIC addressLine8
# MAGIC from
# MAGIC (
# MAGIC SELECT
# MAGIC PARTNER as businessPartnerNumber,
# MAGIC PARTNER_GUID as businessPartnerGUID,
# MAGIC ADDRNUMBER as addressNumber,
# MAGIC DATE_FROM as validFromDate,
# MAGIC DATE_TO as validToDate,
# MAGIC TITLE as titleCode,
# MAGIC NAME1 as businessPartnerName1,
# MAGIC NAME2 as businessPartnerName2,
# MAGIC NAME3 as businessPartnerName3,
# MAGIC NAME_CO as coName,
# MAGIC CITY1 as cityName,
# MAGIC CITY_CODE as cityCode,
# MAGIC POST_CODE1 as postalCode,
# MAGIC POST_CODE2 as poBoxPostalCode,
# MAGIC POST_CODE3 as companyPostalCode,
# MAGIC PO_BOX as poBoxCode,
# MAGIC PO_BOX_NUM as poBoxWithoutNumberIndicator,
# MAGIC PO_BOX_LOC as poBoxCity,
# MAGIC CITY_CODE2 as cityPoBoxCode,
# MAGIC STREET as streetName,
# MAGIC STREETCODE as streetCode,
# MAGIC HOUSE_NUM1 as houseNumber,
# MAGIC HOUSE_NUM2 as houseNumber2,
# MAGIC STR_SUPPL1 as streetType,
# MAGIC STR_SUPPL2 as streetLine3,
# MAGIC STR_SUPPL3 as streetLine4,
# MAGIC LOCATION as streetLine5,
# MAGIC BUILDING as building,
# MAGIC FLOOR as floorNumber,
# MAGIC ROOMNUMBER as appartmentNumber,
# MAGIC COUNTRY as countryShortName,
# MAGIC REGION as stateCode,
# MAGIC PERS_ADDR as personalAddressIndicator,
# MAGIC SORT1 as searchTerm1,
# MAGIC SORT2 as searchTerm2,
# MAGIC TEL_NUMBER as phoneNumber,
# MAGIC FAX_NUMBER as faxNumber,
# MAGIC TIME_ZONE as addressTimeZone,
# MAGIC SMTP_ADDR as emailAddress,
# MAGIC URI_ADDR as uriAddress,
# MAGIC TELDISPLAY as phoneNumberDisplayFormat,
# MAGIC FAXDISPLAY as faxDisplayFormat,
# MAGIC LONGITUDE as longitude,
# MAGIC LATITUDE as latitude,
# MAGIC ALTITUDE as altitude,
# MAGIC PRECISID as precision,
# MAGIC ADDRCOMM as communicationAddressNumber,
# MAGIC ADDR_SHORT as shortFormattedAddress,
# MAGIC ADDR_SHORT_S as shortFormattedAddress2,
# MAGIC LINE0 as addressLine0,
# MAGIC LINE1 as addressLine1,
# MAGIC LINE2 as addressLine2,
# MAGIC LINE3 as addressLine3,
# MAGIC LINE4 as addressLine4,
# MAGIC LINE5 as addressLine5,
# MAGIC LINE6 as addressLine6,
# MAGIC LINE7 as addressLine7,
# MAGIC LINE8 as addressLine8
# MAGIC ,row_number() over (partition by PARTNER,ADDRNUMBER order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table}
# MAGIC )a where  a.rn = 1)

# COMMAND ----------

# DBTITLE 1,[Verification] Duplicate Checks
# MAGIC %sql
# MAGIC SELECT businessPartnerNumber,businessPartnerGUID,addressNumber,validFromDate,validToDate,
# MAGIC titleCode,businessPartnerName1,businessPartnerName2,businessPartnerName3,coName,cityName,
# MAGIC cityCode,postalCode,poBoxPostalCode,companyPostalCode,poBoxCode,poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,cityPoBoxCode,streetName,streetCode,houseNumber,houseNumber2,streetType,streetLine3,
# MAGIC streetLine4,streetLine5,building,floorNumber,appartmentNumber,countryShortName,stateCode,
# MAGIC personalAddressIndicator,searchTerm1,searchTerm2,phoneNumber,faxNumber,addressTimeZone,
# MAGIC emailAddress,uriAddress,phoneNumberDisplayFormat,faxDisplayFormat,longitude,latitude,altitude,
# MAGIC precision,communicationAddressNumber,shortFormattedAddress,shortFormattedAddress2,addressLine0,
# MAGIC addressLine1,addressLine2,addressLine3,addressLine4,addressLine5,addressLine6,addressLine7,addressLine8
# MAGIC , COUNT (*) as count
# MAGIC FROM cleansed.${vars.table}
# MAGIC GROUP BY businessPartnerNumber,businessPartnerGUID,addressNumber,validFromDate,validToDate,
# MAGIC titleCode,businessPartnerName1,businessPartnerName2,businessPartnerName3,coName,cityName,
# MAGIC cityCode,postalCode,poBoxPostalCode,companyPostalCode,poBoxCode,poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,cityPoBoxCode,streetName,streetCode,houseNumber,houseNumber2,streetType,streetLine3,
# MAGIC streetLine4,streetLine5,building,floorNumber,appartmentNumber,countryShortName,stateCode,
# MAGIC personalAddressIndicator,searchTerm1,searchTerm2,phoneNumber,faxNumber,addressTimeZone,
# MAGIC emailAddress,uriAddress,phoneNumberDisplayFormat,faxDisplayFormat,longitude,latitude,altitude,
# MAGIC precision,communicationAddressNumber,shortFormattedAddress,shortFormattedAddress2,addressLine0,
# MAGIC addressLine1,addressLine2,addressLine3,addressLine4,addressLine5,addressLine6,addressLine7,addressLine8
# MAGIC HAVING COUNT (*) > 1

# COMMAND ----------

# DBTITLE 1,[Verification] Duplicate Checks
# MAGIC %sql
# MAGIC SELECT  * FROM  (
# MAGIC     SELECT
# MAGIC       *,row_number() 
# MAGIC       OVER(PARTITION BY businessPartnerNumber,addressNumber
# MAGIC         order by
# MAGIC           businessPartnerNumber,addressNumber
# MAGIC       ) as rn
# MAGIC     FROM  cleansed.${vars.table}
# MAGIC   ) a where  a.rn > 1

# COMMAND ----------

# DBTITLE 1,[Verification] Compare Source and Target Data
# MAGIC %sql
# MAGIC select
# MAGIC businessPartnerNumber,
# MAGIC businessPartnerGUID,
# MAGIC addressNumber,
# MAGIC validFromDate,
# MAGIC validToDate,
# MAGIC titleCode,
# MAGIC businessPartnerName1,
# MAGIC businessPartnerName2,
# MAGIC businessPartnerName3,
# MAGIC coName,
# MAGIC cityName,
# MAGIC cityCode,
# MAGIC postalCode,
# MAGIC poBoxPostalCode,
# MAGIC companyPostalCode,
# MAGIC poBoxCode,
# MAGIC poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,
# MAGIC cityPoBoxCode,
# MAGIC streetName,
# MAGIC streetCode,
# MAGIC houseNumber,
# MAGIC houseNumber2,
# MAGIC streetType,
# MAGIC streetLine3,
# MAGIC streetLine4,
# MAGIC streetLine5,
# MAGIC building,
# MAGIC floorNumber,
# MAGIC appartmentNumber,
# MAGIC countryShortName,
# MAGIC stateCode,
# MAGIC personalAddressIndicator,
# MAGIC searchTerm1,
# MAGIC searchTerm2,
# MAGIC phoneNumber,
# MAGIC faxNumber,
# MAGIC addressTimeZone,
# MAGIC emailAddress,
# MAGIC uriAddress,
# MAGIC phoneNumberDisplayFormat,
# MAGIC faxDisplayFormat,
# MAGIC longitude,
# MAGIC latitude,
# MAGIC altitude,
# MAGIC precision,
# MAGIC communicationAddressNumber,
# MAGIC shortFormattedAddress,
# MAGIC shortFormattedAddress2,
# MAGIC addressLine0,
# MAGIC addressLine1,
# MAGIC addressLine2,
# MAGIC addressLine3,
# MAGIC addressLine4,
# MAGIC addressLine5,
# MAGIC addressLine6,
# MAGIC addressLine7,
# MAGIC addressLine8
# MAGIC from
# MAGIC (
# MAGIC SELECT
# MAGIC case
# MAGIC when PARTNER is null then '' 
# MAGIC else PARTNER end as businessPartnerNumber,
# MAGIC PARTNER_GUID as businessPartnerGUID,
# MAGIC case
# MAGIC when ADDRNUMBER is null then '' 
# MAGIC else ADDRNUMBER end as addressNumber,
# MAGIC case
# MAGIC when DATE_FROM < '1900-01-01' then '1900-01-01'
# MAGIC else DATE_FROM end as validFromDate,
# MAGIC DATE_TO as validToDate,
# MAGIC TITLE as titleCode,
# MAGIC NAME1 as businessPartnerName1,
# MAGIC NAME2 as businessPartnerName2,
# MAGIC NAME3 as businessPartnerName3,
# MAGIC NAME_CO as coName,
# MAGIC CITY1 as cityName,
# MAGIC CITY_CODE as cityCode,
# MAGIC POST_CODE1 as postalCode,
# MAGIC POST_CODE2 as poBoxPostalCode,
# MAGIC POST_CODE3 as companyPostalCode,
# MAGIC PO_BOX as poBoxCode,
# MAGIC PO_BOX_NUM as poBoxWithoutNumberIndicator,
# MAGIC PO_BOX_LOC as poBoxCity,
# MAGIC CITY_CODE2 as cityPoBoxCode,
# MAGIC STREET as streetName,
# MAGIC STREETCODE as streetCode,
# MAGIC HOUSE_NUM1 as houseNumber,
# MAGIC HOUSE_NUM2 as houseNumber2,
# MAGIC STR_SUPPL1 as streetType,
# MAGIC STR_SUPPL2 as streetLine3,
# MAGIC STR_SUPPL3 as streetLine4,
# MAGIC LOCATION as streetLine5,
# MAGIC BUILDING as building,
# MAGIC FLOOR as floorNumber,
# MAGIC ROOMNUMBER as appartmentNumber,
# MAGIC COUNTRY as countryShortName,
# MAGIC REGION as stateCode,
# MAGIC PERS_ADDR as personalAddressIndicator,
# MAGIC SORT1 as searchTerm1,
# MAGIC SORT2 as searchTerm2,
# MAGIC TEL_NUMBER as phoneNumber,
# MAGIC FAX_NUMBER as faxNumber,
# MAGIC TIME_ZONE as addressTimeZone,
# MAGIC SMTP_ADDR as emailAddress,
# MAGIC URI_ADDR as uriAddress,
# MAGIC TELDISPLAY as phoneNumberDisplayFormat,
# MAGIC FAXDISPLAY as faxDisplayFormat,
# MAGIC LONGITUDE as longitude,
# MAGIC LATITUDE as latitude,
# MAGIC ALTITUDE as altitude,
# MAGIC PRECISID as precision,
# MAGIC ADDRCOMM as communicationAddressNumber,
# MAGIC ADDR_SHORT as shortFormattedAddress,
# MAGIC ADDR_SHORT_S as shortFormattedAddress2,
# MAGIC LINE0 as addressLine0,
# MAGIC LINE1 as addressLine1,
# MAGIC LINE2 as addressLine2,
# MAGIC LINE3 as addressLine3,
# MAGIC LINE4 as addressLine4,
# MAGIC LINE5 as addressLine5,
# MAGIC LINE6 as addressLine6,
# MAGIC LINE7 as addressLine7,
# MAGIC LINE8 as addressLine8
# MAGIC ,row_number() over (partition by PARTNER,ADDRNUMBER order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table}
# MAGIC )a where  a.rn = 1
# MAGIC except
# MAGIC select
# MAGIC businessPartnerNumber,
# MAGIC businessPartnerGUID,
# MAGIC addressNumber,
# MAGIC validFromDate,
# MAGIC validToDate,
# MAGIC titleCode,
# MAGIC businessPartnerName1,
# MAGIC businessPartnerName2,
# MAGIC businessPartnerName3,
# MAGIC coName,
# MAGIC cityName,
# MAGIC cityCode,
# MAGIC postalCode,
# MAGIC poBoxPostalCode,
# MAGIC companyPostalCode,
# MAGIC poBoxCode,
# MAGIC poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,
# MAGIC cityPoBoxCode,
# MAGIC streetName,
# MAGIC streetCode,
# MAGIC houseNumber,
# MAGIC houseNumber2,
# MAGIC streetType,
# MAGIC streetLine3,
# MAGIC streetLine4,
# MAGIC streetLine5,
# MAGIC building,
# MAGIC floorNumber,
# MAGIC appartmentNumber,
# MAGIC countryShortName,
# MAGIC stateCode,
# MAGIC personalAddressIndicator,
# MAGIC searchTerm1,
# MAGIC searchTerm2,
# MAGIC phoneNumber,
# MAGIC faxNumber,
# MAGIC addressTimeZone,
# MAGIC emailAddress,
# MAGIC uriAddress,
# MAGIC phoneNumberDisplayFormat,
# MAGIC faxDisplayFormat,
# MAGIC longitude,
# MAGIC latitude,
# MAGIC altitude,
# MAGIC precision,
# MAGIC communicationAddressNumber,
# MAGIC shortFormattedAddress,
# MAGIC shortFormattedAddress2,
# MAGIC addressLine0,
# MAGIC addressLine1,
# MAGIC addressLine2,
# MAGIC addressLine3,
# MAGIC addressLine4,
# MAGIC addressLine5,
# MAGIC addressLine6,
# MAGIC addressLine7,
# MAGIC addressLine8
# MAGIC from
# MAGIC cleansed.${vars.table}

# COMMAND ----------

# DBTITLE 1,[Verification] Compare Target and Source Data
# MAGIC %sql
# MAGIC select
# MAGIC businessPartnerNumber,
# MAGIC businessPartnerGUID,
# MAGIC addressNumber,
# MAGIC validFromDate,
# MAGIC validToDate,
# MAGIC titleCode,
# MAGIC businessPartnerName1,
# MAGIC businessPartnerName2,
# MAGIC businessPartnerName3,
# MAGIC coName,
# MAGIC cityName,
# MAGIC cityCode,
# MAGIC postalCode,
# MAGIC poBoxPostalCode,
# MAGIC companyPostalCode,
# MAGIC poBoxCode,
# MAGIC poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,
# MAGIC cityPoBoxCode,
# MAGIC streetName,
# MAGIC streetCode,
# MAGIC houseNumber,
# MAGIC houseNumber2,
# MAGIC streetType,
# MAGIC streetLine3,
# MAGIC streetLine4,
# MAGIC streetLine5,
# MAGIC building,
# MAGIC floorNumber,
# MAGIC appartmentNumber,
# MAGIC countryShortName,
# MAGIC stateCode,
# MAGIC personalAddressIndicator,
# MAGIC searchTerm1,
# MAGIC searchTerm2,
# MAGIC phoneNumber,
# MAGIC faxNumber,
# MAGIC addressTimeZone,
# MAGIC emailAddress,
# MAGIC uriAddress,
# MAGIC phoneNumberDisplayFormat,
# MAGIC faxDisplayFormat,
# MAGIC longitude,
# MAGIC latitude,
# MAGIC altitude,
# MAGIC precision,
# MAGIC communicationAddressNumber,
# MAGIC shortFormattedAddress,
# MAGIC shortFormattedAddress2,
# MAGIC addressLine0,
# MAGIC addressLine1,
# MAGIC addressLine2,
# MAGIC addressLine3,
# MAGIC addressLine4,
# MAGIC addressLine5,
# MAGIC addressLine6,
# MAGIC addressLine7,
# MAGIC addressLine8
# MAGIC from
# MAGIC cleansed.${vars.table}
# MAGIC except
# MAGIC select
# MAGIC businessPartnerNumber,
# MAGIC businessPartnerGUID,
# MAGIC addressNumber,
# MAGIC validFromDate,
# MAGIC validToDate,
# MAGIC titleCode,
# MAGIC businessPartnerName1,
# MAGIC businessPartnerName2,
# MAGIC businessPartnerName3,
# MAGIC coName,
# MAGIC cityName,
# MAGIC cityCode,
# MAGIC postalCode,
# MAGIC poBoxPostalCode,
# MAGIC companyPostalCode,
# MAGIC poBoxCode,
# MAGIC poBoxWithoutNumberIndicator,
# MAGIC poBoxCity,
# MAGIC cityPoBoxCode,
# MAGIC streetName,
# MAGIC streetCode,
# MAGIC houseNumber,
# MAGIC houseNumber2,
# MAGIC streetType,
# MAGIC streetLine3,
# MAGIC streetLine4,
# MAGIC streetLine5,
# MAGIC building,
# MAGIC floorNumber,
# MAGIC appartmentNumber,
# MAGIC countryShortName,
# MAGIC stateCode,
# MAGIC personalAddressIndicator,
# MAGIC searchTerm1,
# MAGIC searchTerm2,
# MAGIC phoneNumber,
# MAGIC faxNumber,
# MAGIC addressTimeZone,
# MAGIC emailAddress,
# MAGIC uriAddress,
# MAGIC phoneNumberDisplayFormat,
# MAGIC faxDisplayFormat,
# MAGIC longitude,
# MAGIC latitude,
# MAGIC altitude,
# MAGIC precision,
# MAGIC communicationAddressNumber,
# MAGIC shortFormattedAddress,
# MAGIC shortFormattedAddress2,
# MAGIC addressLine0,
# MAGIC addressLine1,
# MAGIC addressLine2,
# MAGIC addressLine3,
# MAGIC addressLine4,
# MAGIC addressLine5,
# MAGIC addressLine6,
# MAGIC addressLine7,
# MAGIC addressLine8
# MAGIC from
# MAGIC (
# MAGIC SELECT
# MAGIC case
# MAGIC when PARTNER is null then '' 
# MAGIC else PARTNER end as businessPartnerNumber,
# MAGIC PARTNER_GUID as businessPartnerGUID,
# MAGIC case
# MAGIC when ADDRNUMBER is null then '' 
# MAGIC else ADDRNUMBER end as addressNumber,
# MAGIC case
# MAGIC when DATE_FROM < '1900-01-01' then '1900-01-01'
# MAGIC else DATE_FROM end as validFromDate,
# MAGIC DATE_TO as validToDate,
# MAGIC TITLE as titleCode,
# MAGIC NAME1 as businessPartnerName1,
# MAGIC NAME2 as businessPartnerName2,
# MAGIC NAME3 as businessPartnerName3,
# MAGIC NAME_CO as coName,
# MAGIC CITY1 as cityName,
# MAGIC CITY_CODE as cityCode,
# MAGIC POST_CODE1 as postalCode,
# MAGIC POST_CODE2 as poBoxPostalCode,
# MAGIC POST_CODE3 as companyPostalCode,
# MAGIC PO_BOX as poBoxCode,
# MAGIC PO_BOX_NUM as poBoxWithoutNumberIndicator,
# MAGIC PO_BOX_LOC as poBoxCity,
# MAGIC CITY_CODE2 as cityPoBoxCode,
# MAGIC STREET as streetName,
# MAGIC STREETCODE as streetCode,
# MAGIC HOUSE_NUM1 as houseNumber,
# MAGIC HOUSE_NUM2 as houseNumber2,
# MAGIC STR_SUPPL1 as streetType,
# MAGIC STR_SUPPL2 as streetLine3,
# MAGIC STR_SUPPL3 as streetLine4,
# MAGIC LOCATION as streetLine5,
# MAGIC BUILDING as building,
# MAGIC FLOOR as floorNumber,
# MAGIC ROOMNUMBER as appartmentNumber,
# MAGIC COUNTRY as countryShortName,
# MAGIC REGION as stateCode,
# MAGIC PERS_ADDR as personalAddressIndicator,
# MAGIC SORT1 as searchTerm1,
# MAGIC SORT2 as searchTerm2,
# MAGIC TEL_NUMBER as phoneNumber,
# MAGIC FAX_NUMBER as faxNumber,
# MAGIC TIME_ZONE as addressTimeZone,
# MAGIC SMTP_ADDR as emailAddress,
# MAGIC URI_ADDR as uriAddress,
# MAGIC TELDISPLAY as phoneNumberDisplayFormat,
# MAGIC FAXDISPLAY as faxDisplayFormat,
# MAGIC LONGITUDE as longitude,
# MAGIC LATITUDE as latitude,
# MAGIC ALTITUDE as altitude,
# MAGIC PRECISID as precision,
# MAGIC ADDRCOMM as communicationAddressNumber,
# MAGIC ADDR_SHORT as shortFormattedAddress,
# MAGIC ADDR_SHORT_S as shortFormattedAddress2,
# MAGIC LINE0 as addressLine0,
# MAGIC LINE1 as addressLine1,
# MAGIC LINE2 as addressLine2,
# MAGIC LINE3 as addressLine3,
# MAGIC LINE4 as addressLine4,
# MAGIC LINE5 as addressLine5,
# MAGIC LINE6 as addressLine6,
# MAGIC LINE7 as addressLine7,
# MAGIC LINE8 as addressLine8
# MAGIC ,row_number() over (partition by PARTNER,ADDRNUMBER order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table}
# MAGIC )a where  a.rn = 1
