# Databricks notebook source
#config parameters
source = 'CRM' #either CRM or ISU
table = '0CRM_SRV_REQ_INCI_H'

environment = 'test'
storage_account_name = "sablobdaftest01"
storage_account_access_key = dbutils.secrets.get(scope="TestScope",key="test-sablob-key")
containerName = "archive"


# COMMAND ----------

# MAGIC %run ../../includes/tableEvaluation

# COMMAND ----------

# DBTITLE 1,[Source] with mapping
# MAGIC %sql
# MAGIC select
# MAGIC headerUUID,
# MAGIC utilitiesStructuredContract,
# MAGIC headerType,
# MAGIC postingDate,
# MAGIC transactionDescription,
# MAGIC logicalSystem,
# MAGIC headerCategory,
# MAGIC createdDate,
# MAGIC createdDateTime,
# MAGIC createdBy,
# MAGIC lastChangedDate,
# MAGIC lastChangedDateTime,
# MAGIC changedBy,
# MAGIC requestHeaderNumber,
# MAGIC scenarioId,
# MAGIC templateType,
# MAGIC recommendedPriority,
# MAGIC urgency,
# MAGIC impact,
# MAGIC escalation,
# MAGIC risk,
# MAGIC lastUpdatedAt,
# MAGIC activityCategory,
# MAGIC activityPriority,
# MAGIC activityDirection,
# MAGIC soldToParty,
# MAGIC salesEmployee,
# MAGIC responsibleEmployee,
# MAGIC contactPerson,
# MAGIC salesOrgResponsible,
# MAGIC salesOrg,
# MAGIC salesOffice,
# MAGIC salesGroup,
# MAGIC serviceOrgResponsible,
# MAGIC serviceOrg,
# MAGIC serviceTeam,
# MAGIC calendarDay,
# MAGIC calendarDatetime,
# MAGIC precedingTransactionGUID,
# MAGIC precedingDocumentObjectType,
# MAGIC precedingActivityGUID,
# MAGIC processCategory,
# MAGIC processCatalog,
# MAGIC processCodeGroup,
# MAGIC processCode,
# MAGIC precedingObjectType,
# MAGIC validTimestamp,
# MAGIC catalogCategoryC,
# MAGIC catalogC,
# MAGIC codeGroupC,
# MAGIC codeC,
# MAGIC defectCountC,
# MAGIC numberOfActivitiesC,
# MAGIC coherentAspectIdC,
# MAGIC coherentCategoryIdC,
# MAGIC dataElementGUIDC,
# MAGIC catalogCategoryD,
# MAGIC catalogD,
# MAGIC codeGroupD,
# MAGIC codeD,
# MAGIC defectCountD,
# MAGIC numberOfActivitiesD,
# MAGIC coherentAspectIdD,
# MAGIC coherentCategoryIdD,
# MAGIC dataElementGUIDD,
# MAGIC defectCountE,
# MAGIC numberOfActivitiesE,
# MAGIC dataElementGUIDE,
# MAGIC defectCountT,
# MAGIC numberOfActivitiesT,
# MAGIC dataElementGUIDT,
# MAGIC defectCountW,
# MAGIC numberOfActivitiesW,
# MAGIC dataElementGUIDW,
# MAGIC subjectProfileCategory,
# MAGIC dataElementGUID,
# MAGIC serviceLifeCycle,
# MAGIC serviceLifeCycleUnit,
# MAGIC workDuration,
# MAGIC workDurationUnit,
# MAGIC totalDuration,
# MAGIC totalDurationUnit,
# MAGIC requestStartDate,
# MAGIC requestEndDate,
# MAGIC dueDateTime,
# MAGIC completionDateTime,
# MAGIC firstEscalateDateTime,
# MAGIC secondEscalateDateTime,
# MAGIC activityReasonCode,
# MAGIC numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,
# MAGIC problemGUID,
# MAGIC notificationNumber,
# MAGIC contractiId,
# MAGIC podStatus,
# MAGIC statusProfile,
# MAGIC maximoWorkOrderNumber,
# MAGIC source,
# MAGIC projectId,
# MAGIC issueResponsibility,
# MAGIC businessPartnerNumber,
# MAGIC agreementNumber,
# MAGIC propertyNumber,
# MAGIC serviceArea,
# MAGIC serviceSubArea,
# MAGIC resolutionCode,
# MAGIC serviceCategoryCode,
# MAGIC rootCauseCode,
# MAGIC facilityNameCode,
# MAGIC secondaryAnalysisCode
# MAGIC from
# MAGIC (select
# MAGIC GUID as headerUUID,
# MAGIC OBJECT_ID as utilitiesStructuredContract,
# MAGIC PROCESS_TYPE as headerType,
# MAGIC POSTING_DATE as postingDate,
# MAGIC DESCRIPTION_UC as transactionDescription,
# MAGIC LOGICAL_SYSTEM as logicalSystem,
# MAGIC OBJECT_TYPE as headerCategory,
# MAGIC CREATED_AT as createdDate,
# MAGIC CREATED_TS as createdDateTime,
# MAGIC CREATED_BY as createdBy,
# MAGIC CHANGED_AT as lastChangedDate,
# MAGIC CHANGED_TS as lastChangedDateTime,
# MAGIC CHANGED_BY as changedBy,
# MAGIC NUM_OF_HEAD as requestHeaderNumber,
# MAGIC SCENARIO as scenarioId,
# MAGIC TEMPLATE_TYPE as templateType,
# MAGIC REC_PRIORITY as recommendedPriority,
# MAGIC URGENCY as urgency,
# MAGIC IMPACT as impact,
# MAGIC ESCALATION as escalation,
# MAGIC RISK as risk,
# MAGIC LAST_UPDATED_AT as lastUpdatedAt,
# MAGIC CATEGORY as activityCategory,
# MAGIC PRIORITY as activityPriority,
# MAGIC DIRECTION as activityDirection,
# MAGIC SOLD_TO_PARTY as soldToParty,
# MAGIC SALES_EMPLOYEE as salesEmployee,
# MAGIC PERSON_RESP as responsibleEmployee,
# MAGIC CONTACT_PERSON as contactPerson,
# MAGIC SALES_ORG_RESP as salesOrgResponsible,
# MAGIC SALES_ORG as salesOrg,
# MAGIC SALES_OFFICE as salesOffice,
# MAGIC SALES_GROUP as salesGroup,
# MAGIC SERVICE_ORG_RESP as serviceOrgResponsible,
# MAGIC SERVICE_ORG as serviceOrg,
# MAGIC SERVICE_TEAM as serviceTeam,
# MAGIC CALDAY as calendarDay,
# MAGIC CALDAY_TS as calendarDatetime,
# MAGIC PREDEC_OBJKEY as precedingTransactionGUID,
# MAGIC PREDEC_OBJTYPE as precedingDocumentObjectType,
# MAGIC PRED_ACT_GUID as precedingActivityGUID,
# MAGIC PROCESS_CATEGORY as processCategory,
# MAGIC PROCESS_CATALOG as processCatalog,
# MAGIC PROCESS_CODEGR as processCodeGroup,
# MAGIC PROCESS_CODE as processCode,
# MAGIC PROCESS_OBJTYPE as precedingObjectType,
# MAGIC QUOT_VALID_TS as validTimestamp,
# MAGIC CATALOG_TYPE_C as catalogCategoryC,
# MAGIC KATALOGART_C as catalogC,
# MAGIC CODEGRUPPE_C as codeGroupC,
# MAGIC CODE_C as codeC,
# MAGIC DEFQUANTITY_C as defectCountC,
# MAGIC COUNTER_C as numberOfActivitiesC,
# MAGIC ASP_ID_C as coherentAspectIdC,
# MAGIC CAT_ID_C as coherentCategoryIdC,
# MAGIC CC_CAT_SUBJECT_C as dataElementGUIDC,
# MAGIC CATALOG_TYPE_D as catalogCategoryD,
# MAGIC KATALOGART_D as catalogD,
# MAGIC CODEGRUPPE_D as codeGroupD,
# MAGIC CODE_D as codeD,
# MAGIC DEFQUANTITY_D as defectCountD,
# MAGIC COUNTER_D as numberOfActivitiesD,
# MAGIC ASP_ID_D as coherentAspectIdD,
# MAGIC CAT_ID_D as coherentCategoryIdD,
# MAGIC CC_CAT_SUBJECT_D as dataElementGUIDD,
# MAGIC DEFQUANTITY_E as defectCountE,
# MAGIC COUNTER_E as numberOfActivitiesE,
# MAGIC CC_CAT_SUBJECT_E as dataElementGUIDE,
# MAGIC DEFQUANTITY_T as defectCountT,
# MAGIC COUNTER_T as numberOfActivitiesT,
# MAGIC CC_CAT_SUBJECT_T as dataElementGUIDT,
# MAGIC DEFQUANTITY_W as defectCountW,
# MAGIC COUNTER_W as numberOfActivitiesW,
# MAGIC CC_CAT_SUBJECT_W as dataElementGUIDW,
# MAGIC PROFILE_TYPE as subjectProfileCategory,
# MAGIC CC_CAT_SUBJECT as dataElementGUID,
# MAGIC cast(LC_SRV_DURATION as bigint) as serviceLifeCycle,
# MAGIC LC_SRV_DUR_UNIT as serviceLifeCycleUnit,
# MAGIC WORK_DURATION as workDuration,
# MAGIC WORK_DURA_UNIT as workDurationUnit,
# MAGIC TOTAL_DURATION as totalDuration,
# MAGIC TOTAL_DURA_UNIT as totalDurationUnit,
# MAGIC REQ_START_DATE as requestStartDate,
# MAGIC REQ_END_DATE as requestEndDate,
# MAGIC DUE_DATE as dueDateTime,
# MAGIC COMPLETION_TS as completionDateTime,
# MAGIC ESCALATE_1_TS as firstEscalateDateTime,
# MAGIC ESCALATE_2_TS as secondEscalateDateTime,
# MAGIC CC_CAT_ACTREASON as activityReasonCode,
# MAGIC NO_OF_IR as numberOfInteractionRecords,
# MAGIC IN_COMPL_BEFORE as completedBeforeIndicator,
# MAGIC PROBLEM_GUID as problemGUID,
# MAGIC NOTIFICATION_NO as notificationNumber,
# MAGIC CRM_ISU_CONTRACT as contractiId,
# MAGIC STATUS as podStatus,
# MAGIC USER_STAT_PROC as statusProfile,
# MAGIC ZZ_MAX_REQ_NO as maximoWorkOrderNumber,
# MAGIC ZZAFLD000026 as source,
# MAGIC ZZAFLD000027 as projectId,
# MAGIC ZZAFLD000028 as issueResponsibility,
# MAGIC ZZREPORTED_BY as businessPartnerNumber,
# MAGIC ZZAGREEMENT_N as agreementNumber,
# MAGIC ZZ_PROPERTY_NO as propertyNumber,
# MAGIC ZZ_SR_AREA as serviceArea,
# MAGIC ZZ_SR_SUB_AREA as serviceSubArea,
# MAGIC ZZ_RESOLUTION_CD as resolutionCode,
# MAGIC ZZ_SR_CATEGORY_CD as serviceCategoryCode,
# MAGIC ZZ_ROOT_CAUSE_CD as rootCauseCode,
# MAGIC ZZ_X_FACILITY_NAME_CD as facilityNameCode,
# MAGIC ZZ_X_SECONDARY_ANALYSIS_CD as secondaryAnalysisCode
# MAGIC ,row_number() over (partition by GUID  order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table} -- WHERE LANGU = 'E'
# MAGIC )a where  a.rn = 1

# COMMAND ----------

# DBTITLE 1,[Verification] Count Check
# MAGIC %sql
# MAGIC select count (*) as RecordCount, 'Target' as TableName from cleansed.${vars.table}
# MAGIC union all
# MAGIC select count (*) as RecordCount, 'Source' as TableName from (select
# MAGIC headerUUID,
# MAGIC utilitiesStructuredContract,
# MAGIC headerType,
# MAGIC postingDate,
# MAGIC transactionDescription,
# MAGIC logicalSystem,
# MAGIC headerCategory,
# MAGIC createdDate,
# MAGIC createdDateTime,
# MAGIC createdBy,
# MAGIC lastChangedDate,
# MAGIC lastChangedDateTime,
# MAGIC changedBy,
# MAGIC requestHeaderNumber,
# MAGIC scenarioId,
# MAGIC templateType,
# MAGIC recommendedPriority,
# MAGIC urgency,
# MAGIC impact,
# MAGIC escalation,
# MAGIC risk,
# MAGIC lastUpdatedAt,
# MAGIC activityCategory,
# MAGIC activityPriority,
# MAGIC activityDirection,
# MAGIC soldToParty,
# MAGIC salesEmployee,
# MAGIC responsibleEmployee,
# MAGIC contactPerson,
# MAGIC salesOrgResponsible,
# MAGIC salesOrg,
# MAGIC salesOffice,
# MAGIC salesGroup,
# MAGIC serviceOrgResponsible,
# MAGIC serviceOrg,
# MAGIC serviceTeam,
# MAGIC calendarDay,
# MAGIC calendarDatetime,
# MAGIC precedingTransactionGUID,
# MAGIC precedingDocumentObjectType,
# MAGIC precedingActivityGUID,
# MAGIC processCategory,
# MAGIC processCatalog,
# MAGIC processCodeGroup,
# MAGIC processCode,
# MAGIC precedingObjectType,
# MAGIC validTimestamp,
# MAGIC catalogCategoryC,
# MAGIC catalogC,
# MAGIC codeGroupC,
# MAGIC codeC,
# MAGIC defectCountC,
# MAGIC numberOfActivitiesC,
# MAGIC coherentAspectIdC,
# MAGIC coherentCategoryIdC,
# MAGIC dataElementGUIDC,
# MAGIC catalogCategoryD,
# MAGIC catalogD,
# MAGIC codeGroupD,
# MAGIC codeD,
# MAGIC defectCountD,
# MAGIC numberOfActivitiesD,
# MAGIC coherentAspectIdD,
# MAGIC coherentCategoryIdD,
# MAGIC dataElementGUIDD,
# MAGIC defectCountE,
# MAGIC numberOfActivitiesE,
# MAGIC dataElementGUIDE,
# MAGIC defectCountT,
# MAGIC numberOfActivitiesT,
# MAGIC dataElementGUIDT,
# MAGIC defectCountW,
# MAGIC numberOfActivitiesW,
# MAGIC dataElementGUIDW,
# MAGIC subjectProfileCategory,
# MAGIC dataElementGUID,
# MAGIC serviceLifeCycle,
# MAGIC serviceLifeCycleUnit,
# MAGIC workDuration,
# MAGIC workDurationUnit,
# MAGIC totalDuration,
# MAGIC totalDurationUnit,
# MAGIC requestStartDate,
# MAGIC requestEndDate,
# MAGIC dueDateTime,
# MAGIC completionDateTime,
# MAGIC firstEscalateDateTime,
# MAGIC secondEscalateDateTime,
# MAGIC activityReasonCode,
# MAGIC numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,
# MAGIC problemGUID,
# MAGIC notificationNumber,
# MAGIC contractiId,
# MAGIC podStatus,
# MAGIC statusProfile,
# MAGIC maximoWorkOrderNumber,
# MAGIC source,
# MAGIC projectId,
# MAGIC issueResponsibility,
# MAGIC businessPartnerNumber,
# MAGIC agreementNumber,
# MAGIC propertyNumber,
# MAGIC serviceArea,
# MAGIC serviceSubArea,
# MAGIC resolutionCode,
# MAGIC serviceCategoryCode,
# MAGIC rootCauseCode,
# MAGIC facilityNameCode,
# MAGIC secondaryAnalysisCode
# MAGIC from
# MAGIC (select
# MAGIC GUID as headerUUID,
# MAGIC OBJECT_ID as utilitiesStructuredContract,
# MAGIC PROCESS_TYPE as headerType,
# MAGIC POSTING_DATE as postingDate,
# MAGIC DESCRIPTION_UC as transactionDescription,
# MAGIC LOGICAL_SYSTEM as logicalSystem,
# MAGIC OBJECT_TYPE as headerCategory,
# MAGIC CREATED_AT as createdDate,
# MAGIC cast(CREATED_TS as timestamp) as createdDateTime,
# MAGIC CREATED_BY as createdBy,
# MAGIC CHANGED_AT as lastChangedDate,
# MAGIC CHANGED_TS as lastChangedDateTime,
# MAGIC CHANGED_BY as changedBy,
# MAGIC NUM_OF_HEAD as requestHeaderNumber,
# MAGIC SCENARIO as scenarioId,
# MAGIC TEMPLATE_TYPE as templateType,
# MAGIC REC_PRIORITY as recommendedPriority,
# MAGIC URGENCY as urgency,
# MAGIC IMPACT as impact,
# MAGIC ESCALATION as escalation,
# MAGIC RISK as risk,
# MAGIC LAST_UPDATED_AT as lastUpdatedAt,
# MAGIC CATEGORY as activityCategory,
# MAGIC PRIORITY as activityPriority,
# MAGIC DIRECTION as activityDirection,
# MAGIC SOLD_TO_PARTY as soldToParty,
# MAGIC SALES_EMPLOYEE as salesEmployee,
# MAGIC PERSON_RESP as responsibleEmployee,
# MAGIC CONTACT_PERSON as contactPerson,
# MAGIC SALES_ORG_RESP as salesOrgResponsible,
# MAGIC SALES_ORG as salesOrg,
# MAGIC SALES_OFFICE as salesOffice,
# MAGIC SALES_GROUP as salesGroup,
# MAGIC SERVICE_ORG_RESP as serviceOrgResponsible,
# MAGIC SERVICE_ORG as serviceOrg,
# MAGIC SERVICE_TEAM as serviceTeam,
# MAGIC CALDAY as calendarDay,
# MAGIC CALDAY_TS as calendarDatetime,
# MAGIC PREDEC_OBJKEY as precedingTransactionGUID,
# MAGIC PREDEC_OBJTYPE as precedingDocumentObjectType,
# MAGIC PRED_ACT_GUID as precedingActivityGUID,
# MAGIC PROCESS_CATEGORY as processCategory,
# MAGIC PROCESS_CATALOG as processCatalog,
# MAGIC PROCESS_CODEGR as processCodeGroup,
# MAGIC PROCESS_CODE as processCode,
# MAGIC PROCESS_OBJTYPE as precedingObjectType,
# MAGIC QUOT_VALID_TS as validTimestamp,
# MAGIC CATALOG_TYPE_C as catalogCategoryC,
# MAGIC KATALOGART_C as catalogC,
# MAGIC CODEGRUPPE_C as codeGroupC,
# MAGIC CODE_C as codeC,
# MAGIC DEFQUANTITY_C as defectCountC,
# MAGIC COUNTER_C as numberOfActivitiesC,
# MAGIC ASP_ID_C as coherentAspectIdC,
# MAGIC CAT_ID_C as coherentCategoryIdC,
# MAGIC CC_CAT_SUBJECT_C as dataElementGUIDC,
# MAGIC CATALOG_TYPE_D as catalogCategoryD,
# MAGIC KATALOGART_D as catalogD,
# MAGIC CODEGRUPPE_D as codeGroupD,
# MAGIC CODE_D as codeD,
# MAGIC DEFQUANTITY_D as defectCountD,
# MAGIC COUNTER_D as numberOfActivitiesD,
# MAGIC ASP_ID_D as coherentAspectIdD,
# MAGIC CAT_ID_D as coherentCategoryIdD,
# MAGIC CC_CAT_SUBJECT_D as dataElementGUIDD,
# MAGIC DEFQUANTITY_E as defectCountE,
# MAGIC COUNTER_E as numberOfActivitiesE,
# MAGIC CC_CAT_SUBJECT_E as dataElementGUIDE,
# MAGIC DEFQUANTITY_T as defectCountT,
# MAGIC COUNTER_T as numberOfActivitiesT,
# MAGIC CC_CAT_SUBJECT_T as dataElementGUIDT,
# MAGIC DEFQUANTITY_W as defectCountW,
# MAGIC COUNTER_W as numberOfActivitiesW,
# MAGIC CC_CAT_SUBJECT_W as dataElementGUIDW,
# MAGIC PROFILE_TYPE as subjectProfileCategory,
# MAGIC CC_CAT_SUBJECT as dataElementGUID,
# MAGIC LC_SRV_DURATION as serviceLifeCycle,
# MAGIC LC_SRV_DUR_UNIT as serviceLifeCycleUnit,
# MAGIC WORK_DURATION as workDuration,
# MAGIC WORK_DURA_UNIT as workDurationUnit,
# MAGIC TOTAL_DURATION as totalDuration,
# MAGIC TOTAL_DURA_UNIT as totalDurationUnit,
# MAGIC REQ_START_DATE as requestStartDate,
# MAGIC REQ_END_DATE as requestEndDate,
# MAGIC DUE_DATE as dueDateTime,
# MAGIC COMPLETION_TS as completionDateTime,
# MAGIC ESCALATE_1_TS as firstEscalateDateTime,
# MAGIC ESCALATE_2_TS as secondEscalateDateTime,
# MAGIC CC_CAT_ACTREASON as activityReasonCode,
# MAGIC NO_OF_IR as numberOfInteractionRecords,
# MAGIC IN_COMPL_BEFORE as completedBeforeIndicator,
# MAGIC PROBLEM_GUID as problemGUID,
# MAGIC NOTIFICATION_NO as notificationNumber,
# MAGIC CRM_ISU_CONTRACT as contractiId,
# MAGIC STATUS as podStatus,
# MAGIC USER_STAT_PROC as statusProfile,
# MAGIC ZZ_MAX_REQ_NO as maximoWorkOrderNumber,
# MAGIC ZZAFLD000026 as source,
# MAGIC ZZAFLD000027 as projectId,
# MAGIC ZZAFLD000028 as issueResponsibility,
# MAGIC ZZREPORTED_BY as businessPartnerNumber,
# MAGIC ZZAGREEMENT_N as agreementNumber,
# MAGIC ZZ_PROPERTY_NO as propertyNumber,
# MAGIC ZZ_SR_AREA as serviceArea,
# MAGIC ZZ_SR_SUB_AREA as serviceSubArea,
# MAGIC ZZ_RESOLUTION_CD as resolutionCode,
# MAGIC ZZ_SR_CATEGORY_CD as serviceCategoryCode,
# MAGIC ZZ_ROOT_CAUSE_CD as rootCauseCode,
# MAGIC ZZ_X_FACILITY_NAME_CD as facilityNameCode,
# MAGIC ZZ_X_SECONDARY_ANALYSIS_CD as secondaryAnalysisCode
# MAGIC ,row_number() over (partition by GUID  order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table} -- WHERE LANGU = 'E'
# MAGIC )a where  a.rn = 1)

# COMMAND ----------

# DBTITLE 1,[Verification] Duplicate Checks
# MAGIC %sql
# MAGIC SELECT headerUUID,utilitiesStructuredContract,headerType,postingDate,transactionDescription,logicalSystem,headerCategory,
# MAGIC createdDate,createdDateTime,createdBy,lastChangedDate,lastChangedDateTime,changedBy,requestHeaderNumber,scenarioId,
# MAGIC templateType,recommendedPriority,urgency,impact,escalation,risk,lastUpdatedAt,activityCategory,activityPriority,activityDirection,
# MAGIC soldToParty,salesEmployee,responsibleEmployee,contactPerson,salesOrgResponsible,salesOrg,salesOffice,salesGroup,serviceOrgResponsible,
# MAGIC serviceOrg,serviceTeam,calendarDay,calendarDatetime,precedingTransactionGUID,precedingDocumentObjectType,precedingActivityGUID,
# MAGIC processCategory,processCatalog,processCodeGroup,processCode,precedingObjectType,validTimestamp,catalogCategoryC,catalogC,
# MAGIC codeGroupC,codeC,defectCountC,numberOfActivitiesC,coherentAspectIdC,coherentCategoryIdC,dataElementGUIDC,catalogCategoryD,
# MAGIC catalogD,codeGroupD,codeD,defectCountD,numberOfActivitiesD,coherentAspectIdD,coherentCategoryIdD,dataElementGUIDD,defectCountE,
# MAGIC numberOfActivitiesE,dataElementGUIDE,defectCountT,numberOfActivitiesT,dataElementGUIDT,defectCountW,numberOfActivitiesW,dataElementGUIDW,
# MAGIC subjectProfileCategory,dataElementGUID,serviceLifeCycle,serviceLifeCycleUnit,workDuration,workDurationUnit,totalDuration,totalDurationUnit,
# MAGIC requestStartDate,requestEndDate,dueDateTime,completionDateTime,firstEscalateDateTime,secondEscalateDateTime,activityReasonCode,numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,problemGUID,notificationNumber,contractiId,podStatus,statusProfile,maximoWorkOrderNumber,source,projectId,
# MAGIC issueResponsibility,businessPartnerNumber,agreementNumber,propertyNumber,serviceArea,serviceSubArea,resolutionCode,serviceCategoryCode,
# MAGIC rootCauseCode,facilityNameCode,secondaryAnalysisCode, COUNT (*) as count
# MAGIC FROM cleansed.${vars.table}
# MAGIC GROUP BY headerUUID,utilitiesStructuredContract,headerType,postingDate,transactionDescription,logicalSystem,headerCategory,
# MAGIC createdDate,createdDateTime,createdBy,lastChangedDate,lastChangedDateTime,changedBy,requestHeaderNumber,scenarioId,
# MAGIC templateType,recommendedPriority,urgency,impact,escalation,risk,lastUpdatedAt,activityCategory,activityPriority,activityDirection,
# MAGIC soldToParty,salesEmployee,responsibleEmployee,contactPerson,salesOrgResponsible,salesOrg,salesOffice,salesGroup,serviceOrgResponsible,
# MAGIC serviceOrg,serviceTeam,calendarDay,calendarDatetime,precedingTransactionGUID,precedingDocumentObjectType,precedingActivityGUID,
# MAGIC processCategory,processCatalog,processCodeGroup,processCode,precedingObjectType,validTimestamp,catalogCategoryC,catalogC,
# MAGIC codeGroupC,codeC,defectCountC,numberOfActivitiesC,coherentAspectIdC,coherentCategoryIdC,dataElementGUIDC,catalogCategoryD,
# MAGIC catalogD,codeGroupD,codeD,defectCountD,numberOfActivitiesD,coherentAspectIdD,coherentCategoryIdD,dataElementGUIDD,defectCountE,
# MAGIC numberOfActivitiesE,dataElementGUIDE,defectCountT,numberOfActivitiesT,dataElementGUIDT,defectCountW,numberOfActivitiesW,dataElementGUIDW,
# MAGIC subjectProfileCategory,dataElementGUID,serviceLifeCycle,serviceLifeCycleUnit,workDuration,workDurationUnit,totalDuration,totalDurationUnit,
# MAGIC requestStartDate,requestEndDate,dueDateTime,completionDateTime,firstEscalateDateTime,secondEscalateDateTime,activityReasonCode,numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,problemGUID,notificationNumber,contractiId,podStatus,statusProfile,maximoWorkOrderNumber,source,projectId,
# MAGIC issueResponsibility,businessPartnerNumber,agreementNumber,propertyNumber,serviceArea,serviceSubArea,resolutionCode,serviceCategoryCode,
# MAGIC rootCauseCode,facilityNameCode,secondaryAnalysisCode
# MAGIC HAVING COUNT (*) > 1

# COMMAND ----------

# DBTITLE 1,[Verification] Duplicate Checks
# MAGIC %sql
# MAGIC SELECT * FROM (
# MAGIC SELECT
# MAGIC *,
# MAGIC row_number() OVER(PARTITION BY headerUUID order by headerUUID) as rn
# MAGIC FROM  cleansed.${vars.table}
# MAGIC )a where a.rn > 1

# COMMAND ----------

# DBTITLE 1,[Verification] Compare Source and Target Data
# MAGIC %sql
# MAGIC select
# MAGIC headerUUID,
# MAGIC utilitiesStructuredContract,
# MAGIC headerType,
# MAGIC postingDate,
# MAGIC transactionDescription,
# MAGIC logicalSystem,
# MAGIC headerCategory,
# MAGIC createdDate,
# MAGIC createdDateTime,
# MAGIC createdBy,
# MAGIC lastChangedDate,
# MAGIC lastChangedDateTime,
# MAGIC changedBy,
# MAGIC requestHeaderNumber,
# MAGIC scenarioId,
# MAGIC templateType,
# MAGIC recommendedPriority,
# MAGIC urgency,
# MAGIC impact,
# MAGIC escalation,
# MAGIC risk,
# MAGIC lastUpdatedAt,
# MAGIC activityCategory,
# MAGIC activityPriority,
# MAGIC activityDirection,
# MAGIC soldToParty,
# MAGIC salesEmployee,
# MAGIC responsibleEmployee,
# MAGIC contactPerson,
# MAGIC salesOrgResponsible,
# MAGIC salesOrg,
# MAGIC salesOffice,
# MAGIC salesGroup,
# MAGIC serviceOrgResponsible,
# MAGIC serviceOrg,
# MAGIC serviceTeam,
# MAGIC calendarDay,
# MAGIC calendarDatetime,
# MAGIC precedingTransactionGUID,
# MAGIC precedingDocumentObjectType,
# MAGIC precedingActivityGUID,
# MAGIC processCategory,
# MAGIC processCatalog,
# MAGIC processCodeGroup,
# MAGIC processCode,
# MAGIC precedingObjectType,
# MAGIC validTimestamp,
# MAGIC catalogCategoryC,
# MAGIC catalogC,
# MAGIC codeGroupC,
# MAGIC codeC,
# MAGIC defectCountC,
# MAGIC numberOfActivitiesC,
# MAGIC coherentAspectIdC,
# MAGIC coherentCategoryIdC,
# MAGIC dataElementGUIDC,
# MAGIC catalogCategoryD,
# MAGIC catalogD,
# MAGIC codeGroupD,
# MAGIC codeD,
# MAGIC defectCountD,
# MAGIC numberOfActivitiesD,
# MAGIC coherentAspectIdD,
# MAGIC coherentCategoryIdD,
# MAGIC dataElementGUIDD,
# MAGIC defectCountE,
# MAGIC numberOfActivitiesE,
# MAGIC dataElementGUIDE,
# MAGIC defectCountT,
# MAGIC numberOfActivitiesT,
# MAGIC dataElementGUIDT,
# MAGIC defectCountW,
# MAGIC numberOfActivitiesW,
# MAGIC dataElementGUIDW,
# MAGIC subjectProfileCategory,
# MAGIC dataElementGUID,
# MAGIC serviceLifeCycle,
# MAGIC serviceLifeCycleUnit,
# MAGIC workDuration,
# MAGIC workDurationUnit,
# MAGIC totalDuration,
# MAGIC totalDurationUnit,
# MAGIC requestStartDate,
# MAGIC requestEndDate,
# MAGIC dueDateTime,
# MAGIC completionDateTime,
# MAGIC firstEscalateDateTime,
# MAGIC secondEscalateDateTime,
# MAGIC activityReasonCode,
# MAGIC numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,
# MAGIC problemGUID,
# MAGIC notificationNumber,
# MAGIC contractiId,
# MAGIC podStatus,
# MAGIC statusProfile,
# MAGIC maximoWorkOrderNumber,
# MAGIC source,
# MAGIC projectId,
# MAGIC issueResponsibility,
# MAGIC businessPartnerNumber,
# MAGIC agreementNumber,
# MAGIC propertyNumber,
# MAGIC serviceArea,
# MAGIC serviceSubArea,
# MAGIC resolutionCode,
# MAGIC serviceCategoryCode,
# MAGIC rootCauseCode,
# MAGIC facilityNameCode,
# MAGIC secondaryAnalysisCode
# MAGIC from
# MAGIC (select
# MAGIC case
# MAGIC when GUID is null then ''
# MAGIC else GUID end as headerUUID,
# MAGIC OBJECT_ID as utilitiesStructuredContract,
# MAGIC PROCESS_TYPE as headerType,
# MAGIC POSTING_DATE as postingDate,
# MAGIC DESCRIPTION_UC as transactionDescription,
# MAGIC LOGICAL_SYSTEM as logicalSystem,
# MAGIC OBJECT_TYPE as headerCategory,
# MAGIC CREATED_AT as createdDate,
# MAGIC to_timestamp(cast(CREATED_TS as STRING),'yyyyMMddHHmmss') as createdDatetime,
# MAGIC CREATED_BY as createdBy,
# MAGIC CHANGED_AT as lastChangedDate,
# MAGIC to_timestamp(cast(CHANGED_TS as STRING),'yyyyMMddHHmmss') as lastChangedDateTime,
# MAGIC CHANGED_BY as changedBy,
# MAGIC NUM_OF_HEAD as requestHeaderNumber,
# MAGIC SCENARIO as scenarioId,
# MAGIC TEMPLATE_TYPE as templateType,
# MAGIC REC_PRIORITY as recommendedPriority,
# MAGIC URGENCY as urgency,
# MAGIC IMPACT as impact,
# MAGIC ESCALATION as escalation,
# MAGIC RISK as risk,
# MAGIC to_timestamp(cast(LAST_UPDATED_AT as STRING),'yyyyMMddHHmmss') as lastUpdatedAt,
# MAGIC CATEGORY as activityCategory,
# MAGIC PRIORITY as activityPriority,
# MAGIC DIRECTION as activityDirection,
# MAGIC SOLD_TO_PARTY as soldToParty,
# MAGIC SALES_EMPLOYEE as salesEmployee,
# MAGIC PERSON_RESP as responsibleEmployee,
# MAGIC CONTACT_PERSON as contactPerson,
# MAGIC SALES_ORG_RESP as salesOrgResponsible,
# MAGIC SALES_ORG as salesOrg,
# MAGIC SALES_OFFICE as salesOffice,
# MAGIC SALES_GROUP as salesGroup,
# MAGIC SERVICE_ORG_RESP as serviceOrgResponsible,
# MAGIC SERVICE_ORG as serviceOrg,
# MAGIC SERVICE_TEAM as serviceTeam,
# MAGIC CALDAY as calendarDay,
# MAGIC to_timestamp(cast(CALDAY_TS as STRING),'yyyyMMddHHmmss') as calendarDatetime,
# MAGIC PREDEC_OBJKEY as precedingTransactionGUID,
# MAGIC PREDEC_OBJTYPE as precedingDocumentObjectType,
# MAGIC PRED_ACT_GUID as precedingActivityGUID,
# MAGIC PROCESS_CATEGORY as processCategory,
# MAGIC PROCESS_CATALOG as processCatalog,
# MAGIC PROCESS_CODEGR as processCodeGroup,
# MAGIC PROCESS_CODE as processCode,
# MAGIC PROCESS_OBJTYPE as precedingObjectType,
# MAGIC to_timestamp(cast(QUOT_VALID_TS as STRING),'yyyyMMddHHmmss') as validTimestamp,
# MAGIC CATALOG_TYPE_C as catalogCategoryC,
# MAGIC KATALOGART_C as catalogC,
# MAGIC CODEGRUPPE_C as codeGroupC,
# MAGIC CODE_C as codeC,
# MAGIC DEFQUANTITY_C as defectCountC,
# MAGIC COUNTER_C as numberOfActivitiesC,
# MAGIC ASP_ID_C as coherentAspectIdC,
# MAGIC CAT_ID_C as coherentCategoryIdC,
# MAGIC CC_CAT_SUBJECT_C as dataElementGUIDC,
# MAGIC CATALOG_TYPE_D as catalogCategoryD,
# MAGIC KATALOGART_D as catalogD,
# MAGIC CODEGRUPPE_D as codeGroupD,
# MAGIC CODE_D as codeD,
# MAGIC DEFQUANTITY_D as defectCountD,
# MAGIC COUNTER_D as numberOfActivitiesD,
# MAGIC ASP_ID_D as coherentAspectIdD,
# MAGIC CAT_ID_D as coherentCategoryIdD,
# MAGIC CC_CAT_SUBJECT_D as dataElementGUIDD,
# MAGIC DEFQUANTITY_E as defectCountE,
# MAGIC COUNTER_E as numberOfActivitiesE,
# MAGIC CC_CAT_SUBJECT_E as dataElementGUIDE,
# MAGIC DEFQUANTITY_T as defectCountT,
# MAGIC COUNTER_T as numberOfActivitiesT,
# MAGIC CC_CAT_SUBJECT_T as dataElementGUIDT,
# MAGIC DEFQUANTITY_W as defectCountW,
# MAGIC COUNTER_W as numberOfActivitiesW,
# MAGIC CC_CAT_SUBJECT_W as dataElementGUIDW,
# MAGIC PROFILE_TYPE as subjectProfileCategory,
# MAGIC CC_CAT_SUBJECT as dataElementGUID,
# MAGIC cast(LC_SRV_DURATION as bigint) as serviceLifeCycle,
# MAGIC LC_SRV_DUR_UNIT as serviceLifeCycleUnit,
# MAGIC WORK_DURATION as workDuration,
# MAGIC WORK_DURA_UNIT as workDurationUnit,
# MAGIC TOTAL_DURATION as totalDuration,
# MAGIC TOTAL_DURA_UNIT as totalDurationUnit,
# MAGIC to_timestamp(cast(REQ_START_DATE as STRING),'yyyyMMddHHmmss') as requestStartDate,
# MAGIC to_timestamp(cast(REQ_END_DATE as STRING),'yyyyMMddHHmmss') as requestEndDate,
# MAGIC to_timestamp(cast(DUE_DATE as STRING),'yyyyMMddHHmmss') as dueDateTime,
# MAGIC to_timestamp(cast(COMPLETION_TS as STRING),'yyyyMMddHHmmss') as completionDateTime,
# MAGIC to_timestamp(cast(ESCALATE_1_TS as STRING),'yyyyMMddHHmmss') as firstEscalateDateTime,
# MAGIC to_timestamp(cast(ESCALATE_2_TS as STRING),'yyyyMMddHHmmss') as secondEscalateDateTime,
# MAGIC CC_CAT_ACTREASON as activityReasonCode,
# MAGIC NO_OF_IR as numberOfInteractionRecords,
# MAGIC IN_COMPL_BEFORE as completedBeforeIndicator,
# MAGIC PROBLEM_GUID as problemGUID,
# MAGIC NOTIFICATION_NO as notificationNumber,
# MAGIC CRM_ISU_CONTRACT as contractiId,
# MAGIC STATUS as podStatus,
# MAGIC USER_STAT_PROC as statusProfile,
# MAGIC ZZ_MAX_REQ_NO as maximoWorkOrderNumber,
# MAGIC ZZAFLD000026 as source,
# MAGIC ZZAFLD000027 as projectId,
# MAGIC ZZAFLD000028 as issueResponsibility,
# MAGIC ZZREPORTED_BY as businessPartnerNumber,
# MAGIC ZZAGREEMENT_N as agreementNumber,
# MAGIC ZZ_PROPERTY_NO as propertyNumber,
# MAGIC ZZ_SR_AREA as serviceArea,
# MAGIC ZZ_SR_SUB_AREA as serviceSubArea,
# MAGIC ZZ_RESOLUTION_CD as resolutionCode,
# MAGIC ZZ_SR_CATEGORY_CD as serviceCategoryCode,
# MAGIC ZZ_ROOT_CAUSE_CD as rootCauseCode,
# MAGIC ZZ_X_FACILITY_NAME_CD as facilityNameCode,
# MAGIC ZZ_X_SECONDARY_ANALYSIS_CD as secondaryAnalysisCode
# MAGIC ,row_number() over (partition by GUID  order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table} -- WHERE LANGU = 'E'
# MAGIC )a where  a.rn = 1
# MAGIC except
# MAGIC select
# MAGIC headerUUID,
# MAGIC utilitiesStructuredContract,
# MAGIC headerType,
# MAGIC postingDate,
# MAGIC transactionDescription,
# MAGIC logicalSystem,
# MAGIC headerCategory,
# MAGIC createdDate,
# MAGIC createdDateTime,
# MAGIC createdBy,
# MAGIC lastChangedDate,
# MAGIC lastChangedDateTime,
# MAGIC changedBy,
# MAGIC requestHeaderNumber,
# MAGIC scenarioId,
# MAGIC templateType,
# MAGIC recommendedPriority,
# MAGIC urgency,
# MAGIC impact,
# MAGIC escalation,
# MAGIC risk,
# MAGIC lastUpdatedAt,
# MAGIC activityCategory,
# MAGIC activityPriority,
# MAGIC activityDirection,
# MAGIC soldToParty,
# MAGIC salesEmployee,
# MAGIC responsibleEmployee,
# MAGIC contactPerson,
# MAGIC salesOrgResponsible,
# MAGIC salesOrg,
# MAGIC salesOffice,
# MAGIC salesGroup,
# MAGIC serviceOrgResponsible,
# MAGIC serviceOrg,
# MAGIC serviceTeam,
# MAGIC calendarDay,
# MAGIC calendarDatetime,
# MAGIC precedingTransactionGUID,
# MAGIC precedingDocumentObjectType,
# MAGIC precedingActivityGUID,
# MAGIC processCategory,
# MAGIC processCatalog,
# MAGIC processCodeGroup,
# MAGIC processCode,
# MAGIC precedingObjectType,
# MAGIC validTimestamp,
# MAGIC catalogCategoryC,
# MAGIC catalogC,
# MAGIC codeGroupC,
# MAGIC codeC,
# MAGIC defectCountC,
# MAGIC numberOfActivitiesC,
# MAGIC coherentAspectIdC,
# MAGIC coherentCategoryIdC,
# MAGIC dataElementGUIDC,
# MAGIC catalogCategoryD,
# MAGIC catalogD,
# MAGIC codeGroupD,
# MAGIC codeD,
# MAGIC defectCountD,
# MAGIC numberOfActivitiesD,
# MAGIC coherentAspectIdD,
# MAGIC coherentCategoryIdD,
# MAGIC dataElementGUIDD,
# MAGIC defectCountE,
# MAGIC numberOfActivitiesE,
# MAGIC dataElementGUIDE,
# MAGIC defectCountT,
# MAGIC numberOfActivitiesT,
# MAGIC dataElementGUIDT,
# MAGIC defectCountW,
# MAGIC numberOfActivitiesW,
# MAGIC dataElementGUIDW,
# MAGIC subjectProfileCategory,
# MAGIC dataElementGUID,
# MAGIC serviceLifeCycle,
# MAGIC serviceLifeCycleUnit,
# MAGIC workDuration,
# MAGIC workDurationUnit,
# MAGIC totalDuration,
# MAGIC totalDurationUnit,
# MAGIC requestStartDate,
# MAGIC requestEndDate,
# MAGIC dueDateTime,
# MAGIC completionDateTime,
# MAGIC firstEscalateDateTime,
# MAGIC secondEscalateDateTime,
# MAGIC activityReasonCode,
# MAGIC numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,
# MAGIC problemGUID,
# MAGIC notificationNumber,
# MAGIC contractiId,
# MAGIC podStatus,
# MAGIC statusProfile,
# MAGIC maximoWorkOrderNumber,
# MAGIC source,
# MAGIC projectId,
# MAGIC issueResponsibility,
# MAGIC businessPartnerNumber,
# MAGIC agreementNumber,
# MAGIC propertyNumber,
# MAGIC serviceArea,
# MAGIC serviceSubArea,
# MAGIC resolutionCode,
# MAGIC serviceCategoryCode,
# MAGIC rootCauseCode,
# MAGIC facilityNameCode,
# MAGIC secondaryAnalysisCode
# MAGIC from
# MAGIC cleansed.${vars.table}

# COMMAND ----------

# DBTITLE 1,[Verification] Compare Target and Source Data
# MAGIC %sql
# MAGIC select
# MAGIC headerUUID,
# MAGIC utilitiesStructuredContract,
# MAGIC headerType,
# MAGIC postingDate,
# MAGIC transactionDescription,
# MAGIC logicalSystem,
# MAGIC headerCategory,
# MAGIC createdDate,
# MAGIC createdDateTime,
# MAGIC createdBy,
# MAGIC lastChangedDate,
# MAGIC lastChangedDateTime,
# MAGIC changedBy,
# MAGIC requestHeaderNumber,
# MAGIC scenarioId,
# MAGIC templateType,
# MAGIC recommendedPriority,
# MAGIC urgency,
# MAGIC impact,
# MAGIC escalation,
# MAGIC risk,
# MAGIC lastUpdatedAt,
# MAGIC activityCategory,
# MAGIC activityPriority,
# MAGIC activityDirection,
# MAGIC soldToParty,
# MAGIC salesEmployee,
# MAGIC responsibleEmployee,
# MAGIC contactPerson,
# MAGIC salesOrgResponsible,
# MAGIC salesOrg,
# MAGIC salesOffice,
# MAGIC salesGroup,
# MAGIC serviceOrgResponsible,
# MAGIC serviceOrg,
# MAGIC serviceTeam,
# MAGIC calendarDay,
# MAGIC calendarDatetime,
# MAGIC precedingTransactionGUID,
# MAGIC precedingDocumentObjectType,
# MAGIC precedingActivityGUID,
# MAGIC processCategory,
# MAGIC processCatalog,
# MAGIC processCodeGroup,
# MAGIC processCode,
# MAGIC precedingObjectType,
# MAGIC validTimestamp,
# MAGIC catalogCategoryC,
# MAGIC catalogC,
# MAGIC codeGroupC,
# MAGIC codeC,
# MAGIC defectCountC,
# MAGIC numberOfActivitiesC,
# MAGIC coherentAspectIdC,
# MAGIC coherentCategoryIdC,
# MAGIC dataElementGUIDC,
# MAGIC catalogCategoryD,
# MAGIC catalogD,
# MAGIC codeGroupD,
# MAGIC codeD,
# MAGIC defectCountD,
# MAGIC numberOfActivitiesD,
# MAGIC coherentAspectIdD,
# MAGIC coherentCategoryIdD,
# MAGIC dataElementGUIDD,
# MAGIC defectCountE,
# MAGIC numberOfActivitiesE,
# MAGIC dataElementGUIDE,
# MAGIC defectCountT,
# MAGIC numberOfActivitiesT,
# MAGIC dataElementGUIDT,
# MAGIC defectCountW,
# MAGIC numberOfActivitiesW,
# MAGIC dataElementGUIDW,
# MAGIC subjectProfileCategory,
# MAGIC dataElementGUID,
# MAGIC serviceLifeCycle,
# MAGIC serviceLifeCycleUnit,
# MAGIC workDuration,
# MAGIC workDurationUnit,
# MAGIC totalDuration,
# MAGIC totalDurationUnit,
# MAGIC requestStartDate,
# MAGIC requestEndDate,
# MAGIC dueDateTime,
# MAGIC completionDateTime,
# MAGIC firstEscalateDateTime,
# MAGIC secondEscalateDateTime,
# MAGIC activityReasonCode,
# MAGIC numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,
# MAGIC problemGUID,
# MAGIC notificationNumber,
# MAGIC contractiId,
# MAGIC podStatus,
# MAGIC statusProfile,
# MAGIC maximoWorkOrderNumber,
# MAGIC source,
# MAGIC projectId,
# MAGIC issueResponsibility,
# MAGIC businessPartnerNumber,
# MAGIC agreementNumber,
# MAGIC propertyNumber,
# MAGIC serviceArea,
# MAGIC serviceSubArea,
# MAGIC resolutionCode,
# MAGIC serviceCategoryCode,
# MAGIC rootCauseCode,
# MAGIC facilityNameCode,
# MAGIC secondaryAnalysisCode
# MAGIC from
# MAGIC cleansed.${vars.table}
# MAGIC except
# MAGIC select
# MAGIC headerUUID,
# MAGIC utilitiesStructuredContract,
# MAGIC headerType,
# MAGIC postingDate,
# MAGIC transactionDescription,
# MAGIC logicalSystem,
# MAGIC headerCategory,
# MAGIC createdDate,
# MAGIC createdDateTime,
# MAGIC createdBy,
# MAGIC lastChangedDate,
# MAGIC lastChangedDateTime,
# MAGIC changedBy,
# MAGIC requestHeaderNumber,
# MAGIC scenarioId,
# MAGIC templateType,
# MAGIC recommendedPriority,
# MAGIC urgency,
# MAGIC impact,
# MAGIC escalation,
# MAGIC risk,
# MAGIC lastUpdatedAt,
# MAGIC activityCategory,
# MAGIC activityPriority,
# MAGIC activityDirection,
# MAGIC soldToParty,
# MAGIC salesEmployee,
# MAGIC responsibleEmployee,
# MAGIC contactPerson,
# MAGIC salesOrgResponsible,
# MAGIC salesOrg,
# MAGIC salesOffice,
# MAGIC salesGroup,
# MAGIC serviceOrgResponsible,
# MAGIC serviceOrg,
# MAGIC serviceTeam,
# MAGIC calendarDay,
# MAGIC calendarDatetime,
# MAGIC precedingTransactionGUID,
# MAGIC precedingDocumentObjectType,
# MAGIC precedingActivityGUID,
# MAGIC processCategory,
# MAGIC processCatalog,
# MAGIC processCodeGroup,
# MAGIC processCode,
# MAGIC precedingObjectType,
# MAGIC validTimestamp,
# MAGIC catalogCategoryC,
# MAGIC catalogC,
# MAGIC codeGroupC,
# MAGIC codeC,
# MAGIC defectCountC,
# MAGIC numberOfActivitiesC,
# MAGIC coherentAspectIdC,
# MAGIC coherentCategoryIdC,
# MAGIC dataElementGUIDC,
# MAGIC catalogCategoryD,
# MAGIC catalogD,
# MAGIC codeGroupD,
# MAGIC codeD,
# MAGIC defectCountD,
# MAGIC numberOfActivitiesD,
# MAGIC coherentAspectIdD,
# MAGIC coherentCategoryIdD,
# MAGIC dataElementGUIDD,
# MAGIC defectCountE,
# MAGIC numberOfActivitiesE,
# MAGIC dataElementGUIDE,
# MAGIC defectCountT,
# MAGIC numberOfActivitiesT,
# MAGIC dataElementGUIDT,
# MAGIC defectCountW,
# MAGIC numberOfActivitiesW,
# MAGIC dataElementGUIDW,
# MAGIC subjectProfileCategory,
# MAGIC dataElementGUID,
# MAGIC serviceLifeCycle,
# MAGIC serviceLifeCycleUnit,
# MAGIC workDuration,
# MAGIC workDurationUnit,
# MAGIC totalDuration,
# MAGIC totalDurationUnit,
# MAGIC requestStartDate,
# MAGIC requestEndDate,
# MAGIC dueDateTime,
# MAGIC completionDateTime,
# MAGIC firstEscalateDateTime,
# MAGIC secondEscalateDateTime,
# MAGIC activityReasonCode,
# MAGIC numberOfInteractionRecords,
# MAGIC completedBeforeIndicator,
# MAGIC problemGUID,
# MAGIC notificationNumber,
# MAGIC contractiId,
# MAGIC podStatus,
# MAGIC statusProfile,
# MAGIC maximoWorkOrderNumber,
# MAGIC source,
# MAGIC projectId,
# MAGIC issueResponsibility,
# MAGIC businessPartnerNumber,
# MAGIC agreementNumber,
# MAGIC propertyNumber,
# MAGIC serviceArea,
# MAGIC serviceSubArea,
# MAGIC resolutionCode,
# MAGIC serviceCategoryCode,
# MAGIC rootCauseCode,
# MAGIC facilityNameCode,
# MAGIC secondaryAnalysisCode
# MAGIC from
# MAGIC (select
# MAGIC case
# MAGIC when GUID is null then ''
# MAGIC else GUID end as headerUUID,
# MAGIC OBJECT_ID as utilitiesStructuredContract,
# MAGIC PROCESS_TYPE as headerType,
# MAGIC POSTING_DATE as postingDate,
# MAGIC DESCRIPTION_UC as transactionDescription,
# MAGIC LOGICAL_SYSTEM as logicalSystem,
# MAGIC OBJECT_TYPE as headerCategory,
# MAGIC CREATED_AT as createdDate,
# MAGIC to_timestamp(cast(CREATED_TS as STRING),'yyyyMMddHHmmss') as createdDatetime,
# MAGIC CREATED_BY as createdBy,
# MAGIC CHANGED_AT as lastChangedDate,
# MAGIC to_timestamp(cast(CHANGED_TS as STRING),'yyyyMMddHHmmss') as lastChangedDateTime,
# MAGIC CHANGED_BY as changedBy,
# MAGIC NUM_OF_HEAD as requestHeaderNumber,
# MAGIC SCENARIO as scenarioId,
# MAGIC TEMPLATE_TYPE as templateType,
# MAGIC REC_PRIORITY as recommendedPriority,
# MAGIC URGENCY as urgency,
# MAGIC IMPACT as impact,
# MAGIC ESCALATION as escalation,
# MAGIC RISK as risk,
# MAGIC to_timestamp(cast(LAST_UPDATED_AT as STRING),'yyyyMMddHHmmss') as lastUpdatedAt,
# MAGIC CATEGORY as activityCategory,
# MAGIC PRIORITY as activityPriority,
# MAGIC DIRECTION as activityDirection,
# MAGIC SOLD_TO_PARTY as soldToParty,
# MAGIC SALES_EMPLOYEE as salesEmployee,
# MAGIC PERSON_RESP as responsibleEmployee,
# MAGIC CONTACT_PERSON as contactPerson,
# MAGIC SALES_ORG_RESP as salesOrgResponsible,
# MAGIC SALES_ORG as salesOrg,
# MAGIC SALES_OFFICE as salesOffice,
# MAGIC SALES_GROUP as salesGroup,
# MAGIC SERVICE_ORG_RESP as serviceOrgResponsible,
# MAGIC SERVICE_ORG as serviceOrg,
# MAGIC SERVICE_TEAM as serviceTeam,
# MAGIC CALDAY as calendarDay,
# MAGIC to_timestamp(cast(CALDAY_TS as STRING),'yyyyMMddHHmmss') as calendarDatetime,
# MAGIC PREDEC_OBJKEY as precedingTransactionGUID,
# MAGIC PREDEC_OBJTYPE as precedingDocumentObjectType,
# MAGIC PRED_ACT_GUID as precedingActivityGUID,
# MAGIC PROCESS_CATEGORY as processCategory,
# MAGIC PROCESS_CATALOG as processCatalog,
# MAGIC PROCESS_CODEGR as processCodeGroup,
# MAGIC PROCESS_CODE as processCode,
# MAGIC PROCESS_OBJTYPE as precedingObjectType,
# MAGIC to_timestamp(cast(QUOT_VALID_TS as STRING),'yyyyMMddHHmmss') as validTimestamp,
# MAGIC CATALOG_TYPE_C as catalogCategoryC,
# MAGIC KATALOGART_C as catalogC,
# MAGIC CODEGRUPPE_C as codeGroupC,
# MAGIC CODE_C as codeC,
# MAGIC DEFQUANTITY_C as defectCountC,
# MAGIC COUNTER_C as numberOfActivitiesC,
# MAGIC ASP_ID_C as coherentAspectIdC,
# MAGIC CAT_ID_C as coherentCategoryIdC,
# MAGIC CC_CAT_SUBJECT_C as dataElementGUIDC,
# MAGIC CATALOG_TYPE_D as catalogCategoryD,
# MAGIC KATALOGART_D as catalogD,
# MAGIC CODEGRUPPE_D as codeGroupD,
# MAGIC CODE_D as codeD,
# MAGIC DEFQUANTITY_D as defectCountD,
# MAGIC COUNTER_D as numberOfActivitiesD,
# MAGIC ASP_ID_D as coherentAspectIdD,
# MAGIC CAT_ID_D as coherentCategoryIdD,
# MAGIC CC_CAT_SUBJECT_D as dataElementGUIDD,
# MAGIC DEFQUANTITY_E as defectCountE,
# MAGIC COUNTER_E as numberOfActivitiesE,
# MAGIC CC_CAT_SUBJECT_E as dataElementGUIDE,
# MAGIC DEFQUANTITY_T as defectCountT,
# MAGIC COUNTER_T as numberOfActivitiesT,
# MAGIC CC_CAT_SUBJECT_T as dataElementGUIDT,
# MAGIC DEFQUANTITY_W as defectCountW,
# MAGIC COUNTER_W as numberOfActivitiesW,
# MAGIC CC_CAT_SUBJECT_W as dataElementGUIDW,
# MAGIC PROFILE_TYPE as subjectProfileCategory,
# MAGIC CC_CAT_SUBJECT as dataElementGUID,
# MAGIC cast(LC_SRV_DURATION as bigint) as serviceLifeCycle,
# MAGIC LC_SRV_DUR_UNIT as serviceLifeCycleUnit,
# MAGIC WORK_DURATION as workDuration,
# MAGIC WORK_DURA_UNIT as workDurationUnit,
# MAGIC TOTAL_DURATION as totalDuration,
# MAGIC TOTAL_DURA_UNIT as totalDurationUnit,
# MAGIC to_timestamp(cast(REQ_START_DATE as STRING),'yyyyMMddHHmmss') as requestStartDate,
# MAGIC to_timestamp(cast(REQ_END_DATE as STRING),'yyyyMMddHHmmss') as requestEndDate,
# MAGIC to_timestamp(cast(DUE_DATE as STRING),'yyyyMMddHHmmss') as dueDateTime,
# MAGIC to_timestamp(cast(COMPLETION_TS as STRING),'yyyyMMddHHmmss') as completionDateTime,
# MAGIC to_timestamp(cast(ESCALATE_1_TS as STRING),'yyyyMMddHHmmss') as firstEscalateDateTime,
# MAGIC to_timestamp(cast(ESCALATE_2_TS as STRING),'yyyyMMddHHmmss') as secondEscalateDateTime,
# MAGIC CC_CAT_ACTREASON as activityReasonCode,
# MAGIC NO_OF_IR as numberOfInteractionRecords,
# MAGIC IN_COMPL_BEFORE as completedBeforeIndicator,
# MAGIC PROBLEM_GUID as problemGUID,
# MAGIC NOTIFICATION_NO as notificationNumber,
# MAGIC CRM_ISU_CONTRACT as contractiId,
# MAGIC STATUS as podStatus,
# MAGIC USER_STAT_PROC as statusProfile,
# MAGIC ZZ_MAX_REQ_NO as maximoWorkOrderNumber,
# MAGIC ZZAFLD000026 as source,
# MAGIC ZZAFLD000027 as projectId,
# MAGIC ZZAFLD000028 as issueResponsibility,
# MAGIC ZZREPORTED_BY as businessPartnerNumber,
# MAGIC ZZAGREEMENT_N as agreementNumber,
# MAGIC ZZ_PROPERTY_NO as propertyNumber,
# MAGIC ZZ_SR_AREA as serviceArea,
# MAGIC ZZ_SR_SUB_AREA as serviceSubArea,
# MAGIC ZZ_RESOLUTION_CD as resolutionCode,
# MAGIC ZZ_SR_CATEGORY_CD as serviceCategoryCode,
# MAGIC ZZ_ROOT_CAUSE_CD as rootCauseCode,
# MAGIC ZZ_X_FACILITY_NAME_CD as facilityNameCode,
# MAGIC ZZ_X_SECONDARY_ANALYSIS_CD as secondaryAnalysisCode
# MAGIC ,row_number() over (partition by GUID  order by EXTRACT_DATETIME desc) as rn
# MAGIC from test.${vars.table} -- WHERE LANGU = 'E'
# MAGIC )a where  a.rn = 1
